### ISSUE TITLE
Workspace Viewer exception on Mac

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1315]
```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 3154, in on_debug_view_workspace
    show_workspace_viewer(self.__frame, workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 41, in show_workspace_viewer
    __the_workspace_viewer = ViewWorkspace(parent, workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 383, in __init__
    self.set_workspace(workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 540, in set_workspace
    self.update_menu(self.frame.menu_subplots)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 554, in update_menu
    self.image.on_update_menu(event, menu)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/cpartists.py", line 782, in on_update_menu
    idx, my_id, name, sub_menu)
  File "/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core.py", line 11120, in InsertMenu
    return _core_.Menu_InsertMenu(*args, **kwargs)
PyAssertionError: C++ assertion "wxAssertFailure" failed at /BUILD/wxPython-src-2.8.12.1/src/common/stockitem.cpp(166) in wxGetStockLabel(): invalid stock item ID
```

**Comment by LeeKamentsky** [comment]
There are a couple breadcrumbs for this that are posted on the web, for instance https://groups.google.com/forum/#!topic/wx-dev/TxC1ZHSN3Dw . The trick I played is to replace the empty string with a string of a single space (" ") to defeat the spurious assert that shows up in the stack trace above. Feel free to open this again if you get the above stack trace after picking up the fix - I couldn't replicate, possibly because of a different WX version.

**Comment by dlogan** [comment]
I got a little farther this time -- the Workspace viewer appeared.  But upon clicking Step in test Mode, I got this similar exception:
```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 2786, in do_step
    update_workspace_viewer(workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 48, in update_workspace_viewer
    __the_workspace_viewer.set_workspace(workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 539, in set_workspace
    self.update_menu(self.frame.menu_subplots)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/viewworkspace.py", line 553, in update_menu
    self.image.on_update_menu(event, menu)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/cpartists.py", line 801, in on_update_menu
    menu_items[idx], menu_items[idx].GetMenu(), data)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/cpartists.py", line 1094, in __update_sub_menu
    event.Text = data.name
  File "/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core.py", line 11516, in SetText
    return _core_.MenuItem_SetText(*args, **kwargs)
PyAssertionError: C++ assertion "wxAssertFailure" failed at /BUILD/wxPython-src-2.8.12.1/src/common/stockitem.cpp(166) in wxGetStockLabel(): invalid stock item ID
```

**Comment by LeeKamentsky** [comment]
Hopefully the last, but you never can tell. Feel free to reopen, thx for finding.
