### ISSUE TITLE
Windows install of Ilastik doesn't run

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1319]
Running Ilastik from the startup menu produces the following stack trace:

    C:\Program Files\CellProfiler_trunk>cellprofiler --ilastik
    Traceback (most recent call last):
      File "CellProfiler.py", line 950, in <module>
      File "CellProfiler.py", line 128, in main
      File "CellProfiler.py", line 781, in run_ilastik
      File "C:\Program Files\CellProfiler_trunk\site-packages\ilastik\ilastikMain.py", line 32, in <module>
        from OpenGL.GL import *
    ImportError: No module named OpenGL.GL

**Comment by LeeKamentsky** [comment]
The build machine has problems with many of the Ilastik dependencies. At this point, the one I need to resolve is PyOpenGL which is not building properly and,  to upgrade using available binary installs, I will have to upgrade numpy which is not an option.

I'm afraid the best solution may be to remove the Ilastik icon from the CellProfiler install and document that users download Ilastik 0.6 from wherever they can find it.

**Comment by LeeKamentsky** [comment]
I spent quite a bit of time on the build, including building PyOpenGL and OpenGL. Everything seems to work, including the GL accelerated graphics mode.
