### ISSUE TITLE
SaveImages: Error if using "Same folder as image" for output location +  derived image

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1325]
Running the attached project file produces the following error:

```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2777, in do_step
  File "cellprofiler\modules\saveimages.pyc", line 471, in run
  File "cellprofiler\modules\saveimages.pyc", line 515, in run_image
  File "cellprofiler\modules\saveimages.pyc", line 689, in save_image
  File "cellprofiler\modules\saveimages.pyc", line 824, in get_filename
  File "cellprofiler\modules\saveimages.pyc", line 1122, in get_absolute_path
  File "cellprofiler\measurements.pyc", line 895, in get_current_image_measurement
  File "cellprofiler\measurements.pyc", line 902, in get_current_measurement
  File "cellprofiler\measurements.pyc", line 946, in get_measurement
  File "cellprofiler\utilities\hdf5_dict.pyc", line 368, in __getitem__
  File "cellprofiler\utilities\hdf5_dict.pyc", line 372, in __getitem__
AssertionError
```

I assume this is b/c the image to be saved has no originating location. There should be a validation warning if this location option is selected for a derived image (probably also for an image retrieved via HTTP).

Attachments:
http://cellprofiler.org/issues/uploaded/DJo2Ku/isssue.cpproj

**Comment by LeeKamentsky** [comment]
Unfortunately, there's code to look at the parent of the image to see if it was loaded using an input module. The image is assigned a parent by the module that creates it, but there's no way for the code to know what the parent images might be until the pipeline is run. So, it''s hard to do, where "hard" means implementing a per-module method that reports the image parent/child relationship and implementing that method within every module that generates an image.

**Comment by AnneCarpenter** [comment]
Sounds like catching the error when the pipeline is created is out of the question and instead we should simply catch this error when it occurs and explain what has happened.

**Comment by VolkerH** [comment]
Earlier this week I ran into this error also and wasted quite a bit of time trying to find the source (until I found this isseu). If it can't be fixed easily it would be good if at least the error message was a bit more meaningful in this case. As a starter, a comment in the source code next to the assertion  with a link to this issue would be useful.

**Comment by AnneCarpenter** [comment]
Does anyone know where in the source code this lurks?

**Comment by VolkerH** [comment]
For me the error happened in 
   
 `get_image_provider(self, name):` in cpimage.py but I'm not on the master branch.
   
I should add that I wanted to save "objects", i.e. label images. The objects in question were filtered upstream using "EditObjectsManually" so I guess the association with an image and the respective image provider got lost somewhere along the way.  
I had this both in Release versions 2 and 2.2.

**Comment by bethac07** [comment]
Just had a look, there's a 
```class SaveImagesDirectoryPath(cps.DirectoryPath)```
 which says it's specifically for saving into the image diretory (as opposed to  ```class SaveImages``` ); the normal SaveImages class has a method called ```source_path``` whose help text is ```The path for the image data, or its first parent with a path``` and seems to do something like that, but I don't see any implementation in the special SaveImagesDirectoryPath.  Usual disclaimer- IANASE.

**Comment by mcquin** [comment]
This functionality is very fragile. How about removing it as an option?

**Comment by bethac07** [comment]
I could live with that for sure.
