### ISSUE TITLE
Can't save file opened from the command line

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1326]
Originally reported here:
http://www.cellprofiler.org/forum/viewtopic.php?f=16&t=4175

Open a project file from the command line - e.g.

    python CellProfiler.py --do-not-build --do-not-fetch -p foo.cpproj

Attempt to save the file using File / Save. The operation fails with the following stack trace:

    Traceback (most recent call last):
      File "c:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 701, in __on_save_workspace
        self.do_save_workspace(path)
      File "c:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 705, in do_save_workspace
        self.__workspace.save(filename)
      File "c:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\workspace.py", line 524, in save
        hdf5dest = h5py.File(path, mode="w")
      File "C:\Python27\lib\site-packages\h5py\_hl\files.py", line 222, in __init__
        fid = make_fid(name, mode, userblock_size, fapl)
      File "C:\Python27\lib\site-packages\h5py\_hl\files.py", line 85, in make_fid
        fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
      File "h5f.pyx", line 90, in h5py.h5f.create (h5py\h5f.c:1998)
    IOError: Unable to create file (Unable to truncate a file which is already open)

**Comment by LeeKamentsky** [comment]
Thank you kyrycell.
