### ISSUE TITLE
Speed up EnhanceOrSuppressFeatures -> Speckles (tophat)

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1341]
EnhanceOrSuppressFeatures -> Speckles (tophat) is a poor man's illumination correction and as such, works nicely without the need for a separate illumination correction pipeline.  Unfortunately with large structuring elements, the computer time is prohibitive.  Below are cluster times for a sample run, with the first EnhanceOrSuppressFeatures -> Speckles set to 140 pixels and the second at 70 pixels:
```
Mon Apr 13 15:47:47 2015: Image # 1, module Images # 1: 0.00 sec
Mon Apr 13 15:47:47 2015: Image # 1, module Metadata # 2: 0.00 sec
Mon Apr 13 15:47:47 2015: Image # 1, module NamesAndTypes # 3: 4.44 sec
Mon Apr 13 15:47:52 2015: Image # 1, module Groups # 4: 0.00 sec
Mon Apr 13 15:47:52 2015: Image # 1, module MeasureImageQuality # 5: 6.33 sec
Mon Apr 13 15:47:58 2015: Image # 1, module EnhanceOrSuppressFeatures # 7: 151.62 sec
Mon Apr 13 15:50:30 2015: Image # 1, module EnhanceOrSuppressFeatures # 8: 28.73 sec
Mon Apr 13 15:50:59 2015: Image # 1, module IdentifyPrimaryObjects # 9: 7.35 sec
Mon Apr 13 15:51:06 2015: Image # 1, module IdentifySecondaryObjects # 10: 1.66 sec
Mon Apr 13 15:51:08 2015: Image # 1, module IdentifyPrimaryObjects # 11: 5.43 sec
Mon Apr 13 15:51:13 2015: Image # 1, module RelateObjects # 13: 0.05 sec
Mon Apr 13 15:51:13 2015: Image # 1, module DisplayDataOnImage # 14: 1.05 sec
Mon Apr 13 15:51:19 2015: Image # 1, module FilterObjects # 15: 0.19 sec
...
```

Investigate methods for speeding up this operation.

**Comment by LeeKamentsky** [comment]
I think I might be able to use the fast median filter for this - it's a percentile filter. White top hat is

    img - open(img, radius)
    img - (dilation(erosion(img, radius), radius))
     # dilation is the maximum for the neighborhood
     # erosion is the minimum for the neighborhood
     img -  median_filter(median_filter(img, radius, percent=0), radius, percent=100)

To be on the safe side, maybe we need to add a parameter for backwards compatibility? The fast median filter is hexagonal, technically. That would change the result of a pipeline slightly and if someone has absolutely true circles of a known radius, they might be disturbed by the aberration.

**Comment by dlogan** [comment]
Error on cluster in the new EnhanceOrSuppress (though locally with the CP Windows build, I had no issue??  Maybe I made a mistake building on cluster?):
```
Sender: LSF System <lsf@node1350>
Subject: Job 2089926: </imaging/batch/4649/11_to_20> Done

Job </imaging/batch/4649/11_to_20> was submitted from host <imagingweb> by user <imageweb> in cluster <cromwell>.
Job was executed on host(s) <node1350>, in queue <hour>, as user <imageweb> in cluster <cromwell>.
</home/unix/imageweb> was used as the home directory.
</imaging/analysis/CPCluster/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c> was used as the working directory.
Started at Thu Apr 16 15:30:02 2015
Results reported at Thu Apr 16 15:31:31 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
./python-2.6.sh CellProfiler.py -p /imaging/analysis/2010_05_18_Malaria_Liver_Infection_Bhatia_Lab/Analysis/Pvivax_ThailandPlate4_Dose_20x_/Batch_data.h5 -c -r -b --do-not-fetch -o /imaging/analysis/2010_05_18_Malaria_Liver_Infection_Bhatia_Lab/Analysis/Pvivax_ThailandPlate4_Dose_20x_ -f 11 -l 20 -d /imaging/analysis/2010_05_18_Malaria_Liver_Infection_Bhatia_Lab/Analysis/Pvivax_ThailandPlate4_Dose_20x_/status/Batch_11_to_20_DONE.mat
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :     24.82 sec.
    Max Memory :       175 MB
    Max Swap   :      1476 MB

    Max Processes  :         5
    Max Threads    :        32

The output (if any) follows:

Xvfb display = :2089926
Xvfb directory = /local/scratch/CellProfilerXVFB.32178.28350
Xvfb PID = 20741
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for inet6
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for inet
Version: 2015-04-16T18:53:47 588caaa / 20150416185347
Failed to stop Ilastik
ilastik import: failed to import the ilastik. Please follow the instructions on 
                          "http://www.ilastik.org" to install ilastik
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/modules/ilastik_pixel_classification.py", line 81, in <module>
    import ilastik_main
ImportError: No module named ilastik_main
Could not load cellprofiler.modules.exporttocellh5
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/modules/exporttocellh5.py", line 27, in <module>
    import cellh5
ImportError: No module named cellh5
could not load these modules: cellprofiler.modules.exporttocellh5
Experiment-wide values for mean threshold, etc calculated by MeasureImageQuality may be incorrect if the run is split into subsets of images.
Times reported are CPU times for each module, not wall-clock time
Thu Apr 16 15:31:13 2015: Image # 11, module Images # 1: 0.00 sec
Thu Apr 16 15:31:13 2015: Image # 11, module Metadata # 2: 0.00 sec
Thu Apr 16 15:31:13 2015: Image # 11, module NamesAndTypes # 3: 4.17 sec
Thu Apr 16 15:31:18 2015: Image # 11, module Groups # 4: 0.00 sec
Thu Apr 16 15:31:18 2015: Image # 11, module MeasureImageQuality # 5: 6.41 sec
Error detected during run of module EnhanceOrSuppressFeatures
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/pipeline.py", line 1797, in run_with_yield
    self.run_module(module, workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/pipeline.py", line 2041, in run_module
    module.run(workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/modules/enhanceorsuppressfeatures.py", line 281, in run
    median_filter(pixel_data, mask, radius, percent = 0),
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2015_04_15_07_40_00-588caaaa4c/cellprofiler/cpmath/filter.py", line 95, in median_filter
    mask = np.ones_like(data, dtype=bool)
TypeError: 'dtype' is an invalid keyword to ones_like
Thu Apr 16 15:31:25 2015: Image # 11, module EnhanceOrSuppressFeatures # 8: 0.02 sec
FreeFontPath: FPE "unix/:7100" refcount is 2, should be 1; fixing.
```

From Batch 4651: 
http://imagingweb.broadinstitute.org/batchprofiler/cgi-bin/FileUI/CellProfiler/BatchProfiler/ViewBatch.py?batch_id=4651

http://imagingweb.broadinstitute.org/batchprofiler/cgi-bin/FileUI/CellProfiler/BatchProfiler/ViewTextFile.py?run_id=2085733

**Comment by LeeKamentsky** [comment]
Its a problem with the numpy version. I will fix it tomorrow from ISBI.
