### ISSUE TITLE
workspace viewer exception color -> gray

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1346]
If you open the workspace vierer, display a color image, and then load a grayscale image with the same image name using a different piipeline, the viewer will raise an exception (paste stack here)

**Comment by LeeKamentsky** [comment]
Exact steps to reproduce:
* Open the ExampleUnmixColors example pipeline
* Add the pipeline's example image
* Start test mode
* Open the workspace viewer
* Select OrigColor from the Images drop-down
* Hit Show to show
* Hit Show to hide
* Hit Step to run UnmixColors
* Choose OrigRed from the Images menu
* Hit Show to show

    Traceback (most recent call last):
      File "c:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\viewworkspace.py", line 104, in on_check_change
        self.vw.redraw()
      File "c:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\viewworkspace.py", line 673, in redraw
        self.frame.figure.canvas.draw()
      File "C:\Python27\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 46, in draw
        FigureCanvasAgg.draw(self)
      File "C:\Python27\lib\site-packages\matplotlib\backends\backend_agg.py", line 461, in draw
        self.figure.draw(self.renderer)
      File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
        draw(artist, renderer, *args, **kwargs)
      File "C:\Python27\lib\site-packages\matplotlib\figure.py", line 1079, in draw
        func(*args)
      File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
        draw(artist, renderer, *args, **kwargs)
      File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2092, in draw
        a.draw(renderer)
      File "c:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\cpartists.py", line 617, in draw
        pixel_data.shape[2]), 0))
    IndexError: tuple index out of range
