### ISSUE TITLE
IdentifyPrimaryObjects: Error in watershed

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1369]
Running the attached 2.1.2 project file yields the error below:
```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2805, in do_step
    self.__pipeline.run_module(module, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2058, in run_module
    module.run(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 917, in run
    object_count)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 1245, in separate_neighboring_objects
    mask=labeled_image!=0)
  File "D:\Trunk\CellProfiler\cellprofiler\cpmath\watershed.py", line 202, in watershed
    c_output)
  File "_watershed.pyx", line 32, in _watershed.watershed (_watershed.c:2042)
TypeError: watershed() takes exactly 8 positional arguments (7 given)
```

Attachments:
http://cellprofiler.org/issues/uploaded/Ep8LUg/1_sequence1_C_R_30Quads.tif
http://cellprofiler.org/issues/uploaded/9RGYCf/44_sequence1_G_R_30Quads.tif
http://cellprofiler.org/issues/uploaded/0mybh2/issue.cpproj

**Comment by braymp** [comment]
Oops, I think I updated to head in my working directory without restarting CP first. Closing.
