### ISSUE TITLE
AttributeError in cpfigure: 'LinearSegmentedColormap' object has no attribute 'set_array'

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1377]
The example neighbors pipeline produces the following error in 2.1.2 from source:
```
Traceback (most recent call last):
  File "c:\Trunk\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2812, in do_step
    module.display(workspace, fig)
  File "c:\Trunk\CellProfiler\cellprofiler\modules\measureobjectneighbors.py", line 577, in display
    sharexy = figure.subplot(0,0))
  File "c:\Trunk\CellProfiler\cellprofiler\gui\cpfigure.py", line 221, in wrapper
    return fn(*args, **kwargs)
  File "c:\Trunk\CellProfiler\cellprofiler\gui\cpfigure.py", line 1232, in subplot_imshow
    colormap.set_array(self.images[(x, y)])
AttributeError: 'LinearSegmentedColormap' object has no attribute 'set_array'
```

**Comment by LeeKamentsky** [comment]
fixed with 9cfd87c
