### ISSUE TITLE
HDF5 error on batch mode

### ISSUE THREAD

**Issue by erexhepa** [CellProfiler/CellProfiler#1386]
Hi,

I was trying to run the analysis of several images from a 384 well plate by creating batch files. I'm trying to run it on our cluster, which nodes run on ubuntu, by specifying for each job the start and end image with the -f and -l flags. The problem I have (it seems to be the -l flag) is that if specify the -l flag I get a message error:

Traceback (most recent call last):
  File "/import/bc_users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/cellprofiler/measurements.py", line 1820, in load_measurements
    image_numbers = image_numbers)
  File "/import/bc_users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/cellprofiler/measurements.py", line 288, in __init__
    image_numbers=image_numbers)
  File "/import/bc_users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/cellprofiler/utilities/hdf5_dict.py", line 272, in __init__
    src_dataset[start:stop]
  File "/import/bc_users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/cellprofiler/utilities/hdf5_dict.py", line 489, in __setitem__
    (object_name, feature_name, [num_idx]), [vals])
  File "/import/bc_users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/cellprofiler/utilities/hdf5_dict.py", line 529, in __setitem__
    idxs=num_idx, data_type = hdf5_type)
  File "/import/bc_users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/cellprofiler/utilities/hdf5_dict.py", line 768, in add_all
    maxshape = (None, ))
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 69, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 88, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5t.pyx", line 1332, in h5py.h5t.py_create (h5py/h5t.c:11600)
  File "h5t.pyx", line 1402, in h5py.h5t.py_create (h5py/h5t.c:11465)
TypeError: Object dtype dtype('object') has no native HDF5 equivalent

I saw there was already a thread open for this problem (the -l option if you think it is this) but the patch is already in the distribution of CellProfiler we are running (I checked the hdf5_dict.py). wea are running version 2.1.1.

If I run it on one image so the same -f and -l index there is no error but the HDF5 file is not updated with the output from the image run. 

Have anyone come accross this problem and do you have any suggestion how we can deal with it ?

Thanks
Elton

**Comment by LeeKamentsky** [comment]
It looks like this is the bug that was fixed by ffe716d. Can you patch with that and try again?

**Comment by erexhepa** [comment]
Yeah, it works now after patching with 

https://github.com/CellProfiler/CellProfiler/commit/ffe716d2a05273f6ee88b217e84290d4e7b95a2d

Thanks a lot

elton

**Comment by erexhepa** [comment]
sorry just one last question related to the hdf5 batch processing mode. 

The hdf5 file after processing doesn't get updated in terms of out image analysis output. I had an export to spreadsheet module before the batch processing module and that produces the standart .csv outputs. However from I read in the help files the output is updated in the HDF5 file. The HDF5 file is empty on the Measurement groups. It has only the Image and Experiment fields but no data.

Do we still need to use the -o flag to indicate the output folder for each job ?

**Comment by LeeKamentsky** [comment]
CellProfiler takes a couple types of HDF5 files as input (Batch_data.h5
from CreateBatchFiles and *.cpproj files for projects) and it references
these as read-only. You can create a measurements file either from the GUI
by viewing the output settings and choosing to write measurements to HDF5
or by specifying the measurements file name as the last parameter on the
command line when operating headless.

The .h5 file's organization is a little arcane and undocumented. I think
almost everyone uses one of the export modules to output their
measurements. 2.1.2 will add ExportToCellH5 which will output an HDF5 file
using the emerging CellH5 standard.

**Comment by erexhepa** [comment]
Hi ,

Thanks for clarifications. Thought something else when I read the helpfile.
