### ISSUE TITLE
Analysis worker error

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1408]
Running the attached project file from source yields the following error:
```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 1948, in run_image_set
    self.run_module(module, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2059, in run_module
    module.run(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\displaydataonimage.py", line 236, in run
    pixel_data = image.pixel_data
  File "D:\Trunk\CellProfiler\cellprofiler\cpimage.py", line 102, in get_image
    return self.__image.get()
  File "D:\Trunk\CellProfiler\cellprofiler\cpimage.py", line 434, in get
    image = self.__backing_store.get_image(self.__name)
  File "D:\Trunk\CellProfiler\cellprofiler\utilities\hdf5_dict.py", line 1551, in get_image
    return self.root[image_name][:]
  File "D:\Python27\lib\site-packages\h5py\_hl\group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\h5o.pyx", line 183, in h5py.h5o.open (h5py\h5o.c:3311)
KeyError: "Unable to open object (Object 'origoverlay' doesn't exist)"
```
A later run produced this error:
```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 1948, in run_image_set
    self.run_module(module, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2059, in run_module
    module.run(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 483, in run
    should_save = self.run_image(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 527, in run_image
    self.save_image(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 659, in save_image
    pixels = image.pixel_data
  File "D:\Trunk\CellProfiler\cellprofiler\cpimage.py", line 102, in get_image
    return self.__image.get()
  File "D:\Trunk\CellProfiler\cellprofiler\cpimage.py", line 434, in get
    image = self.__backing_store.get_image(self.__name)
  File "D:\Trunk\CellProfiler\cellprofiler\utilities\hdf5_dict.py", line 1551, in get_image
    return self.root[image_name][:]
  File "D:\Python27\lib\site-packages\h5py\_hl\group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\h5o.pyx", line 183, in h5py.h5o.open (h5py\h5o.c:3311)
KeyError: "Unable to open object (Object 'displayimage' doesn't exist)"
```
The analysis continues in the background and runs to completion except for sample11. Running on sample11 only completes with no problems.

Attachments:
http://cellprofiler.org/issues/uploaded/ScaALJ/issue.cpproj

**Comment by LeeKamentsky** [comment]
I just tried it from source on my machine with one worker and it ran through to completion with no errors. I ran it with four workers and no errors. Can you try with the compiled version of CP?

**Comment by braymp** [comment]
I think I found the problem: the temp folder was full. Maybe it might be good to have a msg when that occurs? If not, I can close this issue.

**Comment by LeeKamentsky** [comment]
It's a little disappointing that h5py errored silently and decided not to save the dataset rather than raise an exception. Not much we can do about it.
