### ISSUE TITLE
cpmorphology: IndexError

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1412]
Running the attached project from source produces the following error:
```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2813, in do_step
    self.__pipeline.run_module(module, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2059, in run_module
    module.run(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\measureobjectsizeshape.py", line 302, in run
    self.run_on_objects(object_group.name.value, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\measureobjectsizeshape.py", line 372, in run_on_objects
    msolidity[to_indices] = calculate_solidity(labels, indices)
  File "D:\Trunk\CellProfiler\cellprofiler\cpmath\cpmorphology.py", line 2472, in calculate_solidity
    convex_hull_areas = calculate_convex_hull_areas(labels, indexes)
  File "D:\Trunk\CellProfiler\cellprofiler\cpmath\cpmorphology.py", line 2374, in calculate_convex_hull_areas
    index_of_label[indexes] = np.array(range(indexes.shape[0]))
IndexError: index 2 is out of bounds for axis 0 with size 2
```
p.s. When fixed, please patch the 2.1.1-janssen CPCluster folder.

Attachments:
http://cellprofiler.org/issues/uploaded/DQXbzc/issue.cpproj

**Comment by LeeKamentsky** [comment]
Fix is 7a78399. Fix + test added.
