### ISSUE TITLE
wx issue on startup

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1418]
Running from source, this error appears on startup:
```
Exception RuntimeError: 'maximum recursion depth exceeded' in  ignored
Traceback (most recent call last):
  File "c:\CellProfiler\cellprofiler\gui\cpframe.py", line 455, in __on_path_mod
ule_imageset_panel_size
    self.layout_pmi_panel()
  File "c:\CellProfiler\cellprofiler\gui\cpframe.py", line 463, in layout_pmi_pa
nel
    wx.LayoutAlgorithm().LayoutWindow(self.__path_module_imageset_panel,
RuntimeError: maximum recursion depth exceeded
```
The UI then appears without the Input modules panel.
![untitled](https://cloud.githubusercontent.com/assets/1186440/9010286/09ee4990-3774-11e5-93b4-58a75997e580.jpg)

**Comment by LeeKamentsky** [comment]
Mark installed wx 3.0 so I'm going to change the milestone.

**Comment by LeeKamentsky** [comment]
Assign to Allen once he gets here.

**Comment by braymp** [comment]
Fixed.
