### ISSUE TITLE
RHEL6 Batchprofiler errors

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1427]
[Batch #5](http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=5) finished ok and seemingly produced good data.  However there exist error logs for each job. Not sure if they just need to be cleaned up, or if they represent something more serious about database deadlocks.

Here's an example [run.10.1.err](http://imagewebrhel6/batchprofiler/cgi-bin/ViewTextFile.py?batch_array_id=10&task_id=1&file_type=err):
```
Traceback (most recent call last):
  File "/imaging/docs/People/imageweb/batchprofiler/CellProfiler/BatchProfiler/JobStatus.py", line 59, in update_status
    run.wants_xvfb)
  File "/imaging/docs/People/imageweb/batchprofiler/CellProfiler/BatchProfiler/RunBatch.py", line 743, in create
    cursor.execute(cmd)
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
Traceback (most recent call last):
  File "/imaging/docs/People/imageweb/batchprofiler/CellProfiler/BatchProfiler/JobStatus.py", line 59, in update_status
    run.wants_xvfb)
  File "/imaging/docs/People/imageweb/batchprofiler/CellProfiler/BatchProfiler/RunBatch.py", line 743, in create
    cursor.execute(cmd)
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/imaging/analysis/CPCluster/CellProfiler-2.0/builds/redhat_6/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by LeeKamentsky** [comment]
Just MySQL crud - hundreds of jobs hitting the database at the same time, my SQL is clean but MySQL deadlocks anyway, so you need to redo the transaction. Ignore.
