### ISSUE TITLE
Mac build - user stack trace indicates odd dependency resolutions

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1470]
The user seems to have installed CellProfiler, but `cellh5` is not present and matplotlib complains that WX is not >= 2.8. The build runs the ExportToCellH5 tests, so what gives? Buid is aa38cd9 which passed.

Version: 2015-08-05T14:34:41 aa38cd9 / 20150805143441
Failed to stop Ilastik
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/modules/classifypixels.py", line 61, in <module>
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/modules/ilastik_pixel_classification.py", line 58, in <module>
ImportError: No module named vigra
Could not load cellprofiler.modules.exporttocellh5
Traceback (most recent call last):
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/modules/__init__.py", line 303, in add_module
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/modules/exporttocellh5.py", line 27, in <module>
  File "cellh5.pyc", line 18, in <module>
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/matplotlib/pyplot.py", line 95, in <module>
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/matplotlib/backends/__init__.py", line 25, in pylab_setup
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/matplotlib/backends/backend_wxagg.py", line 23, in <module>
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/matplotlib/backends/backend_wx.py", line 67, in <module>
ImportError: Matplotlib backend_wx and backend_wxagg require wxPython >=2.8
could not load these modules: cellprofiler.modules.exporttocellh5
Experiment-wide values for mean threshold, etc calculated by MeasureImageQuality may be incorrect if the run is split into subsets of images.
Times reported are CPU times for each module, not wall-clock time
Exception in thread "Thread-1" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
[Thread-1] INFO loci.formats.FormatHandler - Searching for blocks
[Thread-1] INFO loci.formats.FormatHandler - Parsing block 'ND2 FILE SIG' 0%
[Thread-1] INFO loci.formats.FormatHandler - Parsing block 'ImageMetadat' 0%
[Thread-1] INFO loci.formats.FormatHandler - Parsing block 'CustomData|J' 0%

**Comment by AnneCarpenter** [comment]
I suspect we can't follow this up without someone who can replicate. Closing but if anyone experiences this problem, feel free to re-open!

**Comment by 0x00b1** [comment]
I fixed this a few months back.
