### ISSUE TITLE
Can't open image example in Welcome Screen

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1488]
In current version (dc04181), load Welcome Screen pipeline (first link).  Double-click on any image in Images module and get this:
```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/cpfigure.py", line 1901, in show_image
    image = load_image_url(url)
  File "/Users/dlogan/github/CPhomebrew/Cellar/cellprofiler-dev-python/1/cpdev/lib/python2.7/site-packages/bioformats/formatreader.py", line 523, in load_using_bioformats_url
    with ImageReader(url=url) as rdr:
  File "/Users/dlogan/github/CPhomebrew/Cellar/cellprofiler-dev-python/1/cpdev/lib/python2.7/site-packages/bioformats/formatreader.py", line 621, in __init__
    class_list = get_class_list()
  File "/Users/dlogan/github/CellProfiler/cellprofiler/utilities/cpjvm.py", line 202, in get_class_list
    dir=cpprefs.get_temporary_directory())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/var/folders/8s/r38hcm0s0f3b9cms92c7xlsr0000gp/T/tmpnXIcpJ.garbage'
```

Do I (or does CP) need to flush some tmp files first?

**Comment by braymp** [comment]
Related to #1411?
