### ISSUE TITLE
JavaException on starting CP

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1499]
Starting CP from the cmd line after 5b3567c4ed94b84f9fd4150528eda362bc13c06b produces the following error:
```
Traceback (most recent call last):
  File "CellProfiler.py", line 297, in main
    cp_stop_vm()
  File "c:\Trunk\CellProfiler\cellprofiler\utilities\cpjvm.py", line 230, in cp_stop_vm
    ij1 = javabridge.JClassWrapper("ij.IJ").getInstance()
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\wrappers.py", line 175, in __init__
    self.klass = J.get_class_wrapper(J.class_for_name(class_name), True)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 1713, in class_for_name
    classname, True, ldr)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 908, in static_call
    result = fn(*nice_args)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 888, in fn
    raise JavaException(jexception)
JavaException: ij.IJ
```
This is after using <code>git cllean</code>, then <code>CellProfiler.py --build-and-exit</code>.

I should note that I'm using javabridge from https://github.com/CellProfiler/python-javabridge rather than from https://pypi.python.org/pypi/javabridge (which is older).

**Comment by 0x00B1** [comment]
Interesting. Thanks!

**Comment by braymp** [comment]
I just took a look at https://github.com/CellProfiler/python-javabridge/issues/49, and tried to go through the same steps. Same sort of exception at the 3rd line, i.e., "ij = javabridge.JClassWrapper('ij.IJ')"
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\wrappers.py", line 175, in __init__
    self.klass = J.get_class_wrapper(J.class_for_name(class_name), True)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 1713, in class_for_name
    classname, True, ldr)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 908, in static_call
    result = fn(*nice_args)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 888, in fn
    raise JavaException(jexception)
javabridge.jutil.JavaException: ij.IJ
```

**Comment by 0x00B1** [comment]
Nice! :hankey:

**Comment by 0x00B1** [comment]
Unfortunately, I don’t think this is the same issue.

My current guess: prokaryote isn’t packaging dependencies properly.

**Comment by 0x00B1** [comment]
It’s an issue with cpjvm.py. I’ll fix tomorrow!
