### ISSUE TITLE
Did not find ij1-patcher.jar

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1500]
```sh
$ python CellProfiler.py -c ~/Downloads/ExampleHumanImages/ExampleHuman.cppipe 
running build_ext
skipping '_cpmorphology2.c' Cython extension (up-to-date)
skipping '_watershed.c' Cython extension (up-to-date)
skipping '_propagate.c' Cython extension (up-to-date)
skipping '_filter.c' Cython extension (up-to-date)
skipping '_lapjv.c' Cython extension (up-to-date)
skipping '_convex_hull.c' Cython extension (up-to-date)
skipping '_fastemd.cpp' Cython extension (up-to-date)
Did not find ij1-patcher.jar
```

**Comment by 0x00B1** [comment]
Related to #1499?

**Comment by braymp** [comment]
I think the proper cmd line is <code>python CellProfiler.py -c -r -p ~/Downloads/ExampleHumanImages/ExampleHuman.cppipe</code>

But I get the same error even so, plus more:
```
Exception in thread "Thread-0" java.lang.ClassNotFoundException: org.cellprofiler.imageset.ImageFile
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
Failed to prepare run for module Images
Traceback (most recent call last):
  File "C:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2146, in prepare_run
    if ((not module.prepare_run(workspace)) or
  File "C:\Trunk\CellProfiler\cellprofiler\modules\images.py", line 261, in prepare_run
    ifcls = J.class_for_name("org.cellprofiler.imageset.ImageFile")
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 1713, in class_for_name
    classname, True, ldr)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 908, in static_call
    result = fn(*nice_args)
  File "C:\Python27\lib\site-packages\javabridge-0.0.0-py2.7-win-amd64.egg\javabridge\jutil.py", line 888, in fn
    raise JavaException(jexception)
JavaException: org.cellprofiler.imageset.ImageFile
```

**Comment by 0x00B1** [comment]
```sh
$ python CellProfiler.py -c -r -p ~/Downloads/ExampleHumanImages/ExampleHuman.cppipe
running build_ext
skipping '_cpmorphology2.c' Cython extension (up-to-date)
skipping '_watershed.c' Cython extension (up-to-date)
skipping '_propagate.c' Cython extension (up-to-date)
skipping '_filter.c' Cython extension (up-to-date)
skipping '_lapjv.c' Cython extension (up-to-date)
skipping '_convex_hull.c' Cython extension (up-to-date)
skipping '_fastemd.cpp' Cython extension (up-to-date)
Did not find ij1-patcher.jar
Exception in thread "Thread-1" java.lang.ClassNotFoundException: loci.common.Location
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
Bioformats version does not support directory cacheing
Version: 2015-08-18T14:44:55 5b3567c / 20150818144455
Failed to stop Ilastik
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "CellProfiler.py", line 279, in main
    run_pipeline_headless(options, args)
  File "CellProfiler.py", line 911, in run_pipeline_headless
    from cellprofiler.pipeline import Pipeline, EXIT_STATUS, M_PIPELINE
  File "/Users/agoodman/Documents/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 24, in <module>
    import scipy.io.matlab
ImportError: No module named scipy.io.matlab
Failed to stop Ilastik
```

**Comment by 0x00B1** [comment]
A few issues:

- [ ] `Did not find ij1-patcher.jar`
- [ ] `Exception in thread "Thread-1" java.lang.ClassNotFoundException: loci.common.Location`
- [ ] `Bioformats version does not support directory cacheing`
- [ ] `Failed to stop Ilastik`
- [ ] `ImportError: No module named scipy.io.matlab`

**Comment by 0x00B1** [comment]
I haven’t installed Ilastik, so “Failed to stop Ilastik” is reasonable. However, it should probably determine whether a Ilastik thread exists before the thread is terminated.
