### ISSUE TITLE
Can't open any image

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1501]
Using new build on Mac: rev 5b3567c
Open Welcome Screen, first pipeline.  
Double-click any image in Images module:

```
Traceback (most recent call last):
  File "/Applications/CellProfiler_trunk_20150818.app/Contents/Resources/lib/python2.7/cellprofiler/gui/cpfigure.py", line 1901, in show_image
  File "bioformats/formatreader.pyc", line 523, in load_using_bioformats_url
  File "bioformats/formatreader.pyc", line 621, in __init__
  File "/Applications/CellProfiler_trunk_20150818.app/Contents/Resources/lib/python2.7/javabridge/jutil.py", line 1683, in make_instance
JavaException: loci/common/RandomAccessInputStream
```

**Comment by 0x00B1** [comment]
Another Java problem. Related to #1499.
