### ISSUE TITLE
Headless mode does not work with OMERO

### ISSUE THREAD

**Issue by emilroz** [CellProfiler/CellProfiler#1502]
Hi Guys,

I tried to work with the latest trunk RPM cellprofiler-2.1.2-468.20150813.433.f03b31fSNAPSHOT.x86_64.rpm to run the analysis in the headless mode against OMERO and got the exception:

```
OUT Traceback (most recent call last):
  File "/usr/cellprofiler/src/CellProfiler/CellProfiler.py", line 988, in <module>
    main(sys.argv)
  File "/usr/cellprofiler/src/CellProfiler/CellProfiler.py", line 184, in main
    set_omero_credentials_from_string(options.omero_credentials)
  File "/usr/cellprofiler/src/CellProfiler/CellProfiler.py", line 592, in set_omero_credentials_from_string
    from bioformats.formatreader import use_omero_credentials
  File "/opt/omero/CellProfiler/bioformats/__init__.py", line 20, in <module>
    import cellprofiler.utilities.jutil as jutil
ImportError: No module named jutil
```

Cheers,
Emil

**Comment by emilroz** [comment]
Just notice it's my fault, had another source directory on the path:  
File "/opt/omero/CellProfiler/bioformats/__init__.py", line 20, in <module>
