### ISSUE TITLE
wx ValueError

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1508]
Forgot to mention after #1499: Starting CP from the cmd line after 5b3567c4ed94b84f9fd4150528eda362bc13c06b also produces the following error (just the salient part here):
```
Bioformats version does not support directory cacheing
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "CellProfiler.py", line 253, in main
    pipeline_path = pipeline_path)
  File "c:\Trunk\CellProfiler\cellprofiler\cellprofilerapp.py", line 37, in __init__
    super(CellProfilerApp, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "c:\Trunk\CellProfiler\cellprofiler\cellprofilerapp.py", line 49, in OnInit
    CellProfilerSplash.GetHeight(), 255, 255, 255, 255)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_gdi.py", line 922,in EmptyBitmapRGBA
    return _gdi_._EmptyBitmapRGBA(width, height, red, green, blue, alpha)
ValueError: Width and height must be greater than zero
Failed to stop Ilastik
```
Do I need to bump up my version of wx as well?

**Comment by braymp** [comment]
Might be a hint here: http://www.cellprofiler.org/forum/viewtopic.php?f=18&t=3281

**Comment by braymp** [comment]
This is now the only error now remaining after f2da6c90d1c5f3aab3c2714da3650a41bb6d75c0

**Comment by braymp** [comment]
Also see this: http://wxpython-users.wxwidgets.narkive.com/H7X05Fg4/aquabutton-exception-on-resize

Sounds like it was fixed in 2.9.2? And is it the case that we need 2.9+ to work with 64-bit OSX?

**Comment by 0x00B1** [comment]
Nice work!

It appears it’s a bug in the super useful splash screen code. LOL

**Comment by braymp** [comment]
Using wx 3.0.2.0 fails with a similar error:
```
Traceback (most recent call last):
  File "CellProfiler.py", line 253, in main
    pipeline_path = pipeline_path)
  File "c:\Trunk\CellProfiler\cellprofiler\cellprofilerapp.py", line 37, in __init__
    super(CellProfilerApp, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "c:\Trunk\CellProfiler\cellprofiler\cellprofilerapp.py", line 48, in OnInit
    CellProfilerSplash.GetWidth(),
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 3272, in GetWidth
    return _core_.Image_GetWidth(*args, **kwargs)
PyAssertionError: C++ assertion "IsOk()" failed at ..\..\src\common\image.cpp(1739) in wxImage::GetWidth(): invalid image
```

**Comment by LeeKamentsky** [comment]
Haven't run things yet, but my first guess is that an icon has gone missing after being moved. The icon would fail to be loaded, given a size of zero and, voila, bug. Time for `git bisect`.
