### ISSUE TITLE
OverlayOutlines: Color preset not recognized

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1512]
Using the attached project (adapted from the welcome screen pipeline) gives this error at OverlayOutlines:
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2777, in do_step
  File "cellprofiler\modules\overlayoutlines.pyc", line 208, in run
  File "cellprofiler\modules\overlayoutlines.pyc", line 340, in run_color
  File "cellprofiler\modules\overlayoutlines.pyc", line 377, in get_outline
  File "cellprofiler\settings.pyc", line 2375, in to_rgb
ValueError: Unknown color: light magenta
```
I assume this is Windows-specific? Oddly, sampling some of the other presets appear to work fine; I just randomly happened to chose this one.

Attachments:
http://cellprofiler.org/issues/uploaded/o-jZmX/issue.cpproj

**Comment by braymp** [comment]
The color picker looks like this for light magenta:
![image](https://cloud.githubusercontent.com/assets/1186440/9467836/52750bda-4b0c-11e5-8f4d-ccbd0a011d73.png)
