### ISSUE TITLE
wxWindow::HandleEraseBkgnd() error on resize under wx 3.0.2

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1514]
Post- 00a867889f78963227d6fc00d7ad9b864c58cb54, attempting to resize the UI under wx 3.0.2 produces this error:
```
Traceback (most recent call last):
  File "C:\Trunk\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 1384, in DoGetVirtualSize
    return self.DoGetBestSize()
  File "C:\Trunk\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 1376, in DoGetBestSize
    for i, item in enumerate(self.items):
PyAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\window.cpp(4952) in wxWindow::HandleEraseBkgnd(): unknown background style
```

**Comment by 0x00B1** [comment]
Fixed
