### ISSUE TITLE
Exception in thread AnalysisRunner.interface

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1568]
```sh
test_01_01_start_and_stop (cellprofiler.tests.test_analysis.TestAnalysis) ... Exception in thread AnalysisRunner.interface:

Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner

    self.run()

  File "/usr/lib/python2.7/threading.py", line 504, in run

    self.__target(*self.__args, **self.__kwargs)

  File "/home/travis/build/CellProfiler/CellProfiler/cellprofiler/analysis.py", line 319, in interface

    attach()

  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/javabridge/jutil.py", line 718, in attach

    _javabridge.jb_attach()

  File "_javabridge.pyx", line 393, in _javabridge.jb_attach (_javabridge.c:3086)

AssertionError
```

**Comment by 0x00B1** [comment]
This is responsible for hanging our Travis build:

```sh
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated.
```

**Comment by 0x00B1** [comment]
This test needs to be run with the `--with-javabridge` flag.

**Comment by LeeKamentsky** [comment]
:+1:
