### ISSUE TITLE
OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1569]
```sh
Test recursion down the list of subfolders ... Traceback (most recent call last):

  File "/home/travis/build/CellProfiler/CellProfiler/cellprofiler/modules/tests/test_loadimages.py", line 1903, in test_06_07_subfolders

    os.rmdir(path)

OSError: [Errno 39] Directory not empty: '/tmp/tmppacozB/d2/d4'

Traceback (most recent call last):

  File "/home/travis/build/CellProfiler/CellProfiler/cellprofiler/modules/tests/test_loadimages.py", line 1903, in test_06_07_subfolders

    os.rmdir(path)

OSError: [Errno 39] Directory not empty: '/tmp/tmppacozB/d2'

Traceback (most recent call last):

  File "/home/travis/build/CellProfiler/CellProfiler/cellprofiler/modules/tests/test_loadimages.py", line 1903, in test_06_07_subfolders

    os.rmdir(path)

OSError: [Errno 39] Directory not empty: '/tmp/tmppacozB'

ERROR
```

**Comment by 0x00B1** [comment]
Fixed
