### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1573]
```sh
SLF4J: Found binding in [jar:file:/home/travis/build/CellProfiler/CellProfiler/imagej/jars/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: Found binding in [jar:file:/home/travis/build/CellProfiler/CellProfiler/imagej/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

**Comment by 0x00B1** [comment]
```xml
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.2</version>
    </dependency>
	 <dependency>
	    <groupId>ch.qos.logback</groupId>
	    <artifactId>logback-classic</artifactId>
	    <version>1.1.1</version>	 	
	 </dependency>
	 <dependency>
	    <groupId>ch.qos.logback</groupId>
	    <artifactId>logback-core</artifactId>
	    <version>1.1.1</version>	 	
	 </dependency>
```

**Comment by 0x00B1** [comment]
And:

```xml
    <dependency>
      <groupId>omero</groupId>
      <artifactId>common</artifactId>
      <version>${omero.version}</version>
      <exclusions>
        <exclusion>
          <groupId>ome</groupId>
          <artifactId>bio-formats</artifactId>
        </exclusion>
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-classic</artifactId>
        </exclusion>
        <exclusion>
          <groupId>hsqldb</groupId>
          <artifactId>hsqldb</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>ome</groupId>
      <artifactId>formats-gpl</artifactId>
      <version>${bio-formats.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-classic</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by braymp** [comment]
I've been getting a version of this running from source for some time now; it wasn't always the case, not sure when it started happening or why:
```
running build_ext
skipping '_cpmorphology2.c' Cython extension (up-to-date)
skipping '_watershed.c' Cython extension (up-to-date)
skipping '_propagate.c' Cython extension (up-to-date)
skipping '_filter.c' Cython extension (up-to-date)
skipping '_lapjv.c' Cython extension (up-to-date)
skipping '_convex_hull.c' Cython extension (up-to-date)
skipping '_fastemd.cpp' Cython extension (up-to-date)
running build_ext
java.lang.IllegalArgumentException: Cannot handle replace call to list in ij.Men
us's public static synchronized java.lang.String[] getPlugins()
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:724)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:649)
        at net.imagej.patcher.LegacyExtensions.addExtraPlugins(LegacyExtensions.java:475)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:175)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
        at net.imagej.patcher.JavaAgent.preinit(JavaAgent.java:147)
        at net.imagej.patcher.JavaAgent.premain(JavaAgent.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 15
        at javassist.CtClassType.getClassFile2(CtClassType.java:203)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:110)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:96)
        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:704)
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:681)
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:156)
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:329)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
        at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:390)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:354)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
        at javassist.compiler.Javac.compileStmnt(Javac.java:568)
        at javassist.expr.MethodCall.replace(MethodCall.java:234)
        at net.imagej.patcher.CodeHacker$7.edit(CodeHacker.java:685)
        at javassist.expr.ExprEditor.loopBody(ExprEditor.java:191)
        at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
        at javassist.CtBehavior.instrument(CtBehavior.java:618)
        at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1278)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:669)
        ... 17 more
Caused by: java.io.IOException: invalid constant type: 15
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
        at javassist.bytecode.ConstPool.read(ConstPool.java:970)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
        at javassist.bytecode.ClassFile.read(ClassFile.java:693)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
        at javassist.CtClassType.getClassFile2(CtClassType.java:190)
        ... 37 more
java.lang.IllegalArgumentException: Cannot handle app name in ij.ImageJ's public
 <init>(java.applet.Applet applet, int mode)
        at net.imagej.patcher.CodeHacker.replaceAppNameInCall(CodeHacker.java:445)
        at net.imagej.patcher.LegacyExtensions.insertAppNameHooks(LegacyExtensions.java:404)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:290)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
        at net.imagej.patcher.JavaAgent.preinit(JavaAgent.java:147)
        at net.imagej.patcher.JavaAgent.premain(JavaAgent.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 15
        at javassist.CtClassType.getClassFile2(CtClassType.java:203)
        at javassist.CtClassType.subtypeOf(CtClassType.java:303)
        at javassist.CtClassType.subtypeOf(CtClassType.java:318)
        at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:247)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:119)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:96)
        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:704)

        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:681)
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:156)
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:329)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
        at javassist.compiler.Javac.compileStmnt(Javac.java:568)
        at javassist.expr.MethodCall.replace(MethodCall.java:234)
        at net.imagej.patcher.CodeHacker$4.edit(CodeHacker.java:426)
        at net.imagej.patcher.CodeHacker$4.edit(CodeHacker.java:440)
        at javassist.expr.ExprEditor.loopBody(ExprEditor.java:219)
        at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
        at javassist.CtBehavior.instrument(CtBehavior.java:618)
        at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1278)
        at net.imagej.patcher.CodeHacker.replaceAppNameInCall(CodeHacker.java:401)
        ... 16 more
Caused by: java.io.IOException: invalid constant type: 15
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
        at javassist.bytecode.ConstPool.read(ConstPool.java:970)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
        at javassist.bytecode.ClassFile.read(ClassFile.java:693)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
        at javassist.CtClassType.getClassFile2(CtClassType.java:190)
        ... 37 more
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Trunk/cellprofiler/imagej/jars/slf4j-simpl
e-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Trunk/cellprofiler/imagej/jars/logback-cla
ssic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

**Comment by 0x00B1** [comment]
@braymp Me too. http://fiji.sc/bugzilla/show_bug.cgi?id=1008

**Comment by nickholway** [comment]
We see this too (v2.1.2/rev 51de649)
