### ISSUE TITLE
ApplyThreshold error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1585]
Run the attached pipeline with the Welcome Page fly pipeline.

```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 2836, in do_step
    self.__pipeline.run_module(module, workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/pipeline.py", line 2078, in run_module
    module.run(workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/modules/applythreshold.py", line 149, in run
    self.image_name.value, workspace, wants_local_threshold=True)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/modules/identify.py", line 875, in threshold_image
    image, mask, workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/modules/identify.py", line 1021, in get_threshold
    **kwparams)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/cpmath/threshold.py", line 125, in get_threshold
    threshold_method, image, mask, **kwargs)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/cpmath/threshold.py", line 189, in get_global_threshold
    return fn(image, mask, **kwargs)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/cpmath/threshold.py", line 298, in get_otsu_threshold
    image, d = log_transform(image)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/cpmath/threshold.py", line 808, in log_transform
    noise_min = orig_min + (orig_max-orig_min)/256.0+np.finfo(image.dtype).eps
  File "/Users/dlogan/github/CPhomebrew/Cellar/cellprofiler-dev-python/1/cpdev/lib/python2.7/site-packages/numpy/core/getlimits.py", line 109, in __new__
    raise ValueError("data type %r not inexact" % (dtype))
ValueError: data type <type 'numpy.int32'> not inexact
```

Note: I created this pipeline in the 2.1.1 release version which errored, but then got the same error in the master branch.

Attachments:
http://cellprofiler.org/issues/uploaded/q2KGHO/DLtest.cppipe

**Comment by LeeKamentsky** [comment]
Will fix in centrosome once it replaces cellprofiler.cpmath. Until then, multiply the image by .99999 in ImageMath to make it floating point?
