### ISSUE TITLE
Less scary msg when cancelling project file loading

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1613]
I cancelled the loading of a large project file in 2.1.1. It then gave the following error message:

```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 1212, in <lambda>
  File "cellprofiler\gui\pipelinecontroller.pyc", line 570, in do_open_workspace
  File "cellprofiler\pipeline.pyc", line 2573, in load_file_list
  File "cellprofiler\pipeline.pyc", line 2515, in add_urls
  File "cellprofiler\pipeline.pyc", line 3129, in notify_listeners
  File "cellprofiler\gui\pipelinecontroller.pyc", line 1355, in __on_pipeline_event
  File "cellprofiler\gui\pipelinecontroller.pyc", line 1410, in on_urls_added
  File "cellprofiler\gui\pathlist.pyc", line 261, in add_paths
  File "cellprofiler\preferences.pyc", line 1408, in report_progress
  File "cellprofiler\gui\pipelinecontroller.pyc", line 559, in progress_callback
Exception: User cancelled opening workspace
```

While correct, strictly speaking, this would be nicer as a message box or some such.

**Comment by mcquin** [comment]
@braymp Is "User cancelled opening project" friendlier?

Does a dialog pop up, or is this only logged to console?

**Comment by braymp** [comment]
"User cancelled opening project" is indeed friendlier. But IIRC, the exception appeared in the standard error dialog , even though it was not an error as such. A wx.MessageBox or MessageDialog is more innocuous, I think.

**Comment by AnneCarpenter** [comment]
As long as we are changing it, how about "You cancelled opening this project."?

**Comment by mcquin** [comment]
#2775
