### ISSUE TITLE
PyInstaller

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1625]
Use PyInstaller rather than py2app and py2exe.

**Comment by 0x00B1** [comment]
I spent a few hours working on this:

```sh
$ pyinstaller --additional-hooks-dir=./hooks CellProfiler.py --windowed
$ cp -r imagej/jars/ dist/CellProfiler/imagej/jars
$ cp -r artwork/ dist/CellProfiler/artwork/
$ mkdir -p dist/CellProfiler/imagej
```

works on OS X!

**Comment by 0x00B1** [comment]
Inside `./hooks`, I have a file `hook-scipy.linalg.py` with the contents:

```Python
hiddenimports = [
    'cython_blas',
    'cython_lapack',
]
```

**Comment by 0x00B1** [comment]
You’ll need to copy the modules too:

```sh
$ mv dist/CellProfiler/CellProfiler dist/CellProfiler/CellProfilerApp
$ mkdir dist/CellProfiler/cellprofiler
$ cp -r cellprofiler/modules/ dist/CellProfiler/cellprofiler/modules/
```

**Comment by 0x00B1** [comment]
```sh
$ mv dist/CellProfiler/CellProfiler dist/CellProfiler/CellProfilerApp
```

is required because CellProfiler expects the modules to reside in `cellprofiler/modules` and binary uses the name `CellProfiler`.

**Comment by 0x00B1** [comment]
Lingering issues:

```sh
$ /Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/CellProfilerK ; exit;
Plugin directory doesn't point to valid folder: /Users/agoodman/plugins
objc[49183]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jli/libjli.dylib and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/imagej/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/imagej/jars/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Could not load cellprofiler.modules.align
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/align.py", line 35, in <module>
    from scipy.fftpack import fft2, ifft2
ImportError: No module named fftpack
Could not load cellprofiler.modules.calculateimageoverlap
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/calculateimageoverlap.py", line 75, in <module>
    from contrib.english import ordinal
ImportError: No module named english
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/classifypixels.py", line 61, in <module>
    import vigra
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 58, in <module>
    import vigra
ImportError: No module named vigra
Could not load cellprofiler.modules.correctilluminationcalculate
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/correctilluminationcalculate.py", line 48, in <module>
    from centrosome.bg_compensate import backgr, MODE_AUTO, MODE_BRIGHT
ImportError: No module named bg_compensate
Could not load cellprofiler.modules.correctilluminationapply
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/correctilluminationapply.py", line 28, in <module>
    from cellprofiler.modules.correctilluminationcalculate import IC_BACKGROUND, IC_REGULAR
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/correctilluminationcalculate.py", line 48, in <module>
    from centrosome.bg_compensate import backgr, MODE_AUTO, MODE_BRIGHT
ImportError: No module named bg_compensate
Could not load cellprofiler.modules.displayplatemap
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/displayplatemap.py", line 29, in <module>
    from contrib.english import ordinal
ImportError: No module named english
Could not load cellprofiler.modules.exporttocellh5
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/exporttocellh5.py", line 27, in <module>
    import cellh5
ImportError: No module named cellh5
MySQL could not be loaded.
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 84, in <module>
    import MySQLdb
ImportError: No module named MySQLdb
Could not load cellprofiler.modules.filterobjects
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/filterobjects.py", line 59, in <module>
    import cellprofiler.utilities.rules as cprules
ImportError: No module named rules
Could not load cellprofiler.modules.flagimage
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/flagimage.py", line 49, in <module>
    import cellprofiler.utilities.rules as cprules
ImportError: No module named rules
Could not load cellprofiler.modules.identifyprimaryobjects
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/identifyprimaryobjects.py", line 198, in <module>
    from centrosome.watershed import fast_watershed as watershed
ImportError: No module named watershed
Could not load cellprofiler.modules.identifysecondaryobjects
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/identifysecondaryobjects.py", line 153, in <module>
    from centrosome.propagate import propagate
ImportError: No module named propagate
Could not load cellprofiler.modules.imagemath
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/imagemath.py", line 28, in <module>
    from contrib.english import ordinal
ImportError: No module named english
Could not load cellprofiler.modules.measureimagequality
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/measureimagequality.py", line 82, in <module>
    from centrosome.haralick import Haralick
ImportError: No module named haralick
Could not load cellprofiler.modules.measureobjectsizeshape
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/measureobjectsizeshape.py", line 130, in <module>
    import centrosome.zernike as cpmz
ImportError: No module named zernike
Could not load cellprofiler.modules.measureobjectradialdistribution
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/measureobjectradialdistribution.py", line 63, in <module>
    from centrosome.propagate import propagate
ImportError: No module named propagate
Could not load cellprofiler.modules.measureneurons
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/measureneurons.py", line 61, in <module>
    import centrosome.propagate as propagate
ImportError: No module named propagate
Could not load cellprofiler.modules.measuretexture
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/measuretexture.py", line 141, in <module>
    from centrosome.haralick import Haralick, normalized_per_object
ImportError: No module named haralick
Could not load cellprofiler.modules.run_imagej
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/run_imagej.py", line 51, in <module>
    import imagej.imageprocessor as ijiproc
ImportError: No module named imageprocessor
Could not load cellprofiler.modules.straightenworms
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/straightenworms.py", line 101, in <module>
    from untangleworms import C_WORM, F_CONTROL_POINT_X, F_CONTROL_POINT_Y
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/untangleworms.py", line 103, in <module>
    from centrosome.propagate import propagate
ImportError: No module named propagate
Could not load cellprofiler.modules.trackobjects
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/trackobjects.py", line 192, in <module>
    from centrosome.lapjv import lapjv
ImportError: No module named lapjv
Could not load cellprofiler.modules.untangleworms
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/untangleworms.py", line 103, in <module>
    from centrosome.propagate import propagate
ImportError: No module named propagate
could not load these modules: cellprofiler.modules.align,cellprofiler.modules.calculateimageoverlap,cellprofiler.modules.correctilluminationcalculate,cellprofiler.modules.correctilluminationapply,cellprofiler.modules.displayplatemap,cellprofiler.modules.exporttocellh5,cellprofiler.modules.filterobjects,cellprofiler.modules.flagimage,cellprofiler.modules.identifyprimaryobjects,cellprofiler.modules.identifysecondaryobjects,cellprofiler.modules.imagemath,cellprofiler.modules.measureimagequality,cellprofiler.modules.measureobjectsizeshape,cellprofiler.modules.measureobjectradialdistribution,cellprofiler.modules.measureneurons,cellprofiler.modules.measuretexture,cellprofiler.modules.run_imagej,cellprofiler.modules.straightenworms,cellprofiler.modules.trackobjects,cellprofiler.modules.untangleworms
```

**Comment by 0x00B1** [comment]
```sh
Could not load cellprofiler.modules.calculateimageoverlap
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/calculateimageoverlap.py", line 75, in <module>
    from contrib.english import ordinal
ImportError: No module named english
```

contrib isn’t included.

**Comment by 0x00B1** [comment]
```sh
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/classifypixels.py", line 61, in <module>
    import vigra
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 58, in <module>
    import vigra
ImportError: No module named vigra
```

vigra isn’t included.

**Comment by 0x00B1** [comment]
```sh
Could not load cellprofiler.modules.correctilluminationcalculate
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/correctilluminationcalculate.py", line 48, in <module>
    from centrosome.bg_compensate import backgr, MODE_AUTO, MODE_BRIGHT
ImportError: No module named bg_compensate
Could not load cellprofiler.modules.correctilluminationapply
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/correctilluminationapply.py", line 28, in <module>
    from cellprofiler.modules.correctilluminationcalculate import IC_BACKGROUND, IC_REGULAR
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/correctilluminationcalculate.py", line 48, in <module>
    from centrosome.bg_compensate import backgr, MODE_AUTO, MODE_BRIGHT
ImportError: No module named bg_compensate
```

centrosome.bg_compensate isn’t included.

**Comment by 0x00B1** [comment]
```sh
pyinstaller --additional-hooks-dir=./hooks --hidden-import=centrosome CellProfiler.py --windowed
```

fixes the centrosome issues.

**Comment by 0x00B1** [comment]
Lingering issues:

```sh
Last login: Wed Oct  7 16:23:01 on ttys001
wm0eb-41b:~ agoodman$ /Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/CellProfilerApp ; exit;
Plugin directory doesn't point to valid folder: /Users/agoodman/plugins
objc[50619]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jli/libjli.dylib and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/imagej/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/imagej/jars/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Could not load cellprofiler.modules.align
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/align.py", line 35, in <module>
    from scipy.fftpack import fft2, ifft2
ImportError: No module named fftpack
Could not load cellprofiler.modules.calculateimageoverlap
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/calculateimageoverlap.py", line 75, in <module>
    from contrib.english import ordinal
ImportError: No module named english
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/classifypixels.py", line 61, in <module>
    import vigra
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on 
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 58, in <module>
    import vigra
ImportError: No module named vigra
Could not load cellprofiler.modules.displayplatemap
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/displayplatemap.py", line 29, in <module>
    from contrib.english import ordinal
ImportError: No module named english
Could not load cellprofiler.modules.exporttocellh5
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/exporttocellh5.py", line 27, in <module>
    import cellh5
ImportError: No module named cellh5
MySQL could not be loaded.
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 84, in <module>
    import MySQLdb
ImportError: No module named MySQLdb
Could not load cellprofiler.modules.filterobjects
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/filterobjects.py", line 59, in <module>
    import cellprofiler.utilities.rules as cprules
ImportError: No module named rules
Could not load cellprofiler.modules.flagimage
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/flagimage.py", line 49, in <module>
    import cellprofiler.utilities.rules as cprules
ImportError: No module named rules
Could not load cellprofiler.modules.imagemath
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/imagemath.py", line 28, in <module>
    from contrib.english import ordinal
ImportError: No module named english
Could not load cellprofiler.modules.measureimagequality
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/measureimagequality.py", line 84, in <module>
    import centrosome.radial_power_spectrum as rps
ImportError: No module named radial_power_spectrum
Could not load cellprofiler.modules.run_imagej
Traceback (most recent call last):
  File "/Users/agoodman/github/CellProfiler/CellProfiler/cellprofiler/modules/__init__.py", line 303, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/agoodman/github/CellProfiler/CellProfiler/dist/CellProfiler/cellprofiler/modules/run_imagej.py", line 51, in <module>
    import imagej.imageprocessor as ijiproc
ImportError: No module named imageprocessor
could not load these modules: cellprofiler.modules.align,cellprofiler.modules.calculateimageoverlap,cellprofiler.modules.displayplatemap,cellprofiler.modules.exporttocellh5,cellprofiler.modules.filterobjects,cellprofiler.modules.flagimage,cellprofiler.modules.imagemath,cellprofiler.modules.measureimagequality,cellprofiler.modules.run_imagej
Version: 2015-10-07T18:34:55 442207f / 20151007183455
```

**Comment by 0x00B1** [comment]
```sh
$ pyinstaller --additional-hooks-dir=./hooks --hidden-import=centrosome --hidden-import="scipy.fftpack" CellProfiler.py --windowed
```

fixes the scipy.fftpack issue.

**Comment by 0x00B1** [comment]
```sh
$ pyinstaller --additional-hooks-dir=./hooks --hidden-import=centrosome --hidden-import="scipy.fftpack" --hidden-import="MySQL-python" CellProfiler.py --windowed
```

fixes the MySQL-python issue.

**Comment by 0x00B1** [comment]
```Python
# -*- mode: python -*-

import glob

def data(prefix, *filenames, **kw):
    import os

    def datafile(path, strip_path=True):
        parts = path.split('/')
        path = name = os.path.join(*parts)
        if strip_path:
            name = os.path.basename(path)
        return prefix + name, path, 'DATA'

    strip_path = kw.get('strip_path', True)
    return TOC(
        datafile(filename, strip_path=strip_path)
        for filename in filenames
        if os.path.isfile(filename))

artwork = data("./artwork/", *glob.glob("./artwork/*"))

JARS = data("./imagej/jars/", *glob.glob("./imagej/jars/*"))

modules = data("./cellprofiler/modules/", *glob.glob("./cellprofiler/modules/*"))

block_cipher = None

a = Analysis(
    [
        'CellProfiler.py'
    ],
    binaries=None,
    cipher=block_cipher,
    datas=None,
    excludes=None,
    hiddenimports=[
        'centrosome.bg_compensate',
        'centrosome.haralick',
        'centrosome.propagate',
        'centrosome.zernike',
        'scipy.fftpack',
        'scipy.linalg.cython_blas',
        'scipy.linalg.cython_lapack',
    ],
    hookspath=None,
    pathex=[
        './CellProfiler'
    ],
    runtime_hooks=None,
    win_no_prefer_redirects=None,
    win_private_assemblies=None,
)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='CellProfilerApp',
          debug=False,
          strip=None,
          upx=True,
          console=False )

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    artwork,
    JARS,
    modules,
    strip=None,
    upx=True,
    name='CellProfiler'
)

app = BUNDLE(
    coll,
    bundle_identifier=None,
    icon="./artwork/CellProfilerIcon.png",
    name='CellProfiler.app',
)
```

**Comment by braymp** [comment]
Just wondering, looking at the slashes: is os.path.join better? (I'm thinking for Windows here...)

**Comment by 0x00B1** [comment]
@braymp It is. I’m just hacking away. I’ll fix in post. :stuck_out_tongue:

**Comment by 0x00B1** [comment]
```Python
# -*- mode: python -*-

import glob

def data(prefix, *filenames, **kw):
    import os

    def datafile(path, strip_path=True):
        parts = path.split('/')
        path = name = os.path.join(*parts)
        if strip_path:
            name = os.path.basename(path)
        return prefix + name, path, 'DATA'

    strip_path = kw.get('strip_path', True)
    return TOC(
        datafile(filename, strip_path=strip_path)
        for filename in filenames
        if os.path.isfile(filename))

def get_pandas_path():
    import pandas
    pandas_path = pandas.__path__[0]
    return pandas_path

artwork = data("./artwork/", *glob.glob("./artwork/*"))

JARS = data("./imagej/jars/", *glob.glob("./imagej/jars/*"))

modules = data("./cellprofiler/modules/", *glob.glob("./cellprofiler/modules/*"))

block_cipher = None

a = Analysis(
    [
        'CellProfiler.py'
    ],
    binaries=None,
    cipher=block_cipher,
    datas=None,
    excludes=None,
    hiddenimports=[
        'cellh5',
        'cellprofiler.utilities.rules',
        'centrosome.bg_compensate',
        'centrosome.fastemd',
        'centrosome.haralick',
        'centrosome.lapjv',
        'centrosome.propagate',
        'centrosome.radial_power_spectrum',
        'centrosome.watershed',
        'centrosome.watershed',
        'centrosome.zernike',
        'contrib.english',
        'imagej.imageplus',
        'imagej.imageprocessor',
        'imagej.macros',
        'scipy.fftpack',
        'scipy.linalg.cython_blas',
        'scipy.linalg.cython_lapack',
        'sklearn.utils.sparsetools._graph_validation',
        'sklearn.utils.sparsetools._graph_tools',
        'sklearn.utils.lgamma',
        'sklearn.utils.weight_vector',
        'sklearn.tree._utils',
        'typedefs',
    ],
    hookspath=None,
    pathex=[
        './CellProfiler'
    ],
    runtime_hooks=None,
    win_no_prefer_redirects=None,
    win_private_assemblies=None,
)

dict_tree = Tree(get_pandas_path(), prefix='pandas', excludes=["*.pyc"])
a.datas += dict_tree
a.binaries = filter(lambda x: 'pandas' not in x[0], a.binaries)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    exclude_binaries=True,
    name='CellProfilerApp',
    debug=False,
    strip=None,
    upx=True,
    console=False
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    artwork,
    JARS,
    modules,
    strip=None,
    upx=True,
    name='CellProfiler'
)

app = BUNDLE(
    coll,
    bundle_identifier="org.cellprofiler.CellProfiler",
    icon="./artwork/CellProfilerIcon.png",
    name='CellProfiler.app',
)
```

manages to build everything with just two errors: cellh5 and vigra (i.e. the usual suspects).

**Comment by 0x00B1** [comment]
Installing form the wxPython works, installing from Homebrew doesn’t.

**Comment by 0x00B1** [comment]
Won’t fix (replaced by py2app and py2exe) 

However, this is worth revisiting in the future.
