### ISSUE TITLE
NamesAndTypes: UnboundLocalError

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1633]
To replicate:
* Load welcome screen pipeline
* In NamesAndTypes, add another image. Select [File][Does][Contain][01_POS002_D.TIF]
* In NamesAndTypes, select "metadata" as the image set matching method, and select "(None)" for all 4 channels.

Yields the following error:
```
Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 2094, in prepare_run
  File "cellprofiler\modules\namesandtypes.pyc", line 712, in prepare_run
  File "cellprofiler\modules\namesandtypes.pyc", line 931, in java_make_image_sets
  File "cellprofiler\modules\namesandtypes.pyc", line 1041, in java_make_image_sets_by_metadata
UnboundLocalError: local variable 'anchor_cf' referenced before assignment
```

**Comment by LeeKamentsky** [comment]
Fixed since 6099f41
https://github.com/CellProfiler/CellProfiler/blame/master/cellprofiler/modules/namesandtypes.py#L1112
