### ISSUE TITLE
ExportToDatabase: Experiment table creation fails if I/O folder contains special character

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1654]
To replicate:
- Load welcome screen pipeline
- Add ExportToDatabase module
- Switch db type to "SQLite"
- Point Default Output Folder to a folder which has an apostrophe (or probably any special ASCII char)

Running the pipeline will produce the following error:

```
Traceback (most recent call last):
  File "C:\Trunk\cellprofiler\cellprofiler\pipeline.py", line 2146, in prepare_run
    if ((not module.prepare_run(workspace)) or
  File "C:\Trunk\cellprofiler\cellprofiler\modules\exporttodatabase.py", line 1649, in prepare_run
    self.create_database_tables(self.cursor, workspace)
  File "C:\Trunk\cellprofiler\cellprofiler\modules\exporttodatabase.py", line 2210, in create_database_tables
    execute(cursor, statement, return_result=False)
  File "C:\Trunk\cellprofiler\cellprofiler\modules\exporttodatabase.py", line 262, in execute
    cursor.execute(query)
OperationalError: unrecognized token: "\"
```

**Comment by AnneCarpenter** [comment]
@0x00b1 does the commit solve the problem, can you tell?
