### ISSUE TITLE
UI problem: ExportToSpreadsheet / WX 3.0 / Centos

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1663]
On 26 October 2015 at 16:18, Christian Tischer <Christian.Tischer@embl.de> wrote:
Hi Lee,

maybe you saw my post on the cellprofiler-dev mailing list.

i am trying to run the latest CellProfiler from Git on CentoOS.

it almost works, but i sometimes get errors, for instance when clicking on "Select Measurements" in "ExportToSpreadsheet":

Traceback (most recent call last):
  File "/g/almf/software/CellProfiler-2015-10-23/cellprofiler/gui/moduleview.py", line 816, in on_press
    dlg = TreeCheckboxDialog(self.module_panel, d, size=(320,480))
  File "/g/almf/software/CellProfiler-2015-10-23/cellprofiler/gui/treecheckboxdialog.py", line 67, in __init__
    table_sizer.AddGrowableCol(2)
  File "/g/almf/software/anaconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 15367, in AddGrowableCol
    return _core_.FlexGridSizer_AddGrowableCol(*args, **kwargs)
PyAssertionError: C++ assertion "!m_cols || idx < (size_t)m_cols" failed at ./src/common/sizer.cpp(1980) in AddGrowableCol(): invalid column index

do you know what this could be?

Tischi

**Comment by LeeKamentsky** [comment]
Happens under windows and wx 3.0 too.
