### ISSUE TITLE
Docker build (tag:latest) has CP failures

### ISSUE THREAD

**Issue by purohit** [CellProfiler/CellProfiler#1672]
Hello,

I'm using the cellprofiler/cellprofiler:latest docker version (updated a few hours ago), and get errors like this where I had none before using `:master`:

```
Did not find ij1-patcher.jar
Version: 2015-10-29T13:53:19 d998c87 / 20151029135319
Failed to stop Ilastik
Pipeline saved with CellProfiler version 20140723174500
ilastik import: failed to import the ilastik. Please follow the instructions on 
    "http://www.ilastik.org" to install ilastik
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/modules/classifypixels.py", line 82, in <module>
    from ilastik.core.dataMgr import DataMgr, DataItemImage
ImportError: No module named ilastik.core.dataMgr
ilastik import: failed to import the ilastik. Please follow the instructions on 
                          "http://www.ilastik.org" to install ilastik
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 81, in <module>
    import ilastik_main
ImportError: No module named ilastik_main
Times reported are CPU times for each module, not wall-clock time
Thu Oct 29 17:09:57 2015: Image # 15177, module Images # 1: 0.00 sec
Thu Oct 29 17:09:57 2015: Image # 15177, module Metadata # 2: 0.00 sec
Warning:  org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
CP-JAVA 17:09:59.944 [Thread-0] ERROR loci.formats.ClassList - "loci.formats.in.SlideBook6Reader" is not valid.
CP-JAVA 17:10:00.684 [Thread-0] ERROR loci.formats.ClassList - "loci.formats.in.SlideBook6Reader" is not valid.
Exception in thread "Thread-0" java.lang.NullPointerException
    at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
CP-JAVA 17:10:03.010 [Thread-0] ERROR loci.formats.ClassList - "loci.formats.in.SlideBook6Reader" is not valid.
Exception in thread "Thread-0" java.lang.NullPointerException
    at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
CP-JAVA 17:10:03.869 [Thread-0] ERROR loci.formats.ClassList - "loci.formats.in.SlideBook6Reader" is not valid.
Exception in thread "Thread-0" java.lang.NullPointerException
    at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
CP-JAVA 17:10:04.446 [Thread-0] ERROR loci.formats.ClassList - "loci.formats.in.SlideBook6Reader" is not valid.
Exception in thread "Thread-0" java.lang.NullPointerException
    at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Thu Oct 29 17:09:58 2015: Image # 15177, module NamesAndTypes # 3: 3.99 sec
Thu Oct 29 17:10:05 2015: Image # 15177, module Groups # 4: 0.00 sec
Thu Oct 29 17:10:05 2015: Image # 15177, module IdentifyPrimaryObjects # 5: 6.03 sec
Thu Oct 29 17:10:15 2015: Image # 15177, module IdentifySecondaryObjects # 6: 12.53 sec
Thu Oct 29 17:10:38 2015: Image # 15177, module IdentifyTertiaryObjects # 7: 1.13 sec
Thu Oct 29 17:10:39 2015: Image # 15177, module MeasureObjectIntensity # 8: 28.77 sec
Error detected during run of module MeasureObjectNeighbors
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/pipeline.py", line 1830, in run_with_yield
    self.run_module(module, workspace)
  File "/usr/local/src/CellProfiler/cellprofiler/pipeline.py", line 2078, in run_module
    module.run(workspace)
  File "/usr/local/src/CellProfiler/cellprofiler/modules/measureobjectneighbors.py", line 440, in run
    distance_matrix[:, ~neighbor_has_pixels] = np.inf
IndexError: index 442 is out of bounds for axis 1 with size 435
Thu Oct 29 17:11:09 2015: Image # 15177, module MeasureObjectNeighbors # 9: 1.77 sec
Failed to stop Ilastik
```

If `:latest` is actually a bleeding-edge build, then I probably shouldn't be using it. However I'm not sure if this tag is supposed to work and needs fixing, or if I should just be using `:master` instead.

Thanks!

**Comment by LeeKamentsky** [comment]
Could you send us the pipeline? It looks like that is a bug. I recently made a change in that code, so perhaps I didn't account for a case. I could suggest a version to revert back to, but I'm not sure if it would help.

**Comment by purohit** [comment]
Sure thing, to whom shall I send it? imagingadmin@broadinstitute.org?

**Comment by LeeKamentsky** [comment]
leek@broadinstitute.org

**Comment by purohit** [comment]
Sent, thanks for looking into it!

**Comment by LeeKamentsky** [comment]
The issues/1672 should fix it - it was unrelated to the docker. Docker should work after pull req is taken.
