### ISSUE TITLE
Analysis worker failure

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1676]
Hi Lee,

when running CellProfiler on my Ubuntu VM, i get this error:

    Worker 0:   warnings.warn(msg, UserWarning)
    Worker 0: Traceback (most recent call last):
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/analysis_worker.py", line 325, in run
    Worker 0:     job = self.send(WorkRequest(self.current_analysis_id))
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/analysis_worker.py", line 582, in send
    Worker 0:     req.send_only(work_socket)
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/utilities/zmqrequest.py", line 268, in send_only
    Worker 0:     Communicable.send(self, socket)
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/utilities/zmqrequest.py", line 194, in send
    Worker 0:     buffers, copy=False)
    Worker 0:   File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 236, in send_multipart
    Worker 0:     self.send(msg, SNDMORE|flags, copy=copy, track=track)
    Worker 0:   File "socket.pyx", line 565, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5263)
    Worker 0:   File "socket.pyx", line 619, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5111)
    Worker 0:   File "message.pyx", line 183, in zmq.backend.cython.message.Frame.__cinit__ (zmq/backend/cython/message.c:1682)
    Worker 0: OverflowError: can't convert negative value to size_t
    Worker 0: Exception in thread WorkerThread:
    Worker 0: Traceback (most recent call last):
    Worker 0:   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    Worker 0:     self.run()
    Worker 0:   File "/usr/lib/python2.7/threading.py", line 763, in run
    Worker 0:     self.__target(*self.__args, **self.__kwargs)
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/analysis_worker.py", line 325, in run
    Worker 0:     job = self.send(WorkRequest(self.current_analysis_id))
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/analysis_worker.py", line 582, in send
    Worker 0:     req.send_only(work_socket)
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/utilities/zmqrequest.py", line 268, in send_only
    Worker 0:     Communicable.send(self, socket)
    Worker 0:   File "/home/adminuser/Software/CellProfilerGit-2015_10_31/CellProfiler/cellprofiler/utilities/zmqrequest.py", line 194, in send
    Worker 0:     buffers, copy=False)
    Worker 0:   File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 236, in send_multipart
    Worker 0:     self.send(msg, SNDMORE|flags, copy=copy, track=track)
    Worker 0:   File "socket.pyx", line 565, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5263)
    Worker 0:   File "socket.pyx", line 619, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5111)
    Worker 0:   File "message.pyx", line 183, in zmq.backend.cython.message.Frame.__cinit__ (zmq/backend/cython/message.c:1682)
    Worker 0: OverflowError: can't convert negative value to size_t
    Worker 0: 

any ideas?

**Comment by LeeKamentsky** [comment]
This appears to be an artifact of
https://github.com/zeromq/pyzmq/issues/533

and could be fixed by upgrading ZMQ as indicated. The bug appears to be in 13.1.0 which is what we use to build CellProfiler for Centos. It's possible that the handles have values < 0x80000000 on Centos and > 0x80000000 on Ubuntu and so it works on Centos and not on Ubuntu? I think we have test coverage that should exercise the bug, not sure why we haven't seen it ourselves.
