### ISSUE TITLE
"Caught exception in class loci.formats.in.ZeissLMSReader.isThisType"

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1686]
I see this exception (warning?) a lot on Mac dev, but it seemed excessive after this Plate Viewer fix #1684 .  There were about 24 of these Exceptions after I clicked on a well in Plate Viewer, and indeed there are about 24 sites per well.  The image did finally display (images and project file in #1684). I assumed it was a BioFormats issue and presumably always falls through to some other reader and wasn't a big issue before, but this took about 20 seconds to load the image(s), so I figured it was time to report it.

```
Processing /Users/dlogan/Desktop/PlateViewer_error.cpproj
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
Exception in thread "Thread-4" java.lang.NullPointerException
	at loci.formats.in.ZeissLMSReader.isThisType(ZeissLMSReader.java:76)
Caught exception in class loci.formats.in.ZeissLMSReader.isThisType
```

**Comment by LeeKamentsky** [comment]
The ZeissLMSReader is probably broken in our version of BioFormats (or prokaryote + bio formats). It's being bypassed and isn't the source of your problems. 
I measure 15 seconds reading the files using Python bioformats and the jars in bioformats which do not  produce the error message.

**Comment by dlogan** [comment]
OK thanks, then it just means that it takes that long to load these images.  I'm on VPN at home, so that probably accounts for the small-ish time difference.  Closing.

**Comment by melissalinkert** [comment]
The underlying problem in Bio-Formats should be fixed by https://github.com/openmicroscopy/bioformats/pull/2070, which is expected to be in the upcoming 5.1.6 release.

**Comment by LeeKamentsky** [comment]
Thx Melissa.
