### ISSUE TITLE
Double-click CSV in Images crashes

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1696]
Open ExampleSBS folder
Drag in file 1049_Metadata.csv
Double-click on it:

```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/cpfigure.py", line 1901, in show_image
    image = load_image_url(url)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/bioformats/formatreader.py", line 524, in load_using_bioformats_url
    with ImageReader(url=url) as rdr:
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/bioformats/formatreader.py", line 622, in __init__
    self.path)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/javabridge/jutil.py", line 1683, in make_instance
    raise JavaException(jexception)
JavaException: loci/common/RandomAccessInputStream
```

**Comment by dlogan** [comment]
P.S.  This still occurs even after I just refreshed my Mac install.
