### ISSUE TITLE
JavaException

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1698]
Within ExampleSBSImages folder, drag "ExampleSBSIllumination.cppipe" into the pipeline window.

Drag all the images and other metadata files into the Images window.

I see lots of Red Warning Triangles.

Click on Images > "Apply filters to the file list" and get this error:

```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/moduleview.py", line 1143, in callback
    self.__on_do_something(event, setting)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/moduleview.py", line 2073, in __on_do_something
    setting.on_event_fired()
  File "/Users/dlogan/github/CellProfiler/cellprofiler/settings.py", line 1945, in on_event_fired
    self.__callback(*self.__args)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/settings.py", line 3231, in fn_callback
    self.callback(*args, **kwargs)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 1478, in on_update_pathlist
    self.__workspace))
  File "/Users/dlogan/github/CellProfiler/cellprofiler/pipeline.py", line 2717, in get_filtered_file_list
    self.__prepare_run_module("Images", workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/pipeline.py", line 2702, in __prepare_run_module
    return modules[0].prepare_run(workspace)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/modules/images.py", line 261, in prepare_run
    ifcls = J.class_for_name("org.cellprofiler.imageset.ImageFile")
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/javabridge/jutil.py", line 1711, in class_for_name
    classname, True, ldr)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/javabridge/jutil.py", line 906, in static_call
    result = fn(*nice_args)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/javabridge/jutil.py", line 886, in fn
    raise JavaException(jexception)
JavaException: org.cellprofiler.imageset.ImageFile
```

**Comment by dlogan** [comment]
In fact, if you double-click on even a tif image from the same folder, you get a similar error:

```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/cpfigure.py", line 1901, in show_image
    image = load_image_url(url)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/bioformats/formatreader.py", line 524, in load_using_bioformats_url
    with ImageReader(url=url) as rdr:
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/bioformats/formatreader.py", line 622, in __init__
    self.path)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/javabridge/jutil.py", line 1683, in make_instance
    raise JavaException(jexception)
JavaException: loci/common/RandomAccessInputStream
```

**Comment by braymp** [comment]
Hmm, I don't get this error:
![image](https://cloud.githubusercontent.com/assets/1186440/11215537/bb8797a6-8d14-11e5-8267-94254a558c15.png)

**Comment by dlogan** [comment]
Actually, after just now re-doing the install (probably external_dependencies.py?) I don't get this.  Closing.
