### ISSUE TITLE
Oddity loading images/files in folders with non-standard chars

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1718]
This example uses files located in \argon\imaging_docs\People\mbray\github\cellprofiler\1718. Running CP from either master or 2.1.1 produces this behavior.
- Drag/drop the above folder into Images. This folder has an non-standard character between the '11' and the '3', and contains an image and a pipeline file.
- Dbl-clicking the pipeline to load it yields the following error:

```
Traceback (most recent call last):
  File "C:\Trunk\cellprofiler\cellprofiler\gui\pipelinecontroller.py", line 827, in do_load_pipeline
    if h5py.is_hdf5(pathname):
  File "C:\Python27\lib\site-packages\h5py\_hl\base.py", line 41, in is_hdf5
    return h5f.is_hdf5(fname)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2475)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2432)
  File "h5py\h5f.pyx", line 123, in h5py.h5f.is_hdf5 (D:\Build\h5py\h5py-2.5.x\h5py\h5f.c:2190)
IOError: Unable open file (Unable to open file: name = '\\argon\imaging_docs\people\mbray\github\cellprofiler\1718\11?3 examples for cellprofiler analysis\colortogray.cppipe', errno = 22, error message = 'invalid argument', flags = 0, o_flags = 0)
```
- However, dbl-clicking the image loads the display window just fine.

It seems weird that the former fails while the latter works.

**Comment by LeeKamentsky** [comment]
It looks like CP might be using the same code path for loading pipelines and projects and it figures out whether it's a pipeline or a project by calling h5py.h5f.is_hdf5. That's choking on the unicode file name somehow. Will check in greater detail next week.

**Comment by DavidStirling** [comment]
Should be fixed by native unicode support in Python 3, feel free to re-open if this recurs in CP4.
