### ISSUE TITLE
setup.py failure

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1724]
Based on https://github.com/CellProfiler/CellProfiler/pull/1674#issuecomment-161658369, I tried running  `python setup.py install` on my post-#1674 master. It eventually failed with the error below:
```
running install_scripts
Installing cellprofiler-script.py script to C:\Python27\Scripts
Installing cellprofiler.exe script to C:\Python27\Scripts
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\users\mbray\appdata\local\temp\easy_install-bvqj10\clint-0.5.1\clint\packages\colorama\initialise.py", line 17, in reset_all
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\users\mbray\appdata\local\temp\easy_install-bvqj10\clint-0.5.1\clint\packages\colorama\initialise.py", line 17, in reset_all
TypeError: 'NoneType' object is not callable
```

**Comment by LeeKamentsky** [comment]
Can you try manually installing clint?

    pip install clint

and if that doesn't work, try installing colorama, then clint?

    pip install colorama
    pip install clint

and if that doesn't work, can you do

    pip freeze

and post the results and if that doesn't work, can you do

    set PATH=%PATH%;c:\Program Files\Git\bin
    pip freeze

and if that doesn't work I will visit.

**Comment by braymp** [comment]
Running `pip install clint` worked; I got the exe. However running it gave me this error:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\cellprofiler-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3084, in <module>
    @_call_aside
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyzmq==13.1.0' distribution was not found and is required by cellprofiler
```
`pip freeze` shows I'm running pyzmq 14.7.0

**Comment by LeeKamentsky** [comment]
Yuck. The answer that will get you past that point is to change a line in setup.py from `"pyzmq==13.1.0"` to `"pyzmq"`. But having said that, I think there are later versions of pyzmq that don't work, so it's not an answer that would definitely work if you didn't have pyzmq installed.

It looks like you're not running in a virtual environment. I'm working on some install instructions for the CellProfiler development environment and if you were in a virtual environment, you could have better control over dependency versions and simultaneously have different copies of centrosome and cellprofiler running. For now, I'd just modify setup.py to get by today, but in the long run, you should `pip install virtualenv`, create and activate a virtual environment and then `python setup.py install` CellProfiler. This page has my very tentative instructions going forward: https://gist.github.com/LeeKamentsky/e09f5bbe446a83d89669

**Comment by braymp** [comment]
For the meantime, I chose to modify setup.py. 

Using your gist, I tried to install the remaining packages but encountered this error upon `pip install lxml`:
```
c:\Trunk\cellprofiler>pip install lxml
Collecting lxml
  Downloading lxml-3.5.0.tar.gz (3.8MB)
    100% |################################| 3.8MB 109kB/s
Installing collected packages: lxml
  Running setup.py install for lxml
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\mbray\\appdata\\local\\temp\\pip-build-_nlibt\\lxml
\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\mbray\appdata\local\temp\pip-9xuqqv-record\install-record.txt --single-version-externally-managed
 --compile:
    Building lxml version 3.5.0.
    Building without Cython.
    ERROR: 'xslt-config' is not recognized as an internal or external command,
    operable program or batch file.

    ** make sure the development packages of libxml2 and libxslt are installed *
*

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-2.7\lxml
    creating build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win-amd64-2.7\lxml\includ
es
    creating build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-2.7\lxml\html
    creating build\lib.win-amd64-2.7\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-2.7\lxml\i
soschematron
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-2.7\lxml\includes
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resour
ces\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\src\lxml
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc\lxml\includes -IC:\Python27\include -IC:\Python27\PC /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-2.7\Release\src\lxml\lxml.etree.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    lxml.etree.c
    src\lxml\includes\etree_defs.h(14) : fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    creating users
    creating users\mbray
    creating users\mbray\appdata
    creating users\mbray\appdata\local
    creating users\mbray\appdata\local\temp
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/libxml2 /Tcc:\users\mbray\appdata\local\temp\xmlXPathInitis6rdu.c /Fousers\mbray\appdata\local\temp\xmlXPathInitis6rdu.obj
    xmlXPathInitis6rdu.c
    c:\users\mbray\appdata\local\temp\xmlXPathInitis6rdu.c(1) : fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 insta
lled?
    *********************************************************************************
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\B
in\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\mbray\\appdata\\local\\temp\\pip-build-_nlibt\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\mbray\appdata\local\temp\pip-9xuqqv-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mbray\appdata\local\temp\pip-build-_nlibt\lxml
```
Installing the whl from Christoph's site got me around this.

**Comment by braymp** [comment]
The above was the only remaining error. Running `cellprofiler` now works.

**Comment by LeeKamentsky** [comment]
The error in the terminal window will be fixed once we tag prokaryote and upgrade CellProfiler to use it.  It's unfortunate, but not unprecedented that `lxml` does not pip install and it may be necessary for us to build a binary wheel of it for Python 2.7 or host a copy of Christoph Gohlke's build. Luckily, the lxml binary should only depend on Python 2.7, so we only need to solve the problem once (until we go to 3.x).

**Comment by 0x00B1** [comment]
I just tried this myself. I ran:

```sh
PS C:\Users\Allen Goodman> pip install --no-deps cellprofiler
```

then manually installed the deps from Christoph Gohlke's wheels. If he didn't have one (e.g. centrosome), I installed it using pip. Eventually:

PS C:\Users\Allen Goodman> pip freeze
cellh5==1.3.0
cellprofiler==0.0.3
centrosome==1.0.3
Cython==0.23.4
decorator==4.0.4
h5py==2.5.0
hmmlearn==0.1.1
ilastik==0.5.12
javabridge==1.0.11
lxml==3.4.4
matplotlib==1.4.3
MySQL-python==1.2.5
networkx==1.10
numpy==1.10.1
pandas==0.17.0
Pillow==3.0.0
pyparsing==2.0.6
PyQt4==4.11.4
python-bioformats==1.0.5
python-dateutil==2.4.2
pytz==2015.7
pyzmq==14.7.0
scikit-image==0.11.3
scikit-learn==0.16.1
scipy==0.16.1
six==1.10.0
vigranumpy==1.10.0
virtualenv==13.1.2
wheel==0.26.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0

PS C:\Users\Allen Goodman> python -m cellprofiler
```

ran without issue.
