### ISSUE TITLE
UnicodeDecodeError on loading pipeline and selecting Images

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1737]
In Mac build 20151207, unzip and load this pipeline:
[cellprofiler.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/66513/cellprofiler.cppipe.zip)
Upon clicking Images, I get the error below.

```
Traceback (most recent call last):
  File "/Applications/CellProfiler_20151207.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinelistview.py", line 914, in __on_item_activated
  File "/Applications/CellProfiler_20151207.app/Contents/Resources/lib/python2.7/cellprofiler/gui/moduleview.py", line 411, in set_selection
  File "wx/_core.pyc", line 13075, in SetValue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8: ordinal not in range(128)
```

I tried clearing my CP prefs with 
```
mv ~/Library/Preferences/CellProfilerLocal.cfg ~/Library/Preferences/CellProfilerLocal.cfg.OLD
```
and restarting CP, thinking it might be related to #1612 to no avail.

**Comment by 0x00B1** [comment]
Fixed
