### ISSUE TITLE
Mac source install error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1783]
A user reports on Mac 10.11 this error upon source install following our directions [here](https://github.com/CellProfiler/CellProfiler/wiki/*Source-installation-(OS-X)):

```
Traceback (most recent call last):
  File "/Users/Dirty/Library/Python/2.7/lib/python/site-packages/javabridge/jutil.py", line 247, in start_thread
    vm.create_mac(args, RQCLS, library_path, libjli_path)
  File "_javabridge.pyx", line 661, in _javabridge.JB_VM.create_mac (_javabridge.c:6563)
RuntimeError: Failed to create Java VM. Return code = -1
Failed to create Java VM
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Dirty/CellProfiler/CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/Users/Dirty/CellProfiler/cellprofiler/__main__.py", line 176, in main
    cp_start_vm()
  File "/Users/Dirty/CellProfiler/cellprofiler/utilities/cpjvm.py", line 179, in cp_start_vm
    max_heap_size = heap_size)
  File "/Users/Dirty/Library/Python/2.7/lib/python/site-packages/javabridge/jutil.py", line 284, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
```

The result of
```
java -version
```
is
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

Is the java version an issue?

**Comment by dlogan** [comment]
Related to #1611?

**Comment by LeeKamentsky** [comment]
Java 6 might be an issue at this point. I don't know.

I would ask the user to do the following at the console:

    > python -c "import javabridge;javabridge.start_vm();javabridge.JClassWrapper('java.lang.System').out.printf('Hello, %s.', 'world');javabridge.kill_vm()"
    Hello, world.

That should help us figure out if it's a CellProfiler or Javabridge issue. Also ask the user to run `/usr/libexec/java_home` and report the results.

**Comment by dirtyhemoglobin** [comment]
Hi - Thank you for the help, on running the following command:

`python -c "import javabridge;javabridge.start_vm();javabridge.JClassWrapper('java.lang.System').out.printf('Hello, %s.', 'world');javabridge.kill_vm()"
Hello, world.`

It returns:
```
Failed to open libjvm.dylib.

Traceback (most recent call last):
  File "/Users/Dirty/Library/Python/2.7/lib/python/site-packages/javabridge/jutil.py", line 247, in start_thread
    vm.create_mac(args, RQCLS, library_path, libjli_path)
  File "_javabridge.pyx", line 661, in _javabridge.JB_VM.create_mac (_javabridge.c:6563)
RuntimeError: Failed to create Java VM. Return code = -1
No handlers could be found for logger "javabridge.jutil"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Dirty/Library/Python/2.7/lib/python/site-packages/javabridge/jutil.py", line 284, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
```

Then, on running:

`Dirty$ /usr/libexec/java_home`

It returns:

`/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home`

Any ideas on how I should proceed next?  Thank you again for your help

**Comment by AnneCarpenter** [comment]
@dirtyhemoglobin Sorry for the delay, is this still a problem? If so, please do re-open this issue.

**Comment by MrMinimal64** [comment]
How has this been resolved? I encounter exactly the same problem. Before I tried it with Oracle's JDK 9 installed. The Q&A of the python-weka-wrapper docu says:

> Java environments that are not from Apple don’t seem to get picked up by Python correctly.  Simply install the Java 1.6 that Apple supplies on your system as well.

That's why I tried the old version then. Both tries fail similarly.

**Comment by dschetel** [comment]
Hey,
I am having the same problem.

```
python -c "import javabridge;javabridge.start_vm();javabridge.JClassWrapper('java.lang.System').out.printf('Hello, %s.', 'world');javabridge.kill_vm()" Hello, world.
```
leads to
```
No handlers could be found for logger "javabridge.locate"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/javabridge-1.0.17-py2.7-macosx-10.12-x86_64.egg/javabridge/jutil.py", line 273, in start_thread
    library_path = _find_mac_lib("libjvm")
  File "/usr/local/lib/python2.7/site-packages/javabridge-1.0.17-py2.7-macosx-10.12-x86_64.egg/javabridge/jutil.py", line 125, in _find_mac_lib
    (cmd, library), exc_info=1)
UnboundLocalError: local variable 'cmd' referenced before assignment
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/javabridge-1.0.17-py2.7-macosx-10.12-x86_64.egg/javabridge/jutil.py", line 314, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
```
```
/usr/libexec/java_home
```
returns
```
/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
```

Can you please give me any hints on how to set my system up?
Thank you!

**Comment by willgdjones** [comment]
I am having similar issues. My output is:


```
No handlers could be found for logger "javabridge.locate"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/_javabridge.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/_javabridge.so
  Expected in: flat namespace
 in `/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/_javabridge.so`
```

**Comment by AetherUnbound** [comment]
@MrMinimal64 do you mind pasting your stacktrace?
@dschetel I don't know that javabridge is confirmed to work with Java 10. Can you try installing Java 8 and see if it works there?
@willgdjones I suspect your error is different and unrelated to the above issues. Do you mind opening a ticket in the javabridge repo? https://github.com/LeeKamentsky/python-javabridge/issues

**Comment by MrMinimal64** [comment]
Sorry. I don't have the setup any more.

**Comment by dschetel** [comment]
@AetherUnbound Thank you for your suggestion!
I tried again with Java 8.
The error message using Python 3.6 is still the same:

```
Could not find Java JRE compatible with x86_64 architecture
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dgs/miniconda3/envs/biochem/lib/python3.6/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/dgs/miniconda3/envs/biochem/lib/python3.6/site-packages/javabridge/jutil.py", line 155, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/dgs/miniconda3/envs/biochem/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/dgs/miniconda3/envs/biochem/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/dgs/miniconda3/envs/biochem/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so
```

When using Python 2.7, the error message is very similar to what @MrMinimal64  posted:

```
No handlers could be found for logger "javabridge.locate"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dgs/miniconda3/envs/biochem_python27/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/dgs/miniconda3/envs/biochem_python27/lib/python2.7/site-packages/javabridge/jutil.py", line 155, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/dgs/miniconda3/envs/biochem_python27/lib/python2.7/site-packages/javabridge/_javabridge.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/dgs/miniconda3/envs/biochem_python27/lib/python2.7/site-packages/javabridge/_javabridge.so
  Expected in: flat namespace
 in /Users/dgs/miniconda3/envs/biochem_python27/lib/python2.7/site-packages/javabridge/_javabridge.so
```

Does this help to narrow down, what the problem is exactly?

**Comment by willgdjones** [comment]
Hi @AetherUnbound - I just opened an issue on the Javabridge package.
