### ISSUE TITLE
ExportToDatabase missing MySQL option. MySQLdb not installed

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1812]
I launched today's Mac Dev CP.  ExportToDatabase settings say:
![image](https://cloud.githubusercontent.com/assets/1225595/13498926/fbabdcca-e129-11e5-9bab-f72f09c982fc.png)

MySQLdb is not importing.  Do the Mac Installation Instructions just need to be updated to import mysqldb?

Terminal output:
```
(CellProfiler-2.7.10)[dlogan@wme2f-11a:~/.unison]$ python -m CellProfiler
Plugin directory doesn't point to valid folder: /Users/dlogan/Library/Application Support/Unison/plugins
objc[88977]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jli/libjli.dylib and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
java.lang.IllegalArgumentException: Cannot handle replace call to list in ij.Menus's public static synchronized java.lang.String[] getPlugins()
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:725)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:650)
	at net.imagej.patcher.LegacyExtensions.addExtraPlugins(LegacyExtensions.java:477)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:175)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
	at net.imagej.patcher.JavaAgent.preinit(JavaAgent.java:147)
	at net.imagej.patcher.JavaAgent.premain(JavaAgent.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 18
	at javassist.CtClassType.getClassFile2(CtClassType.java:203)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:110)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:96)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:704)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:681)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:156)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:329)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:390)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:354)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.Javac.compileStmnt(Javac.java:568)
	at javassist.expr.MethodCall.replace(MethodCall.java:234)
	at net.imagej.patcher.CodeHacker$7.edit(CodeHacker.java:686)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:191)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
	at javassist.CtBehavior.instrument(CtBehavior.java:618)
	at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1278)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:670)
	... 17 more
Caused by: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
	at javassist.bytecode.ConstPool.read(ConstPool.java:970)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
	at javassist.bytecode.ClassFile.read(ClassFile.java:693)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
	at javassist.CtClassType.getClassFile2(CtClassType.java:190)
	... 37 more
java.lang.IllegalArgumentException: Cannot handle app name in ij.ImageJ's public <init>(java.applet.Applet applet, int mode)
	at net.imagej.patcher.CodeHacker.replaceAppNameInCall(CodeHacker.java:446)
	at net.imagej.patcher.LegacyExtensions.insertAppNameHooks(LegacyExtensions.java:406)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:291)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
	at net.imagej.patcher.JavaAgent.preinit(JavaAgent.java:147)
	at net.imagej.patcher.JavaAgent.premain(JavaAgent.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 18
	at javassist.CtClassType.getClassFile2(CtClassType.java:203)
	at javassist.CtClassType.subtypeOf(CtClassType.java:303)
	at javassist.CtClassType.subtypeOf(CtClassType.java:318)
	at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:247)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:119)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:96)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:704)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:681)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:156)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:329)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.Javac.compileStmnt(Javac.java:568)
	at javassist.expr.MethodCall.replace(MethodCall.java:234)
	at net.imagej.patcher.CodeHacker$4.edit(CodeHacker.java:427)
	at net.imagej.patcher.CodeHacker$4.edit(CodeHacker.java:441)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:219)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
	at javassist.CtBehavior.instrument(CtBehavior.java:618)
	at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1278)
	at net.imagej.patcher.CodeHacker.replaceAppNameInCall(CodeHacker.java:402)
	... 16 more
Caused by: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
	at javassist.bytecode.ConstPool.read(ConstPool.java:970)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
	at javassist.bytecode.ClassFile.read(ClassFile.java:693)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
	at javassist.CtClassType.getClassFile2(CtClassType.java:190)
	... 37 more
vigra import: failed to import the vigra library. Please follow the instructions on
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/dlogan/CellProfiler/cellprofiler/modules/classifypixels.py", line 50, in <module>
    import vigra
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/Users/dlogan/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 47, in <module>
    import vigra
ImportError: No module named vigra
/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Could not load cellprofiler.modules.exporttocellh5
Traceback (most recent call last):
  File "/Users/dlogan/CellProfiler/cellprofiler/modules/__init__.py", line 292, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/Users/dlogan/CellProfiler/cellprofiler/modules/exporttocellh5.py", line 30, in <module>
    import cellh5.cellh5write
ImportError: No module named cellh5write
MySQL could not be loaded.
Traceback (most recent call last):
  File "/Users/dlogan/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 74, in <module>
    import MySQLdb
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: dlopen(/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/_mysql.so, 2): Library not loaded: /usr/local/opt/mysql/lib/libmysqlclient.18.dylib
  Referenced from: /usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/_mysql.so
  Reason: image not found
could not load these modules: cellprofiler.modules.exporttocellh5
Version: 2016-02-18T20:36:28 dc5df45 / 20160218203628
Warning:  org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Exception in thread "Thread-1" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
Exception in thread "Thread-1" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
Exception in thread "Thread-1" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
```

**Comment by 0x00B1** [comment]
Are you installing with pip?

**Comment by dlogan** [comment]
Yes, I followed the directions here: https://github.com/CellProfiler/CellProfiler/wiki/*Source-installation-(OS-X) within the last couple weeks.

**Comment by dlogan** [comment]
@0x00B1 fixed.  Seems I had another mysql package that may have been in conflict.  Works for me!
