### ISSUE TITLE
KeyError: "Unable to open object (Can't insert duplicate key)"

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler#1825]
I've been trying to run my pipeline (with ~1000 images), but there is always a point I get an error. The individual images seem fine, but when I try to analyze them all, it can't finish (it finishes when there are like 4 images but not everything). This is from the CP e5117de. Any ideas?

Traceback (most recent call last):
  File "wx/_core.pyc", line 16766, in <lambda>
  File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinecontroller.py", line 2697, in on_stop_analysis
  File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/measurements.py", line 364, in __getitem__
  File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/measurements.py", line 960, in get_measurement
  File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/hdf5_dict.py", line 367, in __getitem__
  File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/hdf5_dict.py", line 644, in get_dataset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2458)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2415)
  File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/h5py/_hl/group.py", line 164, in __getitem__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2458)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2415)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5o.c:3507)
KeyError: "Unable to open object (Can't insert duplicate key)"

**Comment by LeeKamentsky** [comment]
Can you post the pipeline?

**Comment by jhung0** [comment]
Can you open this?
[segmentation_train.cpproj.txt](https://github.com/CellProfiler/CellProfiler/files/165907/segmentation_train.cpproj.txt)

**Comment by LeeKamentsky** [comment]
Nope. Can you do File / Export / Pipeline instead?

**Comment by jhung0** [comment]
[segmentation_train.cppipe.txt](https://github.com/CellProfiler/CellProfiler/files/165914/segmentation_train.cppipe.txt)

**Comment by jhung0** [comment]
Were you able to run it?

**Comment by LeeKamentsky** [comment]
oops must have missed that. I'm going to work on this today.

**Comment by LeeKamentsky** [comment]
ExportToSpreadsheet writes its measurements at the end of a run. For 1000 images and millions of cells, this is painfully slow. You should consider shorter runs or using ExportToDatabase with a sqlite database instead. The crash you reported happens if you have configured to write out the measurements to an HDF5 file - you probably don't want to do this. If you click on "View output settings", you probably want to pick "Do not write MATLAB or HDF5 files" (see picture below)

I will look into recreating the problem and fixing, though.
![image](https://cloud.githubusercontent.com/assets/660469/13673856/f16926e4-e6a8-11e5-98e0-feaba85db6b6.png)

**Comment by jhung0** [comment]
Ok I'll try that thanks. I would like a CSV output though for future analysis.

**Comment by jhung0** [comment]
Oh, wait I already had it as Do not write ...

**Comment by LeeKamentsky** [comment]
Just looked - I believe you, sorry about that.

**Comment by jhung0** [comment]
Is there a way to run analyses "in series" like images that contain 0001 first, then those that contain 0002, etc?

**Comment by LeeKamentsky** [comment]
Yes - you can group your images by extracting "0001" and "0002" etc as metadata and then create a group using that metadata. After that, you can run CellProfiler like this

    python CellProfiler.py -c -r -g Metadata_Capture=154757-0002 -p -o <path-to-output>/154757-002 segmentation_train.cpproj

Pipeline that does grouping: 
[issue1825.cppipe.txt](https://github.com/CellProfiler/CellProfiler/files/167468/issue1825.cppipe.txt)

**Comment by jhung0** [comment]
So to do that, I will need to make a batch file first?

**Comment by dlogan** [comment]
A side note(?): Your CP seems to be running from a mounted disk
> /Volumes/CellProfiler/CellProfiler.app/...  

That might work fine, but I suspect you could run into troubles if CP tries to write any tmp files to the CP 'install' directory.

**Comment by LeeKamentsky** [comment]
Nope, no batch file needed.

**Comment by jhung0** [comment]
When I run
```
python CellProfiler.py -c -r -g Metadata_Capture=0001 -p -o /Volumes/imaging_analysis/2010_08_21_Malaria_MartiLab_MatthiasMarti_HSPH/2016_03_07/CP_output/ /Volumes/imaging_analysis/2010_08_21_Malaria_MartiLab_MatthiasMarti_HSPH/2016_03_07/segmentation_train.cpproj
```
it says 

IOError: Could not find file, -o
Failed to stop Ilastik
Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/__main__.py", line 252, in main
    run_pipeline_headless(options, args)
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/__main__.py", line 887, in run_pipeline_headless
    pipeline.load(options.pipeline_filename)
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/pipeline.py", line 852, in load
    raise IOError("Could not find file, " + fd_or_filename)
IOError: Could not find file, -o

**Comment by LeeKamentsky** [comment]
you need your .cpproj file after the -p switch

**Comment by jhung0** [comment]
any clue why the source version would say this 
ValueError: Could not find the ImageMath module?
I checked and imagemath.py is there

**Comment by LeeKamentsky** [comment]
There should be an exception previous to "ValueError" that explains why the ImageMath module couldn't be loaded.

**Comment by LeeKamentsky** [comment]
Looks pretty good. If the image # keeps incrementing you are in good shape.

**Comment by jhung0** [comment]
Do I need to explicitly choose an output directory or should it know from the project file?
At the end of the run, it shows
```
Thu Mar 10 12:50:25 2016: Image # 85, module ExportToSpreadsheet # 19: 0.00 sec
Failed to stop Ilastik
Exception TypeError: "'NoneType' object is not callable" in '_javabridge.JB_Object.__dealloc__' ignored
Exception TypeError: "'NoneType' object is not callable" in '_javabridge.JB_Object.__dealloc__' ignored
Exception TypeError: "'NoneType' object is not callable" in '_javabridge.JB_Object.__dealloc__' ignored
```

**Comment by LeeKamentsky** [comment]
You should explicitly choose an output directory. This is a good thing because you can use different ones for different runs.

the message at the end is expected.

**Comment by AnneCarpenter** [comment]
@jhung0 Is there anything left in this issue to be addressed? If so, please clarify and re-open it.
