### ISSUE TITLE
Help/About on Windows Release

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1838]
Throws the following exception:

    Traceback (most recent call last):
      File "cellprofiler\gui\cpframe.pyc", line 996, in __on_help_about
      File "wx\_controls.pyc", line 997, in __init__
      File "encodings\cp1252.pyc", line 15, in decode
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 865: character maps to <undefined>

**Comment by 0x00B1** [comment]
Fixed
