### ISSUE TITLE
Workspace viewer error

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1888]
Loading the welcome screen pipeline, going into test mode and pressing the workspace viewer button yields
```
Traceback (most recent call last):
  File "C:/Users/brayma2/Desktop/GitHub/CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 3239, in on_debug_view_workspace
    cellprofiler.gui.viewworkspace.show_workspace_viewer(self.__frame, workspace)
  File "C:/Users/brayma2/Desktop/GitHub/CellProfiler\cellprofiler\gui\viewworkspace.py", line 23, in show_workspace_viewer
    __the_workspace_viewer = ViewWorkspace(parent, workspace)
  File "C:/Users/brayma2/Desktop/GitHub/CellProfiler\cellprofiler\gui\viewworkspace.py", line 235, in __init__
    help_menu_items=cellprofiler.gui.help.WV_FIGURE_HELP)
TypeError: __init__() takes exactly 1 argument (5 given)
```

**Comment by 0x00B1** [comment]
Thanks, @braymp. Fixed by #1889. Will merge shortly.
