### ISSUE TITLE
Help/About on Mac nightly

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1898]
```
Traceback (most recent call last):
  File "/Applications/CellProfiler_nightly_20120328.app/Contents/Resources/lib/python2.7/cellprofiler/gui/cpframe.py", line 986, in about
  File "/Applications/CellProfiler_nightly_20120328.app/Contents/Resources/lib/python2.7/cellprofiler/gui/dialog.py", line 11, in __init__
  File "wx/_misc.pyc", line 6672, in SetCopyright
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)
```

related to #1838?

**Comment by 0x00B1** [comment]
No, but it's fixed in master.

**Comment by dlogan** [comment]
right - sorry, I'm on the pixel_classifier branch
