### ISSUE TITLE
About CellProfiler error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1954]
Mac nightly ~2016_04_05
Click "CellProfiler Menu > About CellProfiler":

```
Traceback (most recent call last):
  File "/Applications/CellProfiler_nightly_20160406.app/Contents/Resources/lib/python2.7/cellprofiler/gui/cpframe.py", line 981, in about
  File "/Applications/CellProfiler_nightly_20160406.app/Contents/Resources/lib/python2.7/cellprofiler/gui/dialog.py", line 11, in __init__
  File "wx/_misc.pyc", line 6672, in SetCopyright
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)
```

Related to #1887?

**Comment by dlogan** [comment]
Master fails with this different error:
```
Traceback (most recent call last):
  File "cellprofiler/gui/cpframe.py", line 981, in about
    info = cellprofiler.gui.dialog.AboutDialogInfo()
  File "cellprofiler/gui/dialog.py", line 15, in __init__
    self.Version = pkg_resources.get_distribution("cellprofiler").version
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 551, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'cellprofiler' distribution was not found and is required by the application
```

**Comment by braymp** [comment]
See this issue? #1887

**Comment by dlogan** [comment]
Yep, `pip install -e .` did it!

@0x00B1 should I add this to the Mac (and Windows) source install instructions ?https://github.com/CellProfiler/CellProfiler/wiki/*Source-installation-(OS-X) 
I can then close this.

**Comment by dlogan** [comment]
This bug is still in the nightly build (as of today 2016.04.19) so I'll leave it open.
