### ISSUE TITLE
Can't find Java Virtual Machine

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1955]
Nightly build (2016_04_06) on Win7.

Upon launch, immediately errors with
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Developer>"C:\Program Files\CellProfiler_nightly_2016_04_06\CellProfile
r.exe"
Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
  File "cellprofiler\__main__.pyc", line 180, in main
  File "cellprofiler\utilities\cpjvm.pyc", line 3, in <module>
  File "javabridge\__init__.pyc", line 28, in <module>
  File "javabridge\jutil.pyc", line 137, in <module>
  File "javabridge\jutil.pyc", line 125, in _find_jvm
javabridge.jutil.JVMNotFoundError: Can't find the Java Virtual Machine
```

My Java appears up to date
```
C:\Users\Developer>java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by LeeKamentsky** [comment]
Do you have JAVA_HOME set? If so, please do not set it. I just downloaded ea20858 and it worked for me.

**Comment by dlogan** [comment]
Aha -- removing JAVA_HOME worked, thanks!  I think JAVA_HOME is set by default on the VMs, oops :/
