### ISSUE TITLE
PyAssertionError in 2.4.0rc1

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1989]
After bumping up to 2.4.0rc1 on master, starting CP gets me:
```
ImportError: No module named vigra
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\__main__.py",line 229, in main
    app = App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\app.py", line 24, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "C:\python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "C:\python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\app.py", line 32, in OnInit
    self.frame = cellprofiler.gui.cpframe.CPFrame(None, -1, "Cell Profiler")
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\cpframe.py", line 302, in __init__
    self.__attach_views()
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\cpframe.py", line 1147, in __attach_views
    self.__pipeline_controller = cellprofiler.gui.pipelinecontroller.PipelineController(self.__workspace, self)
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\pipelinecontroller.py", line 66, in __init__
    self.__add_module_frame = cellprofiler.gui.addmoduleframe.AddModuleFrame(frame, -1, "Add modules")
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\addmoduleframe.py", line 106, in __init__
    self.__on_category_selected(None)
  File "c:\Users\brayma2\Desktop\GitHub\cellprofiler\cellprofiler\gui\addmoduleframe.py", line 144, in __on_category_selected
    self.__module_list_box.Select(0)
  File "C:\python27\lib\site-packages\wx-3.0-msw\wx\_controls.py", line 1203, in
 Select
    return _controls_.ListBox_Select(*args, **kwargs)
PyAssertionError: C++ assertion "N == (-1) || IsValid(N)" failed at ..\..\src\msw\listbox.cpp(286) in wxListBox::DoSetSelection(): invalid index in wxListBox::SetSelection
Failed to stop Ilastik
```

**Comment by 0x00B1** [comment]
Fixed and merged! Thanks @braymp. Windows will settle down soon. I promise. :stuck_out_tongue_closed_eyes:
