### ISSUE TITLE
ClassifyPixels error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1991]
Perhaps this won't matter after ClassifyPixels is removed, but this error is thrown in master when you add ClassifyPixels on Mac:

```
Traceback (most recent call last):
  File "cellprofiler/gui/pipelinelistview.py", line 911, in __on_item_activated
    self.__module_view.set_selection(module.module_num)
  File "cellprofiler/gui/moduleview.py", line 595, in set_selection
    control = self.make_html_control(v, control)
  File "cellprofiler/gui/moduleview.py", line 1955, in make_html_control
    from cellprofiler.gui.html import HtmlClickableWindow
ImportError: cannot import name HtmlClickableWindow
```

**Comment by mcquin** [comment]
It appears that ClassifyPixels is dead.
