### ISSUE TITLE
CP terminates immediately, and won’t start Java, even though it is installed

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2041]
On my company (i.e. locked down) laptop, I installed a recent CP nightly in my user directory, seemingly successfully, since I didn’t have admin privileges to do this in /Applications.  (Maybe this is a red herring though.)  

Further, Java 1.8 is installed ok (see below), and it is 64 bit since this is the download name: jre-8u92-macosx-x64.dmg.  
￼
![image](https://cloud.githubusercontent.com/assets/1225595/15441635/fd38e6b0-1ea9-11e6-976c-0fa34b3bce72.png)

But on launch, CP terminates quickly  and this is the Console output:

```
5/20/16 3:36:06.610 PM lsd[1002]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
5/20/16 3:36:18.301 PM lsd[1002]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
5/20/16 3:36:18.765 PM CellProfiler[13938]: Unable to find any JVMs matching architecture "x86_64".
5/20/16 3:36:18.765 PM CellProfiler[13938]: No Java runtime present, try --request to install.
5/20/16 3:36:18.767 PM CellProfiler[13938]: Failed to run /usr/libexec/java_home, defaulting to best guess for Java
5/20/16 3:36:18.767 PM CellProfiler[13938]: Traceback (most recent call last):
5/20/16 3:36:18.767 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/javabridge/locate.py", line 42, in find_javahome
5/20/16 3:36:18.767 PM CellProfiler[13938]:   File "subprocess.pyc", line 573, in check_output
5/20/16 3:36:18.767 PM CellProfiler[13938]: CalledProcessError: Command '['/usr/libexec/java_home', '--arch', 'x86_64']' returned non-zero exit status 1
5/20/16 3:36:19.245 PM CellProfiler[13938]: Unable to find any JVMs matching architecture "x86_64".
5/20/16 3:36:19.248 PM CellProfiler[13938]: No Java runtime present, try --request to install.
5/20/16 3:36:19.249 PM CellProfiler[13938]: Failed to run /usr/libexec/java_home, defaulting to best guess for Java
5/20/16 3:36:19.249 PM CellProfiler[13938]: Traceback (most recent call last):
5/20/16 3:36:19.249 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/javabridge/locate.py", line 42, in find_javahome
5/20/16 3:36:19.249 PM CellProfiler[13938]:   File "subprocess.pyc", line 573, in check_output
5/20/16 3:36:19.249 PM CellProfiler[13938]: CalledProcessError: Command '['/usr/libexec/java_home', '--arch', 'x86_64']' returned non-zero exit status 1
5/20/16 3:36:19.264 PM CellProfiler[13938]: Unable to find any JVMs matching architecture "x86_64".
5/20/16 3:36:19.264 PM CellProfiler[13938]: No Java runtime present, try --request to install.
5/20/16 3:36:19.266 PM CellProfiler[13938]: Failed to run /usr/libexec/java_home, defaulting to best guess for Java
5/20/16 3:36:19.266 PM CellProfiler[13938]: Traceback (most recent call last):
5/20/16 3:36:19.266 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/javabridge/locate.py", line 42, in find_javahome
5/20/16 3:36:19.266 PM CellProfiler[13938]:   File "subprocess.pyc", line 573, in check_output
5/20/16 3:36:19.266 PM CellProfiler[13938]: CalledProcessError: Command '['/usr/libexec/java_home', '--arch', 'x86_64']' returned non-zero exit status 1
5/20/16 3:36:19.281 PM CellProfiler[13938]: Failed to find libjvm
5/20/16 3:36:19.298 PM CellProfiler[13938]: Unable to find any JVMs matching architecture "x86_64".
5/20/16 3:36:19.299 PM CellProfiler[13938]: No Java runtime present, try --request to install.
5/20/16 3:36:19.300 PM CellProfiler[13938]: Failed to run /usr/libexec/java_home, defaulting to best guess for Java
5/20/16 3:36:19.300 PM CellProfiler[13938]: Traceback (most recent call last):
5/20/16 3:36:19.300 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/javabridge/locate.py", line 42, in find_javahome
5/20/16 3:36:19.301 PM CellProfiler[13938]:   File "subprocess.pyc", line 573, in check_output
5/20/16 3:36:19.301 PM CellProfiler[13938]: CalledProcessError: Command '['/usr/libexec/java_home', '--arch', 'x86_64']' returned non-zero exit status 1
5/20/16 3:36:19.317 PM CellProfiler[13938]: Failed to find libjli
5/20/16 3:36:19.317 PM CellProfiler[13938]: Traceback (most recent call last):
5/20/16 3:36:19.317 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/javabridge/jutil.py", line 274, in start_thread
5/20/16 3:36:19.317 PM CellProfiler[13938]: Exception: Javabridge failed to find JVM library
5/20/16 3:36:19.317 PM CellProfiler[13938]: Failed to create Java VM
5/20/16 3:36:19.317 PM CellProfiler[13938]: Traceback (most recent call last):
5/20/16 3:36:19.318 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/__boot__.py", line 81, in <module>
5/20/16 3:36:19.318 PM CellProfiler[13938]:     _run()
5/20/16 3:36:19.318 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/__boot__.py", line 62, in _run
5/20/16 3:36:19.318 PM CellProfiler[13938]:     exec(compile(source, path, 'exec'), globals(), globals())
5/20/16 3:36:19.318 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/CellProfiler.py", line 4, in <module>
5/20/16 3:36:19.318 PM CellProfiler[13938]:     cellprofiler.__main__.main()
5/20/16 3:36:19.318 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 178, in main
5/20/16 3:36:19.318 PM CellProfiler[13938]:     cp_start_vm()
5/20/16 3:36:19.318 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/cpjvm.py", line 102, in cp_start_vm
5/20/16 3:36:19.318 PM CellProfiler[13938]:     max_heap_size=heap_size)
5/20/16 3:36:19.318 PM CellProfiler[13938]:   File "/Users/logand05/Apps/CellProfiler_nightly_20160517.app/Contents/Resources/lib/python2.7/javabridge/jutil.py", line 312, in start_vm
5/20/16 3:36:19.318 PM CellProfiler[13938]:     raise RuntimeError("Failed to start Java VM")
5/20/16 3:36:19.318 PM CellProfiler[13938]: RuntimeError: Failed to start Java VM
5/20/16 3:36:19.388 PM CellProfiler[13938]: CellProfiler Error
5/20/16 3:36:19.388 PM CellProfiler[13938]: 2016-05-20 15:36:19.387 CellProfiler[13938:359387] CellProfiler Error
```

Do I need a JDK too, perhaps?  I ran 

```
/usr/libexec/java_home
```

and it reported

```
$  /usr/libexec/java_home
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
```

and so then I tried with the ‘—request’ switch but it said I needed a JDK to run Java command-line tools.  

Help @0x00B1, you’re my only hope!

**Comment by dlogan** [comment]
I got proper admin access and installed the JDK.  Now CellProfiler Stable 2.2 works! 👍  
But Nightly (20160523) crashes 👎  .  Here's the log below.  Thoughts?
```
5/24/16 11:08:51.490 AM CellProfiler[2815]: Uncaught exception in CellProfiler.py
5/24/16 11:08:51.490 AM CellProfiler[2815]: Traceback (most recent call last):
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 225, in main
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/cellprofiler/gui/app.py", line 20, in __init__
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "wx/_core.pyc", line 8628, in __init__
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "wx/_core.pyc", line 8196, in _BootstrapApp
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/cellprofiler/gui/app.py", line 23, in OnInit
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/cellprofiler/gui/cpframe.py", line 16, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinecontroller.py", line 13, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/cellprofiler/gui/parametersampleframe.py", line 18, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/skimage/io/__init__.py", line 7, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/skimage/io/manage_plugins.py", line 28, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/skimage/io/collection.py", line 12, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "PIL/Image.pyc", line 66, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "PIL/_imaging.pyc", line 14, in <module>
5/24/16 11:08:51.490 AM CellProfiler[2815]:   File "PIL/_imaging.pyc", line 10, in __load
5/24/16 11:08:51.490 AM CellProfiler[2815]: ImportError: dlopen(/Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/lib-dynload/PIL/_imaging.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
5/24/16 11:08:51.490 AM CellProfiler[2815]:   Referenced from: /Applications/CellProfiler_2.4.0_nightly_20160523.app/Contents/Resources/lib/python2.7/lib-dynload/PIL/_imaging.so
5/24/16 11:08:51.490 AM CellProfiler[2815]:   Reason: image not found
```

**Comment by 0x00B1** [comment]
Hi, @dlogan. It appears to be an issue with the bundled version Pillow.

**Comment by dlogan** [comment]
Yup I see the PIL problem, but surprised it passed unit tests.  Anyway, this means that I should just wait for a fix? (I will attempt source install at a later date)

**Comment by 0x00B1** [comment]
I’m looking into this now.

**Comment by dlogan** [comment]
I just tried the new nightly and still get the same PIL error 😢 
```
6/23/16 9:23:42.262 AM CellProfiler[2220]: Uncaught exception in CellProfiler.py
6/23/16 9:23:42.262 AM CellProfiler[2220]: Traceback (most recent call last):
6/23/16 9:23:42.262 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 225, in main
6/23/16 9:23:42.262 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/cellprofiler/gui/app.py", line 20, in __init__
6/23/16 9:23:42.262 AM CellProfiler[2220]:   File "wx/_core.pyc", line 8628, in __init__
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "wx/_core.pyc", line 8196, in _BootstrapApp
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/cellprofiler/gui/app.py", line 23, in OnInit
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/cellprofiler/gui/cpframe.py", line 16, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinecontroller.py", line 13, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/cellprofiler/gui/parametersampleframe.py", line 18, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/skimage/io/__init__.py", line 7, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/skimage/io/manage_plugins.py", line 28, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/skimage/io/collection.py", line 12, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "PIL/Image.pyc", line 66, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "PIL/_imaging.pyc", line 14, in <module>
6/23/16 9:23:42.263 AM CellProfiler[2220]:   File "PIL/_imaging.pyc", line 10, in __load
6/23/16 9:23:42.263 AM CellProfiler[2220]: ImportError: dlopen(/Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/lib-dynload/PIL/_imaging.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
6/23/16 9:23:42.263 AM CellProfiler[2220]:   Referenced from: /Applications/CellProfiler - Nightly 20160623.app/Contents/Resources/lib/python2.7/lib-dynload/PIL/_imaging.so
6/23/16 9:23:42.263 AM CellProfiler[2220]:   Reason: image not found
```

**Comment by AnneCarpenter** [comment]
@dlogan Still a problem?

**Comment by dlogan** [comment]
Just saw this...
Yes, still not working, but for a different reason.  I just installed a new Mac nightly (says it is Sept 3 though, which is a known build issue I realize), but it crashes immediately with this in Console:

```
10/12/16 2:11:49.504 PM CellProfiler[13189]: Traceback (most recent call last):
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/__boot__.py", line 81, in <module>
10/12/16 2:11:49.504 PM CellProfiler[13189]:     _run()
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/__boot__.py", line 62, in _run
10/12/16 2:11:49.504 PM CellProfiler[13189]:     exec(compile(source, path, 'exec'), globals(), globals())
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/CellProfiler.py", line 1, in <module>
10/12/16 2:11:49.504 PM CellProfiler[13189]:     import cellprofiler.__main__
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 5, in <module>
10/12/16 2:11:49.504 PM CellProfiler[13189]:     import cellprofiler.pipeline
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/lib/python2.7/cellprofiler/pipeline.py", line 48, in <module>
10/12/16 2:11:49.504 PM CellProfiler[13189]:     import cellprofiler.utilities.version as cpversion
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/version.py", line 126, in <module>
10/12/16 2:11:49.504 PM CellProfiler[13189]:     version_string = get_version()
10/12/16 2:11:49.504 PM CellProfiler[13189]:   File "/Applications/CellProfiler_nightly.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/version.py", line 97, in get_version
10/12/16 2:11:49.504 PM CellProfiler[13189]:     import cellprofiler.frozen_version
10/12/16 2:11:49.504 PM CellProfiler[13189]: ImportError: No module named frozen_version
10/12/16 2:11:49.642 PM CellProfiler[13189]: CellProfiler Error
10/12/16 2:11:49.642 PM CellProfiler[13189]: 2016-10-12 14:11:49.641 CellProfiler[13189:150651] CellProfiler Error
```

**Comment by 0x00b1** [comment]
The nightly is from today. I ran it this afternoon.

The `frozen_version` bug is my bad. I'll fix.

**Comment by dlogan** [comment]
Closing, as I think these particular Mac nightly issues are resolved, though https://github.com/CellProfiler/CellProfiler/issues/2494 is now the current issue which causes failure.
