### ISSUE TITLE
Ubuntu 15.10 issue with GTK

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2093]
My CellProfiler is compiled mostly with the standard Ubuntu system packages with the instructions from the wiki. When I resize the CellProfiler GUI for CP2.2.0 on Ubuntu Linux 15.10, I sometimes (relatively often) get errors like the following pop up:

```
Traceback (most recent call last):
File "/home/emmenlau/BioDataAnalysis/Projects/TargetInfectX/CellProfiler/GIT-CellProfiler2/cellprofiler/gui/moduleview.py", line 4011, in GetAttr
row, self.v.column_names[col])
File "/home/emmenlau/BioDataAnalysis/Projects/TargetInfectX/CellProfiler/GIT-CellProfiler2/cellprofiler/settings.py", line 3386, in get_cell_attributes
key = (row_index, self.column_names.index(column_name))
PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4096) in GTKSendPaintEvents(): unsupported background style
```

The package versions are:

```
libwxgtk3.0-0v5:amd64/wily 3.0.2+dfsg-1.2 uptodate
python-gtk2:amd64/wily 2.24.0-4ubuntu1 uptodate
python-wxgtk3.0:amd64/wily 3.0.2.0+dfsg-1build1 uptodate
```

**Comment by emmenlau** [comment]
I have googled this issue, and there are some hits from people that use transparent backgrounds. There even seems to be a fix here: https://groups.google.com/forum/#!topic/wx-dev/oeYKYy8MbHE
But if I understand correctly this is scheduled for wxGTK 3.0.1?

**Comment by dctrud** [comment]
We are seeing the `unsupported background style` assertion on a conda install of CellProfiler 2.2.0 on Red Hat EL6. I will ask the user affected to post steps to reproduce here.

![screen shot 2017-06-12 at 8 22 12 pm](https://user-images.githubusercontent.com/4522799/27151913-b58ab88e-5111-11e7-958b-dae7e4e2a976.png)

Installed conda/pip packages
```
# packages in environment at /cm/shared/apps/cellprofiler/2.2.0:
#
cairo                     1.12.18                       6  
cellh5                    1.3.0                     <pip>
CellProfiler              2.2.0                     <pip>
centrosome                1.0.5                     <pip>
cycler                    0.10.0                   py27_0  
cython                    0.25.1                   py27_0  
dask                      0.12.0                    <pip>
dbus                      1.10.10                       0  
decorator                 4.0.10                   py27_0  
expat                     2.1.0                         0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
glib                      2.43.0                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py27_2  
hdf5                      1.8.17                        1  
hmmlearn                  0.2.0                     <pip>
icu                       54.1                          0  
inflect                   0.2.5                     <pip>
javabridge                1.0.14                    <pip>
javabridge                1.0.14                   py27_0  
jbig                      2.1                           0  
jpeg                      8d                            2  
libffi                    3.2.1                         0  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   0.4.0                     <pip>
libtiff                   4.0.6                         2  
libxcb                    1.12                          1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
lxml                      3.6.4                    py27_0  
matplotlib                1.5.3               np111py27_1  
mkl                       11.3.3                        0  
mysql-python              1.2.5                    py27_0  
networkx                  1.11                     py27_0  
numpy                     1.11.2                   py27_0  
openssl                   1.0.2j                        0  
pandas                    0.19.1              np111py27_0  
pillow                    3.4.2                    py27_0  
pip                       9.0.1                    py27_0  
pixman                    0.32.6                        0  
prokaryote                1.0.11                    <pip>
py                        1.4.31                    <pip>
pycairo                   1.10.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_0  
pytest                    3.0.4                     <pip>
python                    2.7.12                        1  
python-bioformats         1.0.9                     <pip>
python-dateutil           2.6.0                    py27_0  
pytz                      2016.7                   py27_0  
pyzmq                     16.0.1                   py27_0  
qt                        5.6.0                         1  
readline                  6.2                           2  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.18.1              np111py27_0  
scipy                     0.18.1              np111py27_0  
setuptools                27.2.0                   py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
toolz                     0.8.0                     <pip>
wheel                     0.29.0                   py27_0  
wxpython                  3.0.0.0                  py27_2  
xz                        5.2.2                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3
```

**Comment by dctrud** [comment]
Apologies, just found the note to try 'conda install -c bjornfjohansson wxpython=3.0.2.0' which has been added to the conda install page since I last looked there. Will try that.

**Comment by larsgw** [comment]
I'm having a similar issue on Debian when I try to load files by dropping the folder in the Images module. I believe the dialog that gets opened triggers the error. wxPython `3.0.2.0` is already installed. This is the error message:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/lib/buttons.py", line 140, in AcceptsFocus
    return self.IsShown() and self.IsEnabled()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 9984, in IsShown
    return _core_.Window_IsShown(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4232) in GTKSendPaintEvents(): unsupported background style
```

**Comment by DavidStirling** [comment]
CellProfiler 4 will be running on wxPython 4, which should hopefully have resolved this issue. Feel free to re-open if this is still a problem in a modern version.
