### ISSUE TITLE
Ubuntu 15.10 issue with wxGTK when using "Duplicate input image" in "MetaDataExtraction"

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2094]
I'm using CP 2.2.0 on Ubuntu Linux 15.10, compiled mostly with system packages. In meta data extraction in the input section, I clicked on "duplicate this image", and got the following error:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_misc.py", line 1367, in Notify
self.notify()
File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16868, in Notify
self.result = self.callable(*self.args, **self.kwargs)
File "/home/emmenlau/BioDataAnalysis/Projects/TargetInfectX/CellProfiler/GIT-CellProfiler2/cellprofiler/gui/moduleview.py", line 2178, in do_reset
self.set_selection(self.__module.module_num)
File "/home/emmenlau/BioDataAnalysis/Projects/TargetInfectX/CellProfiler/GIT-CellProfiler2/cellprofiler/gui/moduleview.py", line 444, in set_selection
text_sizer_item = sizer.Add(static_text, 3, wx.EXPAND|wx.ALL, 2)
File "/home/emmenlau/BioDataAnalysis/Projects/TargetInfectX/CellProfiler/GIT-CellProfiler2/cellprofiler/gui/moduleview.py", line 4116, in Add
item = super(ModuleSizer, self).Add(control, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 14453, in Add
return _core_.Sizer_Add(*args, **kwargs)
PyAssertionError: C++ assertion "!sizer || m_containingSizer != sizer" failed at ../src/common/wincmn.cpp(2470) in SetContainingSizer(): Adding a window to the same sizer twice?
```

The package versions are:

```
libwxgtk3.0-0v5:amd64/wily 3.0.2+dfsg-1.2 uptodate
python-gtk2:amd64/wily 2.24.0-4ubuntu1 uptodate
python-wxgtk3.0:amd64/wily 3.0.2.0+dfsg-1build1 uptodate
```

**Comment by DavidStirling** [comment]
CellProfiler 4 will be running on wxPython 4, which should hopefully have resolved this issue. Feel free to re-open if this is still a problem in a modern version.
