### ISSUE TITLE
Error compiling CellProfiler 2.2.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2113]
This is a report only to track a problem compiling CellProfiler 2.2.0 on Ubuntu 16.04. Its not meant necessarily to be fixed by CellProfiler developers, but rather to keep track of the problem.
```
#> python setup.py install
```
will run for a while and then exit with
```
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/tmp/easy_install-3_Byeq/pandas-0.18.1/pandas/algos.pyx>, 1, 0), 'RemoveUnreachableCode', u'Compiler crash in RemoveUnreachableCode\n\nModuleNode.body = StatListNode(algos.pyx:1:0)\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 183, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/cython-qP7c_y/cython-0.23.4/Cython/Compiler/Visitor.c:4646)\n    return handler_method(obj)\n  File "/usr/lib/python2.7/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 2158, in visit_StatListNode\n    if not self.current_directives[\'remove_unreachable\']:\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'', TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7f5f8d2fb560>)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 27, in clean_up_temporary_directory
    for d in _tmpdirs:
TypeError: 'NoneType' object is not iterable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 27, in clean_up_temporary_directory
    for d in _tmpdirs:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 27, in clean_up_temporary_directory
    for d in _tmpdirs:
TypeError: 'NoneType' object is not iterable
```

**Comment by emmenlau** [comment]
A possible fix is described here: https://github.com/numpy/numpy/issues/7809
Currently all released and unreleased versions of numpy are affected by this problem.

**Comment by emmenlau** [comment]
Fixed in latest numpy and by updating build instructions in our wiki.
