### ISSUE TITLE
HDF5 write error on large data sets even when "Do not generate HDF5/.mat" files is selected"

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2127]
[From the forums](http://forum.cellprofiler.org/t/encountered-error-while-processing/3695):

> I'm running CellProfiler 2.2.0 (rev 9969f42) on a Mac Pro El Capitan (2 x 3.06 GHz 6-Core Intel Xeon. 48 GB 1333 MHz DDR3 ECC).
> I'm running the attached pipeline to analyze 2400 image sets and I SYSTEMATICALLY end up with the following error towards the very end (2360 image sets analyzed over the 2400...which is a bit frustrating..):

```
Traceback (most recent call last):
File "wx/_core.pyc", line 16766, in 
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinecontroller.py", line 2697, in on_stop_analysis
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/measurements.py", line 364, in getitem
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/measurements.py", line 960, in get_measurement
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/hdf5_dict.py", line 367, in getitem
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/hdf5_dict.py", line 644, in get_dataset
File "h5py/_objects.pyx", line 54, in h5py.objects.withphil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2458)
File "h5py/_objects.pyx", line 55, in h5py.objects.withphil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2415)
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/h5py/_hl/group.py", line 164, in getitem
File "h5py/_objects.pyx", line 54, in h5py.objects.withphil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2458)
File "h5py/_objects.pyx", line 55, in h5py.objects.withphil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2415)
File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5o.c:3507)
KeyError: "Unable to open object (Can't insert duplicate key)"
```

Looks like it got Jane too earlier this year... #1825

**Comment by bethac07** [comment]
[Also struck here, though fewer details](http://forum.cellprofiler.org/t/core-processing-error-after-processing-500-image-sets/3307)

**Comment by bethac07** [comment]
Update from the user -

> I found an alternative workaround that has solved my problem (not necessarily yours.. :wink:): As I have Windows running on Parallels on my Mac I used the exact same pipeline on the CellProfiler version installed on the virtual machine (2.2.0rc2).
No issues there, I've been running analysis all week end without a single problem...I guess it's something in the Mac version of CP then..

Windows FTW! :-p

**Comment by bethac07** [comment]
[Keeps striking](http://forum.cellprofiler.org/t/error-in-the-middle-of-the-run/3782)

**Comment by braymp** [comment]
One comment here (though not a fix): I believe 2.2.0 is written to temporarily dump the results to a HDF5 file per-cycle to reduce memory overhead. If you watch your output folder, you might notice an .h5 file show up and then disappear as the pipeline runs.

So this problem may have nothing to do with the "Do not generate HDF5/.mat" files selection, but may be somewhere else.

**Comment by AnneCarpenter** [comment]
Wow this sounds like a big fat pain. Sounds worth investigating given how many people affected.

**Comment by bethac07** [comment]
Possibly related to this, possibly not- I had a pipeline a collaborator wanted me to run in 2.2, but I hit this error so moved it to 3.1.5.  When I ran it there, at an EXTREMELY SIMILAR index, I got #3582 .
