### ISSUE TITLE
Workspace viewer: Error on adding object

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2156]
When adding an object to a workspace viewer overlay, I encountered the following error:

```
Traceback (most recent call last):
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\viewworkspace.py", line 93, in on_check_change
    self.vw.redraw()
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\viewworkspace.py", line 662, in redraw
    self.frame.figure.canvas.draw()
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 51, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\figure.py", line 1159, in draw
    func(*args)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2324, in draw
    a.draw(renderer)
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\cpartists.py", line 733, in draw
    om.points.set_axes(self.axes)
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\cpartists.py", line 258, in points
    color = self.color)
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\cpartists.py", line 1160, in __init__
    pts += .5          # Target the centers of the pixels.
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint32') with casting rule 'same_kind'
```

I know the WSViewer is currently MIA so I'm putting this here for when it eventually returns.

**Comment by braymp** [comment]
Appears that this may be due to a Numpy 1.10+ issue: https://github.com/numpy/numpy/blob/master/doc/release/1.10.0-notes.rst

**Comment by braymp** [comment]
Changing
```
pts += .5
```
to 
```
pts = pts + .5
```
fixes this. I'll leave it to someone else to create a PR for other places where inplace operations would cause this error.

**Comment by bethac07** [comment]
Apparently happens on 2.2.0 on ExpandOrShrinkObjects, but only intermittently- worked fine on my PC, emailed pipeline, collaborator opened on a Mac and got the error; she then saved the pipeline, closed it, and reopened it and it worked again.  I got nothing.

**Comment by braymp** [comment]
@0x00b1: Can you tell me what version of numpy 2.2.0 stable is built with?

**Comment by 0x00b1** [comment]
@braymp 1.11
