### ISSUE TITLE
MeasureCorrelation throws an error when number of objects detected is 0

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2194]
2.2.0 (ac0529e) Stable, running on AWS .  One of my image sets detected no objects due to some gunk in the well, which caused that site to fail with this error

```
Error detected during run of module MeasureCorrelation
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/pipeline.py", line 1819, in run_with_yield
    self.run_module(module, workspace)
  File "/usr/local/src/CellProfiler/cellprofiler/pipeline.py", line 2067, in run_module
    module.run(workspace)
  File "/usr/local/src/CellProfiler/cellprofiler/modules/measurecorrelation.py", line 229, in run
    object_name)
  File "/usr/local/src/CellProfiler/cellprofiler/modules/measurecorrelation.py", line 621, in run_image_pair_objects
    RWC1 = np.array(scind.sum(fi_thresh * weight_thresh,labels[combined_thresh],lrange)) / np.array(tot_fi_thr)
  File "/usr/lib/python2.7/dist-packages/scipy/ndimage/measurements.py", line 574, in sum
    count, sum = _stats(input, labels, index)
  File "/usr/lib/python2.7/dist-packages/scipy/ndimage/measurements.py", line 499, in _stats
    labels.min() < 0 or labels.max() > labels.size):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
Thu Aug 11 10:21:07 2016: Image # 2285, module MeasureCorrelation # 29: 37.08 sec
```

Module settings below

```
MeasureCorrelation:[module_num:29|svn_version:\'Unknown\'|variable_revision_number:3|show_window:False|notes:\x5B\x5D|batch_state:array(\x5B\x5D, dtype=uint8)|enabled:True|wants_pause:False]
    Hidden:3
    Hidden:3
    Select an image to measure:DNA
    Select an image to measure:Channel2
    Select an image to measure:Channel3
    Set threshold as percentage of maximum intensity for the images:15.0
    Select where to measure correlation:Within objects
    Select an object to measure:Nuclei
    Select an object to measure:Cells
    Select an object to measure:Cytoplasm
```

**Comment by DavidStirling** [comment]
Unable to replicate this in CP3, appears to be fixed. Please re-open if this recurs.
