### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by swvanderlaan** [CellProfiler/CellProfiler#2227]
Hi,
I'm trying to install CellProfiler on our HPC (CentOS7). Obviously, I don't have admin rights, which probably explains the error message below.
How can I best solve this without having admin rights to the whole server? I do have rights to install it on a separate part of the cluster which is accessible for our user-group.
Thanks!

Sander

```
[svanderlaan@hpcs03 CellProfiler]$ pip install --editable .
Obtaining file:///hpc/local/CentOS7/dhl_ec/software/git/CellProfiler
Collecting cellh5 (from CellProfiler==2.4.0rc1)
  Downloading cellh5-1.3.0.tar.gz
Collecting centrosome>=1.0.4 (from CellProfiler==2.4.0rc1)
  Downloading centrosome-1.0.5.tar.gz (637kB)
    100% |████████████████████████████████| 638kB 396kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-YUyfvg/centrosome/setup.py", line 1, in <module>
        import Cython.Build
    ImportError: No module named Cython.Build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YUyfvg/centrosome
```

**Comment by swvanderlaan** [comment]
Oh wait. Do I have to do the following?

`pip install --user cython`

Thanks!

Sander

**Comment by 0x00B1** [comment]
@swvanderlaan Yep. You need Cython!
