### ISSUE TITLE
Resolve Java library exceptions

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2228]
When running the example pipeline:

```
INFO:cellprofiler.analysis:Worker 2: Warning:  org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
INFO:cellprofiler.analysis:Worker 2: Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
INFO:cellprofiler.analysis:Worker 2: Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
INFO:cellprofiler.analysis:Worker 2: Exception in thread "Thread-2" java.io.EOFException: Attempting to read beyond end of file.
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
INFO:cellprofiler.analysis:Worker 2: Caused by: java.nio.BufferUnderflowException
INFO:cellprofiler.analysis:Worker 2:    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
INFO:cellprofiler.analysis:Worker 2:    at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
INFO:cellprofiler.analysis:Worker 2:    ... 2 more
INFO:cellprofiler.analysis:Worker 2: Caught exception in class loci.formats.in.PQBinReader.isThisType
INFO:cellprofiler.analysis:Worker 2: Exception in thread "Thread-2" java.lang.IllegalArgumentException
INFO:cellprofiler.analysis:Worker 2:    at java.nio.Buffer.position(Buffer.java:244)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
INFO:cellprofiler.analysis:Worker 2: Caught exception in class loci.formats.in.FlowSightReader.isThisType
INFO:cellprofiler.analysis:Worker 2: Exception in thread "Thread-2" java.io.EOFException: Attempting to read beyond end of file.
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
INFO:cellprofiler.analysis:Worker 2: Caused by: java.nio.BufferUnderflowException
INFO:cellprofiler.analysis:Worker 2:    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
INFO:cellprofiler.analysis:Worker 2:    at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
INFO:cellprofiler.analysis:Worker 2:    ... 2 more
INFO:cellprofiler.analysis:Worker 2: Caught exception in class loci.formats.in.PQBinReader.isThisType
INFO:cellprofiler.analysis:Worker 2: Exception in thread "Thread-2" java.lang.IllegalArgumentException
INFO:cellprofiler.analysis:Worker 2:    at java.nio.Buffer.position(Buffer.java:244)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
INFO:cellprofiler.analysis:Worker 2: Caught exception in class loci.formats.in.FlowSightReader.isThisType
INFO:cellprofiler.analysis:Worker 2: Exception in thread "Thread-2" java.io.EOFException: Attempting to read beyond end of file.
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
INFO:cellprofiler.analysis:Worker 2: Caused by: java.nio.BufferUnderflowException
INFO:cellprofiler.analysis:Worker 2:    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
INFO:cellprofiler.analysis:Worker 2:    at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
INFO:cellprofiler.analysis:Worker 2:    ... 2 more
INFO:cellprofiler.analysis:Worker 2: Caught exception in class loci.formats.in.PQBinReader.isThisType
INFO:cellprofiler.analysis:Worker 2: Exception in thread "Thread-2" java.lang.IllegalArgumentException
INFO:cellprofiler.analysis:Worker 2:    at java.nio.Buffer.position(Buffer.java:244)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
INFO:cellprofiler.analysis:Worker 2:    at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
INFO:cellprofiler.analysis:Worker 2:    at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
INFO:cellprofiler.analysis:Worker 2: Caught exception in class loci.formats.in.FlowSightReader.isThisType
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:32 2016: Image # 1, module NamesAndTypes # 3: 1.95 secs
INFO:cellprofiler.analysis:Worker 2: Running module Groups 4
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:35 2016: Image # 1, module Groups # 4: 0.00 secs
INFO:cellprofiler.analysis:Worker 2: Running module Crop 5
INFO:cellprofiler.analysis:Worker 2: /Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/image.py:473: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
INFO:cellprofiler.analysis:Worker 2:   return image[i_first:i_end, j_first:j_end].copy()
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:35 2016: Image # 1, module Crop # 5: 0.61 secs
INFO:cellprofiler.analysis:Worker 2: Running module Crop 6
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:36 2016: Image # 1, module Crop # 6: 0.01 secs
INFO:cellprofiler.analysis:Worker 2: Running module Crop 7
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:38 2016: Image # 1, module Crop # 7: 0.01 secs
INFO:cellprofiler.analysis:Worker 2: Running module IdentifyPrimaryObjects 8
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:39 2016: Image # 1, module IdentifyPrimaryObjects # 8: 0.10 secs
INFO:cellprofiler.analysis:Worker 2: Running module IdentifySecondaryObjects 9
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:40 2016: Image # 1, module IdentifySecondaryObjects # 9: 0.07 secs
INFO:cellprofiler.analysis:Worker 2: Running module IdentifyTertiaryObjects 10
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:41 2016: Image # 1, module IdentifyTertiaryObjects # 10: 0.04 secs
INFO:cellprofiler.analysis:Worker 2: Running module MeasureObjectSizeShape 11
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:42 2016: Image # 1, module MeasureObjectSizeShape # 11: 0.25 secs
INFO:cellprofiler.analysis:Worker 2: Running module MeasureObjectIntensity 12
INFO:cellprofiler.analysis:Worker 2: Mon Aug 15 10:03:42 2016: Image # 1, module MeasureObjectIntensity # 12: 0.16 secs
INFO:cellprofiler.analysis:Worker 2: Running module MeasureTexture 13
```

**Comment by dlogan** [comment]
Cool - any sort of exception in the logs or the CP terminal displayed to the user, causes many questions by users and developers alike.  My vote is to minimize all the false positives

**Comment by mcquin** [comment]
The errors were due to uncaught exceptions in `isThisType` for two image readers. I've submitted a PR which catches these exceptions and it will be included in the 5.6.1 release. Reference: https://github.com/openmicroscopy/bioformats/pull/2929

**Comment by AnneCarpenter** [comment]
should this be closed?

**Comment by mcquin** [comment]
I will close it once the changes are released in bioformats and incorporated into python-bioformats and prokaryote.

**Comment by sbesson** [comment]
@AnneCarpenter @mcquin we just released [Bio-Formats 5.7.0](http://www.openmicroscopy.org/2017/09/04/bio-formats-5-7-0.html) which should include these fixes. Let us know if you the exceptions persist.

**Comment by 0x00b1** [comment]
Thanks, @sbesson!

**Comment by mcquin** [comment]
Done!
