### ISSUE TITLE
Error using --file-list switch with text file with the "wrong" encoding

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2243]
I used Windows Powershell to produce a text file of images for input using the --file-list switch; FYI the cmd was 

```
gci -r <path_to_image_folder> | % fullname > listmyfolder.txt
```

The resulting text file looked fine but was encoded as UCS-2 BOM (according to Notepad++). Using this as input to CP gave the following error:

```
Traceback (most recent call last):
  File "C:\python27\scripts\cellprofiler-script.py", line 9, in <module>
    load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')()
  File "c:\users\brayma2\desktop\github\cellprofiler\cellprofiler\__main__.py", line 146, in main
    run_pipeline_headless(options, args)
  File "c:\users\brayma2\desktop\github\cellprofiler\cellprofiler\__main__.py", line 659, in run_pipeline_headless
    pipeline.read_file_list(file_list)
  File "c:\users\brayma2\desktop\github\cellprofiler\cellprofiler\pipeline.py", line 2700, in read_file_list
    self.read_file_list(fd, add_undo=add_undo)
  File "c:\users\brayma2\desktop\github\cellprofiler\cellprofiler\pipeline.py", line 2705, in read_file_list
    add_undo=add_undo)
  File "c:\users\brayma2\desktop\github\cellprofiler\cellprofiler\pipeline.py", line 2721, in add_pathnames_to_file_list
    urls.append(pathname2url(pathname))
  File "c:\users\brayma2\desktop\github\cellprofiler\cellprofiler\modules\loadimages.py", line 3373, in pathname2url
    utf8_path = path.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

Using Notepad++ to re-encode as UTF-8 "fixed" the problem. However, if there's a way for CP to handle such cases, it probably should.

**Comment by DavidStirling** [comment]
The move to Python 3 should have solved most instances where this problem could arise by accident, so I think we can close this.
