### ISSUE TITLE
Running headless with the --print-groups or --get-batch-commands switch brings up the UI

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2244]
Both of these switches print output to stdout and nothing else. Running from the cmd line with only these switches brings up the UI. Running them with -c produces an error that no pipeline is supplied.

The proper behavior should be to simply exit.

**Comment by dlogan** [comment]
Yup, traceback for me running locally on Mac OS:
```
$ /Applications/CellProfiler_2.2.0_Stable.app/Contents/MacOS/CellProfiler --get-batch-commands=./Batch_data.h5
Aug 29 10:15:58  CellProfiler[9332] <Notice>: Traceback (most recent call last):
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/__boot__.py", line 355, in <module>
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     _run()
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/__boot__.py", line 336, in _run
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     exec(compile(source, path, 'exec'), globals(), globals())
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/CellProfiler.py", line 4, in <module>
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     cellprofiler.__main__.main()
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 111, in main
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     get_batch_commands(options.batch_commands_file)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 693, in get_batch_commands
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     m = cpmeas.Measurements(filename = path, mode="r")
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/measurements.py", line 292, in __init__
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     mode = mode)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/hdf5_dict.py", line 169, in __init__
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     self.hdf5_file = h5py.File(self.filename, mode)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/h5py/_hl/files.py", line 260, in __init__
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/h5py/_hl/files.py", line 89, in make_fid
Aug 29 10:15:58  CellProfiler[9332] <Notice>:     fid = h5f.open(name, flags, fapl=fapl)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2458)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2415)
Aug 29 10:15:58  CellProfiler[9332] <Notice>:   File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5f.c:1792)
Aug 29 10:15:58  CellProfiler[9332] <Notice>: IOError: Unable to open file (Unable to open file: name = './batch_data.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
Aug 29 10:15:58  CellProfiler[9332] <Notice>: 2016-08-29 10:15:58.206 CellProfiler[9332:1523652] CellProfiler Error
```

However running the same command while logged onto the cluster environment (with only command-line allowed), it works ok:
```
$ cellprofiler --get-batch-commands=./Batch_data.h5
CellProfiler -c -r -b -p ./Batch_data.h5 -f 1 -l 1
CellProfiler -c -r -b -p ./Batch_data.h5 -f 2 -l 2
CellProfiler -c -r -b -p ./Batch_data.h5 -f 3 -l 3
```

**Comment by 0x00b1** [comment]
Thanks, @braymp. However, I can't reproduce. What's the exact command you're running?

**Comment by braymp** [comment]
Pretty much the same as @dlogan, but with no error msg:
```
python .\cellprofiler.py -c --get-batch-commands=.\Batch_data.h5
```

**Comment by VolkerH** [comment]
This should now be fixed

https://github.com/CellProfiler/CellProfiler/pull/2727

**Comment by bethac07** [comment]
Confirmed this still happens
