### ISSUE TITLE
ExportToDB: Is it necessary to import MySQL at runtime? 

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2251]
(tagging @imoutsatsos)

We have a shell script that fires off CP jobs on the cluster. The pipeline run contains ExportToDB and unfortunately, the runs errors at https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/exporttodatabase.py#L74. Apparently, each run attempts to unpack the MySQL module to a preset cache location and sometimes collide:

```
MySQL could not be loaded.
Traceback (most recent call last):
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/src/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 84, in <module>
    import MySQLdb
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/__init__.py", line 19, in <module>
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/_mysql.py", line 7, in <module>
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/_mysql.py", line 4, in __bootstrap__
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/setuptools-1.1.6-py2.7.egg/pkg_resources.py", line 884, in resource_filename
    self, resource_name
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/setuptools-1.1.6-py2.7.egg/pkg_resources.py", line 1523, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/setuptools-1.1.6-py2.7.egg/pkg_resources.py", line 1551, in _extract_resource
    self.egg_name, self._parts(zip_path)
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/setuptools-1.1.6-py2.7.egg/pkg_resources.py", line 950, in get_cache_path
    self.extraction_error()
  File "/usr/prog/cellprofiler/2.1.2-goolf-1.5.14-NX/lib/python2.7/site-packages/setuptools-1.1.6-py2.7.egg/pkg_resources.py", line 930, in extraction_error
    raise err
ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 17] File exists: '/labdata/incell/cluster_runs/CPJENKINS/JCB_2016-08-16_16-49-40/MySQL_python-1.2.3-py2.7-linux-x86_64.egg-tmp'

The Python egg cache directory is currently set to:

  /labdata/incell/cluster_runs/CPJENKINS/JCB_2016-08-16_16-49-40

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.
```

If I'm understanding what's happening correctly, my question is: is it really necessary for MySQL to be loaded this way? Alternately, is there a way to circumvent this issue?

**Comment by 0x00b1** [comment]
@braymp No. It could (and should) be lazy loaded.

**Comment by braymp** [comment]
Any thoughts on how to load the egg *before* the job is submitted?
