### ISSUE TITLE
CreateBatchFiles "Check paths" button error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2263]
I added CreateBatchFiles to a working pipeline (attached below) and then I click the "Check paths" button. (Running CP version Stable 2.2, since that is what my cluster runs because that is what PyPi serves).  I get the error below:

```
Traceback (most recent call last):
  File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/gui/moduleview.py", line 1134, in callback
  File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/gui/moduleview.py", line 2064, in __on_do_something
  File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/settings.py", line 1934, in on_event_fired
  File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/modules/createbatchfiles.py", line 367, in check_paths
  File "/Applications/CellProfiler_2.2.0_Stable.app/Contents/Resources/lib/python2.7/cellprofiler/modules/createbatchfiles.py", line 357, in check
  File "httplib.pyc", line 1057, in request
  File "httplib.pyc", line 1097, in _send_request
  File "httplib.pyc", line 1053, in endheaders
  File "httplib.pyc", line 897, in _send_output
  File "httplib.pyc", line 859, in send
  File "httplib.pyc", line 836, in connect
  File "socket.pyc", line 557, in create_connection
gaierror: [Errno 8] nodename nor servname provided, or not known
```

The code (https://github.com/CellProfiler/CellProfiler/blob/stable/cellprofiler/modules/createbatchfiles.py#L354) seems quite Broad-specific for BatchProfiler, no?  

My suggestions -- either:
(a) This Broad-specific behavior should be made explicit in the help and/or not run based on the IP address, or
(b) Expose the web image server URL (i.e. Broad's 'imageweb') to the user and suggest help on how to set this up in their own environment

[ExampleFly_Stable2.2.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/442496/ExampleFly_Stable2.2.cppipe.zip)

**Comment by 0x00b1** [comment]
Thanks, @dlogan! I agree, this is a mess.

**Comment by DavidStirling** [comment]
Button no longer exists in CP3
