### ISSUE TITLE
NamesAndTypes sometimes converts old pipelines incorrectly

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2281]
Sometimes when you're trying  to open a project in a newish version of CP from an older version of CP (sorry I'm trying to get a clarification on exactly what the starting version was in [this case],(http://forum.cellprofiler.org/t/problem-when-filtering-namesandtypes-or-groups/2114/11) I've also seen it once or twice but not often enough that I know the pattern of when it does and doesn't occur) NamesAndTypes flips out and won't accept input.  When you look at the configuration of the .cppipe file you can see the issue- yellow is what the format should be, red is what the configuration is in a pipeline having the error.   I'm presuming it's something being transcribed incorrectly in upgrade_settings causing it to chop off the "and( )" but nothing jumped out at me as screamingly obvious; I'll add more info as I get it.

![image](https://cloud.githubusercontent.com/assets/6721515/18173784/f0c88ae4-7038-11e6-864c-15f2713ac810.png)

**Comment by mcquin** [comment]
@bethac07 Do you have a pipeline sitting around the N&T doesn't convert properly, for reproducability?

**Comment by bethac07** [comment]
Here's the one from that linked forum post: 
[20160729-Nuc_Glc_RedOx.zip](https://github.com/CellProfiler/CellProfiler/files/943196/20160729-Nuc_Glc_RedOx.zip)

**Comment by bethac07** [comment]
AHA!  New info on this based on a pipeline from [this forum post](http://forum.cellprofiler.org/t/names-and-types-error/4933).  I think the cross-CP version thing turned out to be a red herring- both people running the pipeline that had the issue were on the same version of 2.2.0 (as was I, though Mac vs PC).  

What seems to matter is changing the pieces of Metadata that are extracted IFF that Metadata is used for channel assignment in NamesAndTypes.  When the Metadata module settings are first changed, when you go to NamesAndTypes and try to use a dropdown menu to reset the channel assignment you get the following error (`Wavelength` was a piece of metadata extracted in the original pipeline, the "allowed predicates" listed are the metadata extracted in the new pipeline).

```
Traceback (most recent call last):
  File "cellprofiler\gui\moduleview.pyc", line 2416, in <lambda>
  File "cellprofiler\gui\moduleview.pyc", line 2423, in on_predicate_changed
  File "cellprofiler\settings.pyc", line 2695, in parse
  File "cellprofiler\settings.pyc", line 2740, in parse_token
  File "cellprofiler\settings.pyc", line 2784, in parse_token
ValueError: The filter predicate, "Wavelength", was not in the list of allowed predicates ("ConfChannel","FileLocation","Frame","Series")
```
At this point if you save the pipeline, your pipeline won't run but NamesAndTypes is still correctly formatted (compare "1" and "2" in the zip file I'm attaching).  However, if you now try to type in a text box, CellProfiler's formatting of the rule it needs for NamesAndTypes breaks- see the diff between 1(red) and 3(yellow).

![image](https://user-images.githubusercontent.com/6721515/28332884-39138c5e-6bc4-11e7-838c-dd3d8eea7028.png)

I'd classify this issue as an edge case, but not a corner one- it's not universal to do channel assignments via metadata and it's not super common to change which metadata is extracted from run-to-run of a pipeline, but the intersection of these happens often enough that it's bitten me once or twice and has popped up twice in a year on the forum.  If we want people to be able to reuse pipelines across time (when they may change what metadata they put into file and/or folder names) or share pipelines with other users, it'd be nice if CP handled the case where NamesAndTypes can no longer find the Metadata it was expecting gracefully.

**Comment by bethac07** [comment]
Based on this new information this issue is a duplicate of #1272 , which Lee pushed a fix for in 25fdb60937643a6078df86edc8cc727da4bed8bd ; I think the fix is just bad, if we can "fix the fix" as it were I think that's more than sufficient.
