### ISSUE TITLE
RelateObjects: cpmorphology error

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2442]
Run the attached pipeline from #2441 in master. The following error is thrown when it hits RelateObjects
```
Traceback (most recent call last):
  File "C:\Users\brayma2\Desktop\GitHub\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2851, in do_step
    module.display(workspace, fig)
  File "C:\Users\brayma2\Desktop\GitHub\CellProfiler\cellprofiler\modules\relateobjects.py", line 289, in display
    workspace.display_data.parent_labels)
  File "C:\Users\brayma2\Desktop\GitHub\CellProfiler\cellprofiler\gui\tools.py", line 59, in renumber_labels_for_display
    return centrosome.cpmorphology.distance_color_labels(labels)
  File "C:\Python27\lib\site-packages\centrosome\cpmorphology.py", line 3585, in distance_color_labels
    colors = color_labels(labels, True)
  File "C:\Python27\lib\site-packages\centrosome\cpmorphology.py", line 3624, in color_labels
    return_indices = True)
ValueError: too many values to unpack
```
This error does not occur in 2.1.1.

**Comment by karhohs** [comment]
I ran into the same problem in the master using a 3d image.
