### ISSUE TITLE
Viewing 3d image stack via Images module throws error

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2570]
This is triggered by double-clicking on an image name.

Here is the CP stack trace:
```
Traceback (most recent call last):
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\backends\backend_wx.py", line 953, in _onPaint
    self.draw(drawDC=drawDC)
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 51, in draw
    FigureCanvasAgg.draw(self)
  File "C:\.conda\envs\cp3d\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C\.conda\envs\cp3d\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\axes\_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "C:\\.conda\envs\cp3d\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "c:\\src\cellprofiler\cellprofiler\gui\figure.py", line 2079, in draw
    im = matplotlib.image.fromarray(image, 0)
AttributeError: 'module' object has no attribute 'fromarray'
```

**Comment by mcquin** [comment]
I'd guess this is because CP doesn't know that it has a 3D image.

**Comment by mcquin** [comment]
@karhohs Are you still experiencing this on master? I can't replicate.

**Comment by mcquin** [comment]
Closing: unable to replicate.
