### ISSUE TITLE
3d error in MeasureObjectIntensity

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2574]
```
Traceback (most recent call last):
  File "c:\users\karhohs\documents\github\karhohs_projects\2016_05_04_alleninstitute_3d\src\cellprofiler\cellprofiler\gui\pipelinecontroller.py", line 2846, in do_step
    self.__pipeline.run_module(module, workspace)
  File "c:\users\karhohs\documents\github\karhohs_projects\2016_05_04_alleninstitute_3d\src\cellprofiler\cellprofiler\pipeline.py", line 1997, in run_module
    module.run(workspace)
  File "c:\users\karhohs\documents\github\karhohs_projects\2016_05_04_alleninstitute_3d\src\cellprofiler\cellprofiler\modules\measureobjectintensity.py", line 364, in run
    mesh_x = mesh_x[lmask]
IndexError: too many indices for array
```

**Comment by mcquin** [comment]
Resolved by #2463
