### ISSUE TITLE
matplotlib.image has no attribute 'fromarray' in matplotlib 2.0

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2581]
```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_wx.py", line 953, in _onPaint
    self.draw(drawDC=drawDC)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_wxagg.py", line 51, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/gui/figure.py", line 2079, in draw
    im = matplotlib.image.fromarray(image, 0)
AttributeError: 'module' object has no attribute 'fromarray'
```

**Comment by tacaswell** [comment]
Sorry, this was an API change that got insufficiently documented, removed in cf11aea8172be914cc96dcf3329bf7b694ba1d27 as part of over-hauling how images are handled internally.

**Comment by tacaswell** [comment]
Why are you maintaining your own image artist (https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/figure.py#L2060) ?

**Comment by mcquin** [comment]
Thanks for the information @tacaswell !! ([PR for future reference](https://github.com/matplotlib/matplotlib/pull/5718))

Re: maintaining our own image artist

The quick answer is that I'm not sure. This decision was made a long time ago. I will see if it is still necessary.

**Comment by tacaswell** [comment]
It looks like it is pretty old (has work-arounds for pre 1.0 mpl!).

From reading the code it _looks_ like the thing it is adding is you are doing your own normalization (and color mapping?).

Following a pattern like https://github.com/bokeh/datashader/pull/200 might be a better option.

**Comment by tacaswell** [comment]
Please keep me in the loop on this.

**Comment by mcquin** [comment]
Nice example. Thanks for the suggestion @tacaswell ! :)

**Comment by arcolombo** [comment]
I am receiving this error. what was the solution here?

Traceback (most recent call last):
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\backends\backend_wx.py", line 944, in _onPaint
    self.draw(drawDC=drawDC)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 48, in draw
    FigureCanvasAgg.draw(self)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\axes\_base.py", line 2437, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\cellprofiler\gui\cpfigure.py", line 2011, in draw
    im = matplotlib.image.fromarray(image, 0)
AttributeError: 'module' object has no attribute 'fromarray'
