### ISSUE TITLE
CorrectIlluminationCalculate module not working with volumetric datasets (nightly 2-16-17)

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#2630]
The "CorrectIlluminationCalculate" module is not working with volumetric datasets.  Here is the traceback log from when I tried to run the module.

Traceback (most recent call last):
  File "/home/derekt/git/src/cellprofiler-nightly/cellprofiler/gui/pipelinecontroller.py", line 2847, in do_step
    self.__pipeline.run_module(module, workspace)
  File "/home/derekt/git/src/cellprofiler-nightly/cellprofiler/pipeline.py", line 1997, in run_module
    module.run(workspace)
  File "/home/derekt/git/src/cellprofiler-nightly/cellprofiler/modules/correctilluminationcalculate.py", line 536, in run
    smoothed_image = self.apply_smoothing(dilated_image, orig_image)
  File "/home/derekt/git/src/cellprofiler-nightly/cellprofiler/modules/correctilluminationcalculate.py", line 717, in apply_smoothing
    image.mask)
  File "/home/derekt/git/src/cellprofiler-nightly/cellprofiler/modules/correctilluminationcalculate.py", line 746, in smooth_plane
    output_pixels = skimage.filters.median(pixel_data, strel, mask=mask)
  File "/home/derekt/git/src/scikit-image/skimage/filters/rank/generic.py", line 151, in func_out
    return func(image, selem=selem, *args, **kwargs)
  File "/home/derekt/git/src/scikit-image/skimage/filters/rank/generic.py", line 527, in median
    shift_x=shift_x, shift_y=shift_y)
  File "/home/derekt/git/src/scikit-image/skimage/filters/rank/generic.py", line 114, in _apply_scalar_per_pixel
    out=out, max_bin=max_bin)
  File "skimage/filters/rank/generic_cy.pyx", line 512, in skimage.filters.rank.generic_cy._median (skimage/filters/rank/generic_cy.c:33276)
    char[:, ::1] mask,
ValueError: Buffer has wrong number of dimensions (expected 2, got 3)

**Comment by mcquin** [comment]
Hi @derekthirstrup, thanks for filing an issue! Not all modules support volumes just yet. We'll be working on a way to distinguish 3D compatible modules from those without 3D support. It may be some time before illumination correction can support volumes. We'll be sure to update this issue once support is implemented.
