### ISSUE TITLE
ExpandOrShrinkObjects should support volumes

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2672]
Trying to either shrink to a point or shrink by a specified number of pixels:

```
Failed to run module ExpandOrShrinkObjects
Traceback (most recent call last):
  File "I:\GitHub\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2866, in do_step
    self.__pipeline.run_module(module, workspace)
  File "I:\GitHub\CellProfiler\cellprofiler\pipeline.py", line 1994, in run_module
    module.run(workspace)
  File "I:\GitHub\CellProfiler\cellprofiler\modules\expandorshrinkobjects.py", line 169, in run
    output_objects.segmented = self.do_labels(input_objects.segmented)
  File "I:\GitHub\CellProfiler\cellprofiler\modules\expandorshrinkobjects.py", line 236, in do_labels
    return centrosome.cpmorphology.binary_shrink(labels, iterations=self.iterations.value)
  File "build\bdist.win-amd64\egg\centrosome\cpmorphology.py", line 413, in binary_shrink
    index_i, index_j, image = prepare_for_index_lookup(image, False)
  File "centrosome\_cpmorphology2.pyx", line 483, in centrosome._cpmorphology2.prepare_for_index_lookup (centrosome\_cpmorphology2.cpp:6532)
ValueError: too many values to unpack (expected 2)
```

Trying to skeletonize:

```
Failed to run module ExpandOrShrinkObjects
Traceback (most recent call last):
  File "I:\GitHub\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2866, in do_step
    self.__pipeline.run_module(module, workspace)
  File "I:\GitHub\CellProfiler\cellprofiler\pipeline.py", line 1994, in run_module
    module.run(workspace)
  File "I:\GitHub\CellProfiler\cellprofiler\modules\expandorshrinkobjects.py", line 169, in run
    output_objects.segmented = self.do_labels(input_objects.segmented)
  File "I:\GitHub\CellProfiler\cellprofiler\modules\expandorshrinkobjects.py", line 272, in do_labels
    return centrosome.cpmorphology.skeletonize_labels(labels)
  File "build\bdist.win-amd64\egg\centrosome\cpmorphology.py", line 3756, in skeletonize_labels
    colors = color_labels(labels)
  File "build\bdist.win-amd64\egg\centrosome\cpmorphology.py", line 3629, in color_labels
    v_count, v_index, v_neighbor = find_neighbors(dt_labels)
  File "build\bdist.win-amd64\egg\centrosome\cpmorphology.py", line 3520, in find_neighbors
    new_labels[1:-1,1:-1] = labels
ValueError: could not broadcast input array from shape (40,512,512) into shape (40,512,514)
```

**Comment by mcquin** [comment]
ExpandOrShrinkObjects should support volumes.

**Comment by DavidStirling** [comment]
@bethac07 This functionality can now largely be replicated using the ErodeObjects module from #4114. We still don't have a function to skeletonize, so do we want to keep this open?

**Comment by bethac07** [comment]
skimage has a [3D skeletonization](https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html#lee94), so I think it would be nice to include

**Comment by bethac07** [comment]
Alternately, we could move that into MorphologicalSkeleton, and close this.

**Comment by bethac07** [comment]
Ah, MorphologicalSkeleton ALREADY does support 3D.  This issue can close then.
