### ISSUE TITLE
GUI does not load (blank screen only) in Ubuntu installation

### ISSUE THREAD

**Issue by arunima2** [CellProfiler/CellProfiler#2698]
After installing Cellprofiler in its entirety, when I run "python CellProfiler.py" I get the following output as well as a blank CellProfiler GUI window. Ubuntu 14.04 system. Latest stable release of CellProfiler

Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/opt/CellProfiler/cellprofiler/__main__.py", line 144, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/opt/CellProfiler/cellprofiler/gui/app.py", line 55, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/opt/CellProfiler/cellprofiler/gui/app.py", line 73, in OnInit
    telemetry = cellprofiler.gui.dialog.Telemetry()
  File "/opt/CellProfiler/cellprofiler/gui/dialog.py", line 50, in __init__
    self.SetExtendedMessage(extended_message)
AttributeError: 'Telemetry' object has no attribute 'SetExtendedMessage'

**Comment by mcquin** [comment]
Can you confirm wx 3.0+ is installed? `apt-get install python-wxgtk3.0`

**Comment by mcquin** [comment]
I see that python-wxgtk3.0 isn't available on 14.04. This smells like a bug caused by `SetExtendedMessage` not being implemented in 2.8. In the meantime, you can try these [instructions on installing python-wxgtk3.0 on Ubuntu 14.04](http://www.pygopar.com/installing-wxpython-3-on-ubuntu14-04/).

**Comment by mcquin** [comment]
Closing due to inactivity.
