### ISSUE TITLE
Accept relative paths with -i

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2721]
To reproduce: 
Checkout the 'AdvancedSegmentation' branch on Cellprofiler/Tutorials; 
Try to run the pipeline with a CP version after 5d5b700936fc6835bf378fd392a885c353f54001:
`
cellprofiler -c -r -p ..\tutorials\AdvancedSegmentation\BBBC022_Analysis_Final.cppipe -i ..\tutorials\AdvancedSegmentation\images\ -o ..\tutorials\output
`
Stack trace:
```
Your pipeline version is 20160503183100 but you are running CellProfiler version 300. Loading this pipeline may fail or have unpredictable results.
Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(Unknown Source)
        at org.cellprofiler.imageset.ImageFile.getFileName(ImageFile.java:91)
        at org.cellprofiler.imageset.filter.ExtensionPredicate.eval(ExtensionPredicate.java:33)
        at org.cellprofiler.imageset.filter.ExtensionPredicate.eval(ExtensionPredicate.java:25)
        at org.cellprofiler.imageset.filter.LogicPredicate.eval(LogicPredicate.java:60)
        at org.cellprofiler.imageset.filter.Filter.eval(Filter.java:240)
        at org.cellprofiler.imageset.filter.Filter.filterURLs(Filter.java:154)
Failed to prepare run for module Images
Traceback (most recent call last):
  File "i:\github\cellprofiler\cellprofiler\pipeline.py", line 2057, in prepare_run
    if ((not module.prepare_run(workspace)) or
  File "i:\github\cellprofiler\cellprofiler\modules\images.py", line 268, in prepare_run
    "([Ljava/lang/String;)[Z", file_array)
  File "c:\python27\lib\site-packages\javabridge\jutil.py", line 885, in call
    result = fn(*nice_args)
  File "c:\python27\lib\site-packages\javabridge\jutil.py", line 852, in fn
    raise JavaException(x)
JavaException: URI is not hierarchical
```

**Comment by braymp** [comment]
A clue? http://forum.cellprofiler.org/t/altering-a-cpproj-file-headless/3807/3

**Comment by mcquin** [comment]
Can you retry the command with the full path?

**Comment by bethac07** [comment]
That works!  Should document somewhere though that it needs to be absolute not relative path.

**Comment by mcquin** [comment]
I think it should work with relative paths. I'm marking this as a bug.

**Comment by PeterLu0403** [comment]
Hi, 


> That works! Should document somewhere though that it needs to be absolute not relative path.

Dear Beth,

I'm facing an error when running cellprofiler 3.1.9 with commend mode, could you please help me with this: 
cellprofiler -p ~/Dataset/hTMC_D2/Analysis_hTMC_D2_20200106.cpproj -c --file-list=/home/mynectar5/Dataset/hTMC_D2/filelist_1.txt -r -f 1 -l 1 -o .
/usr/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/cellprofiler/utilities/hdf5_dict.py:539: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  np.issubdtype(hdf5_type, int) or
/usr/local/lib/python2.7/dist-packages/cellprofiler/utilities/hdf5_dict.py:541: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  hdf5_type_is_float = np.issubdtype(hdf5_type, float)
Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at org.cellprofiler.imageset.ImageFile.getFileName(ImageFile.java:72)
	at org.cellprofiler.imageset.filter.ExtensionPredicate.eval(ExtensionPredicate.java:21)
	at org.cellprofiler.imageset.filter.ExtensionPredicate.eval(ExtensionPredicate.java:13)
	at org.cellprofiler.imageset.filter.LogicPredicate.eval(LogicPredicate.java:48)
	at org.cellprofiler.imageset.filter.LogicPredicate.eval(LogicPredicate.java:48)
	at org.cellprofiler.imageset.filter.Filter.eval(Filter.java:224)
	at org.cellprofiler.imageset.filter.Filter.filterURLs(Filter.java:138)
Failed to prepare run for module Images
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/pipeline.py", line 2097, in prepare_run
    if ((not module.prepare_run(workspace)) or
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/modules/images.py", line 342, in prepare_run
    "([Ljava/lang/String;)[Z", file_array)
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 887, in call
    result = fn(*nice_args)
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 854, in fn
    raise JavaException(x)
JavaException: URI is not hierarchical

**Comment by todd-fallesen** [comment]
Out of curosity, did this get fixed? I'm getting this bug still, but it might be a bash issue on our end
