### ISSUE TITLE
Grouping via Metadata values of "0" causes CP to crash.  

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2756]
Was running Distributed-CellProfiler with @cells2numbers, which runs CP stable.  His LoadData file grouped by a few different Metadata variables, including `Metadata_dose`, which for some (the controls) was 0.  All the groupings for which Metadata_dose was nonzero started up just fine, but the ones for which it was 0 failed immediately with the error : 
```
Failed to complete post_run processing for module ExportToSpreadsheet.
Traceback (most recent call last):
    File "/usr/local/src/CellProfiler/cellprofiler/pipeline.py", line 2217, in post_run
    module.post_run(workspace)
    File "/usr/local/src/CellProfiler/cellprofiler/modules/exporttospreadsheet.py", line 542, in post_run
    self.run_objects([object_name], workspace)
    File "/usr/local/src/CellProfiler/cellprofiler/modules/exporttospreadsheet.py", line 611, in run_objects
    workspace, settings_group)
    File "/usr/local/src/CellProfiler/cellprofiler/modules/exporttospreadsheet.py", line 797, in make_image_file
    IMAGE, workspace, image_set_numbers[0], settings_group)
    IndexError: index 0 is out of bounds for axis 0 with size 0
```
Changing the `Metadata_dose` value for those movies from 0 to None resolved the issue, so it seems to be pretty specifically related to using 0 as a metadata value.

**Comment by DavidStirling** [comment]
Appears to be fixed in 3.1.9.
