### ISSUE TITLE
Error from MeasureObjectSizeShape

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2813]
I have a pipeline that runs fine from the Windows gui, but then fails in the CellProfiler/examples repository when travis runs. Here is the error I receive:

```
Error detected during run of module MeasureObjectSizeShape
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/src/cellprofiler/cellprofiler/pipeline.py", line 1763, in run_with_yield
    self.run_module(module, workspace)
  File "/home/travis/virtualenv/python2.7.13/src/cellprofiler/cellprofiler/pipeline.py", line 2007, in run_module
    module.run(workspace)
  File "/home/travis/virtualenv/python2.7.13/src/cellprofiler/cellprofiler/modules/measureobjectsizeshape.py", line 295, in run
    self.run_on_objects(object_group.name.value, workspace)
  File "/home/travis/virtualenv/python2.7.13/src/cellprofiler/cellprofiler/modules/measureobjectsizeshape.py", line 374, in run_on_objects
    zf_l = cpmz.zernike(zernike_numbers, labels, indices)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/centrosome/zernike.py", line 186, in zernike
    zf = construct_zernike_polynomials(x, y, zernike_indexes, mask)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/centrosome/zernike.py", line 57, in construct_zernike_polynomials
    lut = construct_zernike_lookuptable(zernike_indexes) # precompute poly. coeffs.
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/centrosome/zernike.py", line 16, in construct_zernike_lookuptable
    n_max = np.max(zernike_indexes[:,0])
TypeError: list indices must be integers, not tuple
Thu Jul  6 22:27:32 2017: Image # 1, module MeasureObjectSizeShape # 11: 0.22 sec```

**Comment by bethac07** [comment]
I think I've run into this before as well in pipelines where Zernike calculation was turned off.

**Comment by karhohs** [comment]
I confirm @bethac07 's comment. This error only appears when the Zernike option is off. When the Zernike option is on there is no error.
