### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AboutDialogInfo'

### ISSUE THREAD

**Issue by vatese** [CellProfiler/CellProfiler#2829]
I get the following error when calling cellprofiler:

```
Traceback (most recent call last):
  File "/stornext/System/data/apps/anaconda2/anaconda2-4.2.0/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler==3.0.0rc1', 'console_scripts', 'cellprofiler')()
  File "/stornext/System/data/apps/anaconda2/anaconda2-4.2.0/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/__main__.py", line 136, in main
    import cellprofiler.gui.app
  File "/stornext/System/data/apps/anaconda2/anaconda2-4.2.0/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/app.py", line 17, in <module>
    import cellprofiler.gui.dialog
  File "/stornext/System/data/apps/anaconda2/anaconda2-4.2.0/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/dialog.py", line 7, in <module>
    class AboutDialogInfo(wx.AboutDialogInfo):
AttributeError: 'module' object has no attribute 'AboutDialogInfo'
```

Running on Centos 7, anaconda2 4.2.0, and Phoenix 4.0.0b1.

**Comment by vatese** [comment]
Fixed by doing the following change at CellProfiler/cellprofiler/gui/dialog.py line 7.

import wx.adv
class AboutDialogInfo(wx.adv.AboutDialogInfo):

**Comment by mcquin** [comment]
@vatese which version of wxPython?

**Comment by 0x00b1** [comment]
@vatese Whoa! Whoa! Whoa! Are you running CellProfiler with wxPython-Phoenix?

**Comment by vatese** [comment]
I was as it is the default that gets installed with pip. Downgraded to a manual build of "classic" wxPython 3.0.2.0. It works fine after that! Cheers.
