### ISSUE TITLE
Encoding issue in cellprofiler/gui/pathlist.py line 330

### ISSUE THREAD

**Issue by zindy** [CellProfiler/CellProfiler#2836]
Hello,

the problem is that Unicode encoded paths will cause an error in pathlist.py at line 330. This is happening in both CellProfiler 2.2 and 2.4:

```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 1247, in <lambda>
  File "cellprofiler\gui\pipelinecontroller.pyc", line 558, in do_open_workspace
  File "cellprofiler\pipeline.pyc", line 2666, in load_file_list
  File "cellprofiler\pipeline.pyc", line 2604, in add_urls
  File "cellprofiler\pipeline.pyc", line 3281, in notify_listeners
  File "cellprofiler\gui\pipelinecontroller.pyc", line 1394, in __on_pipeline_event
  File "cellprofiler\gui\pipelinecontroller.pyc", line 1456, in on_urls_added
  File "D:\CellProfiler\.\cellprofiler\gui\pathlist.py", line 258, in add_paths
  File "D:\CellProfiler\.\cellprofiler\gui\pathlist.py", line 39, in __init__
  File "D:\CellProfiler\.\cellprofiler\gui\pathlist.py", line 330, in get_folder_display_name
  File "encodings\utf_8.pyc", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-32: ordinal not in range(128)
```

The line in question is:
```python
            return urllib.url2pathname(folder[5:]).decode("utf8")
```

I have an example of folder string that will cause this issue (Windows path, there's a round dot between M1 and M2):
```python
folder = u'file:///C:/Users/lab/Documents/M1%EF%80%A2M2%20macrophages'
```

A quick hack to solve this may be:
```python
        if folder.startswith("file:"):
            folder = urllib.url2pathname(folder[5:])
            try:
                ret = folder.decode("utf8")
            except:
                ret = folder
            return ret
        return folder
```
This may be important in countries that use Unicode encoded paths by default. Unfortunately, I do not know how to solve this properly. 

Cheers,
Egor

**Comment by DavidStirling** [comment]
Should be resolved by native unicode handling in CellProfiler 4.
