### ISSUE TITLE
CP rc4 tries and fails to load plugin modules on every image set

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3031]
There are two modules in the CellProfiler-plugins repo that currently fail to import; when I'm running the ExampleFly pipeline (which contains neither) every single image that runs I get the following error (with only the Worker numbers varying):

```
Worker 1: Starting job
Worker 1: Could not load exporttocellh5
Worker 1: Traceback (most recent call last):
Worker 1:   File "cellprofiler\modules\__init__.py", line 321, in add_module
Worker 1:     m = __import__(mod, globals(), locals(), ['__all__'], 0)
Worker 1:   File "C:\Users\bcimini\GitHub\CellProfiler-plugins\exporttocellh5.py", line 21, in <module>
Worker 1:     from cellprofiler.gui.help import \
Worker 1: ImportError: cannot import name USING_METADATA_TAGS_REF
Worker 1: Could not load measure_population_context
Worker 1: Traceback (most recent call last):
Worker 1:   File "cellprofiler\modules\__init__.py", line 321, in add_module
Worker 1:     m = __import__(mod, globals(), locals(), ['__all__'], 0)
Worker 1:   File "C:\Users\bcimini\GitHub\CellProfiler-plugins\measure_population_context.py", line 35, in <module>
Worker 1:     import cellprofiler.cpmodule as cpm
Worker 1: ImportError: No module named cpmodule
Worker 1: could not load these modules: exporttocellh5,measure_population_context
```

My assumption would be that CP would try to load the plugin modules once on startup (and/or maybe at analysis start or pipeline load), is it expected that they try to load them freshly on every single image?

**Comment by mcquin** [comment]
> Is it expected that they try to load them freshly on every single image?

No, I wouldn't think so.

**Comment by DavidStirling** [comment]
Doesn't appear to be a problem in current. Please re-open if this is still happening.
