### ISSUE TITLE
BatchProfiler error: "No space left on device"

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#306]
BatchProfiler ViewBatch can report that a batch is still in the RUN state, when in fact it has errored because the /tmp directory on the cluster node is apparently full. 

An example Batch output can be found here, in Batch #3550 (Look midway through the txt output, since this batch was restarted)
http://imagingweb.broadinstitute.org/batchprofiler/cgi-bin/CellProfiler2.0/CellProfiler/BatchProfiler/ViewTextFile.py?run_id=1544128

The relevant error message is below:

---

ERROR:cellprofiler.pipeline:Error detected during run of module LoadImages
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2012_03_09_15_12_57/cellprofiler/pipeline.py", line 1306, in run_with_yield
    module.run(workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2012_03_09_15_12_57/cellprofiler/modules/loadimages.py", line 2218, in run
    image.scale)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2012_03_09_15_12_57/cellprofiler/measurements.py", line 299, in add_image_measurement
    self.add_measurement(IMAGE, feature_name, data)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2012_03_09_15_12_57/cellprofiler/measurements.py", line 472, in add_measurement
    self.hdf5_dict[IMAGE, feature_name, image_set_number] = wrap_string(data)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2012_03_09_15_12_57/cellprofiler/utilities/hdf5_dict.py", line 232, in **setitem**
    dest = self.find_index_or_slice(idxs, val)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2012_03_09_15_12_57/cellprofiler/utilities/hdf5_dict.py", line 347, in find_index_or_slice
    ds.resize((cur_size + grow_by,))
  File "/broad/software/free/Linux/redhat_5_x86_64/pkgs/toolbox/0.10.1/lib/python2.6/site-packages/h5py-1.3.1-py2.6-linux-x86_64.egg/h5py/highlevel.py", line 1138, in resize
    h5f.flush(self.id)  # THG recommends
  File "h5f.pyx", line 103, in h5py.h5f.flush (h5py/h5f.c:1524)
IOError: File write failed: time = wed mar 14 15:21:29 2012
, filename = '/tmp/cpmeasurementsc791if.hdf5', file descriptor = 7, errno = 28, error message = 'no space left on device', buf = 0x2aaad5157b47, size = 2529, offset = 71860224 (Low-level I/O: Write failed)
Error detected during run of module LoadImages

---

**Comment by Sorooshi** [comment]
I'm facing almost the same problem when I want to save a Keras model after some iteration.
Here is the error I received.

Does anyone find any solution?

Thanks in advance.

model.save(model_name+".h5")
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1085, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 188, in save_model
    f.close()
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 299, in close
    h5i.dec_ref(id_)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5i.pyx", line 150, in h5py.h5i.dec_ref
OSError: Driver write request failed (file write failed: time = Tue Sep 18 00:12:03 2018
, filename = 'model_act_vgg0-15.h5', file descriptor = 24, errno = 28, error message = 'No space left on device', buf = 0x7ffee0ebd440, total write size = 96, bytes this sub-write = 96, bytes actually written = 18446744073709551615, offset = 0)
Segmentation fault
