### ISSUE TITLE
Crop: Error drawing figure with 0-dim output 

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#3330]
The 3.0rc5 pipeline produces an error when cropping with masking image of all 0s and the user requests removing all empty rows/cols:
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 2894, in do_step
    module.display(workspace, fig)
  File "cellprofiler\modules\crop.py", line 418, in display
    sharexy=figure.subplot(0, 0))
  File "cellprofiler\gui\figure.py", line 180, in wrapper
    return fn(*args, **kwargs)
  File "cellprofiler\gui\figure.py", line 1658, in subplot_imshow_bw
    return self.subplot_imshow(x, y, image, title=title, **kwargs)
  File "cellprofiler\gui\figure.py", line 180, in wrapper
    return fn(*args, **kwargs)
  File "cellprofiler\gui\figure.py", line 1412, in subplot_imshow
    subplot.imshow(self.normalize_image(image, **kwargs))
  File "cellprofiler\gui\figure.py", line 1686, in normalize_image
    image = skimage.exposure.rescale_intensity(image)
  File "C:\Python27\lib\site-packages\skimage\exposure\exposure.py", line 292, i
n rescale_intensity
    imin, imax = intensity_range(image, in_range)
  File "C:\Python27\lib\site-packages\skimage\exposure\exposure.py", line 204, i
n intensity_range
    i_min = np.min(image)
  File "C:\Python27\lib\site-packages\numpy\core\fromnumeric.py", line 2372, in
amin
    out=out, **kwargs)
  File "C:\Python27\lib\site-packages\numpy\core\_methods.py", line 29, in _amin

    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```
This used to work under 2.2.0.
[issue.zip](https://github.com/CellProfiler/CellProfiler/files/1353725/issue.zip)

**Comment by 0x00b1** [comment]
Sentry issue: https://sentry.io/allen-goodman/cellprofiler/issues/361561696/
