### ISSUE TITLE
Crop based on "Mouse" fails if you alter the cropping box

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3358]
From [the forum](http://forum.cellprofiler.org/t/crop-module-error/5224):

> Hi, I get this error using the latest 3.0.0 release if I try to resize the rectangular selection when cropping, but it goes ahead without an error if I leave it as it is (a square):
‘Error while processing Crop:
slice indices must be integers or None or have an index method’

I've verified on my machine- if you just leave the default crop box it starts with, the module completes, but if you move one of the corners you get the full error trace here:
```
Failed to run module Crop
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2887, in do_step
  File "CellProfiler\cellprofiler\pipeline.py", line 2022, in run_module
  File "CellProfiler\cellprofiler\modules\crop.py", line 335, in run
  File "CellProfiler\cellprofiler\modules\crop.py", line 437, in ui_crop
  File "CellProfiler\cellprofiler\modules\crop.py", line 795, in apply_rectangle_cropping
TypeError: slice indices must be integers or None or have an __index__ method
```
Pipeline and image to validate are attached.  
[CP forum question.zip](https://github.com/CellProfiler/CellProfiler/files/1411374/CP.forum.question.zip)

**Comment by AetherUnbound** [comment]
It looks like the `Crop` module wasn't converting the crop locations to integers before trying to use the values as indexes for the pixel array. I think I've resolved this in #3415
