### ISSUE TITLE
ExportToDatabase errors if first image skipped due to FlagImage

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3393]
If you are running a pipeline where FlagImage is used with image skipping on and it skips the first image, the following error message is created and nothing is written to the database.  This works fine if you're skipping the second image rather than the first.

```
Progress Counter({u'Done': 2})
Failed during post-group processing for module ExportToDatabase
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\pipeline.py", line 2324, in post_group
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 2160, in post_group
  File "CellProfiler\cellprofiler\workspace.py", line 287, in interaction_request
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 1980, in handle_interaction
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 1994, in handle_interaction_execute
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 4508, in execute_all
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 283, in execute
OperationalError: no such table: Per_Experiment
```

Pipeline and image sets to reproduce here.  
[SkipFirstImage.zip](https://github.com/CellProfiler/CellProfiler/files/1515913/SkipFirstImage.zip)

**Comment by bethac07** [comment]
My CP installation is being buggy, closing until I can reproduce better or track down the issue.
