### ISSUE TITLE
TrackObjects error when using 'Measurements' tracking method

### ISSUE THREAD

**Issue by GenevieveBuckley** [CellProfiler/CellProfiler#3424]
I've encountered an error when trying to use the 'Measurements' tracking method in the TrackObjects module with CellProfiler3.0.0. Can anyone help with ideas?

Error message:
> Error while processing TrackObjects:
> (Worker) ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)
> Do you want to stop processing?

Reproducing the error:
* [CellProfiler 3.0.0](http://cellprofiler.org/releases/)
* [Pipeline file here](https://drive.google.com/file/d/1He4Q7E-vxUpyOCnWji0qKGGxxG_yqt5V/view?usp=sharing)
* Data downloaded as .zip file from the 'Object Tracking and Metadata Management' [pipeline example here](http://cellprofiler.org/examples/)
The only difference between this example pipeline and the one I've modified is the method set in the TrackObjects module.

**Comment by AetherUnbound** [comment]
I've verified that I encounter this issue as well. It doesn't occur within the first few images of a sequence though. I tried running through the images in test mode and got impatient :) 

I'll give it another look and see what I can find.

**Comment by AetherUnbound** [comment]
After further investigation, it looks like two things:
1. I only get this issue when I run multiple workers (e.g. if I run `Sequence1` and `Sequence2` of the sample data at the same time)
2. This seems to be an error being thrown in `centrosome`. I'm not sure if that means it's an upstream error or not, simply because of how this bug can be reproduced.

For the time being @GenevieveBuckley, do you mind trying to run the sequences one at a time to see if you still experience the issue? @mcquin or @0x00b1, can you try reproducing this on your machines? Specifically: no issue in test mode or with single worker, issue with 2+ workers.

**Comment by AetherUnbound** [comment]
Error Traceback:
```
Worker 0: Error detected during run of module TrackObjects#9
Worker 0: Traceback (most recent call last):
Worker 0:   File "/home/aether/git/CellProfiler/cellprofiler/pipeline.py", line 1912, in run_image_set
Worker 0:     self.run_module(module, workspace)
Worker 0:   File "/home/aether/git/CellProfiler/cellprofiler/pipeline.py", line 2022, in run_module
Worker 0:     module.run(workspace)
Worker 0:   File "/home/aether/git/CellProfiler/cellprofiler/modules/trackobjects.py", line 1159, in run
Worker 0:     self.run_measurements(workspace, objects)
Worker 0:   File "/home/aether/git/CellProfiler/cellprofiler/modules/trackobjects.py", line 1648, in run_measurements
Worker 0:     self.pixel_radius.value)
Worker 0:   File "/home/aether/programs/anaconda3/envs/cellprofiler/lib/python2.7/site-packages/centrosome/cpmorphology.py", line 1772, in associate_by_distance
Worker 0:     b,centers_b[jj,:])
Worker 0:   File "/home/aether/programs/anaconda3/envs/cellprofiler/lib/python2.7/site-packages/centrosome/cpmorphology.py", line 1851, in minimum_distance2
Worker 0:     return faster_minimum_distance2(hull_a, center_a, hull_b, center_b)
Worker 0:   File "/home/aether/programs/anaconda3/envs/cellprofiler/lib/python2.7/site-packages/centrosome/cpmorphology.py", line 1927, in faster_minimum_distance2
Worker 0:     if (np.dot(a-a_next,b-a_next) > 0 and
Worker 0: ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)
```

**Comment by AetherUnbound** [comment]
It looks like this might be an issue with `cpmorphology.faster_minimum_distance2`

**Comment by GenevieveBuckley** [comment]
Sorry for the delay, I've been away over the new year.

@AetherUnbound  I can confirm that the pipeline runs with no errors when using only one worker (tested by loading only the 'Sequence1' data). Would you like me to try anything else?

**Comment by AetherUnbound** [comment]
Thanks for checking that! I know less about centrosome than I do CellProfiler, we'll wait for @0x00b1 or @mcquin to comment before moving forward.

**Comment by todd-fallesen** [comment]
I'm getting the same error in CP4 now, using measurements tracking Center_X

**Comment by ceserthen** [comment]
I'm getting the same error in CP 4.0.7. Operating system is Ubuntu 20.04.

`
Worker 0: Error detected during run of module TrackObjects#9
Worker 0: Traceback (most recent call last):
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1159, in run_image_set
Worker 0:     self.run_module(module, workspace)
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1292, in run_module
Worker 0:     module.run(workspace)
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/cellprofiler/modules/trackobjects.py", line 1323, in run
Worker 0:     self.run_measurements(workspace, objects)
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/cellprofiler/modules/trackobjects.py", line 1812, in run_measurements
Worker 0:     associations = associate_by_distance(
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 1824, in associate_by_distance
Worker 0:     d = minimum_distance2(a, centers_a[ii, :], b, centers_b[jj, :])
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 1906, in minimum_distance2
Worker 0:     return faster_minimum_distance2(hull_a, center_a, hull_b, center_b)
Worker 0:   File "/home/dpb53/anaconda3/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 1985, in faster_minimum_distance2
Worker 0:     if np.dot(a - a_next, b - a_next) > 0 and np.dot(a_next - a, b - a) > 0:
Worker 0:   File "<__array_function__ internals>", line 5, in dot
Worker 0: ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)
`

I tried running with only a single worker and it is still run the error

I upgraded to CP 4.1.3 and the problem persists.
