### ISSUE TITLE
Error when using "Split" mode in IdentifyObjectsManually

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3426]
When using Split mode in IdentifyObjectsManually (to do this, hit "F" and draw in an object, then right click on it so it becomes an outline with control points and hit "S" to select two control points to split the object), it does actually split the object (see picture below, it definitely has two halves), but then immediately throws the error:
```
Traceback (most recent call last):
  File "site-packages\matplotlib\backends\backend_wx.py", line 1079, in _onLeftButtonDown
  File "site-packages\matplotlib\backend_bases.py", line 1917, in button_press_event
  File "site-packages\matplotlib\cbook.py", line 554, in process
  File "site-packages\matplotlib\cbook.py", line 416, in __call__
  File "CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 871, in on_click
  File "CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 1654, in on_split_second_click
  File "CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 1453, in exit_split_mode
  File "CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 1197, in update_artists
  File "site-packages\matplotlib\backends\backend_agg.py", line 451, in restore_region
  File "site-packages\matplotlib\backends\backend_agg.py", line 359, in restore_region
TypeError: restore_region() argument 1 must be matplotlib.backends._backend_agg.BufferRegion, not None
```

Thereafter literally anytime you move the cursor anywhere over the draw-able area you get a stream of repeats of the following error (this is super (not) fun).

```
Traceback (most recent call last):
  File "site-packages\matplotlib\backends\backend_wx.py", line 1163, in _onMotion
  File "site-packages\matplotlib\backend_bases.py", line 1966, in motion_notify_event
  File "site-packages\matplotlib\cbook.py", line 554, in process
  File "site-packages\matplotlib\cbook.py", line 416, in __call__
  File "CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 1122, in on_mouse_moved
  File "CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 1479, in handle_mouse_moved_pick_second_mode
AttributeError: 'NoneType' object has no attribute 'get_data'
```
Image + pipeline to reproduce are below.

![image](https://user-images.githubusercontent.com/6721515/34178223-66a585a8-e4d4-11e7-8a06-de1f4d87f61f.png)

[DrawManually.zip](https://github.com/CellProfiler/CellProfiler/files/1573225/DrawManually.zip)

**Comment by AetherUnbound** [comment]
@bethac07 I think I have a fix for this in `issues/3426`, do you mind trying it out?
