### ISSUE TITLE
DisplayPlatemap error

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3427]
From [the forum](http://forum.cellprofiler.org/t/displayplatemap-error-str-object-has-no-attribute-set-bad/5494)

Trying to run DisplayPlatemap in 3.0 gives the following error:

```
Failed to run module DisplayPlatemap
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2894, in do_step
  File "CellProfiler\cellprofiler\modules\displayplatemap.py", line 251, in display
  File "CellProfiler\cellprofiler\gui\figure.py", line 2054, in subplot_platemap
  File "CellProfiler\cellprofiler\gui\figure.py", line 2073, in draw_platemap
AttributeError: 'str' object has no attribute 'set_bad'
```

Validated on my machine (Windows 10 3.0.0 built).  Images and pipeline to reproduce attached below.

[CellProfiler DisplayPlatemap Error.zip](https://github.com/CellProfiler/CellProfiler/files/1573354/CellProfiler.DisplayPlatemap.Error.zip)

**Comment by AetherUnbound** [comment]
@bethac07 I might have a fix for this in the branch `issues/3427`. I'm not sure what to expect as the end result, do you mind checking?

**Comment by bethac07** [comment]
Looks great!  Thanks so much.
