### ISSUE TITLE
Error running from source w/ numpy

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler#3441]
This only happens with numpy 1.13. numpy 1.12 works. 
When trying to start CP from source (macOS), I get an error: 

> Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')()
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/__main__.py", line 152, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/app.py", line 55, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/app.py", line 64, in OnInit
    self.frame.start(self.workspace_path, self.pipeline_path)
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/cpframe.py", line 350, in start
    self.__pipeline_controller.start(workspace_path, pipeline_path)
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 191, in start
    self.do_create_workspace()
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 657, in do_create_workspace
    self.__pipeline.clear()
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/pipeline.py", line 2382, in clear
    self.notify_listeners(PipelineClearedEvent())
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/pipeline.py", line 3188, in notify_listeners
    listener(self, event)
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 1421, in __on_pipeline_event
    self.on_image_set_modification()
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 1432, in on_image_set_modification
    self.__workspace.invalidate_image_set()
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/workspace.py", line 497, in invalidate_image_set
    self.save_pipeline_to_measurements()
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/workspace.py", line 480, in save_pipeline_to_measurements
    self.measurements.add_experiment_measurement(M_PIPELINE, fd.getvalue())
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/measurement.py", line 522, in add_experiment_measurement
    self.hdf5_dict.add_all(EXPERIMENT, feature_name, [data], [0])
  File "/Users/jyhung/Documents/com/github/CellProfiler/cellprofiler/utilities/hdf5_dict.py", line 792, in add_all
    maxshape=(None, 3))
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/group.py", line 103, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 70, in make_new_dset
    if isinstance(chunks, tuple) and (-numpy.array([ i>=j for i,j in zip(tmp_shape,chunks) if i is not None])).any():
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

**Comment by jhung0** [comment]
Oh yes you're right
