### ISSUE TITLE
Startup fails when $TMP points to non-system drive on Windows

### ISSUE THREAD

**Issue by imagejan** [CellProfiler/CellProfiler#3454]
On Windows, when trying to start CellProfiler while having the `$TMP` environment variable configured to something like `E:\temp` (i.e. not on `C:`), I get the following errors:

<details>

```text
Could not load cellprofiler.modules.calculatestatistics
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\calculatestatistics.py", line 153, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.displayplatemap
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\displayplatemap.py", line 45, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.editobjectsmanually
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\editobjectsmanually.py", line 68, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadimages.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.enhanceorsuppressfeatures
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\enhanceorsuppressfeatures.py", line 36, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.exporttodatabase
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 87, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.exporttospreadsheet
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\exporttospreadsheet.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.filterobjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\filterobjects.py", line 73, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.flagimage
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\flagimage.py", line 52, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.groups
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\groups.py", line 4, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.identifyobjectsingrid
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\identifyobjectsingrid.py", line 65, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.identifyprimaryobjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 19, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.identifysecondaryobjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\identifysecondaryobjects.py", line 9, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\threshold.py", line 32, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.identifytertiaryobjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\identifytertiaryobjects.py", line 17, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.images
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\images.py", line 15, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.loadimages
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadimages.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.loadsingleimage
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadsingleimage.py", line 79, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.loaddata
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loaddata.py", line 229, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadimages.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.metadata
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\metadata.py", line 14, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureimageintensity
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureimageintensity.py", line 9, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureimageoverlap
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureimageoverlap.py", line 106, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureimagequality
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureimagequality.py", line 154, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadimages.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureobjectintensity
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureobjectintensity.py", line 15, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureobjectoverlap
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureobjectoverlap.py", line 75, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureobjectsizeshape
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureobjectsizeshape.py", line 26, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.measureobjectintensitydistribution
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\measureobjectintensitydistribution.py", line 24, in <module>
  File "CellProfiler\cellprofiler\modules\measureobjectintensitydistribution.py", line 11, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.namesandtypes
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 13, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.saveimages
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\saveimages.py", line 46, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadimages.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.smooth
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\smooth.py", line 37, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.straightenworms
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\straightenworms.py", line 105, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.threshold
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\threshold.py", line 32, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.trackobjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\trackobjects.py", line 26, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Could not load cellprofiler.modules.untangleworms
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 321, in add_module
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\untangleworms.py", line 125, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
could not load these modules: cellprofiler.modules.calculatestatistics,cellprofiler.modules.displayplatemap,cellprofiler.modules.editobjectsmanually,cellprofiler.modules.enhanceorsuppressfeatures,cellprofiler.modules.exporttodatabase,cellprofiler.modules.exporttospreadsheet,cellprofiler.modules.filterobjects,cellprofiler.modules.flagimage,cellprofiler.modules.groups,cellprofiler.modules.identifyobjectsingrid,cellprofiler.modules.identifyprimaryobjects,cellprofiler.modules.identifysecondaryobjects,cellprofiler.modules.identifytertiaryobjects,cellprofiler.modules.images,cellprofiler.modules.loadimages,cellprofiler.modules.loadsingleimage,cellprofiler.modules.loaddata,cellprofiler.modules.metadata,cellprofiler.modules.measureimageintensity,cellprofiler.modules.measureimageoverlap,cellprofiler.modules.measureimagequality,cellprofiler.modules.measureobjectintensity,cellprofiler.modules.measureobjectoverlap,cellprofiler.modules.measureobjectsizeshape,cellprofiler.modules.measureobjectintensitydistribution,cellprofiler.modules.namesandtypes,cellprofiler.modules.saveimages,cellprofiler.modules.smooth,cellprofiler.modules.straightenworms,cellprofiler.modules.threshold,cellprofiler.modules.trackobjects,cellprofiler.modules.untangleworms
Traceback (most recent call last):
  File "CellProfiler.py", line 8, in <module>
  File "CellProfiler\cellprofiler\__main__.py", line 152, in main
  File "CellProfiler\cellprofiler\gui\app.py", line 55, in __init__
  File "site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
  File "site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
  File "CellProfiler\cellprofiler\gui\app.py", line 58, in OnInit
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\gui\cpframe.py", line 7, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\gui\figure.py", line 43, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\loadimages.py", line 107, in <module>
  File "c:\users\admini~1\appdata\local\temp\2\pip-build-wsqbac\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "CellProfiler\cellprofiler\modules\_help.py", line 235, in <module>
  File "CellProfiler\cellprofiler\modules\_help.py", line 223, in __image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive E:, start on drive C:
Failed to execute script CellProfiler
```
</details>

See also my related [post on the forum](http://forum.cellprofiler.org/t/cellprofiler-3-0-0-startup-issue-on-windows-10/5519?u=imagejan).

Setting `set TMP=C:\temp` works around the issue, but is inconvenient on multi-user systems with (relatively) small system drives, as we'd like to avoid misbehaving applications filling up the system drive with temporary files.

**Comment by AetherUnbound** [comment]
This looks like it's related to this issue: https://bugs.python.org/issue7195

**Comment by imagejan** [comment]
So this issue turns into "handle `relpath` errors gracefully on Windows, and use an absolute path instead" 😄 .

**Comment by AetherUnbound** [comment]
My thoughts as well :) I'll try to get working on a fix for this

**Comment by imagejan** [comment]
Hi @AetherUnbound, any update on this by chance? :slightly_smiling_face:

**Comment by andmccall** [comment]
Hi @AetherUnbound, came across this issue myself when trying to install Cell Profiler. Couldn't this be fixed using the tempfile library of Python? https://www.tutorialspoint.com/generate-temporary-files-and-directories-using-python

**Comment by DavidStirling** [comment]
Should be fixed in packaged versions of CellProfiler 4

**Comment by imagejan** [comment]
@DavidStirling thanks, when is CellProfiler 4 going to be released?

**Comment by DavidStirling** [comment]
We're hoping to get the last release candidate out in the next couple of days, so hopefully it won't be too long now.
