### ISSUE TITLE
Subtracting two binary masks in ImageMath is broken after numpy 1.14 update

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3470]
I don't think this is covered in CP's tests, but it IS in a tutorial pipeline; that pipeline built (though the overall repo didn't for a reason I've since fixed) on [January 6th](https://travis-ci.org/CellProfiler/tutorials/builds/325875035#L672) on numpy 1.13.3 but failed on [January 7th](https://travis-ci.org/CellProfiler/tutorials/builds/326139269#L685) after update to numpy 1.14.  Error below.  Pipeline and images at the tutorial repo [here](https://github.com/CellProfiler/tutorials/tree/master/3d_monolayer).

```
Error detected during run of module ImageMath
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/src/cellprofiler/cellprofiler/pipeline.py", line 1770, in run_with_yield
    self.run_module(module, workspace)
  File "/home/travis/virtualenv/python2.7.14/src/cellprofiler/cellprofiler/pipeline.py", line 2022, in run_module
    module.run(workspace)
  File "/home/travis/virtualenv/python2.7.14/src/cellprofiler/cellprofiler/modules/imagemath.py", line 397, in run
    output_pixel_data = op(output_pixel_data, pd)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by bethac07** [comment]
FWIW the pipeline also runs fine on my laptop in 3.0.0 built but running from source using `numpy==1.14.0+mkl` it fails with the same error.
