### ISSUE TITLE
Warn users if they're extracting a metadata name CP already uses

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3474]
CP has 4 Metadata features it always extracts (`Path/URL`, `Frame`, `Series`, and `FileName`) and a handful of others it extracts if you use the "Export from image file header" option (`ColorFormat`, `SizeZ`, `SizeT`, `SizeC`, `Z`,`T`,`C`). If a users extracts their own metadata and names it one of the CP options (in the [forum post](http://forum.cellprofiler.org/t/exporttodatabase-error-duplicate-column-name/5605/4?u=bcimini) that alerted me to this they used `series`, so it's not case sensitive apparently), you get the error below.

If it's easy to catch this within the Metadata module itself, it'd be nice to do so and make the user change the name of the feature they're trying to extract; if not, it'd be at least nice to put something in the help for Metadata so that they can't say we didn't warn them.

I'll upload the stuff to reproduce when I'm on a better internet connection.

```
Failed to prepare run for module ExportToDatabase
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\pipeline.py", line 2085, in prepare_run
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 1836, in prepare_run
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 2391, in create_database_tables
  File "CellProfiler\cellprofiler\modules\exporttodatabase.py", line 283, in execute
OperationalError: duplicate column name: Image_Metadata_series
```

**Comment by bethac07** [comment]
Actually it looks like Metadata [already does this](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/metadata.py#L1152) and that the list of [reserved tags](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/measurement.py#L179) just needs to be checked in a case-insensitive way.  I'll make a fork on my branch and make that change.
