### ISSUE TITLE
NamesAndTypes error: ValueError: cannot reshape array of size 524288 into shape (512,512)

### ISSUE THREAD

**Issue by burgerga** [CellProfiler/CellProfiler#3476]
I am using Cellprofiler v2.2.1 installed via the conda method on Ubuntu 14.04 using the following conda environment: 

```
# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: cellprofiler2big
# in order of priority: lowest (top) to highest (bottom)
channels:
  - anaconda
  - goodman # mysql-python for mac
  - bioconda
  - bjornfjohansson # wxpython 3.0.2.0
  - conda-forge
  - cyclus
dependencies:
  - appdirs
  - cython
  - h5py
  - ipywidgets
  - java-jdk
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python=2
  - pyzmq=15.3.0
  - mahotas
  - matplotlib!=2.1.0,>2.0.0
  - mysql-python
  - numpy
  - raven
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - wxpython=3.0.2.0
  - pip:
    - "git+https://github.com/LeeKamentsky/python-javabridge.git@issue-121#egg=javabridge-issue-121"
    - cellh5
    - centrosome
    - inflect
    - prokaryote==2.3.2
    - python-bioformats==1.3.1
    - "git+https://github.com/CellProfiler/CellProfiler.git@v2.2.1#egg=cellprofiler-v2.2.1"
```

When I run my pipeline I get the error: 

```
ValueError
Traceback (most recent call last):
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/pipeline.py", line 1956, in run_image_set
    self.run_module(module, workspace)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/pipeline.py", line 2067, in run_module
    module.run(workspace)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/modules/namesandtypes.py", line 1409, in run
    stack)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/modules/namesandtypes.py", line 1461, in add_image_provider
    series, index, channel)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/modules/namesandtypes.py", line 1494, in add_simple_image
    cpmeas.IMAGE)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/modules/namesandtypes.py", line 1513, in add_provider_measurements
    img = m.get_image(name)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/measurements.py", line 1616, in get_image
    image = matching_providers[0].provide_image(self)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/modules/namesandtypes.py", line 1988, in provide_image
    image = LoadImagesImageProviderURL.provide_image(self, image_set)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/cellprofiler/modules/loadimages.py", line 3230, in provide_image
    channel_names=channel_names)
  File "/home/gerhard/miniconda2/envs/cellprofiler2big/lib/python2.7/site-packages/bioformats/formatreader.py", line 816, in read
    image.shape = (height, width)
ValueError: cannot reshape array of size 524288 into shape (512,512)
```

I get the same error on CellProfiler 3. Is this a dependency issue? I am willing to share images and pipeline if needed.

(By the way, It would really help to get clearer Linux install instructions for both CellProfiler 3 and 2.2.1  (CP3 removed quite some functionality we use in our lab...))

**Comment by burgerga** [comment]
Sorry, my mistake, the images turned out to be color images (probability maps from Ilastik) but in NamesAndTypes I specified GrayScale.
