### ISSUE TITLE
Thresholding with "Adaptive" throws an error if window size >50% of image size

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3530]
In Threshold or modules that inherit their thresholding from it (like IPO), if you try to do adaptive thresholding with an adaptive window size >50% of the total image size, CP throws some rather uninformative errors. This affects both 2D and 3D.  Ideally we'd catch these in the GUI and keep the user from entering these values in the first place, but if we don't want to do that at least let's catch them with nicer error messages.

If the window size is >50% of the image dimensions but <100%:
```
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2887, in do_step
  File "CellProfiler\cellprofiler\pipeline.py", line 2022, in run_module
  File "CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 964, in run
  File "CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 1070, in _threshold_image
  File "CellProfiler\cellprofiler\modules\threshold.py", line 740, in get_threshold
  File "CellProfiler\cellprofiler\modules\threshold.py", line 854, in _threshold_otsu3
  File "site-packages\centrosome\threshold.py", line 237, in get_adaptive_threshold
  File "site-packages\scipy\interpolate\fitpack2.py", line 1174, in __init__
error: (1<=kx && kx<=5) failed for 5th keyword kx: regrid_smth:kx=0
```

If window size is >100%:
```
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2887, in do_step
  File "CellProfiler\cellprofiler\pipeline.py", line 2022, in run_module
  File "CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 964, in run
  File "CellProfiler\cellprofiler\modules\identifyprimaryobjects.py", line 1070, in _threshold_image
  File "CellProfiler\cellprofiler\modules\threshold.py", line 740, in get_threshold
  File "CellProfiler\cellprofiler\modules\threshold.py", line 854, in _threshold_otsu3
  File "site-packages\centrosome\threshold.py", line 224, in get_adaptive_threshold
OverflowError: cannot convert float infinity to integer
```
Pipeline plus image to validate adapted [from the forum](http://forum.cellprofiler.org/t/cellprofiler-3d-threshold-error/5743/)
[AdaptiveThresholdBug.zip](https://github.com/CellProfiler/CellProfiler/files/1853956/AdaptiveThresholdBug.zip)

**Comment by DavidStirling** [comment]
I don't know if we can robustly catch these within the GUI since image sets don't always have the same dimensions, so I've made the centrosome module raise an error if the window is too large. That should at least catch this in test mode.
