### ISSUE TITLE
Resize fails when image isn't between -1 and 1

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3531]
In 3.0.0 and 3.1.1, if you try to do a resize module on an image that's not between -1 and 1, you get the error below.  This happens with all interpolation methods and resizing factors I tried (both up and down).  This is crucial for moving the Cell Painting illumination correction pipeline (or really any illumination correction pipeline done on large images) to 3.X.

```
Failed to run module Resize
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2887, in do_step
  File "CellProfiler\cellprofiler\pipeline.py", line 2022, in run_module
  File "CellProfiler\cellprofiler\modules\resize.py", line 258, in run
  File "CellProfiler\cellprofiler\modules\resize.py", line 336, in apply_resize
  File "site-packages\skimage\transform\_warps.py", line 135, in resize
  File "site-packages\skimage\transform\_warps.py", line 722, in warp
  File "site-packages\skimage\transform\_warps.py", line 535, in _convert_warp_input
  File "site-packages\skimage\util\dtype.py", line 336, in img_as_float
  File "site-packages\skimage\util\dtype.py", line 236, in convert
ValueError: Images of type float must be between -1 and 1.
```

Files and tip via [the forum](http://forum.cellprofiler.org/t/problem-with-the-illumination/5850)
[ResizeBug.zip](https://github.com/CellProfiler/CellProfiler/files/1854112/ResizeBug.zip)

**Comment by AetherUnbound** [comment]
I feel like this may be an issue with the illumination correction module more than it is a module with resize, because resize is expecting float values between -1 and 1 (which I think CellProfiler "should" keep all images in that format internally) but the illumination pipeline provided creates an image with `1` and `2` as values. I'm still investigating this though.

**Comment by bethac07** [comment]
Yeah, someone just posted a bug in another module in the forum the other day re: other modules being cranky with values outside of the -1>x>1 range.  The cases where you have values outside that range are rare (such as illumination correction), but important and CP should be able to handle them.

**Comment by votti** [comment]
Hi there,
I am using CellProfiller for analyzing imaging mass cytometry data (https://github.com/BodenmillerGroup/ImcSegmentationPipeline) . I am currently trying  to move our pipeline to CP3. Our raw data images are 32bit float and CP is loading them without reclscaling to -1/1, which so far was convenient (e.g our in house module to correct metal inpurities can work with the values directly without dealing with value scaling ) . So trying to move to CP3, I also got this error when doing some image resizing.

If nobody has fixed this yet, I am happy to write a pull request.
