### ISSUE TITLE
ColorToGray error

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#3547]
![image](https://user-images.githubusercontent.com/156232/38749589-177eb2dc-3f20-11e8-8e60-a5eb06f601f3.png)

```
Failed to run module ColorToGray
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 2895, in do_step
    module.display(workspace, fig)
  File "cellprofiler\modules\colortogray.py", line 395, in display
    self.display_combine(workspace, figure)
  File "cellprofiler\modules\colortogray.py", line 423, in display_combine
    title="Original image: %s" % self.image_name)
  File "cellprofiler\gui\figure.py", line 180, in wrapper
    return fn(*args, **kwargs)
  File "cellprofiler\gui\figure.py", line 1555, in subplot_imshow_color
    return self.subplot_imshow(x, y, image, title, normalize=normalize, rgb_mask=rgb_mask, **kwargs)
  File "cellprofiler\gui\figure.py", line 180, in wrapper
    return fn(*args, **kwargs)
  File "cellprofiler\gui\figure.py", line 1417, in subplot_imshow
    self.set_subplot_title(title, x, y)
  File "cellprofiler\gui\figure.py", line 875, in set_subplot_title
    self.subplot(x, y).set_title(title, fontname=fontname, fontsize=cellprofiler.preferences.get_title_font_size())
  File "C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\cellprofiler\lib\site-packages\matplotlib\axes\_axes.py", line 185, in set_title
    title.set_text(label)
  File "C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\cellprofiler\lib\site-packages\matplotlib\text.py", line 1178, in set_text
    self._text = '%s' % (s,)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 16: ordinal not in range(128)
```

**Comment by karhohs** [comment]
"closing the eye" circumvents this issue.

**Comment by AetherUnbound** [comment]
Do you mind posting an example pipeline and images?

**Comment by AetherUnbound** [comment]
I've got a fix for this in this branch, do you mind testing it? It might break a bunch of other stuff: https://github.com/CellProfiler/CellProfiler/tree/issues/3547

**Comment by DavidStirling** [comment]
@AetherUnbound - This was a while ago, did you still want to test/merge that branch?

**Comment by bethac07** [comment]
This is fixed elsewhere now.
