### ISSUE TITLE
EnhanceOrSuppressFeatures display error

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#3548]
```
Failed to run module EnhanceOrSuppressFeatures
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 2895, in do_step
    module.display(workspace, fig)
  File "cellprofiler\module.py", line 943, in display
    y=0
  File "cellprofiler\gui\figure.py", line 180, in wrapper
    return fn(*args, **kwargs)
  File "cellprofiler\gui\figure.py", line 1460, in subplot_imshow
    subplot.imshow(self.normalize_image(image, **kwargs))
  File "cellprofiler\gui\figure.py", line 1744, in normalize_image
    image = skimage.exposure.adjust_log(image, **kwargs["normalize_args"])
  File "C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\cellprofiler\lib\site-packages\skimage\exposure\exposure.py", line 398, in adjust_log
    _assert_non_negative(image)
  File "C:\Users\karhohs\AppData\Local\Continuum\Miniconda3\envs\cellprofiler\lib\site-packages\skimage\exposure\exposure.py", line 304, in _assert_non_negative
    raise ValueError('Image Correction methods work correctly only on '
ValueError: Image Correction methods work correctly only on images with non-negative values. Use skimage.exposure.rescale_intensity.
```

**Comment by karhohs** [comment]
Similar to #3547 , "closing the eye" circumvents the issue.

**Comment by DavidStirling** [comment]
Please re-open if this is encountered again.
