### ISSUE TITLE
CP3.1.3 display error for LoadData in moduleview.py Ubuntu16.04

### ISSUE THREAD

**Issue by cmohl2013** [CellProfiler/CellProfiler#3586]
When reopening a previously saved saved project that includes the LoadData module, following error occurs in moduleview.py:

```
Traceback (most recent call last):
gui_1  |   File "/CellProfiler/cellprofiler/workspace.py", line 555, in notify
gui_1  |     callback(event)
gui_1  |   File "/CellProfiler/cellprofiler/gui/moduleview.py", line 2228, in __on_workspace_event
gui_1  |     self.do_reset()
gui_1  |   File "/CellProfiler/cellprofiler/gui/moduleview.py", line 2325, in do_reset
gui_1  |     self.set_selection(self.__module.module_num)
gui_1  |   File "/CellProfiler/cellprofiler/gui/moduleview.py", line 546, in set_selection
gui_1  |     control = self.make_filename_text_control(v, control)
gui_1  |   File "/CellProfiler/cellprofiler/gui/moduleview.py", line 1435, in make_filename_text_control
gui_1  |     if edit_control.Value != v.value:
gui_1  | AttributeError: 'NoneType' object has no attribute 'Value'
```

In the GUI, the file selection is missing (just path selection remaining):

![screenshot_loaddata_error](https://user-images.githubusercontent.com/4705426/41150975-ab2f2082-6b0f-11e8-9fe2-12e13d800a2c.jpg)

As said, this error only occurs when reloading a previously saved project.

**Comment by bethac07** [comment]
Resolved by #3587
