### ISSUE TITLE
JavaException within "Names and Types" in example pipeline

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#3633]
Hi,

I am experiencing as JavaException within "Names and Types" in example pipeline

I just set up a docker container with a  python environment in which I can run Cellprofiler 3.x. To create the dockerfile I adapted the singularity recipe from here: https://github.com/lunarc/singularity_recipies

My `Dockerfile` is at https://github.com/VolkerH/MyDockerStuff/blob/master/CP3_Container/Dockerfile
Basically, it is a minimal install of all the dependencies for Cellprofiler on a Ubuntu 16.04. 
After building the dockerimage I can log into an instance, set X forwarding and start CellProfiler. I then click on the download link for the example pipeline and start the Analysis. It starts some workers but crashes with a Java Exception:

Below is the tail of the console output. You can see the full transcript (including the build process of the docker image) here: https://github.com/VolkerH/MyDockerStuff/blob/master/CP3_Container/logfile.txt

```
(cellprofiler:17): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
Progress Counter({u'Unprocessed': 2, u'FinishedWaitingMeasurements': 1})
Progress Counter({u'Unprocessed': 2, u'Done': 1})
Worker 0: Starting job
Progress Counter({u'Unprocessed': 1, u'Done': 1, u'InProcess': 1})
Worker 0: Doing job: 2
Worker 0: Running module Images 1
Worker 0: Mon Aug 27 01:40:56 2018: Image # 2, module Images # 1: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Worker 0: Running module Metadata 2
Worker 0: Mon Aug 27 01:40:56 2018: Image # 2, module Metadata # 2: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Worker 0: Running module NamesAndTypes 3
Worker 0: Exception in thread "Thread-1" org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (<java-python-bridge>#8)
Worker 0:       at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
Worker 0:       at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
Worker 0:       at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
Worker 0:       at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
Worker 0:       at org.mozilla.javascript.gen._java_python_bridge__18._c_script_0(<java-python-bridge>:8)
Worker 0:       at org.mozilla.javascript.gen._java_python_bridge__18.call(<java-python-bridge>)
Worker 0:       at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
Worker 0:       at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
Worker 0:       at org.mozilla.javascript.gen._java_python_bridge__18.call(<java-python-bridge>)
Worker 0:       at org.mozilla.javascript.gen._java_python_bridge__18.exec(<java-python-bridge>)
Worker 0:       at org.mozilla.javascript.Context.evaluateString(Context.java:1079)
Worker 0: Caused by: java.lang.NullPointerException
Worker 0:       at loci.common.Location.<init>(Location.java:104)
Worker 0:       at loci.common.Location.getParentFile(Location.java:623)
Worker 0:       at loci.formats.in.CellVoyagerReader.isThisType(CellVoyagerReader.java:256)
Worker 0:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Worker 0:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Worker 0:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Worker 0:       at java.lang.reflect.Method.invoke(Method.java:498)
Worker 0:       at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
Worker 0:       ... 9 more
Worker 0: Error detected during run of module NamesAndTypes#3
Worker 0: Traceback (most recent call last):
Worker 0:   File "/CellProfiler/cellprofiler/pipeline.py", line 1921, in run_image_set
Worker 0:     self.run_module(module, workspace)
Worker 0:   File "/CellProfiler/cellprofiler/pipeline.py", line 2031, in run_module
Worker 0:     module.run(workspace)
Worker 0:   File "/CellProfiler/cellprofiler/modules/namesandtypes.py", line 1755, in run
Worker 0:     stack)
Worker 0:   File "/CellProfiler/cellprofiler/modules/namesandtypes.py", line 1807, in add_image_provider
Worker 0:     series, index, channel)
Worker 0:   File "/CellProfiler/cellprofiler/modules/namesandtypes.py", line 1847, in add_simple_image
Worker 0:     self.add_provider_measurements(provider, m, cellprofiler.measurement.IMAGE)
Worker 0:   File "/CellProfiler/cellprofiler/modules/namesandtypes.py", line 1861, in add_provider_measurements
Worker 0:     img = provider.provide_image(m)
Worker 0:   File "/CellProfiler/cellprofiler/modules/namesandtypes.py", line 2360, in provide_image
Worker 0:     image = loadimages.LoadImagesImageProviderURL.provide_image(self, image_set)
Worker 0:   File "/CellProfiler/cellprofiler/modules/loadimages.py", line 3571, in provide_image
Worker 0:     self.__set_image()
Worker 0:   File "/CellProfiler/cellprofiler/modules/loadimages.py", line 3526, in __set_image
Worker 0:     self.get_name(), url=self.get_url())
Worker 0:   File "/usr/local/lib/python2.7/dist-packages/bioformats/formatreader.py", line 961, in get_image_reader
Worker 0:     rdr = ImageReader(path=path, url=url)
Worker 0:   File "/usr/local/lib/python2.7/dist-packages/bioformats/formatreader.py", line 668, in __init__
Worker 0:     stream = self.stream))
Worker 0:   File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 394, in run_script
Worker 0:     raise JavaException(call(e.throwable, "unwrap", "()Ljava/lang/Object;"))
Worker 0: JavaException
```

**Comment by VolkerH** [comment]
I now encountered what appears to be the same error on a windows machine that was set up with a conda environment. Also in CellProfiler v 3.1.5
Error log and pip freeze output below. This was trying to run the test pipeline (link at the top of the splash screen). Seems to happen for other images in Names and Types as well.  
```
Exception in thread "Thread-0" org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (<java-python-bridge>#8)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen._java_python_bridge__24._c_script_0(<java-python-bridge>:8)
        at org.mozilla.javascript.gen._java_python_bridge__24.call(<java-python-bridge>)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen._java_python_bridge__24.call(<java-python-bridge>)
        at org.mozilla.javascript.gen._java_python_bridge__24.exec(<java-python-bridge>)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1079)
Caused by: java.lang.NullPointerException
        at loci.common.Location.<init>(Location.java:104)
        at loci.common.Location.getParentFile(Location.java:623)
        at loci.formats.in.CellVoyagerReader.isThisType(CellVoyagerReader.java:256)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        ... 9 more
Failed to run module NamesAndTypes
Traceback (most recent call last):
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\gui\pipelinecontroller.py", line 2889, in do_step
    self.__pipeline.run_module(module, workspace)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\pipeline.py", line 2031, in run_module
    module.run(workspace)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\namesandtypes.py", line 1755, in run
    stack)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\namesandtypes.py", line 1807, in add_image_provider
    series, index, channel)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\namesandtypes.py", line 1847, in add_simple_image
    self.add_provider_measurements(provider, m, cellprofiler.measurement.IMAGE)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\namesandtypes.py", line 1861, in add_provider_measurements
    img = provider.provide_image(m)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\namesandtypes.py", line 2360, in provide_image
    image = loadimages.LoadImagesImageProviderURL.provide_image(self, image_set)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\loadimages.py", line 3571, in provide_image
    self.__set_image()
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\loadimages.py", line 3526, in __set_image
    self.get_name(), url=self.get_url())
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\bioformats\formatreader.py", line 961, in get_image_reader
    rdr = ImageReader(path=path, url=url)
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\bioformats\formatreader.py", line 668, in __init__
    stream = self.stream))
  File "d:\volker\anaconda\envs\cellprofiler\lib\site-packages\javabridge\jutil.py", line 394, in run_script
    raise JavaException(call(e.throwable, "unwrap", "()Ljava/lang/Object;"))
JavaException

(cellprofiler) D:\>pip freeze
alabaster==0.7.11
appdirs==1.4.3
asn1crypto==0.24.0
Babel==2.6.0
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.lzma==0.0.13
backports.shutil-get-terminal-size==1.0.0
backports.shutil-which==3.5.1
bleach==2.1.4
boto3==1.8.4
botocore==1.11.4
cellh5==1.3.0
CellProfiler==3.1.5
centrosome==1.0.9
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
cloudpickle==0.5.5
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
cryptography==2.3
cryptography-vectors==2.3.1
cycler==0.10.0
Cython==0.28.5
dask==0.18.2
decorator==4.3.0
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
h5py==2.8.0
hmmlearn==0.2.0
html5lib==1.0.1
idna==2.7
imageio==2.3.0
imagesize==1.0.0
inflect==1.0.0
ipaddress==1.0.22
ipykernel==4.8.2
ipython==5.8.0
ipython-genutils==0.2.0
ipywidgets==7.4.0
javabridge==1.0.15
Jinja2==2.10
jmespath==0.9.3
joblib==0.12.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
linecache2==1.0.0
lxml==4.2.4
mahotas==1.4.4
MarkupSafe==1.0
matplotlib==2.2.3
mistune==0.8.3
mkl-fft==1.0.4
MySQL-python==1.2.5
mysqlclient==1.3.13
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.4.1
numpy==1.15.1
olefile==0.45.1
packaging==17.1
pandas==0.23.4
pandocfilters==1.4.2
pathlib==1.0.1
pathlib2==2.3.2
pickleshare==0.7.4
Pillow==5.2.0
prokaryote==2.4.0
prompt-toolkit==1.0.15
pycparser==2.18
Pygments==2.2.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
Pypubsub==4.0.0
PySocks==1.6.8
python-bioformats==1.4.0
python-dateutil==2.7.3
pytz==2018.5
PyWavelets==0.5.2
pywinpty==0.5.4
pyzmq==15.3.0
qtconsole==4.4.1
raven==6.9.0
requests==2.19.1
s3transfer==0.1.13
scandir==1.9.0
scikit-image==0.14.0
scikit-learn==0.19.1
scipy==1.1.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
sip==4.19.12
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.7
sphinxcontrib-websupport==1.1.0
terminado==0.8.1
testpath==0.3.1
tifffile==0.15.1
toolz==0.9.0
tornado==5.1
traceback2==1.4.0
traitlets==4.3.2
typing==3.6.6
unittest2==1.1.0
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.0
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
```

**Comment by VolkerH** [comment]
at least in my docker container this went away after rebuilding the container from the same Dockerfile a few days later. Maybe one of the many upstream repositories (ubuntu and pip) caused this on the day I built the image. Hard to track down.

**Comment by VolkerH** [comment]
I haven't gotten it to work and gave up once I got the docker image running.
I would be very happy if you got rid of the Java dependencies, for me it
wouldn't be a big problem if CP would only accept tifs, but that's just me.

**Comment by AetherUnbound** [comment]
You and me both :) We're slowly working towards it, but one advantage of these dependencies (essentially, bioformats) is that it enables an extremely low barrier for testing images from hundreds of vendors. But, it's only an advantage if you can actually run CellProfiler!

Seeing as you have the docker build working again, can I close this issue?

**Comment by VolkerH** [comment]
Happy to close.
