### ISSUE TITLE
Docker Cellprofiler GUI metadata not extracted

### ISSUE THREAD

**Issue by anou85** [CellProfiler/CellProfiler#3655]
Hi,
I've been trying to get a version of CP (either 2.3.1 or 3.0.0) running on my newly installed Ubuntu 18.04. It installs, but doesn't start because of diverse errors (or dependency issues). 
So I've moved to docker and downloaded the 2.3.1 and latest docker image. The start fine with:
`docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro cellprofiler/cellprofiler:2.3.1 ""`
but when I try to analyse an image, the metadata is not loaded. It seems CP is unable to extract the metadata from the image. But there is no error except for a gtk-warning and a not-existing module vigra...
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Gtk-Message: Failed to load module "canberra-gtk-module"
Exception fetching new version information from http://cellprofiler.org/CPupdate.html: HTTP Error 404: Not Found
vigra import: failed to import the vigra library. Please follow the instructions on
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/modules/classifypixels.py", line 50, in <module>
    import vigra
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 47, in <module>
    import vigra
ImportError: No module named vigra
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Version: 2018-03-07T17:52:44 e07291c / 20180307175244

(cellprofiler:171): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.S8RDQZ': No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.BGB9PZ': No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.O7OFQZ': No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.B8OCQZ': No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.KE9HQZ': No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
Exiting the pipeline validation thread

(cellprofiler:171): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.3GCIQZ': No such file or directory

(cellprofiler:171): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/cellprofiler/ijutils/CellProfilerApp
Caused by: java.lang.ClassNotFoundException: org.cellprofiler.ijutils.CellProfilerApp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Failed to stop Ilastik
Failed to get class org/cellprofiler/ijutils/CellProfilerApp
File name listener doubly removed
[cmd] cellprofiler exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Any ideas how I can get it to work?

Cheers

**Comment by AetherUnbound** [comment]
Hmm, it looks like it might be a Java issue. Do you need to use Docker to run CellProfiler? Perhaps I can help you get it running in native 18.04. I'd start with the Anaconda environment install described in [our wiki](https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation)

**Comment by AetherUnbound** [comment]
Closing this, please feel free to reopen if the issue persists.

**Comment by anou85** [comment]
@AetherUnbound 
Sorry, I didn't actually see your reply. the reason I used Docker is, that I was unable to install the 2.2.0 or 3.0 versions on Ubuntu 16.04 or 18.01. The 18.04 was a clean system, but I still got dependency issues. The latest problem was the correct version of the matplotlib. so I basically gave up and tried my luck with Docker.

**Comment by AetherUnbound** [comment]
Would you like me to re-open this or did you have success with Docker?

**Comment by anou85** [comment]
It would be helpful to know which package versions (matplotlib, javabridge, etc) the different versions of CP require, so I could try and get it running. Or an updated Docker file?

**Comment by bethac07** [comment]
Dockers for 2.3.1, 3.0.0, and 3.1.5 are all available [here](https://hub.docker.com/r/cellprofiler/cellprofiler/tags/).

**Comment by anou85** [comment]
@bethac07 
I've tried the older Docker files without success. Will try the 3.1.5. thanks
