### ISSUE TITLE
Circular Average Filter error

### ISSUE THREAD

**Issue by hkhawar** [CellProfiler/CellProfiler#3686]
Following error in using Circular Average Filter

only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by bethac07** [comment]
Can you post the full error message, as well as pipeline and images to reproduce?  Thanks!

**Comment by hkhawar** [comment]
[pipeline.zip](https://github.com/CellProfiler/CellProfiler/files/2590643/pipeline.zip)

**Comment by bethac07** [comment]
Full error stack

```
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 2889, in do_step
    self.__pipeline.run_module(module, workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 2031, in run_module
    module.run(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/smooth.py", line 212, in run
    output_pixels = circular_average_filter(pixel_data, object_size / 2 + 1, image.mask)
  File "/usr/local/lib/python2.7/site-packages/centrosome/filter.py", line 756, in circular_average_filter
    sgrid[crad,crad] = np.minimum(np.pi*radius**2,np.pi/2)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by bethac07** [comment]
Found the issue in centrosome (numpy won't accept the output of numpy.ceil anymore as an index without explicitly casting it to an int), put in a PR there
