### ISSUE TITLE
CalculateMath throws a bug when you try to add object measurements downstream of RelateObjects

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3692]
It seems to happen only when you're trying to do calculations based on the measurements of the parent objects - child objects and objects that haven't been related seem to work just fine.  Likely related to everything going on in #3677 , just want to make this separate to check if it's been fixed after that issue is resolved.

Stack trace here:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_misc.py", line 1367, in Notify
    self.notify()
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16869, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/moduleview.py", line 2325, in do_reset
    self.set_selection(self.__module.module_num)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/moduleview.py", line 534, in set_selection
    control = self.make_measurement_control(v, control)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/moduleview.py", line 2011, in make_measurement_control
    category, True)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/moduleview.py", line 1988, in set_up_combobox
    ctrl.AppendItems(choices)
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 12870, in AppendItems
    return _core_.ItemContainer_AppendItems(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 5: invalid start byte
```

**Comment by bethac07** [comment]
Fixed in 319

**Comment by bethac07** [comment]
Nope, not fixed in 319
