### ISSUE TITLE
Cannot start CellProfiler 3.1 on Windows from any drive but C:

### ISSUE THREAD

**Issue by cgohlke** [CellProfiler/CellProfiler#3708]
CellProfiler-3.1.x  fails to start when installed on a drive other than `C:`, e.g. a network drive mapped as `X:`:
```
Traceback (most recent call last):
  File "CellProfiler.py", line 3, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "CellProfiler\cellprofiler\__main__.py", line 16, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "CellProfiler\cellprofiler\measurement.py", line 15, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "CellProfiler\cellprofiler\preferences.py", line 25, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "CellProfiler\cellprofiler\gui\help\content.py", line 60, in <module>
  File "CellProfiler\cellprofiler\gui\help\content.py", line 33, in image_resource
  File "ntpath.py", line 529, in relpath
ValueError: path is on drive C:, start on drive X:
[16164] Failed to execute script CellProfiler
```

**Comment by bethac07** [comment]
Related to #3454, a workaround is to set TMP to that drive, then CP should start (see also [the forum](https://forum.image.sc/t/cellprofiler-3-0-doesnt-launch-if-not-installed-on-same-drive-as-user-profiles/18950).  Apologies, we're working on it!

**Comment by cgohlke** [comment]
Yes, #3454 is the same issue.

**Comment by jyning12** [comment]
I have the same issue, but in #3454 I can't find solution
