### ISSUE TITLE
error from ClassifyObjects -pair of measurement 

### ISSUE THREAD

**Issue by hkhawar** [CellProfiler/CellProfiler#3716]
Failed to run module ClassifyObjects
Traceback (most recent call last):
  File "cellprofiler/gui/pipelinecontroller.py", line 2926, in do_step
  File "cellprofiler/modules/classifyobjects.py", line 561, in display
  File "cellprofiler/modules/classifyobjects.py", line 668, in display_two_measurements
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3143 but corresponding boolean dimension is 3142

[test.zip](https://github.com/CellProfiler/CellProfiler/files/2833101/test.zip)

**Comment by bethac07** [comment]
Also, is this built or source? Presumably 3.1.8?
