### ISSUE TITLE
CellProfiler 3.1.8 | Ubuntu 18.04.2 | 3D Watershed error

### ISSUE THREAD

**Issue by dmattek** [CellProfiler/CellProfiler#3731]
I'm trying to process a TIFF stack (2 channels, 35 Z planes, 4 time points) as 3D with CP 3.1.8 pipeline on Ubuntu 18.04.2. Individual time points are processed independently.

I'm getting this error when reaching Watershed module:

```
Worker 2: Running module Watershed 10
Worker 2: Error detected during run of module Watershed#10
Worker 2: Traceback (most recent call last):
Worker 2:   File "/sw_install/CellProfiler/cellprofiler/pipeline.py", line 1924, in run_image_set
Worker 2:     self.run_module(module, workspace)
Worker 2:   File "/sw_install/CellProfiler/cellprofiler/pipeline.py", line 2034, in run_module
Worker 2:     module.run(workspace)
Worker 2:   File "/sw_install/CellProfiler/cellprofiler/modules/watershed.py", line 228, in run
Worker 2:     factors
Worker 2:   File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py", line 428, in downscale_local_mean
Worker 2:     return block_reduce(image, factors, np.mean, cval)
Worker 2:   File "/usr/local/lib/python2.7/dist-packages/skimage/measure/block.py", line 56, in block_reduce
Worker 2:     raise ValueError("`block_size` must have the same length "
Worker 2: ValueError: `block_size` must have the same length as `image.shape`.
```

The full log, the pipeline, and the TIFF stack are available [here](https://www.dropbox.com/sh/1sccl59ka2e3edh/AAAraXP4q9T09GP8XDnTr53_a?dl=0) (~52MB).

**Comment by muddywellyboots** [comment]
Hi,
My issues with 3D processing were solved when I imported separate channels/timepoints as individual tiffs. Does this do anything for you?
