### ISSUE TITLE
Installing via pip on Macosx -- MySQL related

### ISSUE THREAD

**Issue by benblamey** [CellProfiler/CellProfiler#3742]
Great Software!
Tried to install via pip - fails with a MySQL issue:

```
$ python2 -m pip install cellprofiler
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting cellprofiler
  Using cached https://files.pythonhosted.org/packages/31/74/c476bcf870942e9708bd8a94b85ddde79faf976ae52e7f55f9e4b4bdf43e/CellProfiler-3.0.0rc3-py2-none-any.whl
Collecting scikit-learn (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/07/42/a01e4b3eb29cb48f759ea706f65515beb9a149ac248eaa4055a8f6dc989f/scikit_learn-0.20.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting inflect (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/86/02/e6b11020a9c37d25b4767a1d0af5835629f6e75d6f51553ad07a4c73dc31/inflect-2.1.0-py2.py3-none-any.whl
Collecting prokaryote>=2.1.2 (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/76/8e/feedbb800c703356f60f111d9b0490b90f7cddde74538b4f1923caab1800/prokaryote-2.4.1.tar.gz
Collecting scipy (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/85/70/9f8f1e9ed9fd33b96bb27fb080171fb571f7d33fecbd857e9f504e6dcc9a/scipy-1.2.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting python-bioformats>=1.2.0 (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/85/81/a6abd3e367cbbcd9419ebe476557766bc4e4aa662b2ea2def79f508c8b61/python_bioformats-1.5.2-py2-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages/requests-2.19.1-py2.7.egg (from cellprofiler) (2.19.1)
Collecting javabridge (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
Collecting numpy (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/6e/36/e8369aa628b29f50211ba82daec31cc110f6627feca160bc11b0e4ee1191/numpy-1.16.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyzmq==15.3.0 (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/bf/ac/04d33f04420c514dabc623297e73c0e69ab8994c6b901507a328795306f9/pyzmq-15.3.0-cp27-cp27m-macosx_10_6_intel.whl
Collecting h5py (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/98/06/0e711ae0c95d92ec238218448a15c23590cb117ded59e4bfa322b085b59e/h5py-2.9.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting matplotlib (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/3e/d6/4c949597c4186599cc8be08cd11b1e83fe7966676aeee3868bf3e581d852/matplotlib-2.2.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting MySQL-python (from cellprofiler)
  Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6y/qj74h7391tb1xcscdbxhnnz00000gn/T/pip-install-nKWTKn/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6y/qj74h7391tb1xcscdbxhnnz00000gn/T/pip-install-nKWTKn/MySQL-python/
```

Installing MySQL-python by itself gives the same error for me, so its not really a CellProfiler bug per-se.
```
python2 -m pip install MySQL-python
```

**Comment by benblamey** [comment]
Have filed issue for the root cause:
https://github.com/arnaudsj/mysql-python/issues/4

**Comment by ranka47** [comment]
Did you try [this](https://stackoverflow.com/questions/25459386/mac-os-x-environmenterror-mysql-config-not-found)?

I had faced the same error on Ubuntu system. After I installed the `mysqlclient-dev`, the pip installation worked. 

You might also want to try the installation shared [here](https://github.com/CellProfiler/notebooks):

**Comment by 0x00b1** [comment]
Thanks again, @benblamey!
