### ISSUE TITLE
Unable to run headlessly in Python 3

### ISSUE THREAD

**Issue by crm416** [CellProfiler/CellProfiler#3785]
Attempting to run a pipeline headlessly in Python 3 gives me the following trace:

```py
Traceback (most recent call last):
  File "/opt/conda/envs/beam3/bin/cellprofiler", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/beam3/lib/python3.6/site-packages/cellprofiler/__main__.py", line 171, in main
    exit_code = run_pipeline_headless(options, args)
  File "/opt/conda/envs/beam3/lib/python3.6/site-packages/cellprofiler/__main__.py", line 703, in run_pipeline_headless
    pipeline.load(options.pipeline_filename)
  File "/opt/conda/envs/beam3/lib/python3.6/site-packages/cellprofiler/pipeline.py", line 795, in load
    if Pipeline.is_pipeline_txt_fd(fd):
  File "/opt/conda/envs/beam3/lib/python3.6/site-packages/cellprofiler/pipeline.py", line 753, in is_pipeline_txt_fd
    if header.startswith(COOKIE):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

It looks like `header` is `bytes`, but `COOKIE` is a string (`str`). (In Python 2, reading with `rb` and `.read()` returns a `str` so the check seems to work fine.)

For completeness, the initiating command was roughly:

```
cellprofiler -c -r -p Nuclei.cppipe ...
```

**Comment by crm416** [comment]
Apologies, did not realize that there was an independent Python 3 branch.

**Comment by nichollsfj** [comment]
I'm also getting this error - what do you mean by an independent Python 3 branch? A git branch? I couldn't see one...

**Comment by crm416** [comment]
There was a separate branch at time of writing, though I'm no longer seeing it, so it was likely deleted or merged into master.
