### ISSUE TITLE
pip install fails due to NumPy's dropped Python 2 support

### ISSUE THREAD

**Issue by crm416** [CellProfiler/CellProfiler#3786]
Doing a fresh clone of the repo and running `pip install .` (after `git checkout tags/v3.1.8`, though I get the same behavior on `master`) results in the following trace:

```
Collecting centrosome (from CellProfiler==3.1.8)
  Using cached https://files.pythonhosted.org/packages/8e/4d/246b4e375be61fb6a51a4511d749cb5aa845dc5e61d799eece6a1a87f7d1/centrosome-1.1.6.tar.gz
    Complete output from command python setup.py egg_info:
      File "build/bdist.linux-x86_64/egg/_pytest/outcomes.py", line 76
        def skip(msg="", *, allow_module_level=False):
                          ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/_pytest/pytester.py", line 772
        def inline_run(self, *args, plugins=(), no_reraise_ctrlc=False):
                                          ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/_pytest/main.py", line 507
        yield from self._collect(arg)
                 ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/_pytest/assertion/rewrite.py", line 462
        def _get_assertion_exprs(src: bytes):  # -> Dict[int, str]
                                    ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/_pytest/resultlog.py", line 52
        print("{} {}".format(lettercode, testpath), file=self.logfile)
                                                        ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/_pytest/python.py", line 650
        yield from self._collectfile(path)
                 ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/_pytest/pathlib.py", line 131
        ) from e
             ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/main.py", line 507
        yield from self._collect(arg)
                 ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/outcomes.py", line 76
        def skip(msg="", *, allow_module_level=False):
                          ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/pathlib.py", line 131
        ) from e
             ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/pytester.py", line 772
        def inline_run(self, *args, plugins=(), no_reraise_ctrlc=False):
                                          ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/python.py", line 650
        yield from self._collectfile(path)
                 ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/resultlog.py", line 52
        print("{} {}".format(lettercode, testpath), file=self.logfile)
                                                        ^
    SyntaxError: invalid syntax

      File "/tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg/_pytest/assertion/rewrite.py", line 462
        def _get_assertion_exprs(src: bytes):  # -> Dict[int, str]
                                    ^
    SyntaxError: invalid syntax


    Installed /tmp/pip-install-Q2x44A/centrosome/.eggs/pytest-5.0.0-py2.7.egg
    Searching for numpy
    Reading https://pypi.org/simple/numpy/
    Downloading https://files.pythonhosted.org/packages/c1/ff/aeb22192bab0643551a161dc4ed305892cead687ee97453daed4dc1dd38e/numpy-1.17.0rc1.zip#sha256=f53df05f9ca4ec5d72709ffe349704f1f7d945ed59e815574b5c5687acb282c4
    Best match: numpy 1.17.0rc1
    Processing numpy-1.17.0rc1.zip
    Writing /tmp/easy_install-Iftw9E/numpy-1.17.0rc1/setup.cfg
    Running numpy-1.17.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Iftw9E/numpy-1.17.0rc1/egg-dist-tmp-D1SbvN
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Q2x44A/centrosome/setup.py", line 141, in <module>
        version="1.1.6"
      File "/opt/conda/lib/python2.7/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/opt/conda/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/opt/conda/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/opt/conda/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-Iftw9E/numpy-1.17.0rc1/setup.py", line 31, in <module>

    RuntimeError: Python version >= 3.5 required.
```

I believe the issue is that NumPy [released 1.17.0rc1 yesterday](https://github.com/numpy/numpy/releases), and as of 1.17, NumPy no longer supports Python 2. Because CellProfiler accepts `"numpy>=1.16"` (per `setup.py`), it attempts to install an incompatible version. (Centrosome has a similar setup.)

One possible fix (I think?) would be to restrict the NumPy version to `<1.17`.

**Comment by bethac07** [comment]
Will be fixed in 4.0
