### ISSUE TITLE
Can't install on linux, some problem with Numpy? 

### ISSUE THREAD

**Issue by TrentBrick** [CellProfiler/CellProfiler#3787]
I followed all the steps here: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-(Ubuntu-16.04-LTS)

First time trying to run, I get this error. 

`ImportError: No module named _multiarray_umath
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/__main__.py", line 226, in main
    pipeline_path = pipeline_path)
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/cellprofilerapp.py", line 24, in __init__
    super(CellProfilerApp, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/cellprofilerapp.py", line 34, in OnInit
    from cellprofiler.gui.cpframe import CPFrame
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/gui/cpframe.py", line 13, in <module>
    import cellprofiler.measurements as cpmeas
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/measurements.py", line 12, in <module>
    from scipy.io.matlab import loadmat
  File "/usr/lib/python2.7/dist-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 10, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/usr/lib/python2.7/dist-packages/scipy/misc/__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/interpolate.py", line 20, in <module>
    import scipy.linalg
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/__init__.py", line 190, in <module>
    from .misc import *
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: numpy.core.multiarray failed to import
Failed to stop Ilastik
Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler==2.3.1', 'console_scripts', 'cellprofiler')()
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/__main__.py", line 226, in main
    pipeline_path = pipeline_path)
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/cellprofilerapp.py", line 24, in __init__
    super(CellProfilerApp, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/cellprofilerapp.py", line 34, in OnInit
    from cellprofiler.gui.cpframe import CPFrame
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/gui/cpframe.py", line 13, in <module>
    import cellprofiler.measurements as cpmeas
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/measurements.py", line 12, in <module>
    from scipy.io.matlab import loadmat
  File "/usr/lib/python2.7/dist-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 10, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/usr/lib/python2.7/dist-packages/scipy/misc/__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/interpolate.py", line 20, in <module>
    import scipy.linalg
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/__init__.py", line 190, in <module>
    from .misc import *
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: numpy.core.multiarray failed to import`

If I try to run it again I get: 

`RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler==2.3.1', 'console_scripts', 'cellprofiler')()
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/__main__.py", line 175, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/utilities/cpjvm.py", line 3, in <module>
    import javabridge
  File "/usr/local/lib/python2.7/dist-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: numpy.core.multiarray failed to import`

If I run `sudo pip install .` again it says that all the dependencies are fulfilled. 

Btw, this is all after I tried to install using Conda and I couldn't manage to install: 
- wxpython=3.0.2.0 even after being sure to use the - BjornFJohansson channel.

**Comment by gmstanle** [comment]
I've also had similar issues and am totally able to install in Linux. A response here would be amazing.

**Comment by gmstanle** [comment]
By the way, one problem I had is that the latest javabridge version won't install. See error below. I fixed it by specifying javabridge==1.0.15 in setup.py. 

pip install --user --editable .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining file:///home/geoffstanley/apps/CellProfiler
Collecting numpy<=1.13.0 (from CellProfiler==2.3.1)
  Using cached https://files.pythonhosted.org/packages/dd/b5/47bd2174dbb14e5fa2dd6ad28fd1d54d38e84d29c1b131a00354ddb0cae0/numpy-1.13.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting boto3 (from CellProfiler==2.3.1)
  Using cached https://files.pythonhosted.org/packages/e7/f6/29b7254c051801ac182710bda0032c6d4bd20ea914c5f10d6eb3fc47e669/boto3-1.9.187-py2.py3-none-any.whl
Collecting cellh5 (from CellProfiler==2.3.1)
Collecting centrosome>=1.0.4 (from CellProfiler==2.3.1)
Collecting h5py<=2.7.0 (from CellProfiler==2.3.1)
  Using cached https://files.pythonhosted.org/packages/07/22/992b1eaa9a33caa40c0fc700bbd5db60da0335c3b581fe1fc72296942736/h5py-2.7.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting inflect (from CellProfiler==2.3.1)
  Using cached https://files.pythonhosted.org/packages/86/02/e6b11020a9c37d25b4767a1d0af5835629f6e75d6f51553ad07a4c73dc31/inflect-2.1.0-py2.py3-none-any.whl
Collecting javabridge (from CellProfiler==2.3.1)
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3Ic73T/javabridge/setup.py", line 405, in <module>
        cmdclass={'build_ext': build_ext})
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-l4RisP/numpy-1.17.0rc1/setup.py", line 31, in <module>
    
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3Ic73T/javabridge/

**Comment by gmstanle** [comment]
Here is my install error after creating a totally fresh Conda python=2.7 environment and downloading CellProfiler fresh from Github:

pip install --user --editable .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining file:///home/geoffstanley/apps/CellProfiler
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/geoffstanley/apps/CellProfiler/setup.py", line 48, in <module>
        importlib.import_module(import_name)
      File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/geoffstanley/.local/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
        from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
      File "/home/geoffstanley/.local/lib/python2.7/site-packages/javabridge/jutil.py", line 157, in <module>
        import javabridge._javabridge as _javabridge
      File "__init__.pxd", line 861, in init _javabridge (_javabridge.c:28566)
    ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/geoffstanley/apps/CellProfiler/

**Comment by jeffsyang** [comment]
Hey guys, on top of trying out https://github.com/CellProfiler/CellProfiler/issues/3793#issuecomment-511929911, maybe try installing `wxpython==3.0.0.0`?

@TrentBrick If my intuition's correct, the guide you referenced was more for virtualenv users instead of conda users.

**Comment by Swarchal** [comment]
It looks like the wxpython channel [has disappeared](https://anaconda.org/BjornFJohansson/repo), if you change the `BjornFJohansson` channel to `daf` in `environment.yml` it should at least fix the wxpython issue.
