### ISSUE TITLE
Error installing CellProfiler master in conda on Linux

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#3846]
I've managed to modify the conda install instructions to get a more of less successful install of CellProfilre prerequisites on Ubuntu Linux with miniconda3 and Python 3.7.4. But in the final steps of installing CellProfiler, I get the following error:
```
Pip subprocess error:
  Running command git clone -q https://github.com/CellProfiler/CellProfiler.git /tmp/pip-req-build-6ndo_9mc
    ERROR: Command errored out with exit status 1:
     command: /opt/CellProfiler/envs/cellprofiler/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wuwb6l7/javabridge/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wuwb6l7/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-_wuwb6l7/javabridge/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_wuwb6l7/javabridge/setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-_wuwb6l7/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/opt/CellProfiler/envs/cellprofiler/lib/python3.7/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Is this related to Java usage? I've installed OpenJDK 8 on Ubuntu as there where some references that with the commercialization of Oracle JDK, OpenJDK would also be supported.

**Comment by emmenlau** [comment]
Solved with a fix for installing `python-javabridge` as outlined here: https://github.com/LeeKamentsky/python-javabridge/issues/152

It would be very helpful to add this also to the CellProfiler installation instructions and/or FAQ.
