### ISSUE TITLE
Installing Cell profiler 3 using conda - can't find wxpython3.0.2.0 in BjornFJohansson channel

### ISSUE THREAD

**Issue by NachoDave** [CellProfiler/CellProfiler#3852]
Hi
I'm fairly new to Cell profiler and conda.

I've been trying to install CP 3 on Ubuntu 18.04.3 using the guide here:
https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation
with V3.1.8.

However, I get an error message saying that it can't find 
`'ResolvePackageNotFound: - wxpython=3.0.2.0'.`

I think the BjornFJohansson conda channel may no longer be hosting the wxpython package. I think this will be an issue for other users. 

I found another channel which hosts it, https://anaconda.org/aaren/wxpython.

When I put aaren in the channels of the environment.yml file everything installed ok. However, when I run CP I get the following error: 
`Traceback (most recent call last):
  File "/home/dave/anaconda2/envs/cellprofiler/bin/cellprofiler", line 10, in <module>
    sys.exit(main())
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/cellprofiler/__main__.py", line 146, in main
    import cellprofiler.gui.app
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/cellprofiler/gui/app.py", line 12, in <module>
    import wx
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgstreamer-0.10.so.0: cannot open shared object file: No such file or directory
`

I tried adding a symbolic link in the .../wx-3.0-gtk2/wx/ directory to the usr/lib/x86_64-linux-gnu/libgstreamer-0.10.so.0 file on my machine, but I still get the same error. 

As you can probably see by now I'm in over my head a bit, so any help that anyone can give would be gratefully received. 

I did manage to install and run the master branch using python 3 (again with conda), but this had a lot of bugs in (I realize that it is currently undergoing testing ), so I decided to try and install a python 2 version. 

Thanks for you help

**Comment by sunyi000** [comment]
I had issue with wxpython package before, and I used the package wxpython3.0.2 in anaconda channel.
I just added '-c anaconda' when running 'conda build'

not sure if this helps

**Comment by NachoDave** [comment]
Hi sunyi000

Thank you for your suggestion. I tried using the channel you recommended and had a similar error as before, but for a different shared object. 

`Traceback (most recent call last):
  File "/home/dave/anaconda2/envs/cellprofiler/bin/cellprofiler", line 10, in <module>
    sys.exit(main())
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/cellprofiler/__main__.py", line 146, in main
    import cellprofiler.gui.app
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/cellprofiler/gui/app.py", line 12, in <module>
    import wx
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/home/dave/anaconda2/envs/cellprofiler/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: liblzma.so.0: cannot open shared object file: No such file or directory
`
I also went back to using the aarens channel and redid the sym link correctly (yes I screwed it up the first time), which worked in as far as it was a different shared object that it couldn't find.

It seems that these wxpython 3.0.2 packages depend on libraries that are no longer included in recent Linux versions?

Maybe it is better to wait a little while until the Python 3 version of CP is stable?

**Comment by sunyi000** [comment]
I remember I had that liblzma.so.0  issue before , also some other .so file not found issue. What I did is install liblzma-dev and create simlinks. 
For example, there is a liblzma.so.5(if i remember the name correctly) file in liblzma-dev package, I just create a link to liblzma.so.0 
there are two other symlinks i need create but can't remember what are they.

after everything CP started working properly.
