### ISSUE TITLE
Python3 Javabridge error on running module Images

### ISSUE THREAD

**Issue by hissingpanda** [CellProfiler/CellProfiler#3863]
I'm getting the following Javabridge error while trying to run a pipeline within a Python3 notebook.

It errors out on the default module for loading images. This is with cellprofiler v3.1.8. 

```
ERROR:root:Failed to prepare run for module Images
Traceback (most recent call last):
  File "/mnt/c/Users/planctot/Desktop/custom/py37_imc_env/lib/python3.7/site-packages/cellprofiler/pipeline.py", line 2458, in prepare_run
    not module.prepare_run(workspace)
  File "/mnt/c/Users/planctot/Desktop/custom/py37_imc_env/lib/python3.7/site-packages/cellprofiler/modules/images.py", line 347, in prepare_run
    ifcls = javabridge.class_for_name("org.cellprofiler.imageset.ImageFile")
  File "/mnt/c/Users/planctot/Desktop/custom/py37_imc_env/lib/python3.7/site-packages/javabridge/jutil.py", line 1739, in class_for_name
    '()Ljava/lang/ClassLoader;')
  File "/mnt/c/Users/planctot/Desktop/custom/py37_imc_env/lib/python3.7/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/mnt/c/Users/planctot/Desktop/custom/py37_imc_env/lib/python3.7/site-packages/javabridge/jutil.py", line 905, in make_static_call
    klass = env.find_class(class_name)
AttributeError: 'NoneType' object has no attribute 'find_class'
```

**Comment by hissingpanda** [comment]
I tried it with a python 2 environment as well as with version 3.1.5 and it still has the same error. Interestingly it works in headless mode on the command line but not when importing as a python package

**Comment by DavidStirling** [comment]
Sorry it's taken some time to get around to this. The traceback above is definitely a Python 3-exclusive error and Javabridge isn't directly maintained by us. If you're still having trouble could you post any error you're getting with the Python 2 versions?
