### ISSUE TITLE
Error after conda installing cellprofiler 3.1.9 on Ubuntu 18.04

### ISSUE THREAD

**Issue by burgerga** [CellProfiler/CellProfiler#3902]
Maybe we can create Ubuntu 18.04 instructions in the wiki?

I followed the instructions in the wiki, but then when I started cellprofiler I got:

```bash
Traceback (most recent call last):
  File "/opt/conda/envs/cellprofiler-3.1.9/bin/cellprofiler", line 5, in <module>
    from cellprofiler.__main__ import main
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/cellprofiler/__main__.py", line 13, in <module>
    import bioformats.formatreader
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
  File "__init__.pxd", line 861, in init _javabridge (_javabridge.c:28566)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```
Which according to https://github.com/automl/ConfigSpace/issues/107 can be solved with

```bash
pip install --upgrade numpy
```

which gives

```bash
...
ERROR: cellprofiler 3.1.9 has requirement numpy==1.15.4, but you'll have numpy 1.16.6 which is incompatible.
ERROR: cellprofiler 3.1.9 has requirement prokaryote==2.4.1, but you'll have prokaryote 2.4.0 which is incompatible.
ERROR: cellprofiler 3.1.9 has requirement python-bioformats==1.5.2, but you'll have python-bioformats 1.4.0 which is incompatible.
...
```
which we ignore ;)

Then we get:

```bash
Traceback (most recent call last):
  File "/opt/conda/envs/cellprofiler-3.1.9/bin/cellprofiler", line 5, in <module>
    from cellprofiler.__main__ import main
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/cellprofiler/__main__.py", line 17, in <module>
    import cellprofiler.object
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/cellprofiler/object.py", line 7, in <module>
    import skimage.color
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/opt/conda/envs/cellprofiler-3.1.9/lib/python2.7/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name _validate_lengths
```

which we solve with

```bash
pip install --upgrade scikit-image
```
which gives an additional:

```bash
...
ERROR: cellprofiler 3.1.9 has requirement scikit-image==0.14.0, but you'll have scikit-image 0.14.5 which is incompatible.
...
```

which we also ignore, and now CellProfiler appears to work :)

For completeness, my environment file:
```yaml
# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: cellprofiler-3.1.9
# in order of priority: highest (top) to lowest (bottom)
channels:
  - anaconda
  - bioconda
  - conda-forge
  - daf # wxpython for linux
dependencies:
  - appdirs
  - boto3
  - cython
  - h5py
  - ipywidgets
  - java-jdk
  - joblib
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python=2
  - pyzmq=15.3.0
  - mahotas
  - matplotlib!=2.1.0,>2.0.0
  - mysqlclient
  - numpy
  - raven
  - requests
  - scikit-image>=0.13
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - wxpython=3.0.2.0
  - pip:
    - cellh5
    - centrosome
    - inflect
    - prokaryote==2.4.0
    - javabridge==1.0.15
    - python-bioformats==1.4.0
    - git+https://github.com/CellProfiler/CellProfiler.git@v3.1.9
```

**Comment by rbatorsky** [comment]
Just a note that I followed similar steps on Centos 6 in order to get version 3.1.9 to install via conda.
