### ISSUE TITLE
Error from botocore/docutils dependency

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#3933]
This is more of an FYI than anything else...

When I start CP from source (910016e92), I get the following error:
```
Traceback (most recent call last):
  File "C:\anaconda3\Scripts\cellprofiler-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3253, in <module>
    @_call_aside
  File "C:\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "C:\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.16 (c:\anaconda3\lib\site-packages), Requirement.parse('docutils<0.16,>=0.10'), {'botocore'})
```
I tracked it down to this issue: https://github.com/boto/botocore/issues/1942, so it seems that docutils may need to be pinned or hope that botocore gets things straightened out in time for v4 release?

**Comment by alicelucas** [comment]
We pinned docutils for now.
