### ISSUE TITLE
Python 3: Intermittent 'FirstCropping' error in test mode.

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#3945]
This has been annoying me for a while. Seemingly at random, when running the example pipeline, trying to start a test mode run/step will trigger the following error:

```Failed to run module Crop
Traceback (most recent call last):
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 3502, in do_step
    self.__pipeline.run_module(module, workspace)
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\pipeline.py", line 2391, in run_module
    module.run(workspace)
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\modules\crop.py", line 412, in run
    if d[D_FIRST_CROPPING].shape != orig_image.pixel_data.shape[:2]:
KeyError: 'FirstCropping'
```

It appears that workspace.pipeline.test_mode is False when this happens, which then trips up the following:
 https://github.com/CellProfiler/CellProfiler/blob/7b1c8997ccd04fee4b524fcc598e074f37eb7cce/cellprofiler/modules/crop.py#L404-L409

Why test mode would be failing to toggle the test mode flag is a mystery, but I'll try to look into it. Just noting what I've found so far.

**Comment by DavidStirling** [comment]
So everything about this is horrible. I think this is related to the validation thread changing the pipeline's test mode status when old requests sometimes slip into the queue, related to the fix for #411. 

https://github.com/CellProfiler/CellProfiler/blob/7b1c8997ccd04fee4b524fcc598e074f37eb7cce/cellprofiler/gui/moduleview.py#L4818-L4824

It looks like the way the module works has changed a lot in the intervening years, so I'm trying to see whether this is still necessary or if purging the queue when entering test mode might help.
