### ISSUE TITLE
MeasureObjectOverlap option: "Calculate earth mover's distance" fails

### ISSUE THREAD

**Issue by RoccoDAnt** [CellProfiler/CellProfiler#3985]
Dear team I have tried to use in CP 3.1.9 and CP 3.1.5 the
MeasureObjectOverlap option: "Calculate earth mover's distance".
I get as error: sklearn.neighbors.ball_tree.NeighborsHeap has no attribute '__reduce_cython__'

In a reply about a similar error I read from Beth that "CellProfiler 3.1.5 has sklearn-0.19.1":
https://forum.image.sc/t/unable-to-import-sklearn-mixture-in-cp3/12910

Is "earth mover's distance" option requiring a specific version of sklearn?
Thanks,
best
Rocco

**Comment by bethac07** [comment]
Are you running downloaded the website or installed from source? What OS?

**Comment by RoccoDAnt** [comment]
Hi Beth, thanks for the quick reply, downloaded from website:
https://dpvpof9ygr7ad.cloudfront.net/CellProfiler-3.1.9.exe

I have Win10 and the error reported in the prompt is: 
Failed to run module MeasureObjectOverlap
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2919, in do_step
  File "CellProfiler\cellprofiler\pipeline.py", line 2034, in run_module
  File "CellProfiler\cellprofiler\modules\measureobjectoverlap.py", line 440, in run
  File "CellProfiler\cellprofiler\modules\measureobjectoverlap.py", line 722, in compute_emd
  File "CellProfiler\cellprofiler\modules\measureobjectoverlap.py", line 803, in get_kmeans_points
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "site-packages\sklearn\cluster\__init__.py", line 6, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "site-packages\sklearn\cluster\spectral.py", line 16, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "site-packages\sklearn\neighbors\__init__.py", line 6, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 684, in load_module
  File "sklearn\neighbors\binary_tree.pxi", line 566, in init sklearn.neighbors.ball_tree
AttributeError: type object 'sklearn.neighbors.ball_tree.NeighborsHeap' has no attribute '__reduce_cython__'

**Comment by bethac07** [comment]
It looks like it's a version mismatch between the version of cython that's in that build (for both PC and Mac, at least Mac 3.1.9) and the version of sklearn- while we try to keep all the packages synced between our test and build machines, it looks like we may have missed that one inconsistency for that build- we apologize!  The good news is, this should be fixed automatically in our 4.0 release, which will be using newer packages.

You could run CellProfiler from source with updated packages, wait for our 4.0 release (in the next few weeks), or run with the "skeleton" rather than "kmeans" option.   

Sorry for the inconvenience!

**Comment by RoccoDAnt** [comment]
Thanks for your suggestions Beth, looking forward for CP4.
Best regards,
Rocco
