### ISSUE TITLE
Python2 error with Javabridge

### ISSUE THREAD

**Issue by ninning** [CellProfiler/CellProfiler#3987]
Hi cellprofiler team,

I was testing out running cellprofiler as a python package as described here:
https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-as-a-Python-package

Posting some ipython outputs below
```
In [2]: import cellprofiler.pipeline

In [3]: pipeline=cellprofiler.pipeline.Pipeline()

In [4]: pipeline.load("dapimasks-v1.cppipe")
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
No handlers could be found for logger "cellprofiler.modules.exporttodatabase"
Using TensorFlow backend.
WARNING:cellprofiler.modules:could not load these modules: runimagej

In [5]: measure=pipeline.run()
DEBUG:cellprofiler.measurement:Created temporary file /var/folders/sq/qy7gh_jj1lgfdyh2wf4vt8p00000gn/T/CpmeasurementsG820df.hdf5
DEBUG:cellprofiler.measurement:/usr/local/bin/ipython: (8 <module>): sys.exit(start_ipython())
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/__init__.py: (119 start_ipython): return launch_new_instance(argv=argv, **kwargs)
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/traitlets/config/application.py: (664 launch_instance): app.start()
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py: (355 start): self.shell.mainloop()
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py: (495 mainloop): self.interact()
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py: (486 interact): self.run_cell(code, store_history=True)
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py: (2714 run_cell): interactivity=interactivity, compiler=compiler, result=result)
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py: (2818 run_ast_nodes): if self.run_code(code, result):
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py: (2878 run_code): exec(code_obj, self.user_global_ns, self.user_ns)
DEBUG:cellprofiler.measurement:<ipython-input-5-c255fa78fd64>: (1 <module>): measure=pipeline.run()
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/cellprofiler/pipeline.py: (1570 run): copy=initial_measurements)
DEBUG:cellprofiler.measurement:/usr/local/lib/python2.7/site-packages/cellprofiler/measurement.py: (271 __init__): for frame in traceback.extract_stack():
DEBUG:cellprofiler.utilities.hdf5_dict:HDF5Dict.__init__(): /var/folders/sq/qy7gh_jj1lgfdyh2wf4vt8p00000gn/T/CpmeasurementsG820df.hdf5, temporary=True, copy=None, mode=w
/usr/local/lib/python2.7/site-packages/cellprofiler/utilities/hdf5_dict.py:539: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  np.issubdtype(hdf5_type, int) or
/usr/local/lib/python2.7/site-packages/cellprofiler/utilities/hdf5_dict.py:541: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  hdf5_type_is_float = np.issubdtype(hdf5_type, float)
DEBUG:cellprofiler.utilities.hdf5_dict:HDF5Dict.flush(): /var/folders/sq/qy7gh_jj1lgfdyh2wf4vt8p00000gn/T/CpmeasurementsG820df.hdf5, temporary=True
ERROR:root:Failed to prepare run for module Images
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cellprofiler/pipeline.py", line 2097, in prepare_run
    if ((not module.prepare_run(workspace)) or
  File "/usr/local/lib/python2.7/site-packages/cellprofiler/modules/images.py", line 324, in prepare_run
    ifcls = javabridge.class_for_name("org.cellprofiler.imageset.ImageFile")
  File "/usr/local/lib/python2.7/site-packages/javabridge/jutil.py", line 1739, in class_for_name
    '()Ljava/lang/ClassLoader;')
  File "/usr/local/lib/python2.7/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/usr/local/lib/python2.7/site-packages/javabridge/jutil.py", line 905, in make_static_call
    klass = env.find_class(class_name)
AttributeError: 'NoneType' object has no attribute 'find_class'
DEBUG:cellprofiler.utilities.hdf5_dict:HDF5Dict.flush(): /var/folders/sq/qy7gh_jj1lgfdyh2wf4vt8p00000gn/T/CpmeasurementsG820df.hdf5, temporary=True
DEBUG:cellprofiler.utilities.hdf5_dict:HDF5Dict.flush(): /var/folders/sq/qy7gh_jj1lgfdyh2wf4vt8p00000gn/T/CpmeasurementsG820df.hdf5, temporary=True
```

but ended up with a javabridge error.

Im using javabridge 1.0.18 on a Mac OS 10.14.6
Im currently using Java 8 that i installed from Oracles website instead of the default installation of java from Brew. Ive had a host of compatability issues with even installing javabridge with the brew installation of Java.

Thank you again!

**Comment by DavidStirling** [comment]
Since we've updated to Python 3 the instructions on that page were outdated. The page is still being developed, but the current version should be usable now.
