### ISSUE TITLE
Errors when closing CellProfiler 4

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4041]
Particularly after an analysis run has been performed, the following trace sometimes appears in the log after exiting:

```Exiting the pipeline validation thread
Failed to flush temporary measurements file during close
Traceback (most recent call last):
  File "c:\users\administrator\cellprofiler\cellprofiler\gui\cpframe.py", line 522, in OnClose
    self.__workspace.measurements.flush()
  File "c:\users\administrator\core\cellprofiler_core\measurement\_measurements.py", line 193, in flush
    if self.hdf5_dict is not None:
AttributeError: 'Measurements' object has no attribute 'hdf5_dict'
File name listener doubly removed
Failed to close the pipeline controller
Traceback (most recent call last):
  File "c:\users\administrator\cellprofiler\cellprofiler\gui\cpframe.py", line 533, in OnClose
    self.pipeline_controller.on_close()
  File "c:\users\administrator\cellprofiler\cellprofiler\gui\pipelinecontroller.py", line 1726, in on_close
    self.__workspace.close()
  File "c:\users\administrator\core\cellprofiler_core\workspace\_workspace.py", line 479, in close
    os.unlink(self.__filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\Cpmeasurements296l5038.hdf5'
```

I've seen a few other issues with deleting temp files and exiting threads upon closing. We might want to verify this works properly if this is a concern.

**Comment by DavidStirling** [comment]
Appears to be fixed now
