### ISSUE TITLE
CP4 - MetadataControl error

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4085]
```Traceback (most recent call last):
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\gui\metadatactrl.py", line 89, in on_show
    self.make_caret()
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\gui\metadatactrl.py", line 112, in make_caret
    self.__caret = wx.Caret(self, wx.Size(1, self.Size[1] - 2 * self.padding))
RuntimeError: wrapped C/C++ object of type MetadataControl has been deleted
```

Sometimes appears in the console when switching modules, not sure exactly what causes it.

**Comment by DavidStirling** [comment]
To replicate:

- Have metadata enabled.
- View a module which has metadata-supporting fields enabled (e.g. SaveImages with custom directory).
- Click on any other module.
