### ISSUE TITLE
Javabridge ImortError when running CP4 from source

### ISSUE THREAD

**Issue by HenrikeSalie** [CellProfiler/CellProfiler#4107]
Hi all,

I'm having some issues running CP4 from source. The installation works fine but when I try to open CellProfiler from the command prompt I receive this error message:

C:\Program Files (x86)\CellProfiler>cellprofiler
Traceback (most recent call last):
  File "C:\Users\henni\AppData\Local\Programs\Python\Python38\Scripts\cellprofiler-script.py", line 33, in <module>
    sys.exit(load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')())
  File "C:\Users\henni\AppData\Local\Programs\Python\Python38\Scripts\cellprofiler-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\henni\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\henni\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\henni\documents\github\cellprofiler\cellprofiler\__main__.py", line 12, in <module>
    import bioformats.formatreader
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\bioformats\__init__.py", line 21, in <module>
    import javabridge
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\javabridge\__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: DLL load failed while importing _javabridge: The specified module could not be found.

I checked whether javabridge is installed and it is.

To run CP4 from source I followed the instructions on this website: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29
There I had some problems installing the Microsoft .NET Framework 3.5 SP1, could this be an issue? When I clicked the installation file and allowed it to make changes to my computer no window would pop up.

I uninstalled all other python versions except for the 3.8.4 version.
I tried to change the environment variables so that they point towards the right folders but that didn't work either.

I'm using Windows 10 Home (10.0.18363).

I'd appreciate any advice or suggestions on what else I could try.
Thanks!

**Comment by DavidStirling** [comment]
Hi @HenrikeSalie,

There are a couple of things which can cause this. I'd suggest the following:

- Check that the JAVA_HOME environment variable is set properly, see [this page](https://github.com/CellProfiler/CellProfiler/wiki/Windows-Installation-Troubleshooting). If it is, try setting a new variable, JDK_HOME, to match whatever JAVA_HOME is set to.
- If the problem persists you may have an outdated version of python-javabridge. If you could send a copy of the result you get from running `pip freeze` we might be able to provide further insight into this.

Hope that helps!

**Comment by HenrikeSalie** [comment]
Hi David,

Thank you for the extremely quick reply!
I tried your first suggestion but unfortunately it didn't work.

My result from running pip freeze is as follows:

C:\Program Files (x86)\CellProfiler>pip freeze
ERROR: Error [WinError 2] The system cannot find the file specified while executing command git config --get-regexp 'remote\..*\.url'
WARNING: cannot determine version of editable source in c:\users\henni\documents\github\cellprofiler (git command not found in path)
boto3==1.14.23
botocore==1.17.23
-e CellProfiler==4.0.0rc5
cellprofiler-core==4.0.0rc7
centrosome==1.1.7
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
deprecation==2.1.0
docutils==0.15.2
future==0.18.2
h5py==2.10.0
idna==2.10
imageio==2.9.0
inflect==4.1.0
install-jdk==0.1.0
javabridge==1.0.19
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.16.0
kiwisolver==1.2.0
mahotas==1.4.10
MarkupSafe==1.1.1
matplotlib==3.1.3
mysqlclient==1.4.6
networkx==2.4
numpy==1.19.0
packaging==20.4
Pillow==7.0.0
prokaryote==2.4.1
pyparsing==2.4.7
python-bioformats==1.5.2
python-dateutil==2.8.1
python-javabridge==4.0.0rc1
PyWavelets==1.1.1
pyzmq==18.0.1
requests==2.24.0
s3transfer==0.3.3
scikit-image==0.16.2
scikit-learn==0.23.1
scipy==1.5.1
sentry-sdk==0.16.1
six==1.15.0
threadpoolctl==2.1.0
urllib3==1.25.9
wxPython==4.0.7.post2

**Comment by DavidStirling** [comment]
Thanks, could you try running `pip install python-javabridge --upgrade`?

That should get you the fixed version of python-javabridge.

**Comment by HenrikeSalie** [comment]
Hi David, 
thanks for the advice. I tried this but it seems to install a javabridge version that is incompatible with cellprofiler core.
This is my error message:

C:\Program Files (x86)\CellProfiler>pip install python-javabridge --upgrade
Collecting python-javabridge
  Using cached python-javabridge-4.0.0rc2.tar.gz (1.3 MB)
Requirement already satisfied, skipping upgrade: numpy in c:\users\henni\appdata\local\programs\python\python38\lib\site-packages (from python-javabridge) (1.19.0)
Using legacy setup.py install for python-javabridge, since package 'wheel' is not installed.
ERROR: cellprofiler-core 4.0.0rc7 has requirement python-javabridge==4.0.0rc1, but you'll have python-javabridge 4.0.0rc2 which is incompatible.
Installing collected packages: python-javabridge
  Attempting uninstall: python-javabridge
    Found existing installation: python-javabridge 4.0.0rc1
    Uninstalling python-javabridge-4.0.0rc1:
      Successfully uninstalled python-javabridge-4.0.0rc1
    Running setup.py install for python-javabridge ... done
Successfully installed python-javabridge-4.0.0rc2

C:\Program Files (x86)\CellProfiler>cellprofiler
Traceback (most recent call last):
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-javabridge 4.0.0rc2 (c:\users\henni\appdata\local\programs\python\python38\lib\site-packages), Requirement.parse('python-javabridge==4.0.0rc1'), {'cellprofiler-core'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\henni\AppData\Local\Programs\Python\Python38\Scripts\cellprofiler-script.py", line 33, in <module>
    sys.exit(load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')())
  File "C:\Users\henni\AppData\Local\Programs\Python\Python38\Scripts\cellprofiler-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\henni\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\henni\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\henni\documents\github\cellprofiler\cellprofiler\__main__.py", line 16, in <module>
    import pkg_resources
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 3262, in <module>
    def _initialize_master_working_set():
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\henni\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-javabridge 4.0.0rc2 (c:\users\henni\appdata\local\programs\python\python38\lib\site-packages), Requirement.parse('python-javabridge==4.0.0rc1'), {'cellprofiler-core'})


Do you have any other suggestions?
Thank you for your help!

**Comment by DavidStirling** [comment]
Sorry about that, we're actually putting together another set of RCs this week which should fix all these dependency issues.

In the meantime you may be able to correct the requires.txt file from your current cellprofiler-core installation to require python-javabridge RC2 rather than RC1.

**Comment by HenrikeSalie** [comment]
No problem! I really appreciate the help.
I tried it but still didn't have any luck...

**Comment by ctr26** [comment]
Use openjdk11 https://github.com/CellProfiler/CellProfiler/issues/4117

**Comment by DavidStirling** [comment]
Should now be fixed.
