### ISSUE TITLE
WSV bugs

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4139]
As of 30c2133f415e6ac4a51479caed9ec821fb2cabaf

Using the example pipeline:

- [ ] Cropped images are showing as only a tiny fraction of the size of the window, while objects (made from the cropped images!) are showing at the full size (see screenshot below)
- [ ] Upon trying to add a second object, you generate the following stack trace (it will eventually give you another object line a few seconds later)
```py
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 131, in <lambda>
    add_object_button.Bind(wx.EVT_BUTTON, lambda event: self.add_objects_row())
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 258, in add_objects_row
    self.add_row(
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 294, in add_row
    self.update_menu(self.frame.menu_subplots)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 397, in update_menu
    self.image.on_update_menu(event, menu)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/artist.py", line 847, in on_update_menu
    if idx >= len(menu_items) or menu_items[idx].Text != label:
AttributeError: 'MenuItem' object has no attribute 'Text'
```
- [ ] If you close and try to reopen WSV, you get the following stack trace 

```py
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 3829, in on_view_workspace
    self.workspace_view.set_workspace(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 383, in set_workspace
    self.update_menu(self.frame.menu_subplots)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 397, in update_menu
    self.image.on_update_menu(event, menu)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/artist.py", line 847, in on_update_menu
    if idx >= len(menu_items) or menu_items[idx].Text != label:
AttributeError: 'MenuItem' object has no attribute 'Text'
```
- [ ] I'm not sure what should be showing under "Masks", but I would think it would be only thresholded images, yes? Right now, all 3 cropped images are showing up.

It's mostly sooooooo good though, I'm so excited!!!!!

![image](https://user-images.githubusercontent.com/6721515/89900236-75301080-dbb1-11ea-9538-750f9b7d7215.png)

**Comment by DavidStirling** [comment]
Fixed the menu trace, I think we still need to add some kind of call to update the wsv when a module runs, which would then solve it not refreshing.

**Comment by 0x00b1** [comment]
I fixed the cropping issue.

**Comment by bethac07** [comment]
Crosshair cursor one was fixed by https://github.com/CellProfiler/CellProfiler/commit/ae1ca8f18f106a420d00eabc2b606238738c8aee

**Comment by bethac07** [comment]
- [ ] Binary images break the WSV 

```py
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view_row.py", line 40, in on_check_change
    self.workspace_view.redraw()
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/workspace_view/_workspace_view.py", line 519, in redraw
    self.frame.figure.canvas.draw()
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backends/backend_wxagg.py", line 29, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/figure.py", line 1708, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/artist.py", line 631, in draw
    pixel_data = (pixel_data - pd_min) / (pd_max - pd_min)
TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```
