### ISSUE TITLE
Running Windows CP v4.0.0rc7 on WIndows fails on startup

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#4155]
**Describe the bug**
Installing and run CP v4.0.0rc7 under Windows yields the following error:
```
Traceback (most recent call last):
  File "CellProfiler.py", line 3, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler\__main__.py", line 25, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\pipeline\__init__.py", line 4, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\pipeline\_pipeline.py", line 21, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\utilities\core\modules\__init__.py", line 7, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\module\__init__.py", line 1, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\module\_identify.py", line 3, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\module\_module.py", line 17, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\setting\__init__.py", line 20, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cellprofiler_core\setting\_structuring_element.py", line 1, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "skimage\morphology\__init__.py", line 7, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "skimage\measure\__init__.py", line 8, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "skimage\measure\_polygon.py", line 2, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\signal\__init__.py", line 307, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\signal\_peak_finding.py", line 8, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\stats\__init__.py", line 388, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\stats\stats.py", line 180, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\stats\distributions.py", line 11, in <module>
  File "d:\a\cellprofiler\cellprofiler\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\stats\_continuous_distns.py", line 21, in <module>
  File "_stats.pyx", line 1, in init scipy.stats._stats
ModuleNotFoundError: No module named 'scipy.special.cython_special'
[120208] Failed to execute script CellProfiler
```

**To Reproduce**
Run cellprofiler.exe

**Expected behavior**
I expected CP to open :-)

**Desktop (please complete the following information):**
 - Windows 10
 - CellProfiler Version v4.0.0rc7 
 - Obtained from https://github.com/CellProfiler/CellProfiler/releases/tag/v4.0.0rc7

**Comment by DavidStirling** [comment]
This should already be fixed in the next package release. Probably shouldn't have left dead builds up for download, sorry!
