### ISSUE TITLE
Mahotas not loading properly within CellProfiler on Ubuntu 20.04 AWS instance

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4197]
I created an instance following [these instructions](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04); despite mahotas being installed correctly AFAICT (if I open `python3`, I can both `import mahotas` and `import mahotas.features`, CellProfiler fails to load the two mahotas-using modules (MeasureTexture and Watershed) with stack trace below.  

I don't know if it's just a weird thing with this AWS instance not having full permissions, so leaving tagged with "Needs verification", but wanted to report.

```py
Could not load cellprofiler.modules.measuretexture
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/home/ubuntu/CellProfiler/cellprofiler/modules/measuretexture.py", line 107, in <module>
    import mahotas.features
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mahotas/__init__.py", line 83, in <module>
    from . import polygon
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mahotas/polygon.py", line 8, in <module>
    from . import _convex
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: invalid continuation byte
Could not load cellprofiler.modules.watershed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/home/ubuntu/CellProfiler/cellprofiler/modules/watershed.py", line 2, in <module>
    import mahotas
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mahotas/__init__.py", line 83, in <module>
    from . import polygon
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mahotas/polygon.py", line 8, in <module>
    from . import _convex
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: invalid continuation byte
could not load these modules: cellprofiler.modules.measuretexture,cellprofiler.modules.watershed
```

**Comment by bethac07** [comment]
Confirmed in 4191 this is happening elsewhere when following those same instructions.

**Comment by plankter** [comment]
Can confirm the error on Ubuntu 20.04. I also was trying to set locale settings (found this example for 20.04 Docker image: https://github.com/pharmbio/cellprofiler-docker/blob/master/v4.0.6/Dockerfile), but still getting the same error. Mahotas is installed properly and I can use it in container.

Is there any update about when version 4.1 will be available?

**Comment by juliusbierk** [comment]
having the same issue.

**Comment by juliusbierk** [comment]
if you are not using convex hull, this issue can be fixed by replacing `from . import _convex` with `_convex = None` in `polygon.py`.

**Comment by edlaw89** [comment]
I am having the same issue - is there any update on this or is there a good workaround?

Cheers,
Ed

**Comment by vkhodygo** [comment]
Ubuntu 20.04, VM, `mahotas==1.4.11`, the issue is still there.

When I use  `mahotas==1.4.11` that is the most recent one at the moment and is installed by default, I also get a problem similar to [this](https://forum.image.sc/t/cellprofiler-4-2-0-valueerror-could-not-find-the-measuretexture-module/55182), namely, a GUI error saying it couldn't find the `MeasureTexture` module while loading a pipeline. I used `ExampleFly` for this. Downgrading to `mahotas==1.4.10` as recommended doesn't resolve the issue.

**Comment by vkhodygo** [comment]
@bethac07  I did run the tests on my VM using the latest Git based package, core tests fail magnificently. 
Running the same tests but against my Python 3.9 build on Arch resolves this issue. I'm not sure what the difference is as all Python packages should be (roughly) the same.

**Comment by emmenlau** [comment]
Issue remains with current latest Ubuntu 20.04 default packages and current CellProfiler 4.2.1 release.

**Comment by benblamey** [comment]
I'm having similar issues running CellProfiler from Docker. 

The .so file seems to be valid when checked with `readelf`. Importing the module directly from python3 works fine.

In CellProfiler, I get the error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: invalid continuation byte`

Yet the file starts with a 0x7f:
```
$ hd /usr/local/lib/python3.8/dist-packages/mahotas/_convex.cpython-38-x86_64-linux-gnu.so 
00000000  7f 45 4c 46 02 01 01 00  00 00 00 00 00 00 00 00  |.ELF............|
00000010  03 00 3e 00 01 00 00 00  90 10 00 00 00 00 00 00  |..>.............|
00000020  40 00 00 00 00 00 00 00  00 53 03 00 00 00 00 00  |@........S......|
00000030  00 00 00 00 40 00 38 00  07 00 40 00 24 00 23 00  |....@.8...@.$.#.|
00000040  01 00 00 00 05 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

I wonder if it is related to https://bugs.python.org/issue41894
"If a native module fails to load, the dynload code will call PyUnicode_FromString on the error message to give back to the user. This can cause a UnicodeDecodeError if the locale is not a UTF-8 locale and the error message contains non-ASCII code points."

That issue is fixed in Python 3.10, haven't managed to check this.
