### ISSUE TITLE
wx import fails when running CellProfiler in Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by schroeme** [CellProfiler/CellProfiler#4202]
I successfully installed CellProfiler per the instructions [here](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04) locally at [username]/home/CellProfiler. However, when I run ```$cellprofiler``` I get the following error (code pasted below).

**Desktop:**
 * OS: Linux (Ubuntu 20.04)
 * CellProfiler Version 4.0.0
 * Installed from source by cloning from master as described in the instructions

```
Traceback (most recent call last):
  File "/home/mschro/anaconda3/bin/cellprofiler", line 8, in <module>
    sys.exit(main())
  File "/home/mschro/anaconda3/lib/python3.8/site-packages/cellprofiler/__main__.py", line 116, in main
    temp_dir = get_temporary_directory()
  File "/home/mschro/.local/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py", line 1493, in get_temporary_directory
    elif config_exists(TEMP_DIR):
  File "/home/mschro/.local/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py", line 233, in config_exists
    if not get_config().Exists(key):
  File "/home/mschro/.local/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py", line 80, in get_config
    import wx
  File "/home/mschro/.local/lib/python3.8/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/mschro/.local/lib/python3.8/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_ot_metrics_get_position
```

**Comment by CEDRICHK** [comment]
Hello,

yes i encountered this error. But in a new virtual environment (virtualenv -p /usr/bin/python3.8 cellprofiler) that's work fine after have follow the steps [here](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04)

**Comment by TaHmIneHhH** [comment]
I have the same issue in psychopy!
