### ISSUE TITLE
Frozen - 'About' menu option errors out

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4208]
```Traceback (most recent call last):
  File "cellprofiler\gui\help\menu.py", line 102, in <lambda>
  File "cellprofiler\gui\help\menu.py", line 106, in about
  File "cellprofiler\gui\dialog.py", line 18, in __init__
  File "pkg_resources\__init__.py", line 482, in get_distribution
  File "pkg_resources\__init__.py", line 358, in get_provider
  File "pkg_resources\__init__.py", line 901, in require
  File "pkg_resources\__init__.py", line 787, in resolve
pkg_resources.DistributionNotFound: The 'CellProfiler' distribution was not found and is required by the application

**Comment by DavidStirling** [comment]
Fixed
