### ISSUE TITLE
TrackObjects fails if a frame has no objects

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4232]
**Describe the bug**
From the [forum](https://forum.image.sc/t/lap-tracker-cellprofiler-valueerror-dealing-with-no-objects/42694)

>I had a bug in CP4.0.2 using hte lap tracker: “ValueError all the input arrayw dimensions for the concatenation axis must match exactly…” ... Digging down I pinpointed the culprit: my Filtering modul, to remove low expressing H2B nuclei (for classification reasons and so as not to have to remove them by hand in the analysis later on).
Basically, after the filtering there were no objects left

**To Reproduce**
Asked for pipelines and images to reproduce. Also asked if was present in 3.1.9, since not previously reported AFAICT, but the relevant part of TrackObjects looks pretty similar between 3.1.9 and 4.  Will report back (or share internally)

**Screenshots**
![image](https://user-images.githubusercontent.com/6721515/92824619-a52f2700-f39c-11ea-9b7c-ac10e1d9f858.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - CellProfiler Version 4.0.2

**Additional context**
Approximate stack trace (transcribed from pic)
```
Traceback (most recent call last):
File "cellprofiler_core\pipeline\_pipeline.py", line 1608, in post_group
File "cellprofiler\modules\trackobjects.py, line 1966, in post_group
File "cellprofiler\modules\trackobjects.py, line 1967, in <listcomp>
File "<__array_function__ internals>", line 5, in column_stack
File "numpy\lib\shape_base.py", line 656, in column_stack
File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1and the array at index 4 has size 0
```

**Comment by ErinWeisbart** [comment]
Not sure that this is true. Has not been reported since stable CellProfiler 4 versions.
