### ISSUE TITLE
`print_groups` command line option fails with JSON serialization error

### ISSUE THREAD

**Issue by votti** [CellProfiler/CellProfiler#4294]
**Describe the bug**
I am using the '--print-groups' command line option to print the image groups from a batch file in CP4.

The following error presents itself:
```
Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler/__main__.py", line 179, in main
    print_groups(options.print_groups_file)
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler/__main__.py", line 670, in print_groups
    json.dump(groupings, sys.stdout)
  File "/usr/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.8/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
``` 

**To Reproduce**
run `cellprofiler -c --print-groups=Batch.h5` on a previously generated batch file.

**Expected behavior**
The command line script just works :)

**Desktop (please complete the following information):**
 - Docker image: docker://cellprofiler/cellprofiler:4.0.6

**Additional context**
I guess the issue is that this that `Measurements.get_groupings` returns Numpy int64:
https://github.com/CellProfiler/CellProfiler/blob/f7d413adb22560cf9163dec3f1801bb5968d276a/cellprofiler/__main__.py#L668

According to stackoverflow one these would need to be 'manually' coerced to `int`

**Comment by DavidStirling** [comment]
Looks like this was fixed by #4297
