### ISSUE TITLE
Pin h5py <3.1.0 (likely <3 )

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4305]
Apparently it breaks image loading in load data (and probably a lot else)- stupendously unhelpful error message was 

```
Error detected during run of module LoadData
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 958, in run_with_yield
    self.run_module(module, workspace)
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 1275, in run_module
    module.run(workspace)
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/modules/loaddata.py", line 1090, in run
    provider = self.fetch_provider(image_name, m)
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/modules/loaddata.py", line 1052, in fetch_provider
    full_filename = url2pathname(url)
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/utilities/pathname.py", line 18, in url2pathname
    if any([url.lower().startswith(x) for x in PASSTHROUGH_SCHEMES]):
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/utilities/pathname.py", line 18, in <listcomp>
    if any([url.lower().startswith(x) for x in PASSTHROUGH_SCHEMES]):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by DavidStirling** [comment]
Are we sure that this is an h5py-related issue? This looks like it might be another occurance of #4299, wherein the OS module is returning paths in bytes. That user was also using h5py 3.0.0, so it could be the root cause.

**Comment by bethac07** [comment]
Yes, downgrading the h5py to 2.10 fixed the issue. 100% sure.  (It took me 3 hours last night to get there lol)

**Comment by DavidStirling** [comment]
Pinned this for now, at some point we might want to upgrade h5py but right now it's probably more trouble than it's worth.
