### ISSUE TITLE
cellprofiler doesn't start: Could not load cellprofiler.modules.measuretexture: ValueError: module functions cannot set METH_CLASS or METH_STATIC

### ISSUE THREAD

**Issue by juliangilbey** [CellProfiler/CellProfiler#4314]
**Describe the bug**

I have just installed cellprofiler on my Linux machine using pip.  Unfortunately I can't run it; here is the console output:

```
euler:~ $ cellprofiler
11:30:17: Debug: Adding duplicate image handler for 'Windows bitmap file'
11:30:17: Debug: Adding duplicate animation handler for '1' type
11:30:17: Debug: Adding duplicate animation handler for '2' type
Could not load cellprofiler.modules.measuretexture
Traceback (most recent call last):
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler/modules/measuretexture.py", line 107, in <module>
    import mahotas.features
  File "/home/jdg/.local/lib/python3.8/site-packages/mahotas/__init__.py", line 83, in <module>
    from . import polygon
  File "/home/jdg/.local/lib/python3.8/site-packages/mahotas/polygon.py", line 8, in <module>
    from . import _convex
ValueError: module functions cannot set METH_CLASS or METH_STATIC
Could not load cellprofiler.modules.watershed
Traceback (most recent call last):
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler/modules/watershed.py", line 2, in <module>
    import mahotas
  File "/home/jdg/.local/lib/python3.8/site-packages/mahotas/__init__.py", line 83, in <module>
    from . import polygon
  File "/home/jdg/.local/lib/python3.8/site-packages/mahotas/polygon.py", line 8, in <module>
    from . import _convex
ValueError: module functions cannot set METH_CLASS or METH_STATIC
could not load these modules: cellprofiler.modules.measuretexture,cellprofiler.modules.watershed
Traceback (most recent call last):
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler/gui/app.py", line 79, in OnInit
    self.frame = CPFrame(None, -1, "CellProfiler")
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler/gui/cpframe.py", line 349, in __init__
    self.startup_blurb_frame = WelcomeFrame(self)
  File "/home/jdg/.local/lib/python3.8/site-packages/cellprofiler/gui/_welcome_frame.py", line 30, in __init__
    self.content = wx.html2.WebView.New(self)
NotImplementedError
OnInit returned false, exiting...
```
Oh dear :-(

Thanks for your work on this!

**To Reproduce**

See above.

**Desktop (please complete the following information):**
 - OS: Linux Debian testing
 - CellProfiler Version 4.0.7
 - Installed using pip

**Comment by DavidStirling** [comment]
Hi @juliangilbey 

It looks like there may be issues with your Mahotas and Wx installations. Would you be able to post the results from running `pip freeze`?

**Comment by juliangilbey** [comment]
Thanks for the amazingly quick response!  Here is the output; it looks as though it's picked up every Python package installed by Debian's package manager as well as those locally installed by pip, but Mahotas and Wx were installed by pip:

```
absl-py==0.10.0
acme==1.8.0
agate==1.6.1
agate-dbf==0.2.0
agate-excel==0.2.3
agate-sql==0.5.5
aiohttp==3.6.2
alabaster==0.7.8
appdirs==1.4.4
apt-xapian-index==0.49
argon2-cffi==18.3.0
astroid==2.4.2
astunparse==1.6.3
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==20.3.0
Babel==2.8.0
backcall==0.2.0
beautifulsoup4==4.9.3
bleach==3.1.5
blinker==1.4
blis==0.4.1
blosc==1.8.1
boto3==1.16.25
botocore==1.19.25
Bottleneck==1.2.1
breezy==3.1.0
brial==1.0.2
Brlapi==0.8.0
Brotli==1.0.9
brz-debian==3.0.0
brz-etckeeper==0.0.0
cachetools==4.1.1
cajarename==20.1.25
catalogue==1.0.0
CellProfiler==4.0.7
cellprofiler-core==4.0.7
centrosome==1.2.0
certbot==1.8.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.3
coloredlogs==7.3
ConfigArgParse==0.13.0
configobj==5.0.6
cryptography==3.2.1
csvkit==1.0.5
cupshelpers==1.0
cycler==0.10.0
cymem==2.0.4
dask==2.11.0+dfsg
dataclasses==0.6
dbfread==2.0.7
dblatex===0.3.11py3
dbus-python==1.2.16
debmutate==0.10
debtags==2.1
decorator==4.4.2
defusedxml==0.6.0
Deprecated==1.2.10
deprecation==2.1.0
devscripts==2.20.4
distlib==0.3.1
distro==1.5.0
distro-info==0.24
dnspython==2.0.0
docutils==0.15.2
dot2tex==2.11.3
dulwich==0.20.8
entrypoints==0.3
et-xmlfile==1.0.1
fail2ban==0.11.1
fastai==2.1.5
fastcore==1.3.6
fasteners==0.14.1
fastimport==0.9.8
fastprogress==1.0.0
feedparser==5.2.1
filelock==3.0.12
Flask==1.1.2
flatlatex==0.8
fonttools==4.17.0
fs==2.4.11
fsspec==0.8.4
future==0.18.2
gast==0.3.3
gbp==0.9.20
GDAL==3.1.4
Geophar==18.8.6
google-auth==1.22.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
gpg===1.14.0-unknown
grpcio==1.32.0
gyp==0.1
h5py==2.10.0
html5lib==1.1
httplib2==0.18.1
humanfriendly==8.2
icdiff==1.9.5
idna==2.10
imagecodecs==2020.5.30
imageio==2.9.0
imagesize==1.2.0
img2pdf==0.4.0
importlib-metadata==1.6.0
inflect==5.0.2
ipykernel==5.3.4
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
isort==5.6.4
itsdangerous==1.1.0
jdc==0.0.9
jdcal==1.0
jedi==0.17.0
jeepney==0.6.0
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.17.0
josepy==1.2.0
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.6
jupyter-console==6.2.0
jupyter-core==4.7.0
jupyterlab==2.2.8
jupyterlab-server==1.2.0
Keras-Preprocessing==1.1.2
keyring==21.5.0
kiwisolver==1.3.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.5
lazy-object-proxy==1.5.1
leather==0.3.3
llvmlite==0.34.0
locket==0.2.0
logilab-common==1.8.0
louis==3.15.0
lxml==4.6.1
mahotas==1.4.11
Mako==1.1.3
Markdown==3.3.3
MarkupSafe==1.1.1
mate-menu==20.4.1
mate-tweak==20.10.0
matplotlib==3.1.3
mccabe==0.6.1
mercurial==5.5.2
mistune==0.8.4
mock==4.0.2
monotonic==1.5
more-itertools==4.2.0
mpmath==1.1.0
msgpack==0.6.2
multidict==5.0.0
murmurhash==1.0.4
musicbrainzngs==0.7.1
mutagen==1.45.1
mypy-extensions==0.4.3
mysqlclient==1.4.6
nbconvert==5.6.1
nbformat==5.0.8
networkx==2.5
nltk==3.5
nose==1.3.7
notebook==6.1.5
ntp===1.2.0.2020-11-19T06-18-53Z
numba==0.51.2
numexpr==2.7.1
numpy==1.19.3
numpydoc==1.1.0
oauth2client==4.1.2
oauthlib==3.1.0
ocrmypdf==10.3.1+dfsg
odfpy==1.4.1
olefile==0.46
openpyxl==3.0.3
openslide-python==1.1.2
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.4
pandocfilters==1.4.2
parsedatetime==2.4
parso==0.7.0
partd==1.0.0
pathspec==0.8.0
patiencediff==0.2.1
patsy==0.5.1
pbr==5.5.0
pdfarranger==1.6.2
pdfminer.six==20200726
pep8==1.7.1
pexpect==4.6.0
pickleshare==0.7.5
pikepdf==1.17.3+dfsg
Pillow==8.0.1
plac==1.1.3
pluggy==0.13.0
preshed==3.0.4
prokaryote==2.4.2
prometheus-client==0.7.1
prompt-toolkit==3.0.8
protobuf==3.13.0
psutil==5.7.3
pxpx==1.1.0
py==1.9.0
py3dns==3.2.1
pyasn1==0.4.8
pyasn1-modules==0.2.1
PyAudio==0.2.11
pycairo==1.16.2
pycodestyle==2.6.0
pycrypto==2.6.1
pycups==2.0.1
pycurl==7.43.0.6
pydot==1.4.1
pyflakes==2.2.0
pygame==1.9.6
PyGithub==1.43.7
Pygments==2.3.1
PyGObject==3.38.0
pygraphviz==1.6
PyICU==2.5
pyinotify==0.9.6
PyJWT==1.7.1
pylint==2.6.0
PyMuPDF==1.17.4
pyOpenSSL==19.1.0
pyparsing==2.4.7
PyQt5==5.15.1
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.1
pyRFC3339==1.1
pyrsistent==0.15.5
PySimpleSOAP==1.16.2
pysmbc==1.0.23
PyStemmer==2.0.1
pysvn==1.9.12
pytest==4.6.11
python-apt==2.1.5
python-bioformats==4.0.0
python-dateutil==2.8.1
python-debian==0.1.38
python-debianbts==3.0.2
python-gitlab==2.4.0
python-javabridge==4.0.0
python-ly==0.9.6
python-magic==0.4.16
python-poppler-qt5==0.75.0
python-slugify==4.0.0
python-xlib==0.27
pytimeparse==1.1.5
pytz==2020.4
PyWavelets==1.1.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==18.0.1
pyzor==1.0.0
QScintilla==2.11.5
QtAwesome==0.4.4
qtconsole==4.7.6
QtPy==1.9.0
quodlibet==4.3.0
redis==3.3.11
regex==2020.7.14
reportbug==7.8.0
reportlab==3.5.55
requests==2.24.0
requests-oauthlib==1.3.0
requests-toolbelt==0.8.0
roman==2.0.0
rope==0.17.0
rsa==4.0
rubber==1.5.1
s3transfer==0.3.3
safeeyes==2.0.6
scikit-image==0.17.2
scikit-learn==0.23.2
scipy==1.5.4
scour==0.37
seaborn==0.10.1
SecretStorage==3.2.0
Send2Trash==1.5.0
sentry-sdk==0.18.0
setproctitle==1.1.10
simplejson==3.17.0
sip==4.19.24
six==1.15.0
snowballstemmer==2.0.0
sortedcontainers==2.1.0
soupsieve==2.0.1
spacy==2.3.2
Sphinx==3.3.1
sphinx-rtd-theme==0.5.0
spyder==3.3.6
spyder-kernels==0.5.2
SQLAlchemy==1.3.20
srsly==1.0.4
stevedore==3.2.2
sympy==1.6.2
systemd-python==234
tables==3.6.1
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow-estimator==2.3.0
tensorflow-gpu==2.3.1
termcolor==1.1.0
terminado==0.9.1
testpath==0.4.4
thinc==7.4.1
tifffile==2020.11.18
toml==0.10.1
toolz==0.9.0
torch==1.7.0+cu110
torchaudio==0.7.0
torchvision==0.8.1+cu110
tornado==6.1
tqdm==4.51.0
traitlets==5.0.5
typing-extensions==3.7.4.3
ubuntu-dev-tools==0.177
unattended-upgrades==0.1
Unidecode==1.1.1
unidiff==0.5.5
urllib3==1.25.11
virtualenv==20.1.0+ds
virtualenv-clone==0.3.0
virtualenvwrapper==4.8.4
wadllib==1.3.4
wasabi==0.8.0
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
whatmaps==0.0.0
widgetsnbextension==3.5.1
wrapt==1.12.1
wxPython==4.1.0
xattr==0.9.7
xlrd==1.1.0
xlwt==1.3.0
yamllint==1.24.2
yarl==1.4.2
youtube-dl==2020.11.24
zipp==1.0.0
zope.component==4.3.0
zope.event==4.4
zope.hookable==5.0.1
zope.interface==5.1.2
```

**Comment by bethac07** [comment]
It looks like it's the same PLACES we were seeing issues with mahotas imports in #4191 (which was an Ubuntu 20 build), but not the same error; I'm not sure why CellProfiler is continuing to have issues with that on some (but only some) Linux distros.

WX seems like you have the right version, but maybe not all the underlying dependencies- can you uninstall the wx version you have and install the wheel version with [extras](https://extras.wxpython.org/wxPython4/extras/linux/) from the wx site and see if it makes that wx issue clear up?

**Comment by bethac07** [comment]
Also, can you test just mahotas in your shell, and run the mahotas tests, as I did in [this issue](https://github.com/luispedro/mahotas/issues/117)? Just to rule out something funny happening in your mahotas install.

**Comment by juliangilbey** [comment]
Ah, frustratingly I can't install the wx version from the extras site: my Debian testing system has Python 3.8, but the extras wheel was built for Python 3.7, so I get the error message "ERROR: wxPython-4.1.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform."  So I set up a fresh virtual environment and followed the installation instructions for building from source, and - woo-hoo - it works!  What presumably happened was that it built from source without all of the required libraries installed, didn't give any failure message (though there may well have been warning messages I missed) and so sort of worked, but not properly.

Thanks!

**Comment by xxqtony** [comment]
I got the same warnings (not errors) when I build a docker image (from ubuntu 20:04):
warning ... blah blah...
WARNING:root:could not load these modules: cellprofiler.modules.measuretexture,cellprofiler.modules.watershed
When I launch "cellprofiler -c -r -p ExampleHuman.cppipe -i images/ -o output/" from command line. 

The way I fix it is to insert the following two imports into /usr/local/lib/python3.8/dist-packages/cellprofiler/__main__.py
import cellprofiler.modules.measuretexture
import cellprofiler.modules.watershed

HTH
