### ISSUE TITLE
Failure to Launch

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4342]
**Describe the bug**
02:13:12 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
02:13:12 PM: Debug: Adding duplicate animation handler for '1' type
02:13:12 PM: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/Users/eweisbar/Desktop/github/CellProfiler/cellprofiler/gui/app.py", line 69, in OnInit
    from .cpframe import CPFrame
  File "/Users/eweisbar/Desktop/github/CellProfiler/cellprofiler/gui/cpframe.py", line 36, in <module>
    from .pipelinecontroller import PipelineController
  File "/Users/eweisbar/Desktop/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 94, in <module>
    from cellprofiler_core.pipeline.io._v6 import load
ImportError: cannot import name 'load' from 'cellprofiler_core.pipeline.io._v6' (/usr/local/lib/python3.8/site-packages/cellprofiler_core/pipeline/io/_v6.py)
OnInit returned false, exiting...

appdirs==1.4.4
asn1crypto==1.3.0
attrs==19.3.0
awscli==1.18.64
black==19.10b0
botocore==1.16.14
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
conda==4.8.2
conda-package-handling==1.6.0
cryptography==2.8
cytominer-eval==0.0.0
docutils==0.15.2
idna==2.8
jmespath==0.10.0
joblib==0.17.0
numpy==1.19.3
pandas==1.1.4
pathspec==0.8.0
pyasn1==0.4.8
pycosat==0.6.3
pycparser==2.19
pycytominer==0.1
pyOpenSSL==19.1.0
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
regex==2020.5.14
requests==2.22.0
rsa==3.4.2
ruamel-yaml==0.15.87
s3transfer==0.3.3
scikit-learn==0.23.2
scipy==1.5.4
six==1.14.0
SQLAlchemy==1.3.20
threadpoolctl==2.1.0
toml==0.10.1
tqdm==4.42.1
typed-ast==1.4.1
urllib3==1.25.8

 - OS: OSX 15.7
 - CellProfiler Version 4.0.7
 - source

**Comment by ErinWeisbart** [comment]
The solution was to clone CellProfiler/core, `cd` into that directory, `pip3 install -e .`
Then I could launch CellProfiler.

@bethac07 will update the install docs shortly to explain in what scenarios this needs to be done.
