### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by johnduva** [CellProfiler/CellProfiler#4351]
**Describe the bug**
Cannot run cellprofiler command on Mac after recently installing

**To Reproduce**
Install on Mac and run "cellprofiler" 

**Expected behavior**
Should open the GUI

**Screenshots**

**Desktop (please complete the following information):**
 - Installed from source

**Additional context**
This is the error I'm getting:
```
Traceback (most recent call last):
  File "/Users/johnduva/opt/anaconda3/bin/cellprofiler", line 33, in <module>
    sys.exit(load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')())
  File "/Users/johnduva/opt/anaconda3/bin/cellprofiler", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/johnduva/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/johnduva/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/johnduva/Desktop/Git/CellProfiler/cellprofiler/__main__.py", line 29, in <module>
    from cellprofiler_core.preferences import set_conserve_memory
ImportError: cannot import name 'set_conserve_memory' from 'cellprofiler_core.preferences' (/Users/johnduva/opt/anaconda3/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py)

```

**Comment by DavidStirling** [comment]
If you're running the `master` branch, you probably need to clone the cellprofiler-core repo as well rather than using the version on PIP. You can do that with `git clone https://github.com/CellProfiler/core.git` and `pip install -e .`.

**Comment by johnduva** [comment]
Okay, that helped. Now it says `This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
`
How do I run with a Framework build of Python?

**Comment by bethac07** [comment]
You'll need to call with pythonw https://stackoverflow.com/questions/48531006/wxpython-this-program-needs-access-to-the-screen

**Comment by johnduva** [comment]
Okay, now looks like it can't find JVM library. Did I make a mistake during install maybe?

```
(base) johnduva@Johns-MacBook-Pro-2 CellProfiler % pythonw cellprofiler
Failed to find libjvm (jvmdir: /usr/bin/java
Failed to find libjli (jvmdir: /usr/bin/java
Traceback (most recent call last):
  File "/Users/johnduva/opt/anaconda3/lib/python3.8/site-packages/javabridge/jutil.py", line 281, in start_thread
    raise Exception("Javabridge failed to find JVM library")
Exception: Javabridge failed to find JVM library
Failed to create Java VM
Traceback (most recent call last):
  File "/Users/johnduva/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/johnduva/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "cellprofiler/__main__.py", line 936, in <module>
    sys.exit(main())
  File "cellprofiler/__main__.py", line 256, in main
    app = cellprofiler.gui.app.App(
  File "/Users/johnduva/Desktop/Git/CellProfiler/cellprofiler/gui/app.py", line 54, in __init__
    start_java()
  File "/Users/johnduva/Desktop/Git/core/cellprofiler_core/utilities/java.py", line 114, in start_java
    javabridge.start_vm(args=args, class_path=class_path)
  File "/Users/johnduva/opt/anaconda3/lib/python3.8/site-packages/javabridge/jutil.py", line 319, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
Sentry is attempting to send 3 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by bethac07** [comment]
Did you set your Java home? And otherwise follow the steps on the install instruction page? https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29

**Comment by johnduva** [comment]
got it :) thanks so much @bethac07 and @DavidStirling
