### ISSUE TITLE
Issue opening a pipeline through cellprofiler_core

### ISSUE THREAD

**Issue by Bazarganigilani** [CellProfiler/CellProfiler#4352]
Hi, I am tryin to load a pipeline which I have developed by cellprofile 4.0.7 through your desktop application. I juts exported my pipeline and trying to load it by your convntila codes you introduced in your website as bellow. But I am getting error.

Please note that , I installed cellprofile on python3.8.7 by using pip install cellprofiler

```
>>> import cellprofiler_core.image
import cellprofiler_core.object
import cellprofiler_core.pipeline
import cellprofiler_core.preferences
import cellprofiler_core.workspace
cellprofiler_core.preferences.set_headless()>>> >>> >>> >>> >>>
>>> pipeline = cellprofiler_core.pipeline.Pipeline()
>>> pipeline.load("malen4_v4_g.cppipe")
WARNING:root:Could not load cellprofiler_core.modules.align
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/modules/align.py", line 54, in <module>
    from centrosome.filter import stretch
  File "/usr/local/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.convertobjectstoimage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/convertobjectstoimage.py", line 24, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.correctilluminationcalculate
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/correctilluminationcalculate.py", line 47, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.crop
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/crop.py", line 43, in <module>
    import centrosome.filter
  File "/usr/local/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.definegrid
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/definegrid.py", line 50, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.enhanceedges
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/enhanceedges.py", line 26, in <module>
    import centrosome.filter
  File "/usr/local/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.enhanceorsuppressfeatures
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/enhanceorsuppressfeatures.py", line 23, in <module>
    import centrosome.filter
  File "/usr/local/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.expandorshrinkobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/expandorshrinkobjects.py", line 59, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:MySQL could not be loaded.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/exporttodatabase.py", line 156, in <module>
    import sqlite3
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
WARNING:root:Could not load cellprofiler.modules.identifydeadworms
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/identifydeadworms.py", line 80, in <module>
    from centrosome.cpmorphology import all_connected_components
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.identifyobjectsingrid
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/identifyobjectsingrid.py", line 68, in <module>
    from centrosome.cpmorphology import centers_of_labels
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.identifyprimaryobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/identifyprimaryobjects.py", line 5, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.identifysecondaryobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/identifysecondaryobjects.py", line 1, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.maskobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/maskobjects.py", line 23, in <module>
    from centrosome.cpmorphology import fixup_scipy_ndimage_result
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measurecolocalization
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measurecolocalization.py", line 94, in <module>
    from centrosome.cpmorphology import fixup_scipy_ndimage_result as fix
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measuregranularity
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measuregranularity.py", line 15, in <module>
    from centrosome.cpmorphology import fixup_scipy_ndimage_result as fix
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureimageoverlap
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureimageoverlap.py", line 93, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureimagequality
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureimagequality.py", line 5, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureobjectintensity
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureobjectintensity.py", line 1, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureobjectoverlap
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureobjectoverlap.py", line 60, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureobjectsizeshape
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureobjectsizeshape.py", line 1, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureobjectneighbors
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureobjectneighbors.py", line 86, in <module>
    from centrosome.cpmorphology import fixup_scipy_ndimage_result as fix
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureobjectintensitydistribution
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureobjectintensitydistribution.py", line 1, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.measureobjectskeleton
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/measureobjectskeleton.py", line 64, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.morph
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/morph.py", line 257, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.smooth
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/smooth.py", line 38, in <module>
    from centrosome.filter import median_filter, circular_average_filter
  File "/usr/local/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.splitormergeobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/splitormergeobjects.py", line 1, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.straightenworms
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/straightenworms.py", line 134, in <module>
    from cellprofiler.modules.untangleworms import C_WORM
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/untangleworms.py", line 97, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.threshold
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/threshold.py", line 20, in <module>
    import centrosome.threshold
  File "/usr/local/lib/python3.8/site-packages/centrosome/threshold.py", line 15, in <module>
    from .filter import stretch, unstretch
  File "/usr/local/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.trackobjects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/trackobjects.py", line 236, in <module>
    from centrosome.lapjv import lapjv
  File "/usr/local/lib/python3.8/site-packages/centrosome/lapjv.py", line 5, in <module>
    from ._lapjv import reduction_transfer
  File "centrosome/_lapjv.pyx", line 1, in init centrosome._lapjv
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:Could not load cellprofiler.modules.untangleworms
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler/modules/untangleworms.py", line 97, in <module>
    import centrosome.cpmorphology
  File "/usr/local/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "centrosome/_cpmorphology2.pyx", line 1, in init centrosome._cpmorphology2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
WARNING:root:could not load these modules: cellprofiler_core.modules.align,cellprofiler.modules.convertobjectstoimage,cellprofiler.modules.correctilluminationcalculate,cellprofiler.modules.crop,cellprofiler.modules.definegrid,cellprofiler.modules.enhanceedges,cellprofiler.modules.enhanceorsuppressfeatures,cellprofiler.modules.expandorshrinkobjects,cellprofiler.modules.identifydeadworms,cellprofiler.modules.identifyobjectsingrid,cellprofiler.modules.identifyprimaryobjects,cellprofiler.modules.identifysecondaryobjects,cellprofiler.modules.maskobjects,cellprofiler.modules.measurecolocalization,cellprofiler.modules.measuregranularity,cellprofiler.modules.measureimageoverlap,cellprofiler.modules.measureimagequality,cellprofiler.modules.measureobjectintensity,cellprofiler.modules.measureobjectoverlap,cellprofiler.modules.measureobjectsizeshape,cellprofiler.modules.measureobjectneighbors,cellprofiler.modules.measureobjectintensitydistribution,cellprofiler.modules.measureobjectskeleton,cellprofiler.modules.morph,cellprofiler.modules.smooth,cellprofiler.modules.splitormergeobjects,cellprofiler.modules.straightenworms,cellprofiler.modules.threshold,cellprofiler.modules.trackobjects,cellprofiler.modules.untangleworms
ERROR:root:Failed to load pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 519, in setup_modules
    module = self.setup_module(
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 545, in setup_module
    module = self.instantiate_module(module_name)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 186, in instantiate_module
    return instantiate_module(module_name)
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 180, in instantiate_module
    module = get_module_class(module_name)()
  File "/usr/local/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 175, in get_module_class
    raise ValueError("Could not find the %s module" % module_class)
ValueError: Could not find the IdentifyPrimaryObjects module
```
I am not sure what is the cause of above error?

running pip list give me below packages installed on my python3.8
```
[root@*** azureuser]# python3.8 -m pip list
Package           Version
----------------- ---------
boto3             1.17.5
botocore          1.20.5
CellProfiler      4.0.7
cellprofiler-core 4.0.7
centrosome        1.2.0
certifi           2020.12.5
chardet           4.0.0
cycler            0.10.0
decorator         4.4.2
deprecation       2.1.0
docutils          0.15.2
future            0.18.2
h5py              2.10.0
idna              2.10
imageio           2.9.0
inflect           5.0.2
Jinja2            2.11.3
jmespath          0.10.0
joblib            1.0.1
kiwisolver        1.3.1
mahotas           1.4.11
MarkupSafe        1.1.1
matplotlib        3.1.3
mysqlclient       1.4.6
networkx          2.5
numpy             1.19.3
packaging         20.9
Pillow            8.1.0
pip               20.2.3
prokaryote        2.4.2
psutil            5.8.0
pyparsing         2.4.7
python-bioformats 4.0.0
python-dateutil   2.8.1
python-javabridge 4.0.0
PyWavelets        1.1.1
pyzmq             18.0.1
requests          2.25.1
s3transfer        0.3.4
scikit-image      0.18.1
scikit-learn      0.24.1
scipy             1.6.0
sentry-sdk        0.18.0
setuptools        49.2.1
six               1.15.0
threadpoolctl     2.1.0
tifffile          2021.2.1
urllib3           1.26.3
wheel             0.36.2
wxPython          4.1.1
```

**Comment by Bazarganigilani** [comment]
H, I just uninstall and reinstall centrosome and the error still persists..

**Comment by DavidStirling** [comment]
Did you notice whether it downloaded the package again? You may need to run `pip install centrosome --no-cache-dir` to avoid reinstalling the bugged copy.

**Comment by Bazarganigilani** [comment]
Hi, doing above again the error remains and the pip list also is the same like the previous post.

**Comment by DavidStirling** [comment]
That's very unusual, I think the next thing to try would be to clone this repo and run `pip install -e .` in the resulting folder

**Comment by Bazarganigilani** [comment]
Hi, I got the same error running above command no matter I use pip or install it manually,

I had to upgrade numpy from 1.19.3 to 1.20.1 and now it works

**Comment by DavidStirling** [comment]
Cool, we've upgraded numpy now so this should be fixed.
