### ISSUE TITLE
Numpy version requirement

### ISSUE THREAD

**Issue by jburel** [CellProfiler/CellProfiler#4353]
**Describe the bug**
using ``numpy 1.19.3`` as required in ``setup.py`` leads to 
```
  WARNING:root:Could not load cellprofiler_core.modules.align
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/cellprofiler_core/utilities/core/modules/__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/cellprofiler_core/modules/align.py", line 54, in <module>
    from centrosome.filter import stretch
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/centrosome/filter.py", line 15, in <module>
    from . import _filter
  File "centrosome/_filter.pyx", line 1, in init centrosome._filter
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
when importing the package.

Bumping to 1.20.1 solves the issue.

Happy to open a PR, any reason to keep it at 1.19.3?

**Comment by bethac07** [comment]
Pinning was due to a windows issue, Windows recently pushed a fix but we haven't had a chance to make sure unpinning doesn't lead to any other issues (and that the fix Windows pushed is truly a fix).

**Comment by bethac07** [comment]
We should be able to dig into this next week.

**Comment by jburel** [comment]
Thanks
I am testing on Ubuntu

**Comment by DavidStirling** [comment]
We've now unpinned Numpy for the 4.1.3 release, so this should be fixed.

**Comment by jburel** [comment]
Thanks
I have rebuilt the conda environment and everything works nicely
``numpy 1.20.1 py38h18fd61f_0    conda-forge``
