### ISSUE TITLE
Check on 3-pixel-level presence can be too strict in adaptive thresholding

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4436]
When you are doing adaptive thresholding with a 3 class thresholding (see attached pipeline + 2 example images), if your adaptive window is relatively small, you can end up with some windows that do not contain 3 separate pixel levels, causing the error below, meaning we have to skip the whole image even if only one small window has an issue.

I can imagine a couple different ways we might want to handle this- 
- Exactly as we are, but perhaps with just a more descriptive error message (to look at maybe increasing the adaptive window size, for example)
- Seeing if there are less than a cutoff percent of windows (10%, etc) affected, and if so just assign those windows the mean from the rest of the windows
- Above, but do something fancier (give it the values of its neighboring windows, or its closest-mean-windows, etc)
- Something else entirely?
---

```
Failed to run module IdentifyPrimaryObjects
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 3363, in do_step
    self.__pipeline.run_module(module, workspace_model)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/pipeline/_pipeline.py", line 1298, in run_module
    module.run(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/identifyprimaryobjects.py", line 1056, in run
    binary_image, global_threshold, sigma = self._threshold_image(
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/identifyprimaryobjects.py", line 1193, in _threshold_image
    final_threshold, orig_threshold, guide_threshold = self.threshold.get_threshold(
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/threshold.py", line 878, in get_threshold
    th_original = self.get_local_threshold(image_data, image.mask, image.volumetric)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/threshold.py", line 950, in get_local_threshold
    local_threshold = self._run_local_threshold(
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/threshold.py", line 983, in _run_local_threshold
    t_local = self._get_adaptive_threshold(image_data, method, **kwargs)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/threshold.py", line 1041, in _get_adaptive_threshold
    threshold_out = threshold_method(block, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/skimage/filters/thresholding.py", line 1213, in threshold_multiotsu
    raise ValueError(msg.format(nvalues, classes))
ValueError: The input image has only 2 different values. It can not be thresholded in 3 classes
```

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - CellProfiler Version 4.2 (built and source both)

**Pipeline and images to reproduce**
[3ClassAdaptive.zip](https://github.com/CellProfiler/CellProfiler/files/6841921/3ClassAdaptive.zip)

**Comment by DavidStirling** [comment]
I would have said that adaptive thresholding shouldn't be used with such a small window anyway, the method necessitates a reasonable sampling of pixel intensities. Because of the smoothing between Windows it's still important that we provide a value if we want to have a usable overall result. I do see a couple more options for solving this:

- Fall back to the mean value of the pixels.
- Fall back to the global guide threshold.

Ultimately if this error appears you've effectively asked it to segment a binary image, so calling Otsu or any other algorithm isn't really worth it.

**Comment by Alxcho** [comment]
Noticed the same, can indeed be solved by increasing the size. For cases where one image in a whole set has a window <3 classes but bigger than the specified window, a fall back step would still be great though.

**Comment by bethac07** [comment]
This has zombies back in 4.2.4/4.2.5, in a pipeline using adaptive 3 class otsu - need to figure out why

**Comment by bethac07** [comment]
So we've ended up in a bit of a corner case:
- 3-class otsu in the skimage implementation (see linked issue above) bins the image values into a finite number of bins, then runs the Otsu algorithm. 
- In our logic, if the user has asked for 3 class otsu, and there are more than 3 values present, run 3 class otsu with 128 bins (I don't know where we came up with that number, exactly) and if that errors because only 2 bins have any values in them (aka the values are all very close together), run it with 256 bins (the default).  This helps apparently most of the time, but in the example image provided, there are 6 values (below), but all but one are so close that even at 256 bins, there are only 2 bins with values. Even 512 isn't enough in this one case, you have to go out to 1024. We might therefore want some sort of while loop, to keep going out as far as we need. The below is messy, but works in terms of "code runs" and might be sufficiently fine. WDYT?

`
[0.0000000e+00 6.2584877e-06 1.9490719e-05 3.3736229e-05 3.4749508e-05
 2.0886213e-02]
`

```
diff --git a/cellprofiler/modules/threshold.py b/cellprofiler/modules/threshold.py
index c9ed0b882..69e44c4bb 100644
--- a/cellprofiler/modules/threshold.py
+++ b/cellprofiler/modules/threshold.py
@@ -1041,9 +1041,18 @@ staining.
                 else:
                     try: 
                         threshold_out = threshold_method(block, **kwargs)
-                    except ValueError:
-                        # Drop nbins kwarg when multi-otsu fails. See issue #6324 scikit-image
-                        threshold_out = threshold_method(block)
+                    except ValueError as e:
+                        nbins_found = False
+                        adj_nbins=128
+                        while nbins_found==False:
+                            try:
+                                # Iteratively increase the number of bins when multi-otsu fails. See issue #6324 scikit-image
+                                adj_nbins*=2
+                                threshold_out = threshold_method(block,nbins=adj_nbins)
+                                nbins_found=True
+                            except:
+                                if adj_nbins>65535: #don't try literally forever
+                                    raise e 
                 if isinstance(threshold_out, numpy.ndarray):
                     # Select correct bin if running multiotsu
                     threshold_out = threshold_out[bin_wanted]
```

**Comment by bethac07** [comment]
>(the other option, of course, is to be more deterministic (I don't LOVE that actual calculation of the threshold might be different in different boxes, though in practice, since these thresholds then all get checked and possibly changed anyway in correct_local_threshold, it's probably fine) and be like "sorry, adaptive window is too small, fix it", aka keep the current behavior)

So I tried to actually run some numbers on this in the image in question. This will be a bit dirty, because the order of operations is "calculate per-block-threshold -> smooth blocks -> filter for between 0.7 and 1.5 of the global threshold", and the filtering happens in another function, so what I'm reporting here is pre-smoothing block calculation and not what will ACTUALLY go into the filter, but the basic tenet should still stand. 

For the one out of 11,636 blocks in this image (I'm not sure why it's not 11,664, because they're 20 pixel bins and the image is 2160 pixels per side, so it should be 108^2, but let's just go with it for now), we had to go out to 1024 bins - in that case, the threshold was unsurprisingly way, way off (unsurprising because the bin was nearly all background), so it's destined for being overriden anyway. No matter whether the threshold is pretty close to global and would (ish) be kept, or pretty far from global and wouldn't, changing the number of bins 2, 4, 8, or 16 fold doesn't really adjust the final threshold at all - means are in the mid 90s percents and standard deviations are less than 10 percents. So, TLDR, we probably want to just fix it (open to input on if the fix above is the RIGHT fix), rather than obsessing (cough*SELF*cough) on the fact that the threshold won't be calculated in exactly the same way as the rest of the image in some blocks, because realistically the answer should be pretty close and it's destined for smoothing and then almost certainly being filtered anyway.

```
Had to go out to 1024 to get a threshold, which is 0.02442314287693557% of global
2214 blocks have their thresholds kept (ish), 9421 thrown out
Kept means 97.56891410003892 96.3730538323218 95.73146883836638 95.39710705037758
Kept stdevs 6.592848180055912 7.324340525461502 7.766649439226809 7.953335602111493
Overridden means 97.60167772131149 96.27712336371845 95.59263780492076 95.22793721055477
Overridden stdevs 6.394918399025022 7.891146509763211 8.552227940691294 8.843937954173514
```

```
diff --git a/cellprofiler/modules/threshold.py b/cellprofiler/modules/threshold.py
index c9ed0b882..aa6e63d66 100644
--- a/cellprofiler/modules/threshold.py
+++ b/cellprofiler/modules/threshold.py
@@ -1019,6 +1019,16 @@ staining.
         # Loop once per block, computing the "global" threshold within the
         # block.
         #
+        global_for_print = threshold_method(image_data, **kwargs)
+        if isinstance(global_for_print, numpy.ndarray):
+            # Select correct bin if running multiotsu
+            global_for_print = global_for_print[bin_wanted]
+        thresh_corr_dict={
+            "Kept":
+            {2:[],4:[],8:[],16:[]},
+            "Overridden":
+            {2:[],4:[],8:[],16:[]},
+        }
         block_threshold = numpy.zeros([nblocks[0], nblocks[1]])
         for i in range(nblocks[0]):
             i0 = int(i * increment[0])
@@ -1041,14 +1051,39 @@ staining.
                 else:
                     try: 
                         threshold_out = threshold_method(block, **kwargs)
-                    except ValueError:
-                        # Drop nbins kwarg when multi-otsu fails. See issue #6324 scikit-image
-                        threshold_out = threshold_method(block)
+                        tout1 = threshold_method(block,nbins=128)[bin_wanted]
+                        if tout1/global_for_print >0.7 and tout1/global_for_print <1.5:
+                            thresh_corr_dict["Kept"][2].append(100*threshold_method(block,nbins=256)[bin_wanted]/tout1)
+                            thresh_corr_dict["Kept"][4].append(100*threshold_method(block,nbins=512)[bin_wanted]/tout1)
+                            thresh_corr_dict["Kept"][8].append(100*threshold_method(block,nbins=1024)[bin_wanted]/tout1)
+                            thresh_corr_dict["Kept"][16].append(100*threshold_method(block,nbins=2048)[bin_wanted]/tout1)
+                        else:
+                            thresh_corr_dict["Overridden"][2].append(100*threshold_method(block,nbins=256)[bin_wanted]/tout1)
+                            thresh_corr_dict["Overridden"][4].append(100*threshold_method(block,nbins=512)[bin_wanted]/tout1)
+                            thresh_corr_dict["Overridden"][8].append(100*threshold_method(block,nbins=1024)[bin_wanted]/tout1)
+                            thresh_corr_dict["Overridden"][16].append(100*threshold_method(block,nbins=2048)[bin_wanted]/tout1)                           
+                    except ValueError as e:
+                        nbins_found = False
+                        adj_nbins=128
+                        while nbins_found==False:
+                            try:
+                                # Iteratively increase the number of bins when multi-otsu fails. See issue #6324 scikit-image
+                                adj_nbins*=2
+                                threshold_out = threshold_method(block,nbins=adj_nbins)
+                                print(f"Had to go out to {adj_nbins} to get a threshold, which is {100*threshold_out[bin_wanted]/global_for_print}% of global")
+                                nbins_found=True
+                            except:
+                                if adj_nbins>65535: #don't try literally forever
+                                    raise e 
                 if isinstance(threshold_out, numpy.ndarray):
                     # Select correct bin if running multiotsu
                     threshold_out = threshold_out[bin_wanted]
                 block_threshold[i, j] = threshold_out
-
+        print(f'{len(thresh_corr_dict["Kept"][2])} blocks have their thresholds kept (ish), {len(thresh_corr_dict["Overridden"][2])} thrown out')
+        print("Kept means", numpy.array(thresh_corr_dict["Kept"][2]).mean(),numpy.array(thresh_corr_dict["Kept"][4]).mean(),numpy.array(thresh_corr_dict["Kept"][8]).mean(),numpy.array(thresh_corr_dict["Kept"][16]).mean())
+        print("Kept stdevs", numpy.array(thresh_corr_dict["Kept"][2]).std(),numpy.array(thresh_corr_dict["Kept"][4]).std(),numpy.array(thresh_corr_dict["Kept"][8]).std(),numpy.array(thresh_corr_dict["Kept"][16]).std())
+        print("Overridden means", numpy.array(thresh_corr_dict["Overridden"][2]).mean(),numpy.array(thresh_corr_dict["Overridden"][4]).mean(),numpy.array(thresh_corr_dict["Overridden"][8]).mean(),numpy.array(thresh_corr_dict["Overridden"][16]).mean())
+        print("Overridden stdevs", numpy.array(thresh_corr_dict["Overridden"][2]).std(),numpy.array(thresh_corr_dict["Overridden"][4]).std(),numpy.array(thresh_corr_dict["Overridden"][8]).std(),numpy.array(thresh_corr_dict["Overridden"][16]).std())
         #
         # Use a cubic spline to blend the thresholds across the image to avoid image artifacts
         #
```
