### ISSUE TITLE
Watershed module in 'Advanced' mode does not respect downsampling

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4440]
Running 4.2.1 on Windows. Setting up the Watershed module with the new 'Advanced' mode triggers an error if a downsampling factor was used in the initial watershed settings.

Full trace:

```Failed to run module Watershed
Traceback (most recent call last):
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 3363, in do_step
    self.__pipeline.run_module(module, workspace_model)
  File "C:\Users\dstirlin\Github\core\cellprofiler_core\pipeline\_pipeline.py", line 1298, in run_module
    module.run(workspace)
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\cellprofiler\modules\watershed.py", line 565, in run
    watershed_boundaries = skimage.segmentation.watershed(
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\venv\lib\site-packages\skimage\segmentation\_watershed.py", line 203, in watershed
    image, markers, mask = _validate_inputs(image, markers, mask, connectivity)
  File "C:\Users\dstirlin\Github\CellProfiler\CellProfiler\venv\lib\site-packages\skimage\segmentation\_watershed.py", line 73, in _validate_inputs
    raise ValueError(message)
ValueError: `mask` (shape (17, 200, 200)) must have same shape as `image` (shape (17, 400, 400))
```

I believe the problem is that, when downscaling is enabled, the original `x_data` object is overwritten with the scaled version and then the output is scaled back up to make `y_data`. The advanced mode then tries to use `x_data` to create a new mask which will be used on `y_data`, but the sizes now mismatch.

Module settings below. This shouldn't be specific to 3D mode. 

![image](https://user-images.githubusercontent.com/26802537/127561069-5940d5be-134b-46eb-a127-fc5bf0b83f09.png)

**Comment by DavidStirling** [comment]
@rsenft1 That approach should work, though with large scaling factors trying to resize back up could be quite lossy. It might be worth trying to just generate a full-res binary image using `x_data = x.pixel_data > threshold`.

**Comment by rsenft1** [comment]
@DavidStirling Good point! I'll revise accordingly.
