### ISSUE TITLE
Source installation (macOS)

### ISSUE THREAD

**Issue by pdichiaro** [CellProfiler/CellProfiler#4456]
- MacOS BigSur 11.4
 - CellProfiler Version 4.2
 - pip3 install cellprofiler

**Describe the issue**
error with python-javabridge installation

**Error messages**
<img width="969" alt="Screenshot 2021-08-27 at 12 09 44" src="https://user-images.githubusercontent.com/50377927/131111630-0772f841-6582-4114-b84c-d4092b0cae35.png">

**Comment by pdichiaro** [comment]
yes.
<img width="817" alt="Screenshot 2021-08-30 at 11 42 40" src="https://user-images.githubusercontent.com/50377927/131364485-2a919403-6b46-4e2d-8f7c-c440ea6cd9e1.png">

**Comment by ricoba** [comment]
I apologize in advance if this is not relevant, but before opening a new thread I prefer to add my issue to this. Hope it is proper, otherwise please tell me the best course of action in reporting the issue. 

I am also experiencing problems in source installation of CellProfiler on a Mac, OS Mojave 10.14.6 (18G9323). 

I am trying to install it following the instructions on 
[https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29]
 and after the 
pip3 install cellprofiler 
I have the following series of problems 


(CellProf_cellpose) screening-mac-7:CellProfiler_CellPose barsacch$ pip3 install -e .
Obtaining file:///Users/barsacch/CellProfiler_CellPose
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 326, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 526, in prepare_editable_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_vendor/pep517/wrappers.py", line 161, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'


Any hint?

**Comment by ricoba** [comment]
Thanks, I will try to update to python 3.8 . as for the setup tools, I have done it and
(CellProf_cellpose) screening-mac-7:CellProfiler_CellPose barsacch$ /Users/barsacch/anaconda3/envs/CellProf_cellpose/bin/pip3 install setuptools
Requirement already satisfied: setuptools in /Users/barsacch/anaconda3/envs/CellProf_cellpose/lib/python3.6/site-packages (50.3.0.post20201006)
