### ISSUE TITLE
Unable to install CellProfiler on Centos7 on HPC using pip install: error "MySQLdb could not be loaded"

### ISSUE THREAD

**Issue by SA-uToronto** [CellProfiler/CellProfiler#4461]
Hi I am picking up the following error each time I try to run CellProfiler headlessly on HPC. Its really driving me up the wall and would really appreciate your advice. 

Thank you very much.
Regards,
Shamini A
-------------------------------------------------------------------------------------------------------------------------

**System**
------------
HPC cluster compute canada, Centos7/8

**Bug/Error message**
----------
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
MySQL could not be loaded.
Traceback (most recent call last):
  File "/home/mystique/cpVirtual/lib/python3.8/site-packages/cellprofiler/modules/exporttodatabase.py", line 154, in <module>
    import MySQLdb
  File "/home/mystique/cpVirtual/lib/python3.8/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmysqlclient.so.21: cannot open shared object file: No such file or directory
CP-JAVA 16:23:16.747 [Thread-0] WARN  o.c.imageset.ChannelFilter - Empty image set list: no images passed the filtering criteria.
---

**Code reproduced below**
------------------------------
1. module load python/3.8.10
2. module load java/13.0.2
3. virtualenv cpVirtual
4. source cpVirtual/bin/activate
5. PYTHONPATH= pip install h5py==3.2.1 (since our HPC does not have the wheel for this)
5. pip install cellprofiler
6. cellprofiler -c -r -p ~/pipeline.cppipe -o ~/outputdirectory -i ~/inputdirectory

**Expected behavior**
-----------------------
pip list gives me the following packages installed and it all seems ok. So I am not sure what the problem is but I searched and realized others have this issue but I tried doing what they've done and its not working. 

Package            Version                
------------------ -----------------------
boto3              1.18.32                
botocore           1.21.32                
CellProfiler       4.2.1                  
cellprofiler-core  4.2.1                  
centrosome         1.2.0                  
certifi            2021.5.30+computecanada
charset-normalizer 2.0.4+computecanada    
cycler             0.10.0+computecanada   
deprecation        2.1.0+computecanada    
docutils           0.15.2+computecanada   
future             0.18.2+computecanada   
h5py               3.2.1                  
idna               3.2+computecanada      
imageio            2.9.0+computecanada    
inflect            5.3.0                  
Jinja2             3.0.1+computecanada    
jmespath           0.10.0+computecanada   
joblib             1.0.1+computecanada    
kiwisolver         1.3.1+computecanada    
mahotas            1.4.11                 
MarkupSafe         2.0.1+computecanada    
matplotlib         3.1.3                  
mysqlclient        1.4.6                  
networkx           2.6.2+computecanada    
numpy              1.21.2                 
packaging          21.0+computecanada     
Pillow             8.3.1+computecanada    
pip                20.0.2                 
prokaryote         2.4.4                  
psutil             5.8.0+computecanada    
pyparsing          2.4.7+computecanada    
python-bioformats  4.0.5                  
python-dateutil    2.8.2+computecanada    
python-javabridge  4.0.3                  
pywavelets         1.1.1+computecanada    
pyzmq              18.0.1                 
requests           2.26.0+computecanada   
s3transfer         0.5.0+computecanada    
scikit-image       0.18.2+computecanada   
scikit-learn       0.24.1+computecanada   
scipy              1.7.0+computecanada    
sentry-sdk         0.18.0                 
setuptools         46.1.3                 
six                1.16.0+computecanada   
threadpoolctl      2.2.0+computecanada    
tifffile           2021.8.8+computecanada 
urllib3            1.26.6+computecanada   
wheel              0.34.2                 
wxPython           4.1.0

**Comment by SA-uToronto** [comment]
Hi my HPC technician helped fix this problem. This had to do with the version libmysqlclient.so.21. He had the right version linked for CP execution. I am leaving a comment here for other users to check with their cluster technicians first if they run into this issue when running on their clusters. Otherwise, following the steps above, I was able to run CP4 successfully on our HPC. Thank you.
