### ISSUE TITLE
Failure in analysis startup/[Errno 13] Permission denied when installing from source

### ISSUE THREAD

**Issue by emmanuel-contreras** [CellProfiler/CellProfiler#4525]
Hello, I want to ultimately try the RunCellpose plugin which requires installing cellprofiler from source but keep running into this error. Please see below for more details
---

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - CellProfiler Version: 4.2.1
 - Installed from source 
I followed the steps below for the installation of cellprofiler
https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29

**Describe the issue**
Everything seems to have installed fine and I see the RunCellpose plugin but running any analysis throws that "Failure in analysis startup" error. I have also tried the _ExampleHuman_ pipeline and it still throws the same error. 

Other notes: I pip installed cellpose and then installed gpu version of it. I had to upgrade numpy because cellpose downgraded it and also install numba 0.53.0 to resolve a different error of using numba 0.55.0. Installed everything in a conda environment called "cellprofiler"

**Error messages**
```
(cellprofiler) C:\Users\econtrerasguzman\Desktop>cellprofiler
Could not load enhancedmeasuretexture
Traceback (most recent call last):
  File "c:\users\econtrerasguzman\desktop\cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\econtrerasguzman\Desktop\cellprofiler\CellProfiler-plugins-master\enhancedmeasuretexture.py", line 1057
    return setting_values, variable_revision_number
                                                  ^
IndentationError: unindent does not match any outer indentation level
Could not load runimagejscript
Traceback (most recent call last):
  File "c:\users\econtrerasguzman\desktop\cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\econtrerasguzman\Desktop\cellprofiler\CellProfiler-plugins-master\runimagejscript.py", line 25, in <module>
    import cpij.bridge as ijbridge, cpij.server as ijserver
  File "C:\Users\econtrerasguzman\Desktop\cellprofiler\CellProfiler-plugins-master\cpij\bridge.py", line 3, in <module>
    import atexit, cpij.server as ijserver
  File "C:\Users\econtrerasguzman\Desktop\cellprofiler\CellProfiler-plugins-master\cpij\server.py", line 9, in <module>
    import jpype, imagej, multiprocessing, socket, threading, time
ModuleNotFoundError: No module named 'jpype'
Could not load runstardist
Traceback (most recent call last):
  File "c:\users\econtrerasguzman\desktop\cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\econtrerasguzman\Desktop\cellprofiler\CellProfiler-plugins-master\runstardist.py", line 5, in <module>
    from stardist.models import StarDist2D
ModuleNotFoundError: No module named 'stardist'
could not load these modules: enhancedmeasuretexture,runimagejscript,runstardist
Your pipeline was saved using an old version
of CellProfiler (rev ).
The current version of CellProfiler can load
and run this pipeline, but if you make changes
to it and save, the older version of CellProfiler
(perhaps the version your collaborator has?) may
not be able to load it.

You can ignore this warning if you do not plan to save
this pipeline or if you will only use it with this or
later versions of CellProfiler.
[Errno 13] Permission denied
```

**Screenshots**
![image](https://user-images.githubusercontent.com/14666496/159751153-ef51e272-f938-4931-aa52-2a2777b404f8.png)

**Installed modules** 
```
(cellprofiler) C:\Users\econtrerasguzman\Desktop>conda list
# packages in environment at C:\Users\econtrerasguzman\Anaconda3\envs\cellprofiler:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
boto3                     1.21.24                  pypi_0    pypi
botocore                  1.24.24                  pypi_0    pypi
ca-certificates           2022.3.18            haa95532_0
cellpose                  1.0.2                    pypi_0    pypi
cellprofiler              4.2.1                     dev_0    <develop>
cellprofiler-core         4.2.1                     dev_0    <develop>
centrosome                1.2.0                    pypi_0    pypi
certifi                   2021.10.8        py38haa95532_2
charset-normalizer        2.0.12                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.3.1               h59b6b97_2
cycler                    0.11.0                   pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
fastremap                 1.12.2                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
git                       2.34.1               haa95532_0
h5py                      3.6.0                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.16.1                   pypi_0    pypi
inflect                   5.4.0                    pypi_0    pypi
intel-openmp              2022.0.0          haa95532_3663
jinja2                    3.0.3                    pypi_0    pypi
jmespath                  1.0.0                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
kiwisolver                1.4.0                    pypi_0    pypi
libuv                     1.40.0               he774522_0
llvmlite                  0.36.0                   pypi_0    pypi
mahotas                   1.4.12                   pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.1.3                    pypi_0    pypi
mkl                       2022.0.0           haa95532_115
mysqlclient               1.4.6                    pypi_0    pypi
natsort                   8.1.0                    pypi_0    pypi
networkx                  2.7.1                    pypi_0    pypi
numba                     0.53.0                   pypi_0    pypi
numpy                     1.22.3                   pypi_0    pypi
opencv-python-headless    4.5.5.64                 pypi_0    pypi
openssl                   1.1.1n               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.2           py38haa95532_0
prokaryote                2.4.4                    pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
python                    3.8.12               h6244533_0
python-bioformats         4.0.5                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
python-javabridge         4.0.3                    pypi_0    pypi
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pywavelets                1.3.0                    pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
s3transfer                0.5.2                    pypi_0    pypi
scikit-image              0.19.2                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
sentry-sdk                0.18.0                   pypi_0    pypi
setuptools                58.0.4           py38haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.0               h2bbff1b_0
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.3.16                pypi_0    pypi
tqdm                      4.63.0                   pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py38haa95532_2
wxpython                  4.1.0                    pypi_0    pypi
```
**Additional context**
Please let me know if you need any more info. Thanks!

**Comment by emmanuel-contreras** [comment]
Got it, good to know that there is a version that works! I also had full permissions on the machine and still had the permission error 13. After sinking about a day into it I put it on hold, it would be nice to see eventually though!

**Comment by iamsaad2** [comment]
I'm having the same problem, I was just wondering how you would install cell profiler 4.1.3 from source since github only has the latest version?

**Comment by kochild** [comment]
@iamsaad2 You can find releases on the main repository page. It's on the right side of the webpage where it says releases. But here's the link if you're having trouble finding it https://github.com/CellProfiler/CellProfiler/releases as well as the direct link to the 4.1.3 version https://github.com/CellProfiler/CellProfiler/releases/tag/v4.1.3. Just download the source code zip folder and follow the latest compilation for windows instructions and you should be good to go on that. If you want to compile the plugins, then you'll have to follow the instructions from that repository as well.

**Comment by bethac07** [comment]
Agreed that this seems to be a general conda permissions issue - from [their help](https://github.com/conda/conda/issues/4534), it seems installing conda on only your own user account or using "Run as Administrator" may help with this. Closing here as not CellProfiler specific, but very sorry for the inconvenience!
