### ISSUE TITLE
CellProfiler Source Installation MacOS M1

### ISSUE THREAD

**Issue by rayhendricks** [CellProfiler/CellProfiler#4536]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce may be closed without investigation. You may delete this section before posting your issue below.
---

**Desktop (please complete the following information):**
 - OS: Macos 12.3.1
 - CellProfiler Version [e.g. 2.2, 3.1.9]
 - Downloaded from the website or installed from source: from github 4.2.1
 - If the latter, how (**cloned**, installed from pypi, etc)?

**Describe the issue**
I followed the M1 Mac install guide from https://github.com/CellProfiler/CellProfiler/wiki/Installation-of-CellProfiler-4-from-source-on-MacOS-M1
**Error messages**
If applicable, post any error messages that you saw/received.  Text is preferable to screenshots, and more text preferable to less.  
If posting text, you may post it between the two lines of ` ``` ` below, otherwise you may delete those lines.

```
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting joblib>=0.13
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 KB 10.0 MB/s eta 0:00:00
Collecting requests>=2.22
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 2.8 MB/s eta 0:00:00
Collecting wxPython==4.1.0
  Downloading wxPython-4.1.0.tar.gz (65.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 MB 21.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting sentry-sdk==0.18.0
  Downloading sentry_sdk-0.18.0-py2.py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.7/120.7 KB 4.4 MB/s eta 0:00:00
Collecting imageio>=2.5
  Downloading imageio-2.16.2-py3-none-any.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 21.9 MB/s eta 0:00:00
Collecting scikit-learn>=0.20
  Downloading scikit_learn-1.0.2-cp38-cp38-macosx_12_0_arm64.whl (6.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 22.8 MB/s eta 0:00:00
Collecting mysqlclient==1.4.6
  Downloading mysqlclient-1.4.6.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 KB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting scikit-image>=0.17.2
  Downloading scikit_image-0.19.2-cp38-cp38-macosx_12_0_arm64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 23.1 MB/s eta 0:00:00
Collecting python-javabridge==4.0.3
  Downloading python-javabridge-4.0.3.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Could not find Java JRE compatible with x86_64 architecture
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zk/09h281y956b6fwdcrpm3r5zr0000gn/T/pip-install-s862n51o/python-javabridge_33490302deb6442489970a91f81c6161/setup.py", line 412, in <module>
          ext_modules=ext_modules(),
        File "/private/var/folders/zk/09h281y956b6fwdcrpm3r5zr0000gn/T/pip-install-s862n51o/python-javabridge_33490302deb6442489970a91f81c6161/setup.py", line 98, in ext_modules
          raise Exception("JVM not found")
      Exception: JVM not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ray@rays-air CellProfiler % pip3 install -e .

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Obtaining file:///Users/ray/Documents/GitHub/CellProfiler
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting joblib>=0.13
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting requests>=2.22
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting python-javabridge==4.0.3
  Using cached python-javabridge-4.0.3.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Could not find Java JRE compatible with x86_64 architecture
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zk/09h281y956b6fwdcrpm3r5zr0000gn/T/pip-install-bxqdhj4s/python-javabridge_c881e434fc1a418682eb48c8a300e8b6/setup.py", line 412, in <module>
          ext_modules=ext_modules(),
        File "/private/var/folders/zk/09h281y956b6fwdcrpm3r5zr0000gn/T/pip-install-bxqdhj4s/python-javabridge_c881e434fc1a418682eb48c8a300e8b6/setup.py", line 98, in ext_modules
          raise Exception("JVM not found")
      Exception: JVM not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Screenshots**

**Additional context**

**Comment by callum-jpg** [comment]
Hello @rayhendricks, thanks for posting this issue. Have you added `JAVA_HOME` to your `~/.zshrc` and sourced the zshrc afterwards (as shown below)? If so, would it be possible for you to post the contents of your zshrc file?

```
echo "export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)" >> ~/.zshrc
```
```
source ~/.zshrc
```

**Comment by rayhendricks** [comment]
I tried setting the java_home, still getting the following error when tryig to build 

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/ray/Documents/wxPython-4.1.2a1.dev5310+af8cca51
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5310+af8cca51) (9.1.0)
Requirement already satisfied: six in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5310+af8cca51) (1.16.0)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5310+af8cca51) (1.22.3)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running bdist_wheel
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build
      Traceback (most recent call last):
        File "build.py", line 49, in <module>
          from buildtools.wxpysip import sip_runner
        File "/Users/ray/Documents/wxPython-4.1.2a1.dev5310+af8cca51/buildtools/wxpysip.py", line 20, in <module>
          from sipbuild.code_generator import (set_globals, parse, generateCode,
      ModuleNotFoundError: No module named 'sipbuild'
      Command '"/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      /opt/homebrew/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build
      Traceback (most recent call last):
        File "build.py", line 49, in <module>
          from buildtools.wxpysip import sip_runner
        File "/Users/ray/Documents/wxPython-4.1.2a1.dev5310+af8cca51/buildtools/wxpysip.py", line 20, in <module>
          from sipbuild.code_generator import (set_globals, parse, generateCode,
      ModuleNotFoundError: No module named 'sipbuild'
      Command '"/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by callum-jpg** [comment]
Could you try `pip install sip` then attempt to install wxPython? Please report back if this works for you.

**Comment by rayhendricks** [comment]
Tried pip3 install sip, it's not working still giving a wxPython build error. Could it be a python interpreter location problem?   

```
ray@rays-air wxPython-4.1.2a1.dev5310+af8cca51 % which python3
/opt/homebrew/opt/python@3.8/bin/python3
```

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/ray/Documents/wxPython-4.1.2a1.dev5310+af8cca51
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5310+af8cca51) (9.1.0)
Requirement already satisfied: six in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5310+af8cca51) (1.16.0)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5310+af8cca51) (1.22.3)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running bdist_wheel
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build
      Traceback (most recent call last):
        File "build.py", line 49, in <module>
          from buildtools.wxpysip import sip_runner
        File "/Users/ray/Documents/wxPython-4.1.2a1.dev5310+af8cca51/buildtools/wxpysip.py", line 20, in <module>
          from sipbuild.code_generator import (set_globals, parse, generateCode,
      ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/opt/homebrew/lib/python3.8/site-packages/sipbuild/code_generator.abi3.so)
      Command '"/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      /opt/homebrew/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build
      Traceback (most recent call last):
        File "build.py", line 49, in <module>
          from buildtools.wxpysip import sip_runner
        File "/Users/ray/Documents/wxPython-4.1.2a1.dev5310+af8cca51/buildtools/wxpysip.py", line 20, in <module>
          from sipbuild.code_generator import (set_globals, parse, generateCode,
      ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/opt/homebrew/lib/python3.8/site-packages/sipbuild/code_generator.abi3.so)
      Command '"/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by callum-jpg** [comment]
Well, your python3 location makes sense and it seems that pip has previously installed `pillow` during a previous wxPython installation attempt to the correct brew python version. This makes me think `pip3` is referring to the right python, rather than python3 installed elsewhere on your system. Do you have python installed elsewhere? Would it be possible for you to post the output of `pip3 freeze`/`python3 -m pip freeze`?
