### ISSUE TITLE
import cellprofiler_core.pipeline

### ISSUE THREAD

**Issue by 302850047** [CellProfiler/CellProfiler#4551]
Traceback (most recent call last):

  File "/data/chenzhi/.conda/envs/Chenjy/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_2938032/2261310168.py", line 1, in <module>
    import cellprofiler_core.pipeline

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/pipeline/__init__.py", line 4, in <module>
    from ._pipeline import Pipeline

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/pipeline/_pipeline.py", line 22, in <module>
    from ..utilities.core.modules import instantiate_module, reload_modules

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/utilities/core/modules/__init__.py", line 7, in <module>
    from ....module import Module

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/module/__init__.py", line 2, in <module>
    from ._image_processing import ImageProcessing

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/module/_image_processing.py", line 2, in <module>
    from ..image import Image

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/image/__init__.py", line 3, in <module>
    from ._image_set import ImageSet

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/image/_image_set.py", line 7, in <module>
    from .abstract_image import VanillaImage

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/image/abstract_image/__init__.py", line 4, in <module>
    from .file import FileImage

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/image/abstract_image/file/__init__.py", line 1, in <module>
    from ._file_image import FileImage

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/image/abstract_image/file/_file_image.py", line 12, in <module>
    import cellprofiler_core.preferences

  File "/data/chenzhi/Chenjy/Pathomics/paper_repetition/cellprofiler_core/preferences/__init__.py", line 169
    __cached_values: dict = {}
                              ^
SyntaxError: annotated name '__cached_values' can't be global

**Comment by DavidStirling** [comment]
CellProfiler requires Python 3.8, rather than 3.7
