### ISSUE TITLE
Error when following Wiki entry on M1 installation

### ISSUE THREAD

**Issue by pascalschulthess** [CellProfiler/CellProfiler#4577]
I'm following the installation instructions from the wiki on _Installation of CellProfiler 4 from source on MacOS M1_ and receive an error during step 11.
I've downloaded and extracted `wxPython-4.1.2a1.dev5417+85aea3fd` and when `pip3 install .` I get

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/pascalschulthess/Downloads/wxPython-4.1.2a1.dev5417+85aea3fd
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/pascalschulthess/Downloads/wxPython-4.1.2a1.dev5417+85aea3fd/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/Users/pascalschulthess/Downloads/wxPython-4.1.2a1.dev5417+85aea3fd/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

So, I did `pip3 install attrdict` and retried `pip3 install .` which resulted in the following issue:

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/pascalschulthess/Downloads/wxPython-4.1.2a1.dev5417+85aea3fd
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /Users/pascalschulthess/Library/Python/3.8/lib/python/site-packages (from wxPython==4.1.2a1.dev5417+85aea3fd) (9.1.1)
Requirement already satisfied: six in /opt/homebrew/lib/python3.8/site-packages (from wxPython==4.1.2a1.dev5417+85aea3fd) (1.16.0)
Requirement already satisfied: numpy in /Users/pascalschulthess/Library/Python/3.8/lib/python/site-packages (from wxPython==4.1.2a1.dev5417+85aea3fd) (1.22.4)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running bdist_wheel
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build
      Traceback (most recent call last):
        File "build.py", line 49, in <module>
          from buildtools.wxpysip import sip_runner
        File "/Users/pascalschulthess/Downloads/wxPython-4.1.2a1.dev5417+85aea3fd/buildtools/wxpysip.py", line 20, in <module>
          from sipbuild.code_generator import (set_globals, parse, generateCode,
      ModuleNotFoundError: No module named 'sipbuild'
      Command '"/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.8/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      /opt/homebrew/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build
      Traceback (most recent call last):
        File "build.py", line 49, in <module>
          from buildtools.wxpysip import sip_runner
        File "/Users/pascalschulthess/Downloads/wxPython-4.1.2a1.dev5417+85aea3fd/buildtools/wxpysip.py", line 20, in <module>
          from sipbuild.code_generator import (set_globals, parse, generateCode,
      ModuleNotFoundError: No module named 'sipbuild'
      Command '"/opt/homebrew/opt/python@3.8/bin/python3.8" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Any tips on how to solve this?

**Comment by mccruz07** [comment]
Hi @pascalschulthess ,

Sorry to hear that, can you please run:

pip3 install attrdict
pip3 install sip==5.5.0

before attempting to install wxPython?

Best,
Mario

**Comment by pascalschulthess** [comment]
This worked, thanks! However, I ran into another problem when installing `core`

```
Building wheel for h5py (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-38
      creating build/lib.macosx-12-arm64-cpython-38/h5py
      copying h5py/h5py_warnings.py -> build/lib.macosx-12-arm64-cpython-38/h5py
      copying h5py/version.py -> build/lib.macosx-12-arm64-cpython-38/h5py
      copying h5py/__init__.py -> build/lib.macosx-12-arm64-cpython-38/h5py
      copying h5py/ipy_completer.py -> build/lib.macosx-12-arm64-cpython-38/h5py
      creating build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.macosx-12-arm64-cpython-38/h5py/_hl
      creating build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/conftest.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_errors.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_big_endian_file.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5o.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/common.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests
      creating build/lib.macosx-12-arm64-cpython-38/h5py/tests/data_files
      copying h5py/tests/data_files/__init__.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/data_files
      creating build/lib.macosx-12-arm64-cpython-38/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/test_vds
      copying h5py/tests/data_files/vlen_string_s390x.h5 -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_dset_utc.h5 -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.macosx-12-arm64-cpython-38/h5py/tests/data_files
      running build_ext
      Loading library to get build settings and version: libhdf5.dylib
      ********************************************************************************
                             Summary of the h5py configuration

      HDF5 include dirs: [
        '/opt/homebrew/Cellar/hdf5/1.12.1_1/include'
      ]
      HDF5 library dirs: [
        '/opt/homebrew/Cellar/hdf5/1.12.1_1/lib'
      ]
           HDF5 Version: (1, 12, 2)
            MPI Enabled: False
       ROS3 VFD Enabled: False
       Rebuild Required: True

      ********************************************************************************
      Executing api_gen rebuild of defs
      Executing cythonize()
      [ 1/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/_conv.pyx
      [ 2/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/_errors.pyx
      [ 3/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/_objects.pyx
      [ 4/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/_proxy.pyx
      [ 5/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/_selector.pyx
      [ 6/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/defs.pyx
      [ 7/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5.pyx
      [ 8/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5a.pyx
      [ 9/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5ac.pyx
      [10/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5d.pyx
      [11/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5ds.pyx
      [12/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5f.pyx
      [13/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5fd.pyx
      [14/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5g.pyx
      [15/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5i.pyx
      [16/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5l.pyx
      [17/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5o.pyx
      [18/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5p.pyx
      [19/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5pl.pyx
      [20/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5r.pyx
      [21/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5s.pyx
      [22/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5t.pyx
      [23/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/h5z.pyx
      [24/24] Cythonizing /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/utils.pyx
      building 'h5py.defs' extension
      creating build/temp.macosx-12-arm64-cpython-38
      creating build/temp.macosx-12-arm64-cpython-38/private
      creating build/temp.macosx-12-arm64-cpython-38/private/var
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256
      creating build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DH5_USE_18_API -DNPY_NO_DEPRECATED_API=0 -I./h5py -I/opt/homebrew/Cellar/hdf5/1.12.1_1/include -I/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/lzf -I/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/lzf/lzf -I/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-build-env-v7z8hd9w/overlay/lib/python3.8/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/defs.c -o build/temp.macosx-12-arm64-cpython-38/private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/defs.o
      In file included from /private/var/folders/fp/f5_24s996j1fy1q_vz286yhh0000gp/T/pip-install-60uk6yqh/h5py_67d059f1a0704f418675949b186b5256/h5py/defs.c:758:
      ./h5py/api_compat.h:27:10: fatal error: 'hdf5.h' file not found
      #include "hdf5.h"
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Building wheel for pyzmq (pyproject.toml) ... done
  Created wheel for pyzmq: filename=pyzmq-22.3.0-cp38-cp38-macosx_12_0_arm64.whl size=780862 sha256=40298147e1857b364b168034ce5da143b9e4ccbb6f72d514f6ee24b409cc667b
  Stored in directory: /Users/pascalschulthess/Library/Caches/pip/wheels/2a/64/03/b111f370c913a3b24321c7bc45dcf7aa4c19fc49f9f5e6c848
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491070 sha256=33161cd00cfa4c040c3c4e897acd512cbbba00749c86bcf4871bf81727d6378f
  Stored in directory: /Users/pascalschulthess/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built cellprofiler-core centrosome matplotlib prokaryote python-javabridge pyzmq future
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
```

**Comment by gnodar01** [comment]
Can you try:

```
brew install hdf5
export HDF5_DIR="$(brew --prefix hdf5)"
pip install --no-binary=h5py h5py
```

or if you're installing in a conda environment:

```
conda install h5py
```

and then try running again.

**Comment by pascalschulthess** [comment]
Installation worked. Thanks. When I try `python3 -m cellprofiler` I get

```
09:05:05: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:05:05: Debug: Adding duplicate animation handler for '1' type
09:05:05: Debug: Adding duplicate animation handler for '2' type
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "/Users/pascalschulthess/Applications/core/CellProfiler/cellprofiler/gui/app.py", line 69, in OnInit
    from .cpframe import CPFrame
  File "/Users/pascalschulthess/Applications/core/CellProfiler/cellprofiler/gui/cpframe.py", line 25, in <module>
    from ._workspace_model import Workspace
  File "/Users/pascalschulthess/Applications/core/CellProfiler/cellprofiler/gui/_workspace_model.py", line 8, in <module>
    import cellprofiler.gui.figure
  File "/Users/pascalschulthess/Applications/core/CellProfiler/cellprofiler/gui/figure/__init__.py", line 1, in <module>
    from ._figure import Figure
  File "/Users/pascalschulthess/Applications/core/CellProfiler/cellprofiler/gui/figure/_figure.py", line 8, in <module>
    import centrosome.cpmorphology
  File "/opt/homebrew/lib/python3.8/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
SystemError: execution of module centrosome._cpmorphology2 raised unreported exception
OnInit returned false, exiting...
```

The application is launching but freezing immediately.

**Comment by pascalschulthess** [comment]
Doing the first two resulted in the same error as before.

**Comment by callum-jpg** [comment]
Hey @pascalschulthess, would it be possible for you to retry the installation within a conda environment following the instructions [here](https://github.com/CellProfiler/CellProfiler/wiki/Installation-of-CellProfiler-4-from-source-on-MacOS-M1#conda-installation)?

**Comment by pascalschulthess** [comment]
@callum-jpg Was the Wiki page pulled?

**Comment by alxndrkalinin** [comment]
Instructions for [installation with conda](https://github.com/CellProfiler/CellProfiler/wiki/Installation-of-CellProfiler-4-from-source-on-MacOS-M1#conda-installation) were just updated for `v4.2.5` and tested on M1. It should work now.

**Comment by nklick** [comment]
I am attempting to install CellProfiler on an M2 mac following the conda instructions for an M1 mac. 

I can make it all the way through until installing the dependencies when I get the error:

```
INFO: pip is looking at multiple versions of cellprofiler-core to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cellprofiler-core==4.2.5 and scikit-image>=0.19.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested scikit-image>=0.19.3
    cellprofiler-core 4.2.5 depends on scikit-image==0.18.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

If I change the command to install scikit-image to "scikit-image==0.18.3", I get a huge log that starts with: 

```
Collecting scikit-image>=0.18.3
  Using cached scikit-image-0.18.3.tar.gz (29.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3366 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_python_implementation == "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_python_implementation == "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
```

and ends:

```
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error


× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Let me know if you have any ideas on how to go forward.

**Comment by alxndrkalinin** [comment]
@nklick Changing command to `scikit-image==0.18.3` works on M1, but haven't tested it on M2. Could you try [installing](https://wheel.readthedocs.io/en/stable/user_guide.html#installing-wheels) 18.3 directly from [a wheel file](https://files.pythonhosted.org/packages/d2/ab/0946a696f593f1a904550168e07ffc3a4f13f71afa7228e6eae4ce3a4ff5/scikit_image-0.18.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)?

**Comment by nklick** [comment]
@alxndrkalinin Thanks for the suggestion, but I got this error message after trying to install sci-kit directly from the wheel file you linked:
```
 pip install scikit_image-0.18.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
ERROR: scikit_image-0.18.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.
```

**Comment by nklick** [comment]
I think I solved my issue installing CellProfiler 4.2.5 on an M2. I haven't tested all the functionalities yet, but so far so good.
I used [Mamba](https://mamba.readthedocs.io/en/latest/index.html) which may be responsible for fixing the package dependency problems. I also installed sci-kit image with mamba after installing cellprofiler before the rest of the dependencies. 

Steps
1. Install java (same)
2. Install [Mamba](https://mamba.readthedocs.io/en/latest/index.html)
3. Create and activate new environment, same except using mamba
`mamba create --name cellprofiler -y python=3.8
`
4. Activate environment
`mamba activate cellprofiler
`
5. Install dependencies from mamba
`mamba install libgfortran==5.0.0.dev0 h5py~=3.6.0 mysqlclient python.app wxpython==4.2
`
6. Install CellProfiler without dependencies (same)
7. Install scikit-image with mamba
`mamba install scikit-image==0.18.3
`
8 Install the rest of the dependencies from pip (same minus scikit-image)
`pip install "boto3>=1.12.28" "cellprofiler-core==4.2.5" "centrosome==1.2.1" "docutils==0.15.2" "imageio>=2.5" "inflect>=2.1"  "Jinja2>=2.11.2" "joblib>=0.13" "mahotas>=1.4" "matplotlib==3.1.3" "Pillow>=7.1.0" "prokaryote==2.4.4"  "python-bioformats==4.0.7" "python-javabridge==4.0.3" "pyzmq~=22.3" "sentry-sdk==0.18.0" "requests>=2.22" "scikit-learn>=0.20" "scipy==1.9.0" "six" "tifffile<2022.4.22" "numpy==1.23"`

After this, I get the following error message, like what is in the Wiki, except adding mysqlclient incompatibility, but so far it hasn't been an issue.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cellprofiler 4.2.5 requires mysqlclient==1.4.6, but you have mysqlclient 2.2.0 which is incompatible.
cellprofiler 4.2.5 requires wxPython==4.1.0, but you have wxpython 4.2.0 which is incompatible.
```

**Comment by alxndrkalinin** [comment]
@nklick thanks for sharing the solution! From you posted, I assume that it could've been solved by installing `scikit-image==0.18.3` with conda instead of pip, because mamba is a drop-in replacement for conda.

**Comment by nklick** [comment]
It's likely conda would have fixed it as well, but mamba uses a different package dependency solver, so I noted it just in case :)
