### ISSUE TITLE
Error during headless run - TypeError: gray2rgb() got an unexpected keyword argument 'alpha'

### ISSUE THREAD

**Issue by sbamin** [CellProfiler/CellProfiler#4597]
**Describe the bug**

Running CellProfiler in headless mode results into `TypeError: gray2rgb() got an unexpected keyword argument 'alpha'`. Pipeline involved batch processing of HCS images, including use of module: GrayToColor

**To Reproduce**
1. Construct CellProfiler workflow that involves use of module: GrayToColor, e.g., processing multi-channel HCS images.
2. Once workflow is successfully running in GUI mode, export it as pipeline with .cppipe extension.
3. Run cellprofiler in headless mode on HPC environment.

```sh
cellprofiler -c -r -p hcs_run1_batch.cppipe -o /fastscratch/foo/cellprofiler/output -i /fastscratch/foo/cellprofiler/input -L 20
```

5. See error

```
TypeError: gray2rgb() got an unexpected keyword argument 'alpha'
```

**Expected behavior**

**Screenshots**

```
(grogu) foo@sumner105:/fastscratch/foo/cellprofiler$ cellprofiler -c -r -p hcs_run1_batch.cppipe -o /fastscratch/foo/cellprofiler/output -i /fastscratch/foo/cellprofiler/input -L 20
Times reported are CPU and Wall-clock times for each module
Mon Jul 25 01:44:44 2022: Image # 1, module Images # 1: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Mon Jul 25 01:44:44 2022: Image # 1, module Metadata # 2: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Error detected during run of module NamesAndTypes
Traceback (most recent call last):
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 976, in run_with_yield
    self.run_module(module, workspace)
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1298, in run_module
    module.run(workspace)
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/modules/namesandtypes.py", line 1940, in run
    self.add_image_provider(
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/modules/namesandtypes.py", line 2003, in add_image_provider
    self.add_simple_image(
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/modules/namesandtypes.py", line 2062, in add_simple_image
    self.add_provider_measurements(provider, m, "Image")
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/modules/namesandtypes.py", line 2076, in add_provider_measurements
    img = provider.provide_image(m)
  File "/hpc/tier1/foo/hpcenv/mambaforge/envs/grogu/lib/python3.8/site-packages/cellprofiler_core/image/abstract_image/file/url/_color_image.py", line 27, in provide_image
    image.pixel_data = skimage.color.gray2rgb(image.pixel_data, alpha=False)
TypeError: gray2rgb() got an unexpected keyword argument 'alpha'
Mon Jul 25 01:44:44 2022: Image # 1, module NamesAndTypes # 3: CPU_time = 1.29 secs, Wall_time = 1.28 secs
```

**Desktop (please complete the following information):**
 - OS: el7.x86_64
 - CellProfiler Version

```
# on Mac OS 10.15.7
4.2.1

# HPC
cellprofiler              4.2.1            py38hec16e2b_2    bioconda
cellprofiler-core         4.2.1              pyhdfd78af_0    bioconda
```

 - Downloaded from the website or installed from source?
 - If the latter, how (cloned, installed from pypi, etc)?

**Additional context**

### Potential bugfix:

I was able to run cellprofiler pipeline without errors after removing `alpha=False` from this file `...lib/python3.8/site-packages/cellprofiler_core/image/abstract_image/file/url/_color_image.py` However, I could not trace path to `_color_image.py` in this repo.

```py
    def provide_image(self, image_set):
        image = URLImage.provide_image(self, image_set)

        if image.pixel_data.ndim == image.dimensions:
            ## 20220725: bugfix - removed alpha=False option as it resulted into
            ## TypeError: gray2rgb() got an unexpected keyword argument 'alpha'
            ## alpha option seems to be absent in recent versions of skimage
            ## https://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.gray2rgb
            image.pixel_data = skimage.color.gray2rgb(image.pixel_data)

        return image
```

**Comment by bethac07** [comment]
Hi,

This is an incompatibility between CellProfiler 4.2.1 and skimage 0.19; your fix is [exactly the right one](https://github.com/CellProfiler/core/pull/99/files). You can bump skimage back to 0.18 until our 4.2.2 release comes out if you need to. Thanks for letting us know!
