### ISSUE TITLE
Measurements file locked to reads on Windows with h5py 3.3+

### ISSUE THREAD

**Issue by TummyPan** [CellProfiler/CellProfiler#4606]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version 4.2.2rc (also on 4.1.3 and 4.2.1)
 - Terminal: PowerShell 7 (x64)
 - Installed from source
 - I followed the steps below:
https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29

**Describe the bug**
I have full permission for my machine. The installation of 4.2.2rc is fine, however, when I tried the example in the Welcome Screen and also the "Human cells" example, both hit the "Failure in analysis startup" error. I've run some diagnosis and it seems that CellProfiler is blocked from accessing an hdf5 file inside ``C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\Cpmeasurementsd3u8adm0.hdf5``. When I open this file, there is nothing useful there.  (I attached an old screenshot here just to illustrate what was inside.)
![Screenshot3](https://user-images.githubusercontent.com/97114518/182398928-fcfadbaa-ba1c-4ca5-a171-2d8d33f34ad8.jpg)

**To Reproduce**
1. Install CellProfiler from source as instructed (clone the latest repo).
2. "Help" -> "Show Welcome Screen" -> "Try Example" -> "Analyze Images"
3. See error:
![Screenshot1](https://user-images.githubusercontent.com/97114518/182396688-63ed5e37-ed68-4d4a-9478-2c12bf556fa3.jpg)

And:
![Screenshot2](https://user-images.githubusercontent.com/97114518/182397252-849ebee8-827e-4f60-b50b-4af0d3e49746.jpg)

**Installed Modules**
```
Package                       Version             Editable project location
----------------------------- ------------------- ----------------------------------------------------------------------------
absl-py                       1.0.0
anyio                         3.5.0
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asn1crypto                    0.24.0
asttokens                     2.0.5
astunparse                    1.6.3
atomicwrites                  1.4.0
attrs                         21.4.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.5
bcrypt                        3.1.6
bleach                        5.0.0
boto3                         1.20.48
botocore                      1.23.48
cachetools                    5.0.0
cellh5                        1.3.0
CellProfiler                  4.2.2rc0            c:\users\tianyi.pan\cellprofiler
cellprofiler-core             4.2.2               c:\users\tianyi.pan\appdata\local\programs\python\python38\lib\site-packages
centrosome                    1.2.1
certifi                       2018.11.29
cffi                          1.15.0
chardet                       3.0.4
charset-normalizer            2.0.11
click                         8.0.3
cloudpickle                   2.0.0
colorama                      0.4.4
configparser                  3.7.1
contextlib2                   0.5.5
coverage                      6.3.2
cPython                       0.0.6
cryptography                  3.3.2
cycler                        0.10.0
dask                          2022.4.0
DateTime                      4.3
debugpy                       1.5.1
decorator                     4.3.2
defusedxml                    0.7.1
deprecation                   2.0.6
dill                          0.3.4
docutils                      0.15.2
entrypoints                   0.4
enum34                        1.1.6
executing                     0.8.3
flatbuffers                   2.0
fsspec                        2022.3.0
future                        0.18.2
gast                          0.5.3
globus-sdk                    3.3.1
google-auth                   2.6.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.43.0
h5py                          3.6.0
hmmlearn                      0.2.6
idna                          2.8
imageio                       2.14.1
imglyb                        2.0.0
importlib-metadata            4.10.1
importlib-resources           5.4.0
inflect                       2.1.0
iniconfig                     1.1.1
ipaddress                     1.0.22
ipykernel                     6.9.1
ipython                       8.1.1
ipython-genutils              0.2.0
javabridge                    1.0.19
jedi                          0.18.1
jgo                           1.0.3
Jinja2                        3.0.3
jmespath                      0.9.3
joblib                        1.1.0
JPype1                        1.3.0
json5                         0.9.6
jsonschema                    4.4.0
jupyter-client                7.1.2
jupyter-core                  4.9.2
jupyter-server                1.13.5
jupyterlab                    3.3.0
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
keras                         2.8.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.0.1
libclang                      13.0.0
libsubmit                     0.5.0
llvmlite                      0.36.0
locket                        0.2.1
lxml                          4.7.1
mahotas                       1.4.5
Markdown                      3.3.6
MarkupSafe                    2.0.1
matplotlib                    3.1.3
matplotlib-inline             0.1.3
microscopeimagequality        0.1.0.dev5
mistune                       0.8.4
mysqlclient                   1.4.6
nbclassic                     0.3.6
nbclient                      0.5.12
nbconvert                     6.4.2
nbformat                      5.1.3
nbstripout                    0.5.0
nest-asyncio                  1.5.4
networkx                      2.2
nose                          1.3.7
notebook                      6.4.8
notebook-shim                 0.1.0
numba                         0.53.0
numpy                         1.23.0
oauthlib                      3.2.0
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.4.0
pandocfilters                 1.5.0
paramiko                      2.4.2
parsl                         1.1.0
parso                         0.8.3
partd                         1.2.0
pathlib                       1.0.1
pickleshare                   0.7.5
Pillow                        9.0.1
pip                           22.2.1
pluggy                        1.0.0
prokaryote                    2.4.4
prometheus-client             0.13.1
prompt-toolkit                3.0.28
protobuf                      3.19.4
psutil                        5.9.0
pure-eval                     0.2.2
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.19
Pygments                      2.11.2
pyimagej                      1.0.2
PyJWT                         2.3.0
pymongo                       4.2.0
PyNaCl                        1.3.0
pyparsing                     2.3.1
pyrsistent                    0.18.1
PySide2                       5.15.2.1
pytest                        6.2.5
pytest-cov                    3.0.0
python-bioformats             4.0.5
python-box                    3.2.4
python-dateutil               2.8.2
python-javabridge             4.0.3
pytz                          2021.3
PyWavelets                    1.2.0
pywin32                       303
pywinpty                      1.1.6
PyYAML                        5.4.1
pyzmq                         22.3.0
raven                         6.10.0
requests                      2.27.1
requests-oauthlib             1.3.1
rsa                           4.8
runipy                        0.1.5
Rynner                        0.0.1
s3transfer                    0.5.1
scikit-image                  0.19.1
scikit-learn                  0.20.2
scipy                         1.8.1
scyjava                       1.4.1
Send2Trash                    1.8.0
sentry-sdk                    0.18.0
setuptools                    56.0.0
shiboken2                     5.15.2.1
six                           1.12.0
sniffio                       1.2.0
stack-data                    0.2.0
tabulate                      0.8.9
tblib                         1.7.0
tensorboard                   2.8.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.8.0
tensorflow-io-gcs-filesystem  0.24.0
termcolor                     1.1.0
terminado                     0.13.3
testpath                      0.6.0
tf-estimator-nightly          2.8.0.dev2021122109
threadpoolctl                 3.1.0
tifffile                      2022.2.2
timeago                       1.0.9
toml                          0.10.2
tomli                         2.0.1
toolz                         0.9.0
tornado                       6.1
traitlets                     5.1.1
typeguard                     2.13.3
typing_extensions             4.0.1
urllib3                       1.26.8
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.3.1
Werkzeug                      2.0.2
wheel                         0.37.1
wrapt                         1.13.3
wxPython                      4.1.0
xarray                        0.21.1
zipp                          3.7.0
zope.interface                5.4.0
```
Apologies for the long list as some of them are not relevant to CellProfiler.

**Additional context**
I've also tried CellProfiler 4.2.1 and 4.3.1 using the exact source code from the Previous Release as some others suggested in another ticket (i.e. #4525). Both hit the same error. Please let me know if you need any more info. Thanks!

**Comment by bethac07** [comment]
Thank you for letting us know! We just came across this yesterday in our built 4.2.2rc version as well and were wondering if it was something in the build process, so it's super helpful to know you're seeing it in source too.

If you go into the preferences menu, scroll down near the bottom, and then change the "Temporary folder" option to something like your Desktop, does that make the issue go away? Thanks!

**Comment by TummyPan** [comment]
Hi, thanks for your reply. The error still persists after changing the "Temporary folder" to either my home directory or my Desktop. Interestingly, "Temporary folder" always changes back to ``C:\Users\MYUSERNAME\AppData\Local\Temp``, I am sure that I clicked the "Save" button.

**Comment by bethac07** [comment]
So I've been able to trace this to [this line](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/utilities/hdf5_dict.py#L389-L390) in our hdf5_dict utility. It tries to read the file, then barfs. 
It's something to do with the file locking, because if I set the new-in-3.5 [locking parameter](https://docs.h5py.org/en/stable/high/file.html#h5py.File) when we [make the h5py File](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/utilities/hdf5_dict.py#L191), then all the tests pass. This doesn't feel like a good solution to me, though, because presumably there ARE times where we very much do want to lock. 

I'm still not sure why now, why only on Windows, and why only in Analysis mode rather than test mode.

**Comment by bethac07** [comment]
I'm assuming we don't want at this juncture to post the full failure traces for all 24, but here it is just for the first one.
```
====================================================== FAILURES =======================================================
_______________________________________ TestAnalysis.test_01_01_start_and_stop ________________________________________

self = <tests.analysis.test_analysis.TestAnalysis testMethod=test_01_01_start_and_stop>

    def test_01_01_start_and_stop(self):
        logger.debug(
            "Entering %s" % inspect.getframeinfo(inspect.currentframe()).function
        )
>       self.make_pipeline_and_measurements_and_start()

..\core\tests\analysis\test_analysis.py:327:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\core\tests\analysis\test_analysis.py:299: in make_pipeline_and_measurements_and_start
    self.analysis = Analysis(pipeline, m)
..\core\cellprofiler_core\analysis\_analysis.py:43: in __init__
    self.initial_measurements_buf = initial_measurements.file_contents()
..\core\cellprofiler_core\measurement\_measurements.py:212: in file_contents
    return self.hdf5_dict.file_contents()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cellprofiler_core.utilities.hdf5_dict.HDF5Dict object at 0x00000231F215E730>

    def file_contents(self):
        with self.lock:
            self.flush()
            print("file_contents", self.filename,os.path.exists(self.filename))
            #import IPython
            #IPython.embed()
            with open(self.filename, "rb+") as f:
>               return memoryview(f.read())
E               PermissionError: [Errno 13] Permission denied

..\core\cellprofiler_core\utilities\hdf5_dict.py:395: PermissionError
```

**Comment by bethac07** [comment]
Nothing jumps out to me in the [3.2.1 to 3.3 diff](https://github.com/h5py/h5py/compare/3.2.1...3.3.0) , but I'll be the first to admit that a) it's late and b) not a library I'm super familiar with .

**Comment by bethac07** [comment]
@TummyPan It looks to me like you're running Python 3.8; you may be able to patch this for now for yourself by bumping back h5py to 3.2.1 .

**Comment by TummyPan** [comment]
Hi Beth, 

Thanks for testing this issue. I traced to ``hdf5_dict.py`` and then added ``breakpoint()`` to find out it did not have permission to access a temporary file (e.g. ``Cpmeasurementsd3u8adm0.hdf5``). Sorry that I did not mention this in the first place.

Yes, I am running Python 3.8.10. I've attempted to downgrade ``h5py`` to 3.2.1, I also changed the version of ``h5py`` in ``setup.py`` for both ``cellprofiler 4.2.2rc0`` and ``cellprofiler-core-4.2.2``, however, I got this error during installation from source:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cellprofiler 4.2.2rc0 requires h5py~=3.6.0, but you have h5py 3.2.1 which is incompatible.
Successfully installed cellprofiler-core-4.2.2
```

I ignored this and tried to launch CellProfiler, then I got this:

```
PS C:\Users\tianyi.pan\CellProfiler\core> cellprofiler
Traceback (most recent call last):
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (h5py 3.2.1 (c:\users\tianyi.pan\appdata\local\programs\python\python38\lib\site-packages), Requirement.parse('h5py~=3.6.0'), {'CellProfiler'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\Scripts\cellprofiler-script.py", line 33, in <module>
    sys.exit(load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')())
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\Scripts\cellprofiler-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\tianyi.pan\cellprofiler\cellprofiler\__main__.py", line 17, in <module>
    import pkg_resources
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Users\tianyi.pan\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'h5py~=3.6.0' distribution was not found and is required by CellProfiler
```

If you could tell me how to correctly modify the requirement of ``h5py``, I'll be very grateful. Thanks.

**Comment by TummyPan** [comment]
Update:

I tried it again a few minutes ago using ``pip install -e .`` to install ``cellprofiler 4.2.2rc``. There was no dependencies conflict error at this time, CellProfiler is launchable. I also tried the example in the Welcome Screen, no ``[Errno 13] Permission denied`` error, and it can quickly process the example and produce the results as expected.

Versions of some typical packages:

```
Package                       Version             Editable project location
----------------------------- ------------------- -------------------------------------
...
CellProfiler                  4.2.2rc0            c:\users\...\cellprofiler
cellprofiler-core             4.2.2               c:\users\...\cellprofiler\core
h5py                          3.2.1
javabridge                    1.0.19
numpy                         1.23.0
pyzmq                         22.3.0
wxPython                      4.1.0
...
```

I will reproduce a clean installation later today. If there will be no issue, I'll close my ticket then.

**Comment by bethac07** [comment]
It would be great if we can leave this open until we fully trace the underlying issue, though of course feel free to unsubscribe from notifications on this thread :)

**Comment by bethac07** [comment]
Closed in https://github.com/CellProfiler/core/pull/112
