### ISSUE TITLE
ExportToSpreadsheet: TypeError: '>=' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#4653]
**Describe the bug**
Running the attached pipeline/images yields the following error at ExportToSpreadsheet:
```
Failed to complete post_run processing for module ExportToSpreadsheet.
Traceback (most recent call last):
  File "cellprofiler_core\pipeline\_pipeline.py", line 1527, in post_run
  File "cellprofiler\modules\exporttospreadsheet.py", line 859, in post_run
  File "cellprofiler\modules\exporttospreadsheet.py", line 927, in run_objects
  File "cellprofiler\modules\exporttospreadsheet.py", line 1409, in make_object_file
  File "<__array_function__ internals>", line 180, in amax
  File "numpy\core\fromnumeric.py", line 2793, in amax
  File "numpy\core\fromnumeric.py", line 86, in _wrapreduction
TypeError: '>=' not supported between instances of 'NoneType' and 'NoneType'
```
**Desktop (please complete the following information):**
 - OS: Windows
 - CellProfiler Version 4.2.4
 - Downloaded from the website
 
I've tried to come up with a more minimal example but seem to be unable to do so.
Due to size constraints, I had to break up the images into two zip; the images from both are to be loaded through the Images module.
 
[images_01.zip](https://github.com/CellProfiler/CellProfiler/files/9775471/images_01.zip)
[images_02.zip](https://github.com/CellProfiler/CellProfiler/files/9775472/images_02.zip)
[github_pipeline.zip](https://github.com/CellProfiler/CellProfiler/files/9775485/github_pipeline.zip)

**Comment by bethac07** [comment]
This is the behavior that past-Mark asked for in the case of "Ignore flag skips on last cycle" :) . 

https://github.com/CellProfiler/CellProfiler/issues/310#issuecomment-557348273

**Comment by bethac07** [comment]
(Or, at least, that's how past-Beth interpreted past-Mark, which she might have done incorrectly!)

**Comment by braymp** [comment]
Revised the original report and included pipeline + images.
