### ISSUE TITLE
 math domain error in MeasureObjectSizeAndShape

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4663]
H/T [the forum](https://forum.image.sc/t/cellprofiler-math-domain-error-on-3d-measureobjectsizeshape/73302?u=bcimini)

---
User has an issue with MeasureObjectSizeAndShape with one object class in his pipeline - Cells and Nuclei are fine, but if he includes his mitochondria, we get the stack trace below. I reproduced on 4.2.4 built and source.

It's an "axis minor length error" and mito are small and stringy, so my initial suspicion was that Watershed was generating an object of 0 pixels or something like that, but I think I've ruled that out by checking with FilterObjects for mito objects that get filtered out by a minimum IntegratedIntensity of something like 0.00001; nothing does get filtered out so I suspect it's not that. 

**To Reproduce**
[3Dtest.zip](https://github.com/CellProfiler/CellProfiler/files/9932433/3Dtest.zip)

**Desktop (please complete the following information):**
 - OP based on file names was using Windows, Mac 4.2.4 built and source for me.

**Additional context**
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/cellprofiler/gui/pipelinecontroller.py", line 3390, in do_step
    self.__pipeline.run_module(module, workspace_model)
  File "/opt/homebrew/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1341, in run_module
    module.run(workspace)
  File "/opt/homebrew/lib/python3.8/site-packages/cellprofiler/modules/measureobjectsizeshape.py", line 527, in run
    self.run_on_objects(object_name, workspace)
  File "/opt/homebrew/lib/python3.8/site-packages/cellprofiler/modules/measureobjectsizeshape.py", line 590, in run_on_objects
    features_to_record = self.analyze_objects(objects, desired_properties)
  File "/opt/homebrew/lib/python3.8/site-packages/cellprofiler/modules/measureobjectsizeshape.py", line 773, in analyze_objects
    props = skimage.measure.regionprops_table(
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/measure/_regionprops.py", line 996, in regionprops_table
    return _props_to_dict(
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/measure/_regionprops.py", line 807, in _props_to_dict
    column_buffer[i] = regions[i][prop]
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/measure/_regionprops.py", line 675, in __getitem__
    value = getattr(self, key, None)
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/measure/_regionprops.py", line 526, in axis_minor_length
    return sqrt(10 * (-ev[0] + ev[1] + ev[2]))
ValueError: math domain error
```

**Comment by Mas515** [comment]
Hi Beth, sorry I am finally getting around to it. Here is my pipeline giving a similar error and example data (blood vessels segmentation) https://drive.google.com/drive/folders/1nA6c3g39qvM7buJx_hBcscmlrX4T8AmA?usp=share_link 

I was using CP 4.2.4 but not from source.

**Comment by mccruz07** [comment]
Apparently the Math error we’re seeing here is coming from the axis_minor_length function inside regionprop.py from scikit-image. The return value of this function should be a sqrt(10 * (-ev[0] + ev[1] + ev[2])). But In fact, minor_axis_length calls internally _moments.inertia_tensor_eigvals, with dependency to _moments.inertia_tensor, _moments.moments_central and finally _moments.centroid which could result in values <1 causing the sqrt Math Domain Error for 1 pixel objects as mentioned in this scikit-image open issue from 2017 (https://github.com/scikit-image/scikit-image/issues/2792). 

To solve the issue they suggest clipping the the result to 1.

**Comment by mccruz07** [comment]
Hi @bethac07,
Marine and I looked again in to this issue and downgrading scikit-image to <0.19 solves the problem.
