### ISSUE TITLE
Error while processing NamesAndTypes: (Worker) ValueError: the input array must have size 3 along 'channel_axis”

### ISSUE THREAD

**Issue by mccruz07** [CellProfiler/CellProfiler#4686]
Related with the forum error: 

https://forum.image.sc/t/error-while-processing-namesandtypes-worker-valueerror-the-input-array-must-have-size-3-along-channel-axis-got-1110-1641-4/73128

**Describe the bug**
Error trying to import a specific color image (4channels) as a grayscale image in CP 4.2.4
Ps. this error doesn't appear in CP4.2.1 or in CP5.0.0b1

**To Reproduce**
1. Go to CellProfiler
2. Load the example image [here ](https://forum.image.sc/t/error-while-processing-namesandtypes-worker-valueerror-the-input-array-must-have-size-3-along-channel-axis-got-1110-1641-4/73128)
3. In NamesAndTypes - Select the image type as grayscale
4.  Start the test mode
5. See error

**Screenshots**

<img width="992" alt="Screen Shot 2022-12-05 at 1 47 53 PM" src="https://user-images.githubusercontent.com/52753134/205717948-d35762df-3a9e-460d-a159-2b76e4fd92e9.png">

**Desktop (please complete the following information):**
 - CellProfiler Version [4.2.4]
 - Downloaded from the website or from github 

**Additional context**

**Comment by bethac07** [comment]
The provided test image is weiiiiiiird - it seems to have a 4th channel that is a masking channel (see below) which is non-standardly applied - Fiji and skimage both only think it has 3 channels (Fiji thinks the type is RGB, and when you split the channels, it splits to 3); this is why skimage (not CellProfiler) is barfing when trying to handle it. When I made a composite Cell Painting image containing 4 or 5 channels,  it set it to grayscale just fine - those plus the forum-provided image attached.

Laura already asked the person for more details and they declined to provide them, so I think I'm fine declaring "weird image" rather than CellProfiler bug. If we get more details about this happening in an image type we want to support, I'm happy to reopen.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/6721515/207449837-6aba7d40-c8be-4985-9de2-0b47b404df05.png">

```
Multichannel display is only supported for RGB (3-channel) data. Input image has 4 channels. The first 3 channels are displayed as RGB.
Failed to run module NamesAndTypes
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 3390, in do_step
    self.__pipeline.run_module(module, workspace_model)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/pipeline/_pipeline.py", line 1341, in run_module
    module.run(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/modules/namesandtypes.py", line 1931, in run
    self.add_image_provider(workspace, name, load_choice, rescale, image_set[0])
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/modules/namesandtypes.py", line 2003, in add_image_provider
    self.add_simple_image(
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/modules/namesandtypes.py", line 2062, in add_simple_image
    self.add_provider_measurements(provider, m, "Image")
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/modules/namesandtypes.py", line 2076, in add_provider_measurements
    img = provider.provide_image(m)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/image/abstract_image/file/url/_monochrome_image.py", line 36, in provide_image
    image.pixel_data = skimage.color.rgb2gray(image.pixel_data)
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/_shared/utils.py", line 394, in fixed_func
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/color/colorconv.py", line 875, in rgb2gray
    rgb = _prepare_colorarray(rgb)
  File "/opt/homebrew/lib/python3.8/site-packages/skimage/color/colorconv.py", line 140, in _prepare_colorarray
    raise ValueError(msg)

ValueError: the input array must have size 3 along `channel_axis`, got (1110, 1641, 4)

```
[Issues4686.zip](https://github.com/CellProfiler/CellProfiler/files/10222331/Issues4686.zip)
