### ISSUE TITLE
Error message when running with conda

### ISSUE THREAD

**Issue by u95306** [CellProfiler/CellProfiler#4688]
I used the files posted [here](https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation) to install cellprofiler4, but when I run it on conda, it runs with an error message.

> (cp) [user@srvd1 ~/Cellprofiler]$ cellprofiler
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/cp/bin/cellprofiler", line 5, in <module>
    from cellprofiler.__main__ import main
  File "/home/user/anaconda3/envs/cp/lib/python3.8/site-packages/cellprofiler/__main__.py", line 13, in <module>
    import bioformats.formatreader
  File "/home/user/anaconda3/envs/cp/lib/python3.8/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/home/user/anaconda3/envs/cp/lib/python3.8/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/home/user/anaconda3/envs/cp/lib/python3.8/site-packages/javabridge/jutil.py", line 162, in <module>
    import javabridge._javabridge as _javabridge
ImportError: libjvm.so: cannot open shared object file: No such file or directory

**Comment by braymp** [comment]
A possible duplicate of this issue? https://github.com/CellProfiler/CellProfiler/issues/3597
