### ISSUE TITLE
Names and type - calling Images using a Metadata column

### ISSUE THREAD

**Issue by Mas515** [CellProfiler/CellProfiler#4692]
Link to the pipeline and example data 

https://drive.google.com/drive/folders/1l2w_RMn3fm9fr_9zwSYHKmxGQFy6KOB3?usp=share_link

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/80129123/206732121-18e10086-facf-4972-86f4-cb28bed2285a.png">

Traceback (most recent call last):
  File "/Users/secchim/cp_jamboree/CellProfiler/cellprofiler/gui/module_view/_filter_panel_controller.py", line 245, in <lambda>
Resetting dropped connection: sentry.io
    lambda event: self.on_predicate_changed(event, index, address),
  File "/Users/secchim/cp_jamboree/CellProfiler/cellprofiler/gui/module_view/_filter_panel_controller.py", line 258, in on_predicate_changed
    while len(sequence) <= index:
TypeError: object of type 'DoesPredicate' has no len()
https://sentry.io:443 "POST /api/152399/store/ HTTP/1.1" 200 41

**Comment by bethac07** [comment]
This is a jamboree-branch issue, not master
