### ISSUE TITLE
ExportToDatabase issue when writing particular channels to a properties file

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4717]
**Describe the bug**
H/T @sugan89!

When using ExportToDatabase in a situation where the user wants to specify which channels are used in the properties file and/or which color they're assigned (aka where `Include information for all images, using default values?` is No), in certain circumstances, ExportToDatabase failed with the stack trace below. It turns out it's due to not checking in that part of the code path whether the `"ExportToDb", "ExportToDb_Channels"` measurement was made - that measurement was added in #4396 . As far as I can tell, this measurement IS correctly written into the measurement tables during the run, but in the post_run (where the properties file is made, it's done. No idea why. I _assume_ we tested at the time that #4396 worked, but I can't get it to work in a couple of test cases in my hands.

**To Reproduce**
Run the QC tutorial at tutorials.cellprofiler.org

**Screenshots**
![image](https://user-images.githubusercontent.com/6721515/214383405-adeb7cb2-907e-45f9-b479-c58b610425b8.png)

**Desktop (please complete the following information):**
OSX 12.6, 4.2.4&4.2.5 built, 4.2.x source branch; Windows 4.2.5 built

**Additional context**
```
Failed to complete post_run processing for module ExportToDatabase.
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/pipeline/_pipeline.py", line 1535, in post_run
    module.post_run(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 2857, in post_run
    self.write_properties_file(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 4148, in write_properties_file
    all_properties = self.get_property_file_text(workspace)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 4421, in get_property_file_text
    channels_list = workspace.measurements.get_measurement("ExportToDb", "ExportToDb_Channels")
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/measurement/_measurements.py", line 854, in get_measurement
    vals = self.hdf5_dict[object_name, feature_name, image_set_number]
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/utilities/hdf5_dict.py", line 430, in __getitem__
    result = self[object_name, feature_name, [num_idx]]
  File "/Users/bcimini/Documents/GitHub/CellProfiler/core/cellprofiler_core/utilities/hdf5_dict.py", line 435, in __getitem__
    assert feature_exists, "Feature {} for {} does not exist".format(
AssertionError: Feature ExportToDb_Channels for ExportToDb does not exist
```

**Comment by bethac07** [comment]
I made and closed a PR, #4716, that avoided the barf, but it still never gets the measurement passed through - I'd like to fix that

**Comment by bethac07** [comment]
```
    def get_property_file_text(self, workspace):
        """Get the text for all property files

        workspace - the workspace from prepare_run
```

Oh, that would do it....

**Comment by bethac07** [comment]
I spent a couple hours in the code base, and I don't fully understand why the property file text needs to be coming from the prepare_run version of the workspace, but I guess that's how it currently works.

Given that a) I'm not sure this ever worked to actually record multichannel image sizes correctly (@DavidStirling, feel free to prove me wrong) and that b) [we plan to separate database and property file writing](https://github.com/CellProfiler/CellProfiler/discussions/4714), I'm tempted to just patch-fix 4.2.5 with #4716 and call it a day. Thoughts?

**Comment by DavidStirling** [comment]
This probably arose from #4396, which in itself was a hacky attempt to solve problems with a bad system.

To generate the properties file correctly, we need to know how many channels each selected image contains. CellProfiler insists on creating the properties file in the pre-run phase and the post-run phases. In both of these phases we have access to the image names, but not their dimensionality. Conversely, during the run we have access to the image dimensionality but can't write experiment-level measurements. The solution here was to store the requested image names as an experiment measurement and then call them back during the run to note the image dimensionality as another, hidden measurement.

I'd tried to make the ExportToDb measurement group used for this into a distinct set of measurements that never get exported, but it looks like some segments of code are lacking that exclusion. Sorry!

**Comment by bethac07** [comment]
Yup @DavidStirling , that matches with my understanding. Do you happen to recall if it ever actually worked to record the multichannel image dimensionalities? The example case I'm testing with is always setting channel numbers as 1,1,1, etc, no matter that they are correctly identified in your record_ code as RGB. I likely won't do _much_ more to try to fix this, but if you recall it was creating the correct property files, I might spend another hour or so. Otherwise, I think the effort is better spent on writing a better module!

**Comment by DavidStirling** [comment]
I believe it worked, but it's possible some combinations aren't detected properly or something. The idea of having a distinct CPA properties generator module does sound like a much better solution to begin with, so perhaps don't spend much time on it.
