### ISSUE TITLE
Deprecated arugment names prevent MeasureGranularity module from running in CellProfilerv4.2.4 with current pip install

### ISSUE THREAD

**Issue by jenna-tomkinson** [CellProfiler/CellProfiler#4767]
**Describe the bug**
I have noticed that this change for this error has been made for [MeasureGranularity.py](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/measuregranularity.py), with my recent pip install of CellProfiler this past week, the issue with the deprecated argument names as impacted my pipeline. 

This is what the error I am getting in my log file is:
```
Error detected during run of module MeasureGranularity
Traceback (most recent call last):
  File "/Users/tomkinsj/opt/anaconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1008, in run_with_yield
    self.run_module(module, workspace)
  File "/Users/tomkinsj/opt/anaconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1341, in run_module
    module.run(workspace)
  File "/Users/tomkinsj/opt/anaconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/cellprofiler/modules/measuregranularity.py", line 251, in run
    statistic = self.run_on_image_setting(workspace, image_name)
  File "/Users/tomkinsj/opt/anaconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/cellprofiler/modules/measuregranularity.py", line 342, in run_on_image_setting
    back_pixels = skimage.morphology.erosion(back_pixels_mask, selem=selem)
  File "/Users/tomkinsj/opt/anaconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/skimage/morphology/misc.py", line 38, in func_out
    return func(image, footprint=footprint, *args, **kwargs)
TypeError: erosion() got an unexpected keyword argument 'selem'
```

**To Reproduce**
To reproduce this behavior, I have pip-installed CellProfilerv4.2.4 using a conda environment where I do not specify the version of `scikit-image` using conda-forge.

**Expected behavior**
Started to run a pipeline using MeasureGranularity, and it produced the error above.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - CellProfiler Version 4.2.4
 - Installed from source
 - Installed from pypi in conda environment

**Additional context**
There is already a solution I have for this which is to specify the version of scikit-image in the conda environment to v0.19.3 which is the last version to work. But for current users, it would probably be best for the pip install requirements to prevent the v0.20.0 to be installed.

**Comment by callum-jpg** [comment]
If you're installing your own version of skimage alongside CellProfiler 4.2.X, you'll have to make sure it's a version lower than 0.20 (`pip install cellprofiler` should install the right version of skimage and avoid this problem). Skimage removed `selem` in favour of `footprint`, as seen in the latest release notes: https://scikit-image.org/docs/stable/release_notes.html

If installing CellProfiler from github, the changes have already been made to change `selem` to `footprint` in #4741.
