### ISSUE TITLE
Failed to install cellprofiler in windows 10 with pip or conda

### ISSUE THREAD

**Issue by zoccoler** [CellProfiler/CellProfiler#4775]
**Desktop:**
 - OS: Windows 10
 - CellProfiler Version 4.2.5
 - Downloaded from the website or installed from source? from source with `pip` and `conda`
 - If the latter, how (cloned, installed from pypi, etc)? 
 
**Describe the issue**
I created a conda environment with just python 3.8 and then ran `pip install cellprofiler==4.2.5`. It failed to install (see error message below)

**Error message**

<details><summary>Click me</summary>

```python
pip install cellprofiler==4.2.5
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting cellprofiler==4.2.5
  Downloading CellProfiler-4.2.5-py3-none-any.whl (24.9 MB)
     ---------------------------------------- 24.9/24.9 MB 3.8 MB/s eta 0:00:00
Collecting boto3>=1.12.28 (from cellprofiler==4.2.5)
  Downloading boto3-1.26.130-py3-none-any.whl (135 kB)
     ---------------------------------------- 135.6/135.6 kB 7.8 MB/s eta 0:00:00
Collecting cellprofiler-core==4.2.5 (from cellprofiler==4.2.5)
  Downloading cellprofiler_core-4.2.5-py3-none-any.whl (554 kB)
     ---------------------------------------- 555.0/555.0 kB 2.9 MB/s eta 0:00:00
Collecting centrosome==1.2.1 (from cellprofiler==4.2.5)
  Downloading centrosome-1.2.1.tar.gz (619 kB)
     ---------------------------------------- 619.6/619.6 kB 4.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting docutils==0.15.2 (from cellprofiler==4.2.5)
  Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
     ---------------------------------------- 547.6/547.6 kB 1.8 MB/s eta 0:00:00
Collecting h5py~=3.6.0 (from cellprofiler==4.2.5)
  Downloading h5py-3.6.0-cp38-cp38-win_amd64.whl (2.8 MB)
     ---------------------------------------- 2.8/2.8 MB 2.2 MB/s eta 0:00:00
Collecting imageio>=2.5 (from cellprofiler==4.2.5)
  Downloading imageio-2.28.1-py3-none-any.whl (3.4 MB)
     ---------------------------------------- 3.4/3.4 MB 2.8 MB/s eta 0:00:00
Collecting inflect>=2.1 (from cellprofiler==4.2.5)
  Downloading inflect-6.0.4-py3-none-any.whl (34 kB)
Collecting Jinja2>=2.11.2 (from cellprofiler==4.2.5)
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.1/133.1 kB 2.6 MB/s eta 0:00:00
Collecting joblib>=0.13 (from cellprofiler==4.2.5)
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ---------------------------------------- 298.0/298.0 kB 2.6 MB/s eta 0:00:00
Collecting mahotas>=1.4 (from cellprofiler==4.2.5)
  Downloading mahotas-1.4.13-cp38-cp38-win_amd64.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 3.4 MB/s eta 0:00:00
Collecting matplotlib==3.1.3 (from cellprofiler==4.2.5)
  Downloading matplotlib-3.1.3-cp38-cp38-win_amd64.whl (9.1 MB)
     ---------------------------------------- 9.1/9.1 MB 4.1 MB/s eta 0:00:00
Collecting mysqlclient==1.4.6 (from cellprofiler==4.2.5)
  Downloading mysqlclient-1.4.6-cp38-cp38-win_amd64.whl (263 kB)
     ---------------------------------------- 263.1/263.1 kB 4.0 MB/s eta 0:00:00
Collecting numpy>=1.20.1 (from cellprofiler==4.2.5)
  Downloading numpy-1.24.3-cp38-cp38-win_amd64.whl (14.9 MB)
     ---------------------------------------- 14.9/14.9 MB 5.5 MB/s eta 0:00:00
Collecting Pillow>=7.1.0 (from cellprofiler==4.2.5)
  Downloading Pillow-9.5.0-cp38-cp38-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 4.5 MB/s eta 0:00:00
Collecting prokaryote==2.4.4 (from cellprofiler==4.2.5)
  Downloading prokaryote-2.4.4.tar.gz (84.2 MB)
     ---------------------------------------- 84.2/84.2 MB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting python-bioformats==4.0.7 (from cellprofiler==4.2.5)
  Downloading python_bioformats-4.0.7-py3-none-any.whl (40.6 MB)
     ---------------------------------------- 40.6/40.6 MB 3.7 MB/s eta 0:00:00
Collecting python-javabridge==4.0.3 (from cellprofiler==4.2.5)
  Downloading python-javabridge-4.0.3.tar.gz (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mazo260d\AppData\Local\Temp\pip-install-7mwt89f6\python-javabridge_fc2524a018e54ffeac933c3db225dee8\setup.py", line 412, in <module>
          ext_modules=ext_modules(),
        File "C:\Users\mazo260d\AppData\Local\Temp\pip-install-7mwt89f6\python-javabridge_fc2524a018e54ffeac933c3db225dee8\setup.py", line 96, in ext_modules
          java_home = find_javahome()
        File "C:\Users\mazo260d\AppData\Local\Temp\pip-install-7mwt89f6\python-javabridge_fc2524a018e54ffeac933c3db225dee8\javabridge\locate.py", line 181, in find_javahome
          raise RuntimeError(
      RuntimeError: Failed to find the Java Runtime Environment. Please download and install the Oracle JRE 1.6 or later
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

I also tried a suggested conda installation from the yaml file [here](https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation#cellprofiler-4) and it also failed:

**Error message**

```python
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - mysqlclient=1.4.4
  - gtk2
```

**Comment by gnodar01** [comment]
Did you try consulting the windows installation instructions here: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29

From the error it seems as though the Java installation was not found. Either because it's not installed, or the environment variables are not set.

If that doesn't help, it may be the lack of build tools, Visual C++. 

If you've tried all of the above, please let us know and we'll dig further.
