### ISSUE TITLE
v4.2.1 MySQLdb attribute error escape_string

### ISSUE THREAD

**Issue by ptrebert** [CellProfiler/CellProfiler#4792]
Hi,

**Describe the bug**
`AttributeError: module 'MySQLdb' has no attribute 'escape_string'`

**To Reproduce**
Test run on small dataset with all default CLI parameters (should be shareable upon request)

**Expected behavior**
No error

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: CentOS
 - CellProfiler Version: 4.2.1 installed via bioconda / pipeline file created with 4.2.4

**Additional context**
Full error trace:

```
1 JVM will be started with AWT in headless mode
2 Creating JVM object
3 Signalling caller
4 Enabled Bio-formats directory cacheing
5 Created temporary file /var/tmp/pbs.7853514.hpc-batch/Cpmeasurementsrlbms9_1.hdf5
6 /[...]/projects/test-cellprofiler/exenv/bin/cellprofiler: (10 <module>): sys.exit(main())
7 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/__main__.py: (267 main): exit_code = run_pipeline_headless(options, args)
8 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/__main__.py: (820 run_pipeline_headless): initial_measurements = load_measurements(
9 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler_core/utilities/measurement.py: (74 load_measurements): m = Measurements(
10 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler_core/measurement/_measurements.py: (109 __init__): for frame in traceback.extract_stack():
11 HDF5Dict.__init__(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurementsrlbms9_1.hdf5, temporary=True, copy=<HDF5 group "/Measurements/2021-10-21-11-10-30" (2 members)>, mode=w
12 Creating converter from 3 to 5
13 Your pipeline version is 424 but you are running CellProfiler version 421. Loading this pipeline may fail or have unpredictable results.
14 Created temporary file /var/tmp/pbs.7853514.hpc-batch/Cpmeasurements45xki6mu.hdf5
15 /[...]/projects/test-cellprofiler/exenv/bin/cellprofiler: (10 <module>): sys.exit(main())
16 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/__main__.py: (267 main): exit_code = run_pipeline_headless(options, args)
17 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/__main__.py: (892 run_pipeline_headless): measurements = pipeline.run(
18 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py: (700 run): measurements = Measurements(
19 /[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler_core/measurement/_measurements.py: (109 __init__): for frame in traceback.extract_stack():
20 HDF5Dict.__init__(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurements45xki6mu.hdf5, temporary=True, copy=<HDF5 group "/Measurements/2023-07-26-14-07-30" (2 members)>, mode=w
21 Creating converter from 5 to 3
22 HDF5Dict.flush(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurements45xki6mu.hdf5, temporary=True
23 Failed to prepare run for module ExportToDatabase
24 Traceback (most recent call last):
25   File "/[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1368, in prepare_run
26     not module.prepare_run(workspace)
27   File "/[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/modules/exporttodatabase.py", line 2457, in prepare_run
28     self.create_database_tables(self.cursor, workspace)
29   File "/[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/modules/exporttodatabase.py", line 3104, in create_database_tables
30     for statement in self.get_experiment_table_statements(workspace):
31   File "/[...]/projects/test-cellprofiler/exenv/lib/python3.8/site-packages/cellprofiler/modules/exporttodatabase.py", line 3155, in get_experiment_table_statements
32     MySQLdb.escape_string(self.experiment_name.value).decode(),
33 AttributeError: module 'MySQLdb' has no attribute 'escape_string'
34 HDF5Dict.flush(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurements45xki6mu.hdf5, temporary=True
35 HDF5Dict.flush(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurements45xki6mu.hdf5, temporary=True
36 HDF5Dict.__del__(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurements45xki6mu.hdf5, temporary=True
37 HDF5Dict.__del__(): /var/tmp/pbs.7853514.hpc-batch/Cpmeasurementsrlbms9_1.hdf5, temporary=True
```

Best,
Peter

P.S.: if the first question is if that bug also occurs with 4.2.5, I would have to reply by asking when 4.2.5 will be available via bioconda, which is the most straightforward way of setting up software on our isolated infrastructure :-)

**Comment by kavkat** [comment]
Facing the same issue with CellProfiler 4.2.6.
Working with Visual Studio Code on Puhti infrastructure, with a containerised conda environment. 
Tried manual import of MySQLdb module, the error is still present. Any solutions yet?

Here's a copy of my error messages:
Experiment-wide values for mean threshold, etc calculated by MeasureImageQuality may be incorrect if the run is split into subsets of images.
Experiment-wide values for mean threshold, etc calculated by MeasureImageQuality may be incorrect if the run is split into subsets of images.
Failed to prepare run for module ExportToDatabase
Traceback (most recent call last):
  File "/PUHTI_TYKKY_FqLqZeJ/miniconda/envs/env1/lib/python3.10/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1427, in prepare_run
    not module.prepare_run(workspace)
  File "/PUHTI_TYKKY_FqLqZeJ/miniconda/envs/env1/lib/python3.10/site-packages/cellprofiler/modules/exporttodatabase.py", line 2457, in prepare_run
    self.create_database_tables(self.cursor, workspace)
  File "/PUHTI_TYKKY_FqLqZeJ/miniconda/envs/env1/lib/python3.10/site-packages/cellprofiler/modules/exporttodatabase.py", line 3104, in create_database_tables
    for statement in self.get_experiment_table_statements(workspace):
  File "/PUHTI_TYKKY_FqLqZeJ/miniconda/envs/env1/lib/python3.10/site-packages/cellprofiler/modules/exporttodatabase.py", line 3155, in get_experiment_table_statements
    MySQLdb.escape_string(self.experiment_name.value).decode(),
AttributeError: module 'MySQLdb' has no attribute 'escape_string'

![A36A1CF5-6236-4C58-B5AC-D2B3798A9CEB_1_201_a](https://github.com/CellProfiler/CellProfiler/assets/133776843/498267ba-1cde-481a-a7be-167ec05eba45)
