### ISSUE TITLE
cython version for cellprofiler 4.2.5

### ISSUE THREAD

**Issue by sunyi000** [CellProfiler/CellProfiler#4795]
The new release of Cython 3.0.0 introduced error for Cellprofiler 4.2.5 installation. 

Install an older version of Cython 0.29.32 fixed the error below.

It seems to me that we need to pin Cython or centrosome version?

the same issue is also mentioned [here](https://forum.image.sc/t/issue-with-centrosome-while-installing-cellprofiler4-2-5-on-ubuntu22-04/83982) 

Thank you

```

Error compiling Cython file:
      ------------------------------------------------------------
      ...
            heap.ptrs[child][k] = new_elem[k]
        heap.items += 1
      
        # restore heap invariant, all parents <= children
        while child>0:
            parent = (child + 1) / 2 - 1 # __parent(i)
                                     ^
      ------------------------------------------------------------
 centrosome/heap.pxd:148:31: Cannot assign type 'double' to 'unsigned int'
      Compiling centrosome/_propagate.pyx because it changed.
      Compiling centrosome/_convex_hull.pyx because it changed.
      Compiling centrosome/_cpmorphology2.pyx because it changed.
      Compiling centrosome/_fastemd.pyx because it changed.
      Compiling centrosome/_filter.pyx because it changed.
      Compiling centrosome/_lapjv.pyx because it changed.
      [1/6] Cythonizing centrosome/_convex_hull.pyx
      [2/6] Cythonizing centrosome/_cpmorphology2.pyx
      [3/6] Cythonizing centrosome/_fastemd.pyx
      [4/6] Cythonizing centrosome/_filter.pyx
      [5/6] Cythonizing centrosome/_lapjv.pyx
      [6/6] Cythonizing centrosome/_propagate.pyx
      Traceback (most recent call last):
        File "/opt/conda/envs/cellprofiler-4.2.5/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/envs/cellprofiler-4.2.5/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/envs/cellprofiler-4.2.5/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-prwdohc6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-prwdohc6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-prwdohc6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 89, in <module>
        File "/tmp/pip-build-env-prwdohc6/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-prwdohc6/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: centrosome/_propagate.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

**Comment by unode** [comment]
See https://github.com/CellProfiler/centrosome/pull/119 for a simple fix.

**Comment by gnodar01** [comment]
Thanks for reporting. Should be all set now with the latest change to master. You can also just run `pip install centrosome==1.2.2` (you can safely ignore dependency conflict errors reported by pip for cellprofiler and cellprofiler-core).
