### ISSUE TITLE
ERROR:root:Failed to load pipeline

### ISSUE THREAD

**Issue by 302850047** [CellProfiler/CellProfiler#4796]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce, including an attached/linked image set and pipeline, may be closed without investigation. You may delete this section before posting your issue below.
---
pipeline.load(r'D:\Downloads\Edge\ExampleHuman\ExampleHuman\ExampleHuman.cppipe')
i don't know how to solve
**Describe the bug**
ERROR:root:Failed to load pipeline
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\cellprofiler_core\pipeline\_pipeline.py", line 543, in setup_modules
    module = self.setup_module(
  File "D:\anaconda3\lib\site-packages\cellprofiler_core\pipeline\_pipeline.py", line 569, in setup_module
    module = self.instantiate_module(module_name)
  File "D:\anaconda3\lib\site-packages\cellprofiler_core\pipeline\_pipeline.py", line 197, in instantiate_module
    return instantiate_module(module_name)
  File "D:\anaconda3\lib\site-packages\cellprofiler_core\utilities\core\modules\__init__.py", line 180, in instantiate_module
    module = get_module_class(module_name)()
  File "D:\anaconda3\lib\site-packages\cellprofiler_core\utilities\core\modules\__init__.py", line 175, in get_module_class
    raise ValueError("Could not find the %s module" % module_class)
ValueError: Could not find the IdentifyPrimaryObjects module
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX 14.6]
 - CellProfiler Version [e.g. 2.2, 3.1.9]
 - Downloaded from the website or installed from source?
 - If the latter, how (cloned, installed from pypi, etc)?

**Additional context**

**Comment by bethac07** [comment]
Sorry to hear you're having trouble! Can you provide the output of `conda list` in your environment, and share a little more about how it was made? Thanks!
