### ISSUE TITLE
Cellprofiler v2.1.1 w64 pipeline issue

### ISSUE THREAD

**Issue by cd791** [CellProfiler/CellProfiler#4806]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce may be closed without investigation. You may delete this section before posting your issue below.
---

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version 2.1.1
 - Downloaded from: https://cellprofiler.org/previous-releases 

**Describe the issue**

Dear Cellprofiler Developer,

I am trying to use an outdated Cellprofiler pipeline (SeedScoring, doi: 10.1007/978-1-0716-2253-7_10) on Windows 10.
However, 

1. when I launch the software, the prompt shows the follow error message:

Qt: Untested Windows version 6.2 detected!

if I ignore the previous error and run the pipeline (please, see attachment), the prompt displays:
Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 2176, in post_run
  File "cellprofiler\modules\exporttospreadsheet.pyc", line 544, in post_run
  File "cellprofiler\modules\exporttospreadsheet.pyc", line 609, in run_objects
  File "cellprofiler\modules\exporttospreadsheet.pyc", line 997, in make_object_file
  File "cellprofiler\measurements.pyc", line 861, in get_feature_names
  File "cellprofiler\utilities\hdf5_dict.pyc", line 707, in second_level_names
  File "h5py\highlevel.pyc", line 386, in __getitem__
  File "h5py\highlevel.pyc", line 347, in _get18
  File "h5o_body.pyx", line 165, in h5py.h5o.get_info (h5py\h5o.c:2217)
KeyError: "Name doesn't exist (Symbol table: Object not found)" 

2. the software is unable to load example pipeline from the Welcome Screen Page

3. when I run Examples from outdated version [Previous Examples | CellProfiler](https://cellprofiler.org/previous-examples) , the software generates different errors for different example data

4. intuitively, the SeedScoring pipeline that I need to use, could not run on the latest Cellprofiler version
Note, a colleague of mine is able to use the same pipeline without any issue.

That said, which would be the best action to take? Any explanation about my issue?

Please, let me know if you need further info from me.
Thanks.

Kind regards,
Chiara

**Comment by bethac07** [comment]
Hi,

I received an email that said you had resolved this issue - do you mind sharing how, for the benefit of those who come across this issue in the future?

We certainly do recommend though updating the pipeline to a more modern version of CellProfiler to ensure future use - that version is approximately 10 years old and will likely encounter issues on modern computers. If you run into trouble doing so, I recommend posting on forum.image.sc, our team will be happy to help!

**Comment by cd791** [comment]
Dear Beth,

Thank you for your reply.

I previously posted my issue on forum.image.sc, now updated with my response and a new question about how to prevent overwriting a .jpg data list in a csv file.
https://forum.image.sc/t/cellprofiler-v2-1-1-w64-pipeline-issue/84991/5
https://forum.image.sc/t/seedscoring-for-cellprofiler-v2-1-1-w64-how-to-prevent-overwriting-a-list-of-data/85044


Thanks.

Best regards,
Chiara
________________________________
