### ISSUE TITLE
ClassifyObjects: TypeError: Invalid shape (1, 1024, 1024) for image data

### ISSUE THREAD

**Issue by ErikWulms** [CellProfiler/CellProfiler#4817]
**Describe the bug**
When using ClassifyObjects with a pair of measurements it runs fine in test mode but throws an error when running analyze

**To Reproduce**
Run the attached pipeline in test and analyze mode

**Expected behavior**
I expect analyze and testmode to behave the same and not throw errors

**Screenshots**
Analyze
![image](https://github.com/CellProfiler/CellProfiler/assets/18581038/9b70162d-ecdb-472d-9792-d514de960242)

Test
![image](https://github.com/CellProfiler/CellProfiler/assets/18581038/482eb1ab-7570-4768-a019-d3168f4e3083)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CellProfiler Version: 2.4.6
 - Downloaded from the website or installed from source? Downloaded from website
 - If the latter, how (cloned, installed from pypi, etc)? -

**Additional context**
Stacktrace:
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 2992, in module_display_request
  File "cellprofiler\modules\classifyobjects.py", line 978, in display
  File "cellprofiler\modules\classifyobjects.py", line 1112, in display_two_measurements
  File "cellprofiler\gui\utilities\figure.py", line 90, in wrapper
  File "cellprofiler\gui\figure\_figure.py", line 1886, in subplot_imshow_labels
  File "cellprofiler\gui\utilities\figure.py", line 90, in wrapper
  File "cellprofiler\gui\figure\_figure.py", line 1643, in subplot_imshow
  File "matplotlib\__init__.py", line 1599, in inner
  File "matplotlib\cbook\deprecation.py", line 369, in wrapper
  File "matplotlib\cbook\deprecation.py", line 369, in wrapper
  File "matplotlib\axes\_axes.py", line 5679, in imshow
  File "matplotlib\image.py", line 689, in set_data
TypeError: Invalid shape (1, 1024, 1024) for image data

Included are some images and the pipeline
[cellprofiler pipeline.zip](https://github.com/CellProfiler/CellProfiler/files/12535882/cellprofiler.pipeline.zip)

**Comment by bethac07** [comment]
Huh, it's weird you're only seeing it in analysis mode rather than test mode! But it seems to be a display error only, so can you confirm that you do not get the error if running with the "eye" closed?

**Comment by ErikWulms** [comment]
Good catch, that is the case. With the display disabled (eye closed) it does not throw any errors.
