### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by tubulocristate** [CellProfiler/CellProfiler#4849]
**Desktop:**
 - OS: arch linux
 - CellProfiler Version 4.2.6
 - Downloaded from pip

**Describe the issue**
I tried to install cellprofiler with pip in virtual environment. During installation I received an error indicating that it could not find numpy even though it is installed in local env.

**Error messages**

```
      Traceback (most recent call last):
        File "/home/fairy_head/Programming/cellprofiler_test/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/fairy_head/Programming/cellprofiler_test/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/fairy_head/Programming/cellprofiler_test/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g8keaq8g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g8keaq8g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g8keaq8g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-g8keaq8g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 412, in <module>
        File "<string>", line 100, in ext_modules
      ModuleNotFoundError: No module named 'numpy'
```

**Comment by JiangXL** [comment]
There is the same issue on Fedora 39.

**Comment by bradgy** [comment]
This is the same issue I'm getting too. Manually installing numpy using pip doesn't affect python-javabridge failing to build. Host system has numpy installed.

Arch Linux  6.7.0-arch3-1 #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux
Cellprofiler from pip

`~]$ python -m venv cellprofiler`
`~]$ source cellprofiler/bin/activate`
`(cellprofiler) [~]$ pip install cellprofiler`
```
Collecting cellprofiler
  Obtaining dependency information for cellprofiler from https://files.pythonhosted.org/packages/89/f6/2fe134b0fa622d31afdde0cea41a8c13ed5bfb5f39527376c230a4ec9049/CellProfiler-4.2.6-py3-none-any.whl.metadata
  Using cached CellProfiler-4.2.6-py3-none-any.whl.metadata (2.0 kB)
Collecting boto3>=1.12.28 (from cellprofiler)
  Obtaining dependency information for boto3>=1.12.28 from https://files.pythonhosted.org/packages/5d/0b/af4e4bb5f87d1542da2f9d618393fbdcaa86bc35673df48c23163a10ee79/boto3-1.34.23-py3-none-any.whl.metadata
  Using cached boto3-1.34.23-py3-none-any.whl.metadata (6.6 kB)
Collecting cellprofiler-core==4.2.6 (from cellprofiler)
  Obtaining dependency information for cellprofiler-core==4.2.6 from https://files.pythonhosted.org/packages/7b/83/4a68576ddedb424fa375d0ff61cabe5218595a0dd366ff6db0c42b5e6f65/cellprofiler_core-4.2.6-py3-none-any.whl.metadata
  Using cached cellprofiler_core-4.2.6-py3-none-any.whl.metadata (1.3 kB)
Collecting centrosome==1.2.2 (from cellprofiler)
  Using cached centrosome-1.2.2.tar.gz (628 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting docutils==0.15.2 (from cellprofiler)
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting h5py<4,~=3.6.0 (from cellprofiler)
  Using cached h5py-3.6.0.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting imageio>=2.5 (from cellprofiler)
  Obtaining dependency information for imageio>=2.5 from https://files.pythonhosted.org/packages/c0/69/3aaa69cb0748e33e644fda114c9abd3186ce369edd4fca11107e9f39c6a7/imageio-2.33.1-py3-none-any.whl.metadata
  Using cached imageio-2.33.1-py3-none-any.whl.metadata (4.9 kB)
Collecting inflect<7,>=2.1 (from cellprofiler)
  Obtaining dependency information for inflect<7,>=2.1 from https://files.pythonhosted.org/packages/6a/e1/79603e4ae91b38a91dfd855f92321afb65e7f3d0192ac831d00bc9c45cca/inflect-6.2.0-py3-none-any.whl.metadata
  Using cached inflect-6.2.0-py3-none-any.whl.metadata (21 kB)
Collecting Jinja2>=2.11.2 (from cellprofiler)
  Obtaining dependency information for Jinja2>=2.11.2 from https://files.pythonhosted.org/packages/30/6d/6de6be2d02603ab56e72997708809e8a5b0fbfee080735109b40a3564843/Jinja2-3.1.3-py3-none-any.whl.metadata
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting joblib>=0.13 (from cellprofiler)
  Obtaining dependency information for joblib>=0.13 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting mahotas>=1.4 (from cellprofiler)
  Using cached mahotas-1.4.13-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
Collecting matplotlib<4,>=3.1.3 (from cellprofiler)
  Obtaining dependency information for matplotlib<4,>=3.1.3 from https://files.pythonhosted.org/packages/92/1a/cd3e0c90d1a763ad90073e13b189b4702f11becf4e71dbbad70a7a149811/matplotlib-3.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached matplotlib-3.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting mysqlclient==1.4.6 (from cellprofiler)
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.20.1 (from cellprofiler)
  Obtaining dependency information for numpy>=1.20.1 from https://files.pythonhosted.org/packages/5a/62/007b63f916aca1d27f5fede933fda3315d931ff9b2c28b9c2cf388cd8edb/numpy-1.26.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached numpy-1.26.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting Pillow>=7.1.0 (from cellprofiler)
  Obtaining dependency information for Pillow>=7.1.0 from https://files.pythonhosted.org/packages/66/9c/2e1877630eb298bbfd23f90deeec0a3f682a4163d5ca9f178937de57346c/pillow-10.2.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata
  Using cached pillow-10.2.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (9.7 kB)
Collecting prokaryote==2.4.4 (from cellprofiler)
  Using cached prokaryote-2.4.4.tar.gz (84.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-bioformats==4.0.7 (from cellprofiler)
  Using cached python_bioformats-4.0.7-py3-none-any.whl (40.6 MB)
Collecting python-javabridge==4.0.3 (from cellprofiler)
  Using cached python-javabridge-4.0.3.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/brad/cellprofiler/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/brad/cellprofiler/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/brad/cellprofiler/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-h8eohr62/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-h8eohr62/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-h8eohr62/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-h8eohr62/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 412, in <module>
        File "<string>", line 100, in ext_modules
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
`(cellprofiler) [~]$ pip list`
```
(cellprofiler) [brad@clabs-nuc-bio ~]$ pip list
Package    Version
---------- -------
pip        23.2.1
setuptools 65.5.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
```
`(cellprofiler) [~]$ pip install numpy`
```Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/5a/62/007b63f916aca1d27f5fede933fda3315d931ff9b2c28b9c2cf388cd8edb/numpy-1.26.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached numpy-1.26.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.3
```

`(cellprofiler) [~]$ pip list`
```
Package    Version
---------- -------
numpy      1.26.3
pip        23.2.1
setuptools 65.5.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip


```
`(cellprofiler) [~]$ pip install cellprofiler`
```
Collecting cellprofiler
  Obtaining dependency information for cellprofiler from https://files.pythonhosted.org/packages/89/f6/2fe134b0fa622d31afdde0cea41a8c13ed5bfb5f39527376c230a4ec9049/CellProfiler-4.2.6-py3-none-any.whl.metadata
  Using cached CellProfiler-4.2.6-py3-none-any.whl.metadata (2.0 kB)
Collecting boto3>=1.12.28 (from cellprofiler)
  Obtaining dependency information for boto3>=1.12.28 from https://files.pythonhosted.org/packages/5d/0b/af4e4bb5f87d1542da2f9d618393fbdcaa86bc35673df48c23163a10ee79/boto3-1.34.23-py3-none-any.whl.metadata
  Using cached boto3-1.34.23-py3-none-any.whl.metadata (6.6 kB)
Collecting cellprofiler-core==4.2.6 (from cellprofiler)
  Obtaining dependency information for cellprofiler-core==4.2.6 from https://files.pythonhosted.org/packages/7b/83/4a68576ddedb424fa375d0ff61cabe5218595a0dd366ff6db0c42b5e6f65/cellprofiler_core-4.2.6-py3-none-any.whl.metadata
  Using cached cellprofiler_core-4.2.6-py3-none-any.whl.metadata (1.3 kB)
Collecting centrosome==1.2.2 (from cellprofiler)
  Using cached centrosome-1.2.2.tar.gz (628 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting docutils==0.15.2 (from cellprofiler)
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting h5py<4,~=3.6.0 (from cellprofiler)
  Using cached h5py-3.6.0.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting imageio>=2.5 (from cellprofiler)
  Obtaining dependency information for imageio>=2.5 from https://files.pythonhosted.org/packages/c0/69/3aaa69cb0748e33e644fda114c9abd3186ce369edd4fca11107e9f39c6a7/imageio-2.33.1-py3-none-any.whl.metadata
  Using cached imageio-2.33.1-py3-none-any.whl.metadata (4.9 kB)
Collecting inflect<7,>=2.1 (from cellprofiler)
  Obtaining dependency information for inflect<7,>=2.1 from https://files.pythonhosted.org/packages/6a/e1/79603e4ae91b38a91dfd855f92321afb65e7f3d0192ac831d00bc9c45cca/inflect-6.2.0-py3-none-any.whl.metadata
  Using cached inflect-6.2.0-py3-none-any.whl.metadata (21 kB)
Collecting Jinja2>=2.11.2 (from cellprofiler)
  Obtaining dependency information for Jinja2>=2.11.2 from https://files.pythonhosted.org/packages/30/6d/6de6be2d02603ab56e72997708809e8a5b0fbfee080735109b40a3564843/Jinja2-3.1.3-py3-none-any.whl.metadata
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting joblib>=0.13 (from cellprofiler)
  Obtaining dependency information for joblib>=0.13 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting mahotas>=1.4 (from cellprofiler)
  Using cached mahotas-1.4.13-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
Collecting matplotlib<4,>=3.1.3 (from cellprofiler)
  Obtaining dependency information for matplotlib<4,>=3.1.3 from https://files.pythonhosted.org/packages/92/1a/cd3e0c90d1a763ad90073e13b189b4702f11becf4e71dbbad70a7a149811/matplotlib-3.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached matplotlib-3.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting mysqlclient==1.4.6 (from cellprofiler)
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.20.1 in ./cellprofiler/lib/python3.11/site-packages (from cellprofiler) (1.26.3)
Collecting Pillow>=7.1.0 (from cellprofiler)
  Obtaining dependency information for Pillow>=7.1.0 from https://files.pythonhosted.org/packages/66/9c/2e1877630eb298bbfd23f90deeec0a3f682a4163d5ca9f178937de57346c/pillow-10.2.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata
  Using cached pillow-10.2.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (9.7 kB)
Collecting prokaryote==2.4.4 (from cellprofiler)
  Using cached prokaryote-2.4.4.tar.gz (84.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-bioformats==4.0.7 (from cellprofiler)
  Using cached python_bioformats-4.0.7-py3-none-any.whl (40.6 MB)
Collecting python-javabridge==4.0.3 (from cellprofiler)
  Using cached python-javabridge-4.0.3.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/brad/cellprofiler/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/brad/cellprofiler/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/brad/cellprofiler/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-21dn0ukd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-21dn0ukd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-21dn0ukd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-21dn0ukd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 412, in <module>
        File "<string>", line 100, in ext_modules
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by bradgy** [comment]
Fixed by installing Python 3.8 from the AUR :)

Then made a new venv with python 3.8. After that pip install cellprofiler worked immediately.

(why is it always after immediately writing out a github issue do I work out the problem?)

**Comment by bethac07** [comment]
Hi folks -

Was coming here to say that indeed, can you try CellProfiler 3.8 or 3.9? We do not support 3.11.

**Comment by bradgy** [comment]
No worries Beth, I actually went ahead and wrote a page on Arch installation for the [wiki](https://github.com/CellProfiler/CellProfiler/wiki/Arch-Linux), hope that's okay.

**Comment by gnodar01** [comment]
More than okay. Thanks @bradgy
