### ISSUE TITLE
IdentifyPrmaryObjects: Error when using adaptive thresholding on completely masked image

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#4862]
**Describe the bug**
Running the attached pipeline (a variation of the welcome screen example pipeline) in which the entire image is masked out yields the error message below:
> Failed to run module IdentifyPrimaryObjects
> Traceback (most recent call last):
>   File "cellprofiler\gui\pipelinecontroller.py", line 3390, in do_step
>   File "cellprofiler_core\pipeline\_pipeline.py", line 1341, in run_module
>   File "cellprofiler\modules\identifyprimaryobjects.py", line 1076, in run
>   File "cellprofiler\modules\identifyprimaryobjects.py", line 1213, in _threshold_image
>   File "cellprofiler\modules\threshold.py", line 879, in get_threshold
>   File "cellprofiler\modules\threshold.py", line 940, in get_local_threshold
>   File "<__array_function__ internals>", line 180, in amin
>   File "numpy\core\fromnumeric.py", line 2918, in amin
>   File "numpy\core\fromnumeric.py", line 86, in _wrapreduction
> ValueError: zero-size array to reduction operation minimum which has no identity`

**Desktop (please complete the following information):**
Running version 4.2.4 on windows.
[pipeline.zip](https://github.com/CellProfiler/CellProfiler/files/14126075/pipeline.zip)

**Comment by bethac07** [comment]
Not pulled to main becuase we couldn't reproduce there, but we could
