### ISSUE TITLE
cellprofiler 4.2.6 failing to launch in Ubuntu 20.04

### ISSUE THREAD

**Issue by schroeme** [CellProfiler/CellProfiler#4901]
**Describe the bug**
When I try to launch by running `$cellprofiler` (installed on a Linux 20.04 OS via pip, see below), I get the following error:

`Traceback (most recent call last):
  File "/home/mschro/anaconda3/envs/cellprofiler/bin/cellprofiler", line 8, in <module>
    sys.exit(main())
  File "/home/mschro/anaconda3/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler/__main__.py", line 154, in main
    temp_dir = get_temporary_directory()
  File "/home/mschro/anaconda3/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py", line 1579, in get_temporary_directory
    elif config_exists(TEMP_DIR):
  File "/home/mschro/anaconda3/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py", line 235, in config_exists
    if not get_config().Exists(key):
  File "/home/mschro/anaconda3/envs/cellprofiler/lib/python3.8/site-packages/cellprofiler_core/preferences/__init__.py", line 80, in get_config
    import wx
  File "/home/mschro/anaconda3/envs/cellprofiler/lib/python3.8/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/mschro/anaconda3/envs/cellprofiler/lib/python3.8/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0`

**Output of conda list**
# packages in environment at /home/mschro/anaconda3/envs/cellprofiler:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
annotated-types           0.6.0                    pypi_0    pypi
boto3                     1.34.105                 pypi_0    pypi
botocore                  1.34.105                 pypi_0    pypi
ca-certificates           2024.3.11            h06a4308_0  
cellprofiler              4.2.6                    pypi_0    pypi
cellprofiler-core         4.2.6                    pypi_0    pypi
centrosome                1.2.2                    pypi_0    pypi
certifi                   2024.2.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
fonttools                 4.51.0                   pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
h5py                      3.6.0                    pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.34.1                   pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
inflect                   6.2.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
mahotas                   1.4.15                   pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
mysqlclient               1.4.6                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.0.13               h7f8727e_1  
packaging                 24.0                     pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0             py38h06a4308_0  
prokaryote                2.4.4                    pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pydantic                  2.7.1                    pypi_0    pypi
pydantic-core             2.18.2                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.8.19               h955ad1f_0  
python-bioformats         4.0.7                    pypi_0    pypi
python-dateutil           2.9.0.post0              pypi_0    pypi
python-javabridge         4.0.3                    pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
s3transfer                0.10.1                   pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
sentry-sdk                0.18.0                   pypi_0    pypi
setuptools                69.5.1           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2022.4.8                 pypi_0    pypi
tk                        8.6.14               h39e8969_0  
typing-extensions         4.11.0                   pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0  
wxpython                  4.2.1                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CellProfiler Version 4.2.6
 - Installed via `pip install cellprofiler` in a fresh conda environment with python 3.8 (`conda create -n cellprofiler python=3.8`
followed by `conda activate cellprofiler`)

**Comment by fefossa** [comment]
Hi,

Have you managed to open cellprofiler on your machine? On mine, I had to run the following:

```
wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.0-cp38-cp38-linux_x86_64.whl
pip3 install wxPython-4.1.0-cp38-cp38-linux_x86_64.whl
```

I just bumped here cause I'm also trying to install it on Ubuntu 22.04.5

**Comment by fefossa** [comment]
For me what worked was the following (bear in mind I'm running cellprofiler headless):

- created conda env with python 3.8
- `pip install numpy`
- `pip install cellprofiler`

error: failed building wheel for python-javabridge
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (python-javabridge)

- so run:
`conda install -c conda-forge python-javabridge`

- `pip install cellprofiler` again
- now it's installed!

Run the beginner segmentation from cellprofiler-tutorials to test if everything works ( download here https://github.com/CellProfiler/tutorials)

`cellprofiler -c -r -p /home/f.garciafossa/projects/cellprofiler4/Beginner_segmentation/segmentation_final.cppipe -o /home/f.garciafossa/projects/cellprofiler4/Beginner_segmentation/output -i /home/f.garciafossa/projects/cellprofiler4/Beginner_segmentation/images_Illum-corrected/`


- but many errors appeared related to numpy, so I ran:

`pip install numpy --upgrade`

- Run the same command above and complete the analysis with no errors.
