### ISSUE TITLE
Plugin Installation Issues（cellpose）

### ISSUE THREAD

**Issue by ATAICwillbebest** [CellProfiler/CellProfiler#4931]
OS: [Windows 11 Enterprise]
CellProfiler Version [4.2.7]
conda environment cellpose plugin with python3.10
git clone https://github.com/CellProfiler/CellProfiler-plugins.git
Set the plugins path in CellProfiler C:\Users\86185\CellProfiler-plugins\active_plugins

**Error messages**
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\86185\AppData\Local\Temp\pip-install-9r7yhel3\python-javabridge_026155e9a5eb4710ba15720efd54d85d\setup.py", line 412, in <module>
          ext_modules=ext_modules(),
                      ^^^^^^^^^^^^^
        File "C:\Users\86185\AppData\Local\Temp\pip-install-9r7yhel3\python-javabridge_026155e9a5eb4710ba15720efd54d85d\setup.py", line 100, in ext_modules
          from numpy import get_include
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Describe the issue**
Installing plugins with dependencies, using CellProfiler from source，cellpose plugin installation failed

conda create -n pluginsCellpose python=3.10
conda activate pluginsCellpose
git clone https://github.com/CellProfiler/CellProfiler-plugins.git
cd CellProfiler-plugins
pip install -e .[cellpose]

Obtaining file:///C:/Users/86185/CellProfiler-plugins
  Preparing metadata (setup.py) ... done
Collecting cellprofiler (from cellprofiler_plugins==0.0.0)
  Using cached CellProfiler-4.2.7-py3-none-any.whl.metadata (2.0 kB)
Collecting cellprofiler-core (from cellprofiler_plugins==0.0.0)
  Using cached cellprofiler_core-4.2.7-py3-none-any.whl.metadata (1.3 kB)
Collecting cellpose<3.0,>=1.0.2 (from cellprofiler_plugins==0.0.0)
  Using cached cellpose-2.3.2-py3-none-any.whl.metadata (21 kB)
Collecting numpy>=1.20.0 (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached numpy-2.0.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting scipy (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached scipy-1.14.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting natsort (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Collecting tifffile (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached tifffile-2024.7.24-py3-none-any.whl.metadata (31 kB)
Collecting tqdm (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting numba>=0.53.0 (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached numba-0.60.0-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Collecting llvmlite (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached llvmlite-0.43.0-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Collecting torch>=1.6 (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached torch-2.4.0-cp311-cp311-win_amd64.whl.metadata (27 kB)
Collecting opencv-python-headless (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting fastremap (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached fastremap-1.15.0-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting imagecodecs (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached imagecodecs-2024.6.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting roifile (from cellpose<3.0,>=1.0.2->cellprofiler_plugins==0.0.0)
  Using cached roifile-2024.5.24-py3-none-any.whl.metadata (4.6 kB)
Collecting boto3>=1.12.28 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached boto3-1.34.154-py3-none-any.whl.metadata (6.6 kB)
Collecting centrosome<1.3,>=1.2.3 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached centrosome-1.2.3.tar.gz (657 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting docutils==0.15.2 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached docutils-0.15.2-py3-none-any.whl.metadata (2.6 kB)
Collecting h5py<4,~=3.6.0 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached h5py-3.6.0.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting imageio>=2.5 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached imageio-2.34.2-py3-none-any.whl.metadata (4.9 kB)
Collecting inflect<7,>=2.1 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached inflect-6.2.0-py3-none-any.whl.metadata (21 kB)
Collecting Jinja2>=2.11.2 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib>=0.13 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting mahotas>=1.4 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached mahotas-1.4.18-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting matplotlib<4,>=3.1.3 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached matplotlib-3.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting mysqlclient==1.4.6 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
  Preparing metadata (setup.py) ... done
Collecting Pillow>=7.1.0 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached pillow-10.4.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Collecting prokaryote==2.4.4 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached prokaryote-2.4.4.tar.gz (84.2 MB)
  Preparing metadata (setup.py) ... done
Collecting python-bioformats==4.0.7 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached python_bioformats-4.0.7-py3-none-any.whl.metadata (1.7 kB)
Collecting python-javabridge==4.0.3 (from cellprofiler->cellprofiler_plugins==0.0.0)
  Using cached python-javabridge-4.0.3.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\86185\AppData\Local\Temp\pip-install-9r7yhel3\python-javabridge_026155e9a5eb4710ba15720efd54d85d\setup.py", line 412, in <module>
          ext_modules=ext_modules(),
                      ^^^^^^^^^^^^^
        File "C:\Users\86185\AppData\Local\Temp\pip-install-9r7yhel3\python-javabridge_026155e9a5eb4710ba15720efd54d85d\setup.py", line 100, in ext_modules
          from numpy import get_include
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by gnodar01** [comment]
Are you able to use python 3.9? If so, try it with that. 3.10 does work, but is somewhat problematic for CellProfiler 4
