### ISSUE TITLE
ClassifyPixels on Win32 release build does not work

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#990]
Sadness - the APIs don't match. Running the all-modules pipeline after enabling the classifypixels module.

Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 1919, in run_image_set
  File "cellprofiler\modules\classifypixels.pyc", line 227, in run
  File "C:\Program Files\CellProfiler\site-packages\ilastik\core\volume.py", line 56, in __init__
AttributeError: 'module' object has no attribute '_VigraArray'

**Comment by braymp** [comment]
Abandoned CP Win32 a while back.
