### ISSUE TITLE
HDF5 error at end of run

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#995]
Run the attached pipeline from source(c0a74b1) to reproduce:
```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\utilities\thread_excepthook.py", line 27, in run_with_except_hook
    run_old(*args, **kw)
  File "C:\Python27\lib\threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Trunk\CellProfiler\cellprofiler\analysis.py", line 448, in interface
    self.copy_recieved_measurements(recd_measurements, measurements, image_numbers)
  File "D:\Trunk\CellProfiler\cellprofiler\analysis.py", line 552, in copy_recieved_measurements
    = recd_measurements[o, feature, image_numbers]
  File "D:\Trunk\CellProfiler\cellprofiler\measurements.py", line 338, in __setitem__
    self.add_measurement(key[0], key[1], value, image_set_number=key[2])
  File "D:\Trunk\CellProfiler\cellprofiler\measurements.py", line 790, in add_measurement
    self.hdf5_dict[object_name, feature_name, image_set_number] = data
  File "D:\Trunk\CellProfiler\cellprofiler\utilities\hdf5_dict.py", line 529, in __setitem__
    dataset = feature_group.create_dataset('data', **kwds)
  File "C:\Python27\lib\site-packages\h5py\_hl\group.py", line 71, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Python27\lib\site-packages\h5py\_hl\dataset.py", line 89, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5t.pyx", line 1361, in h5py.h5t.py_create (h5py\h5t.c:12754)
  File "h5t.pyx", line 1433, in h5py.h5t.py_create (h5py\h5t.c:12601)
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```
Interestingly, this forum user noticed the same thing: http://cellprofiler.org/forum/viewtopic.php?f=18&t=3510&p=10262#p10263

Attachments:
http://cellprofiler.org/issues/uploaded/OIGqk_/issue.cppipe

**Comment by LeeKamentsky** [comment]
I found this problem in Fiocruz. There is another path where this happens. I made it work by looping and setting the dataset by hand

   check for dataset.dtype.kind = "O"
   create dataset empty with correct length
   set each element by hand.
